### ISSUE TITLE
Package external solvers for all platforms

### ISSUE THREAD

**Issue by AltGr** [ocaml/opam#1267]
It is now very recommended to run OPAM using an external solver -- `aspcud` at the moment. We need to make sure there is one properly packaged available on all platforms. This should also be better documented in the installation instructions (https://github.com/ocaml/opam/wiki/Quick_Install)

Supersedes #685 and #985

**Comment by rneswold** [comment]
> If this is recommended now, should we output a warning if the builtin solver is used?

I believe so. I upgraded to OPAM 1.2 and started having many problems (especially with respect to maintaining `lwt`.) It turns out that using an external solver fixed my problems (the Solver Farm, in my case.) If OPAM's solver can't handle it's default repository, a warning should be given when using it.

Is there a reason to have a built-in solver, if it can't even be used in the default repository?

**Comment by rneswold** [comment]
> The cloud solver isn't ideal as well, as it forces a system that works fine offline to go online all the time (e.g. ocaml/opam#1154 style usecases simply wouldnt work).

Actually, I think the cloud solver *is* ideal:

1. It prevents me from installing and maintaining many 3rd party libraries and tools to build an external solver (which should arguably be part of OPAM.)
2. The solver farm is cross-platform.
3. If I'm working offline, I can't do an `opam update`, so a locally installed solver doesn't buy me anything.

In my opinion, OPAM's internal solver should be replaced with the Solver Farm. Users that want to use a local solver can still do it but, this way, OPAM can properly handle its own repository.

**Comment by amirmc** [comment]
> Is there a reason to have a built-in solver, if it can't even be used in the default repository?

I think it's worth pointing out that the internal solver began life before many of the other pieces were readily available (and before there were so many packages in the repo).  I'd agree with emitting some kind of warning though.

> In my opinion, OPAM's internal solver should be replaced with the Solver Farm.

I disagree.  Introducing a default that *relies* on network connectivity would end up being a hindrance in the long term.  opam itself has improved due to reports of people that have had to use it under rather poor network conditions (as linked in this thread).  The solver farm is ideal for your use-case and I'm very happy that option is available.  However, making it the default seems inappropriate to me.  The issue here seems to be surfacing when the internal solver is used and also making it easy to use other options (e.g `aspcud`, solver farm, etc)

**Comment by rneswold** [comment]
> Introducing a default that relies on network connectivity would end up being a hindrance in the long term.

I admit I'm not an OPAM power-user. Whenever I use OPAM, I need network connectivity because I'm updating my repository or installing a new library. Having a network-based solver works well in this configuration.

Power users may use OPAM in ways that don't require the network. Since they're power users, they won't mind building and installing 3rd-party solvers.

What *is* a hinderance is the internal solver not able to handle the default repository that OPAM wants to use. `lwt`, in particular, seems to be difficult for the internal solver to analyze (I reported this here: ocsigen/lwt/issues/177).

**Comment by yomimono** [comment]
> Power users may use OPAM in ways that don't require the network. Since they're power users, they won't mind building and installing 3rd-party solvers.

I don't think this necessarily is the case.  I frequently had a poor or nonexistent network connection when I was new to using OPAM and hadn't hit on a decent switch arrangement yet, which resulted in my frequently recompiling packages with new optional dependencies.  I probably invoked the solver much more often when I was new to OPAM than I do now.

**Comment by AltGr** [comment]
Where @meswold may have a point is that we _could_ integrate a solver-farm backend into opam (avoiding the wrapper script that calls curl), or at least make it easier to install. Then the users would readily have access to the different options.

I agree that there may be issues with making it the default when no local solver is available (privacy, connectivity) ; but letting the user know about it (or even ask, e.g. at `opam init` when no local solver is found, whether it should be made the default) could improve the opam UX.

**Comment by rneswold** [comment]
@avsm:
> I believe the 1.2 internal solver is in better shape than the 1.1 one (untested by me though)

It's not. On 32-bit and 64-bit BSD systems and OSX, I cannot install `lwt` properly after v2.4.5. The solver farm properly upgraded my systems to `lwt` v2.5.0.

I've said it before, but no one has yet addressed my concern, that the internal solver can no longer properly handle the repository. Either it needs to be fixed enough to work (even if it doesn't yield optimal results) or it should be replaced. Leaving a user's repository in an un-upgradable/downgradable state (like mine was in) is not acceptable.

**Comment by dbuenzli** [comment]
> If I'm working offline, I can't do an opam update, so a locally installed solver doesn't buy me anything.

You are not taking pin workflows into account here. Defaulting to the solver farm is not a good idea.

> I've said it before, but no one has yet addressed my concern, that the internal solver can no longer properly handle the repository.

I don't think it ever did. The situation hasn't changed, there are some *configurations* that the handler doesn't handle well.

> Leaving a user's repository in an un-upgradable/downgradable state (like mine was in) is not acceptable.

Was it really ? Did you try to specify full constraints on the command line ?

**Comment by rneswold** [comment]
> You are not taking pin workflows into account here. Defaulting to the solver farm is not a good idea.

Yes, I can see how this would be negatively impacted. Thank you.

> > the internal solver can no longer properly handle the repository.
 
> I don't think it ever did.

Then why is it included and enabled by default? Get rid of it; it'll remove some confusion, it'll reduce the amount of code in the project; and the users will have an OPAM configuration that will always work.

>> Leaving a user's repository in an un-upgradable/downgradable state (like mine was in) 

> Was it really? Did you try to specify full constraints on the command line?

Yes: ocsigen/lwt/issues#177.

**Comment by dbuenzli** [comment]
> Then why is it included and enabled by default? Get rid of it; it'll remove some confusion, it'll reduce the amount of code in the project; and the users will have an OPAM configuration that will always work.

External solvers have a lot of dependencies which may be a problem in more constrained environments. For example unfolding the recursive dependencies for installing apscud on osx you need boost, cmake, re2c, gringo, scons, bison and clasp.

> Yes: ocsigen/lwt#177.

That looks like a bug ("no package matches lwt"), did you report it ? In my opinion not finding a solution or a sub-optimal solution is fine as long as you can specify one the command line.

**Comment by rneswold** [comment]
>> Yes: ocsigen/lwt#177.

> That looks like a bug ("no package matches lwt"), did you report it ? In my opinion not finding a solution or a sub-optimal solution is fine as long as you can specify one the command line.

I agree. I reported it to the `lwt` project because I thought it was a bad specification in their OPAM package info. Their consensus was that the internal solver is bad and an external solver works, so I closed the issue. I then stumbled across this discussion.

If I was able to specify a version and get around the internal solver's limitations, I wouldn't have reported anything. But my repository was getting further and further out of date and it wasn't obvious to me that the interval solver was the problem.

**Comment by avsm** [comment]
There are very valid both points on all sides here.

- The internal solver used to work given the state of the package repository around a year ago.  At that time, Lwt in particular was largely constraint-free, so the package universe wasn't split too much.  Nowadays, things are a little more split down the middle due to regular API cranks, and the constraint solver needs to work harder.

- It would be nice to integrate the external solver in a neater way into current OPAM.  My only request is that the server code also be included with OPAM, or at least the specification for the remote call.  Baking in a remote solver farm URL is counter to the otherwise highly distributed design of OPAM.

- Can the internal solver at least be patched to verify that the solution it does find is sound, by walking the package constraints and checking if the picked solution violates them?  This happens right now with depopts quite often.  If it really can't be fixed, then it ought to be dropped or least disabled without an environment variable override.  The major platforms without aspcud are really the BSDs right now -- mostly due to a newer Bison being required on OpenBSD last I looked.

**Comment by AltGr** [comment]
Indeed. On 3., the internal solver should not, indeed, ever output an unsound solution. This needs to be investigated.

On 2., one big plus of the remote solver interface is that it's really trivial, all the difficult stuff being handled by the cudf layer. The shell-script provided at http://cudf-solvers.irill.org/cudf_remote_proxy  is basically a direct call to curl, with only three small quirks:
 1. the client script answers to `-v` (this allows opam to detect compat and use the best default criteria)
 2. on failure, it just writes "FAIL" to its output file
 3. it uses two-way bzip2 compression at `<api>/cudf.bz2` instead of `<api>/cudf` if bzip2 is available.

In fact, with the new, more expressive `OPAMEXTERNALSOLVER`/`--solver`/`.opam/config:solver field`, it could be used by calling curl directly without any script (the above quirks put aside), with
```
OPAMEXTERNALSOLVER='curl -f --data-binary @%{input}% -o %{output}% http://cudf-solvers.irill.org/cudf?criteria=%{criteria}%'
```
or in `~/.opam/config`:
```
solver: [ "curl" "-f" "--data-binary" "@%{input}%" "-o" "%{output}%" "http://cudf-solvers.irill.org/cudf?criteria=%{criteria}%" ]
```

The server could trivially be done with a cgi binding to aspcud (although they weren't quite clear about it, I think that's the real reason why the guys at Irill didn't share the server source: they thought it was just server configuration).

**Comment by avsm** [comment]
> The server could trivially be done with a cgi binding to aspcud (although they weren't quite clear about it, I think that's the real reason why the guys at Irill didn't share the server source: they thought it was just server configuration).

Or we could provide a Cohttp wrapper that directly spins up and serves Aspcud without the need for a webserver.

**Comment by AltGr** [comment]
That's clearly the idea! that would probably be just a few lines of OCaml. (I said cgi, but I don't think that's how the irill solver farm handles it).
From opam, maybe we should just accept an url as argument to `--solver` ?

**Comment by avsm** [comment]
or perhaps a `solver-url` field that takes priority over the `solver` command line (in the interests of avoiding detection magic)?  That would let OPAM use its builtin URL retrieval mechanism, which is definitely better than recreating it on the `solver` command line.

**Comment by rdicosmo** [comment]
This issue has been discussed at length for a couple of years, see for example
https://github.com/ocaml/opam/issues/685 (first gentle call for volunteers to work on a solver farm)
https://github.com/ocaml/opam/issues/1371 (first proposal to directly support a solver farm in Opam)

It seems that the opam repo has now grown to the point that direct support in
opam for accessing one (out of several) solver farms is something that would
definitely benefit end users, and the logic to be implemented is rather
straigthforward (from #1371):

   IF a local external solver is available, use it (1) 
   ELSE IF one (out of several) solver farm is available, use it (2) 
        ELSE use the internal solver, warn the user and accept its limitations (3) 

As @AltGr recalls, the protocol to be used in (2) is quite trivial, just a
typical http request, and one can implement the server side part in a 
variety of manners. http://cudf-solvers.irill.org/index.html is one of them.

Some concerns were rised about the fact that (2) might leak confidential
information over the network, which some companies might consider problematic.
One might add a configurable warning message in (2) informing the user that his/her
Opam package status is going to be sent to an external server, and giving the
option to fallback on (3). The same fallback may be used if the solver farm
is too busy or unavailable.

Let me add that I have nothing against working towards a cudf-solvers.ocaml.org,
with proper credits given. A first step might be to point cudf-solvers.ocaml.org
to cudf-solvers.irill.org

Cheers

--
Roberto

**Comment by AltGr** [comment]
Built-in mccs solver resolves this!
