### ISSUE TITLE
Make internal-solver fallback work again

### ISSUE THREAD

**Issue by rdicosmo** [ocaml/opam#1280]
Commit 960a7b4734a52715e70c3bb2395b1f5d3464011b disables the currently broken fallback to the internal solver, adding this issue to remember to fix it sometimes in the future.

**Comment by AltGr** [comment]
Current behaviour (advertise `--use-internal-solver` rather than run it already) has the merit of being clear what happens to the user, and avoiding a fallback that adds pitfalls to the situation. Shouldn't happen anyway, and that also makes sure the error is not overlooked in case it does, so it seems ok as it is for now.
