### ISSUE TITLE
opam should map available ocamlfind packages to installed opam packages

### ISSUE THREAD

**Issue by ygrek** [ocaml/opam#1434]
So that `opam info` could show the list of ocamlfind packages provided by installed opam package.
This seems to be easy to do - just call `ocamlfind list` prior and after the installation.
Next convenience could be to map module names to ocamlfind packages. That can be of course done without opam : 

```
let modules name =
  let (|>) x f = f x in
  Findlib.package_directory name |>
  Sys.readdir |>
  Array.to_list |>
  List.filter (fun s -> Filename.check_suffix s ".cmi") |>
  List.map (fun s -> String.capitalize (Filename.chop_extension s)) |>
  List.sort compare |> String.concat " " |> print_endline
```

From my observation that's one of the points that traps novices often - the correspondence between library names, ocamlfind package names, ocaml modules and now opam package names. It would be great if this information was available in one place. The advantage of doing this for installed packages only is that it is 100% automatic and correct.

**Comment by AltGr** [comment]
Since installations are now unparallelised (while builds are), and we actually have hooks that can be set in opam's configuration, one so inclined could experiment with this using calls to `ocamlfind list` and diff.
Something like (in `~/.opam/config`, or `~/.opam/<switch>/.opam-switch/switch-config`):
```
pre-install-commands: [ ["sh" "-c" "ocamlfind list >ocamlfind_list"] ]
post-install-commands: ...
```

You could also use `opam search --owns-file` on the installed `META` files, which would be simpler, though.

**Comment by dra27** [comment]
@AltGr - presumably this is now much easier/faster to do with the directory tracking change?

**Comment by AltGr** [comment]
With #573 solved, and, more importantly, the new `jbuilder` ecosystem and better guidelines on the opam/ocamlfind package relationship, I think we should (soon) be OK about this ?
