### ISSUE TITLE
opam install options for depopts

### ISSUE THREAD

**Issue by Drup** [ocaml/opam#1494]
Would it be possible to have an option (compatible with --deps-only) to install all the optional dependencies of a package ? 

It would be useful in the context of CI, for example.

**Comment by maroneze** [comment]
This feature is exactly what we need. Is it somehow still available on opam 2? The `-e` option does not exist anymore.

Otherwise, we considered creating a new package, say `<package>-full`, which installs all the optional dependencies listed in `<package>`; but maintaining two dependent packages is much more cumbersome, so we'd like to avoid it if possible.
