### ISSUE TITLE
Aborted opam pin should not leave a package as pinned.

### ISSUE THREAD

**Issue by vbmithr** [ocaml/opam#1719]
When I Ctrl-C a command, I like the state of the program to be rollbacked to before I typed the aborted command. This is not the case with opam pin.

**Comment by AltGr** [comment]
I'm not sure about this, when you C-c in the middle of package installations (or removals), opam doesn't roll-back; here, the pinning command is actually instant, and it's only the following action (install, reinstall, unless you specified `--no-action`) that takes time. From that point of view, it makes sense to only cancel the ongoing state, and not the complete pin (esp. since one may have been wanting to pin, but the precise resolution doesn't fit, or `--no-action` was just forgotten).

Also, in one case you'd need to re-run the pin with `--no-action`, in the other, to run `opam unpin`. In case you just mistyped the target, you can `opam pin add` again in any case.

**Comment by AltGr** [comment]
Related to  #1492

**Comment by AltGr** [comment]
I still think this makes sense as it is, and at least opam prints a clear message (`[NOTE] Pinning command successful, but your installed packages may be out of sync.`) upon this happening, so leaving as is.
