### ISSUE TITLE
Switching compilers requires GCC and fails on FreeBSD

### ISSUE THREAD

**Issue by michipili** [ocaml/opam#1837]
Starting with FreeBSD 10.0 (IIRC) the compiler GCC is not part of the base system — which uses CLANG instead. This causes `opam switch` to fail on a system where GCC is not installed:

```console
% opam switch 4.01.0
…
# 5 shift/reduce conflicts.
# Warning: Element Mutex.t not found
# gcc: not found
# gmake[3]: *** [amd64.o] Error 2
# gmake[2]: *** [makeruntimeopt] Error 2
# gmake[1]: *** [opt-core] Error 2
# gmake: *** [world.opt] Error 2
```

Either should OPAM check for GCC or the FreeBSD package should depend on GCC.

----
```console
% uname -a
FreeBSD llea 10.0-RELEASE FreeBSD 10.0-RELEASE #0 r260789: Thu Jan 16 22:34:59 UTC 2014     root@snap.freebsd.org:/usr/obj/usr/src/sys/GENERIC  amd64
```

**Comment by jorisgio** [comment]
Hi, i am supposed to be the package maintainer for opam on freebsd. The issue is that i never had a FreeBSD system, i used to package and use opam on DragonFlyBSD. Although quite similar, this is the sort of issue i wouldn't be able to detect. And now, i don't even use opam on DragonFly anymore.
That's to say that the package needs some love, and if someone actually uses opam on FreeBSD and wants to take the port in charge, it would probably be much better than the current state. Sorry about that.

**Comment by michipili** [comment]
Okay I'll take it.

**Comment by hannesm** [comment]
for me, on FreeBSD-CURRENT my opam just uses cc for compiling the runtime...

**Comment by michipili** [comment]
I opened the ticket one an half year ago, it is probably worth checking this again. :)
