### ISSUE TITLE
Discuss "opam changelog"

### ISSUE THREAD

**Issue by Drup** [ocaml/opam#1900]
Following https://github.com/AltGr/opam-publish/issues/8. An "opam changelog" tool would be very nice. I'm not sure how it should be implemented though.

**Comment by haselwarter** [comment]
It would easy enough to have a build target that generates a "ChangeLogNews" that could then be printed after an upgrade.
The requirements are
1) having access to pre-upgrade version of the package installed
2) using a file generated during package generation as post-message

In fact, instead of (1) it would be even more useful to access the state of the previous install. Then one could simply store the version number, which may or may not be the opam package version number, in some file. I guess %{share_root}% could be abused for that, putting a file there with install and then not removing it, but there should be a cleaner way. Reminds me of how apt-get distinguishes between remove and purge. opam upgrade should do a remove, not a purge, which could let some files survive.

**Comment by dbuenzli** [comment]
> It would easy enough to have a build target that generates a "ChangeLogNews" that could then be printed after an upgrade.

Usually I upgrade more than one thing at the time and it's not immediately after install that I need this information. Also it's not only the latest version release note that matter, it's just the first one you'd like to see, which is easy to provide by writing them at the top of the `CHANGES` file.

The [`odig`](http://erratique.ch/software/odig) tool will allow you to look up for `README` and `CHANGES` if they are installed in the `doc` directory. Simply invoke `odig changes PKG`.

**Comment by dbuenzli** [comment]
Unless people disagree I think `odig` provides a good solution to this and this can be closed.

**Comment by Drup** [comment]
I agree, odig provides a good solution for this.
