### ISSUE TITLE
How to opam switch to local fork of OCaml

### ISSUE THREAD

**Issue by jordwalke** [ocaml/opam#1930]
It wasn't clear to me based on the OPAM instructions:
How do we point OPAM switch to a local fork of the OCaml compiler. Suppose I'd like to test compiler changes easily and switch back and forth between this version and the official versions. I do not have my local OCaml fork installed as the system OCaml compiler because I may want to have several forks locally and making them the system compiler would be such a hassle (because you don't have OPAM to manage that - it's "make install" etc).

So how can I point OPAM switch to a particular directory that contains my OCaml fork (and build artifacts)? It's so easy to point at a GitHub pull request. I'm assuming it's as easy to point to a local directory but I didn't see it mentioned.

**Comment by Drup** [comment]
This is actually more annoying that it could be, because there is no notion of "pins" for compilers as there is for packages. The current solution is to create a custom local repository and add a compiler in this repository that points to a local path.

**Comment by AltGr** [comment]
Actually, I've merged the base changes needed for putting compilers in packages ; not what you could call user-friendly yet, but you're very welcome if you want to try and experiment with it, as this is possibly a use-case where it'll prove useful.

The idea is quite simple: you're now allowed to define a compiler without build instructions or source, and that is not a system compiler -- so basically that's just the seed for a blank switch. Any entries you put in the `packages` field of the [compiler definition](http://opam.ocaml.org/doc/manual/dev-manual.html#sec24) will be considered as "base", immovable packages (we may relax some constraints, step by step, later on). These must be self-contained and will be installed at switch installation, but you don't actually have to specify any.

There are mainly two shortcomings at the moment:
- all packages should have an (implicit?, build-) dependency on the compiler package. At the moment you'd be allowed to change the compiler without recompiling anything, if it's not a base package or you pin it.
- lack of a mechanism for detecting and updating depending on external stuff (like we have for the system compiler) ; but that would benefit from a more general implementation covering depexts.

Here is an example of a `4.02.1+blank.comp` you could use:
```
opam-version: "1.2"
version: "4.02.1"
env: [ CAML_LD_LIBRARY_PATH = "%{lib}%/stublibs" ]
```
(you still need to add a local repo at the moment. But that's just (i) `mkdir -p myrepo/compilers` (ii) put your `.comp` file there (iii) `opam repo add myrepo`)

And a possible ocaml compiler package definition which you can pin:
```
opam-version: "1.2"
maintainer: ""
build: [
  ["./configure" "-prefix" prefix "-with-debug-runtime"]
  [make "world"]
  [make "world.opt"]
  [make "install"]
]
```

If you want to play more, the script `admin-scripts/compilers-to-packages.ml`, if run at the root of a repository, will rewrite all compilers to move their source to newly created versions of the `ocaml` package, and transform all packages' `ocaml-version` field to a dynamic dependency on the ocaml package. It doesn't add explicit dependencies to `ocaml` otherwise, though it would be trivial to change it to do so.

Ah, of course, you'll need to be on a recent master too, 1.2.0 won't do.

**Comment by jordwalke** [comment]
Why is it so easy to do this with github pull requests, yet more complicated for something local? Is there some way to simulate a pull request by creating a local git repo, without having to actually submit the pull request to github?

**Comment by AltGr** [comment]
It's not easy with github pull-requests. It's just that machinery has been put in place to automate it (get info from the PR and create the corresponding compiler description). The program that does it is here: https://github.com/avsm/opam-sync-github-prs

But as I said, we're working on making it easier to play with custom compilers.

**Comment by jordwalke** [comment]
I see. Sounds great.

**Comment by avsm** [comment]
Yep, the compilers-as-packages branch will make it much easier to treat a custom compiler just like any other development package.  Until then also see @gasche's https://github.com/gasche/opam-compiler-conf for local OCaml trees.
