### ISSUE TITLE
New conflicts force removal instead of upgrade

### ISSUE THREAD

**Issue by dsheets** [ocaml/opam#1974]
```
$ opam reinstall doc-ock-lib --cudf=kill-dnscurve
=-=- Synchronising pinned packages =-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=
[doc-ock-lib] /home/dsheets/Code/doc-ock-lib already up-to-date
The following actions will be performed:
  ⊘  remove    dnscurve    0.3.0 
  ↻  recompile doc-ock-lib 0.0.0*
  ⊘  remove    dns         0.13.0
  ↻  recompile doc-ock-xml 0.0.0              [uses doc-ock-lib]
===== ↻  2   ⊘  2 =====
Do you want to continue ? [Y/n] n
```

<https://gist.githubusercontent.com/dsheets/68f716ea91dbc57a7d2d/raw>

Adding `-count(removed)` to `OPAMCRITERIA` does nada.

```
$ opam config report
# OPAM status report
# opam-version    1.2.1
# self-upgrade    no
# os              linux
# external-solver aspcud
# criteria        -count(removed),-notuptodate(request),-count(down),-notuptodate(changed),-count(changed),-notuptodate(solution)*
# jobs            4
# repositories    0 (http), 3 (local), 2 (version-controlled)
# pinned          4 (version control)
# current-switch  doc
# last-update     2015-02-01 17:02
```

**Comment by dsheets** [comment]
Probably a case of new constraints causing confusion without an error message.

See:

```
$ opam remove doc-ock-lib
Your request can't be satisfied:
  - dns.0.13.0 is in conflict with io-page.1.3.0

No solution found, exiting
```

**Comment by dsheets** [comment]
The `io-page` conflict on `dns.0.13.0` was new during an update. To my mind, acceptable solutions are downgrading `io-page` (`io-page.1.3.0` was an installed root) or upgrading `dns` to 0.14.0 (which fails during compile in this case because `dnscurve.0.3.0` uses an interface changed by `dns.0.14.0` but it is an acceptable solution by the constraints).

In either case, some kind of message about new conflicts (during update) or actions taken due to discovered conflicts (during install) would be nice. I don't understand why removal of an installed root (and a dependency) is the right solution for a new conflict.

**Comment by AltGr** [comment]
Hm, complex situation indeed. There is a message on new conflicts after update (advertising `fixup`), but it's actually triggered if conflicts would be happening on an `upgrade` command, and not just if conflicts appeared in your current state: this should probably be changed. In your case the conflict happened on `remove` but not on `upgrade`.

As soon as you are in an inconsistent state, the solver will attempt to fix that _besides_ solving your request, which may lead to weird answers, or plain conflicts. `reinstall`, in order to minimise changes, uses the same criteria as `fixup` which are, by default, `-changed,-notuptodate` (overriden by `--criteria` or `OPAMFIXUPCRITERIA`) ; these criteria explain the answer you got from `opam reinstall`, they were not expected to run from an inconsistent state.

Two more remarks on implementation details: (i) tracking the cause of each action is done by an heuristic that is actually run after the solver (and based on the actions that you asked for), and is just for information -- we can't really track which actions have been caused by the new conflict. (ii) the solver makes no difference between roots and automatically installed packages (there is no weight on packages), some commands do

**Comment by dsheets** [comment]
some commands do...?

**Comment by AltGr** [comment]
Some commands behave differently for "root" packages, like `remove -a` (obviously), but also `upgrade --fixup`
