### ISSUE TITLE
Pinning workflow not detecting preexisting opam file in 1.2.1

### ISSUE THREAD

**Issue by avsm** [ocaml/opam#2015]
I have an `opam` file in this new package, but then pin ignores it.

```
$ opam pin add lterm-progress-bar .
Package lterm-progress-bar does not exist, create as a NEW package ? [Y/n] y
lterm-progress-bar is now git-pinned to /Users/avsm/src/git/avsm/ocaml-progress-bar
[NOTE] Pinning in mixed mode: OPAM will use tracked files in the current working
       tree from /Users/avsm/src/git/avsm/ocaml-progress-bar. If this is not what you want, pin to a given branch (e.g.
       /Users/avsm/src/git/avsm/ocaml-progress-bar#HEAD)

[lterm-progress-bar] /Users/avsm/src/git/avsm/ocaml-progress-bar already up-to-date

Invalid opam file:
    error: File format error: at ~/.opam/system/overlay/lterm-progress-bar/opam_:9:11, Bad url format ""
Errors in /Users/avsm/.opam/system/overlay/lterm-progress-bar/opam, retry editing ? [Y/n] n
[ERROR] No valid metadata available.
lterm-progress-bar is now unpinned from git /Users/avsm/src/git/avsm/ocaml-progress-bar
```

It brings up an editor, despite there being an `opam` file in the current directory...

**Comment by AltGr** [comment]
Did you `git add` the opam file ? Since it's "mixed mode", it's otherwise invisible to OPAM.

**Comment by avsm** [comment]
Hm, so mixed-mode as a default is a change in behaviour from 1.2.0.  This is a bit of a surprise, since it can never work with `opam pin add` by default since the newly created `opam` file wont be tracked...

I reckon defaulting to the old behaviour is least surprising.  Perhaps exporting a OPAMPINMODE variable would make it easier for advanced users to control what they want.

**Comment by AltGr** [comment]
Er, we had two old behaviours actually, both of which had their surprises. I am still confident, that, after the discussions last year, this new compromise is the best choice ; a better solution here may be to make an exception for the `opam` file, retrieving it at the source rather than in OPAM's mirror.

We could go as far as having the `"Do you want to save the opam file back to the source dir"` feature `git add` the file, but I know I personnaly wouldn't like it at all (nobody messes with my git ;)).

**Comment by avsm** [comment]
Changing the behaviour in a point release isn't ideal... I just want to upgrade and not have all my scripts and workflows break.  It also becomes essential to explicitly specify the pin type in all tutorials, as we won't know if users are on 1.2 and 1.2.1

I agree that this is a more sensible default, but I think it should be added as an option to 1.2.1, and made the default in 1.3

**Comment by AltGr** [comment]
Two things have been changed actually:
- When VC-pinning without specifying the HEAD (branch, tag...), mixed mode is turned on, which means OPAM will fetch the latest on-disk state of version-controlled files (only) rather than just `git clone` or equivalent
- When doing `pin add`, VC pinning is used rather than path pinning if a VCS is found at the given source path. Which effectively uses the above.

Ref #1868 for context.

So there isn't really an option to add, `--kind` is there already ; but disabling VC detection like in 1.2.0 would be easy, although @dbuenzli sure won't be happy :p. Adding e.g. `--kind auto` and an env/configuration variable `OPAMPINKIND` could indeed be an option though.

To be honest, I am quite surprised it breaks scripts and workflows that badly at this point. Then again this was maybe the first patch after 1.2.0 got out so I got plenty of time to get used to it.
