### ISSUE TITLE
opam wide installation, strange lock problem

### ISSUE THREAD

**Issue by william3** [ocaml/opam#2029]
I use opam and would like to setup an ocaml installation for several users. So I installed opam in a shared linux folder. Opam works fine for me, but for some unknown reason since recently, it does not work for the others.

Opam is installed in a shared folder /path/to/opam-v1.2 : 
drwxrwsr-x 10 myself    mygroup      4096 feb. 24 14:03 opam-v1.2

If someone else connects to a new terminal, with the following two lines in their .bashrc : 

export PATH="/path/to/opam-build/bin:$PATH"
eval `opam config env --root=/path/to/opam-v1.2/`

They get the following error : 

opam: "open" failed on /path/to/opam-v1.2/lock: Permission denied
Backtrace:
  Raised by primitive operation at file "core/opamSystem.ml", line 517, characters 4-56
  Called from file "core/opamFilename.ml", line 328, characters 13-52
  Called from file "client/opamArg.ml", line 981, characters 27-77

After that, Everyone gets the problem, even myself, because of the following file in /path/to/opam-v1.2: 
-rw-------  1 someoneelse mygroup         0 feb. 24 14:03 lock

until I do : 
rm /path/to/opam-v1.2/lock

In order to solve this issue, I remembered a setup that disappeared from your documentation. Instead of using : 
export PATH="/path/to/opam-build/bin:$PATH"
eval `opam config env --root=/path/to/opam-v1.2/`
I tried to use 
. /path/to/opam-v1.2/opam-init/init.sh > /dev/null 2> /dev/null || true

It solved the lock problem, but there was an new issue : init.sh calls /path/to/opam-v1.2/opam-init/variables.sh which has a setup different from the result of "opam config env". In "opam config env  --root /path/to/opam-v1.2/" : 
CAML_LD_LIBRARY_PATH="/path/to/opam-v1.2/4.02.1/lib/stublibs"; export CAML_LD_LIBRARY_PATH;
while in /path/to/opam-v1.2/opam-init/variables.sh : 
CAML_LD_LIBRARY_PATH=/path/to/opam-v1.2/4.02.1/lib/stublibs:/usr/lib/ocaml/stublibs; export CAML_LD_LIBRARY_PATH;

So to solve the lock problem : 
- remove /path/to/opam-v1.2/lock
- replace in file /path/to/opam-v1.2/opam-init/variables.sh the lines according to the output of "opam config env --root=/path/to/opam-v1.2"
- replace, for third party users, configuration lines like "eval `opam config env --root=/path/to/opam-v1.2/`" with : 
. /path/to/opam-v1.2/opam-init/init.sh > /dev/null 2> /dev/null || true

And there are actually 3 issues : 
* the lock problem
* inconsistancy between /path/to/opam-v1.2/opam-init/variables.sh and "opam config env --root=/path/to/opam-v1.2"
* no documentation on system wide installation good practice, such as using /path/to/opam-v1.2/opam-init/variables.sh (and probably it is not the right way) The idea is that other users should not acces opam, just ocaml configuration.

Best regards

**Comment by AltGr** [comment]
Thanks for reporting. Do you know if there was an OPAM version upgrade at this point, and from/to which version ? Locking behaviour changed a bit in 1.2 (proper use of `flock()`

On the details:
> * remove /path/to/opam-v1.2/lock

Gah. The issue seems to be that the lock file is only user-readable, so the other user's OPAM process fails to open it. This is normally a read lock so locking itself shouldn't block once you opened the file (unless you are in the middle of e.g. an `opam install`, in which case, it should). What's weird is that `opam config env` doesn't normally need any lock, but that may have been the case in older versions. Anyway, this error should be avoided by:
  - making the lock file world-readable (modulo _umask_)
  - opening the file read-only for read locks

I'll look into it

> * variables.sh issue

This is a [known bug](https://github.com/ocaml/opam/issues/1874) in 1.2.0, now fixed (in either trunk or the 1.2.1 beta).

> * documentation for system-wide installation

Indeed, there should at least be some hints in the [opam Tricks](http://opam.ocaml.org/doc/Tricks.html) page. In your case, other users should indeed not have write access to the OPAM dir, or even actually need the `opam` command, unless you want to allow them to change the installation -- so giving them a static file to source in their shell seems quite right, given it's compatible with their shell.

There have also been questions on _serving_ the OPAM root, for example through NFS: it's a close use-case, but raises a couple of other questions (compiling over NFS, keeping the same PATH accross machines, and `flock()` not working).

**Comment by william3** [comment]
"Do you know if there was an OPAM version upgrade at this point, and from/to which version ? Locking behaviour changed a bit in 1.2 (proper use of flock()"
The directory "/path/to/opam-v1.2/" was dedicated to the new version 1.2. It is possible that at some point two versions were used simutaneously (during transition from old to new repository), though I don't think it is related.

**Comment by AltGr** [comment]
Hm, ok. The issues on file permissions for the lock files should be fixed now -- left open for the documentation issue.

**Comment by RandomDSdevel** [comment]
@AltGr:  Hurrah!  Can you leave an update on this at #1950, too, though?
