### ISSUE TITLE
The documentation for `opam pin --kind` is wrong

### ISSUE THREAD

**Issue by samoht** [ocaml/opam#2033]
```
 -k KIND, --kind=KIND
           Set the kind of pinning. Must be one of version, path, git, hg or
           darcs.
```

`mixed` is missing.

**Comment by dbuenzli** [comment]
According to what I [read here](https://github.com/ocaml/opam/blob/9ad5b763d8b762ba0e8331c87d103cff29bfc1a1/src/client/opamArg.ml#L1533-L1556) `mixed` doesn't exist. But I don't understand why @AltGr decided not to document `rsync` and `local`.

**Comment by AltGr** [comment]
`mixed` is used for any VCS when on the filesystem and without a branch specification (`#foo` suffix). it's not a mode in itself -- you'd need git-mixed, hg-mixed, etc. It's explained [here](https://github.com/ocaml/opam/blob/9ad5b763d8b762ba0e8331c87d103cff29bfc1a1/src/client/opamArg.ml#L1491-L1494) and you'll actually get a `[NOTE]` when it's enabled.
Thanks to latest `cmdliner`, the list is printed using `Arg.doc_alts_enum` so it doesn't risk to get outdated as much. `rsync` and `local` being synonyms to `path`, I prefer to deprecate them (OPAM will print it as `path` pinned anyway, so that could get confusing).
