### ISSUE TITLE
Deprecating packages

### ISSUE THREAD

**Issue by dbuenzli** [ocaml/opam#2046]
Is there a package deprecation mechanism in opam ? 

I would like to deprecate [`rtime`](http://erratique.ch/software/rtime) which was a proof of concept module and I highly doubt anybody is using it (I don't). 

Maybe a field could be introduced in opam files for that. Adititional useful metadata would be a global reason for deprecation (e.g. to warn the user on usage) and a list of `package * reason` alternatives for the package (I'm thinking here about the case of a package that has been exploded in sub packages).

**Comment by AltGr** [comment]
Nothing dedicated at the moment, but indeed, worth thinking about.
Your best option at the moment is to use the `messages:` field:
```
message: "DEPRECATED. This package is outdated, you should consider using xxx instead" {installed}
```
which would yield, upon installation:
```
The following actions would be performed:
  ∗  install   foo  0.1*  
       DEPRECATED: This package is outdated, you should consider using xxx instead
  ↻  recompile bar 0.1.2*
===== ∗  1   ↻  1 =====
```

**Comment by dbuenzli** [comment]
Well actually this + adding `deprecated` in the `tags:` field seems enough to me. No need to engineer something here. Maybe add it to the FAQ ?

**Comment by avsm** [comment]
Looks good, except for capitalising 'deprecated'.  I HATE IT WHEN COMPUTERS SHOUT AT ME.

**Comment by dbuenzli** [comment]
@avsm Actually consistency would then rely on the packagers. I'd prefer if we had a scheme like if a package has an `opam:deprecated` tag then something happens ui-wise.

**Comment by avsm** [comment]
Yep. However, we can enforce the consistency in the short term via keeping an eye on merged requests.

**Comment by gasche** [comment]
Can we use the same mechanism to deprecate switches? Hugo Herbelin ( @herbelin ) got bitten by the fact that 4.02.0 has really long compile times, and it would be nice if we could keep the switch available (for version-compat testing etc.) but effectively discourage users from using it.

Is this use-case for "messages" documented somewhere?

Re. 4.02.0: maybe another solution would be to backport, in the 4.02.0 switch, the compile-time regression fix so that future users don't notice the problem anymore. Any opinion?

**Comment by gasche** [comment]
Thinking about this issue more: the workflow I would like to have for a deprecated switch (or a deprecated version of a package) is to be warned about the deprecation *before* the installation starts, and OPAM to ask me confirmation that I really want to install this version (with "no" being the default). My understanding of the `messages` workaround is that I will only be warned after some time spent compiling the bad package/compiler. If that is correct, then I would really be interested in proper OPAM support for "are you sure? This version is deprecated because <blah> and we really recommend using <foo> instead".

**Comment by avsm** [comment]
You could create a `conf-coq` package that checks for the prerequisites (such as a reasonable OCaml version).

**Comment by gasche** [comment]
OCaml maintainers may want the ability to tell *anyone* trying to use the 4.02.0 switch (not just Coq developers) that it is not a good idea. (I think this would also be useful for packages, not just switches.)

Through discussing with Hugo I understood that fixing this issue at the OPAM level is really important. Indeed, the webpages make it hard to install 4.02.0 (they will propose you 4.02.3 by default and you have to dig through the website to find the old tarballs). On the contrary, with OPAM it is no harder to install 4.02.0 than any 4.02.x version: just type `opam switch install 4.02.x`. The distracted user (not closely following OCaml upstream) that thinks "oh let's just test my code on some 4.02" may very well start with 4.02.0 -- without thinking of checking the website first.

**Comment by agarwal** [comment]
For now, updating the [descr](https://github.com/ocaml/opam-repository/blob/master/compilers/4.02.0/4.02.0/4.02.0.descr) should help. Just add "(deprecated)" to the string.

Compilers are not often deprecated, so my 2 cents is that engineering a solution for that use case isn't justified. Deprecating packages sounds more useful to me. This discussion is related to #1879.

**Comment by agarwal** [comment]
> Re. 4.02.0: maybe another solution would be to backport, in the 4.02.0 switch, the compile-time regression fix so that future users don't notice the problem anymore. Any opinion?

That sounds wrong to me. Releases should not be modified. If you change 4.02.0, it isn't 4.02.0 anymore. You'd have to bump the version number, but that is basically what 4.02.1 already is.

**Comment by gasche** [comment]
But users don't care about the description of OCaml versions (they know what it is!), they just type `opam switch 4.02.0` and they're done. Re. engineering efforts, I expect that any work towards deprecating switches could be shared with deprecating packages -- and if my understanding of the downsides of the proposed workaround is correct, this feature would also be useful.

**Comment by agarwal** [comment]
> But users don't care about the description of OCaml versions

Right, but it _might_ get noticed earlier because the description shows up when you do `opam switch`.

```
$ opam switch
--         -- 3.11.2      Official 3.11.2 release
--         -- 3.12.1      Official 3.12.1 release
--         -- 4.00.0      Official 4.00.0 release
--         -- 4.00.1      Official 4.00.1 release
4.01.0      I 4.01.0      Official 4.01.0 release
--         -- 4.02.0      Official 4.02.0 release
--         -- 4.02.1      Official 4.02.1 release
4.02.2      I 4.02.2      Official 4.02.2 release
4.02.3      I 4.02.3      Official 4.02.3 release
```

The 4.02.0 line would instead be:
```
--         -- 4.02.0      Official 4.02.0 release (deprecated)
```

**Comment by dbuenzli** [comment]
> Re. engineering efforts, I expect that any work towards deprecating switches could be shared with deprecating packages

@gasche work is ongoing to treat compilers as packages. So deprecating switches may not make much sense in the future.

**Comment by herbelin** [comment]
To support Gabriel, there is a real problem of information. I have no idea of the proportion of users liable to encounters problems as critical as we observed for Coq (several files taking more than 20s to compile, up to 120 times slower than other versions), but if the case of Coq is not isolated, then, it seems reasonable to me that 4.02.0 could not be installed without being aware that it suffers from development-critical compilation performance issues (so thanks already for #727).

As for Coq, we already planned to have our configure file ruling out ocaml 4.02.0, and I guess that any package maintainer suffering from similar redhibitory compilation times would do the same.

By the way, what are the reasons for maintaining 4.02.0 as a "standard" compiler. For instance, I don't see 3.12.0 in the main list, so not all versions have to be there. So, why not to simply remove it or at worst to downgrade it in the list so that it is visible only by doing "opam switch --all". Wouldn't that make things easier?

**Comment by AltGr** [comment]
@gasche I am actually in the process or _removing_ .comp files, merging their functionality with the opam files, which would effectively solve the issue.

**Comment by gasche** [comment]
@AltGr so you confirm that an equivalent deprecation mechanism (that warns *before* the package is installed and asks for user confirmation) already exists (or will exist) for packages?

**Comment by AltGr** [comment]
- using `messages:` will warn before installation (although it doesn't add a confirmation step)
- removing packages from the repo can now be done without fear of breaking other packages thanks to Camelus
- an option could be to move deprecated packages to another repo so that people wanting them can still get to them
