### ISSUE TITLE
Shortcut to run the build step on locally pinned packages.

### ISSUE THREAD

**Issue by jordwalke** [ocaml/opam#2049]
Is there a way to run *only* the build step for locally pinned packages? I expected such a command to be `opam build`.

It seems that merely doing `opam install myPackage` within the locally pinned directory does not automatically build my package before installing it. Is this expected?

**Comment by jordwalke** [comment]
I believe the build step may have been called but the errors were not printed. I will reopen if I can reproduce the issue.

**Comment by AltGr** [comment]
Note that the package is built within a clone inside `~/.opam`, not directly in its source directory -- maybe some confusion arose from there. With this in mind, `opam build` would only be useful to check for errors. It may be worth it in the future, but due to the fact that in OPAM 1.1 there was only a `build:` field, including the install instructions, many packages still don't use the `install:` field. In this case, just running the build could actually install the package, so that would be a bit dangerous.

**Comment by AltGr** [comment]
Related: #1805

**Comment by avsm** [comment]
Also related to sandboxing...
