### ISSUE TITLE
Detecting suspicious depopts

### ISSUE THREAD

**Issue by cakeplus** [ocaml/opam#2064]
OPAM should detect dependencies that are both in "depends" and "depopts".

It would help to avoid silly situations like this:
https://github.com/ocaml/opam-repository/pull/3763#discussion-diff-26660727

**Comment by samoht** [comment]
`opam lint` already does this I think.

**Comment by cakeplus** [comment]
Didn't know about `opam lint`, as a user of OPAM 1.1. Seems like a useful tool.
I've checked the sources, and it does indeed support this kind of a semantic check:
https://github.com/ocaml/opam/blob/1.2/src/core/opamFile.ml#L1554

Why not perform validation each time OPAM reads a file?

**Comment by AltGr** [comment]
Well, it may be costly, and basically, as a user you don't want to be bothered with all the warnings of all packages that wouldn't validate every time you start OPAM: running `opam lint` before adding a new package should be enough.

To be honest, though:
* this should be done automatically by the automated tests (it's currently only done either manually, or when using the `opam-publish` tool)
* lots of packages on the repository may have warnings, because they were there before `opam lint` and haven't been cleaned up.

**Comment by cakeplus** [comment]
Makes sense. Thank you.


> Well, it may be costly

I'm pretty sure it's not, given how tiny the typical package descriptions are. A proper benchmark would be needed, of course, for a sound claim. 


> lots of packages on the repository may have warnings, because they were there before opam lint and haven't been cleaned up.

Automatic and mandatory validation can be enabled for all the packages that have `opam-version: "1.3"`. Warnings, at the same time, can be considered errors. Why not render all ambiguous descriptions invalid, starting from a certain release of OPAM? The compatibility wouldn't be broken, as validation would be performed only for those packages that have an appropriate `opam-version`; yet it may spare lots of headaches in the long run.
