### ISSUE TITLE
Don't abuse UTF-8

### ISSUE THREAD

**Issue by planar** [ocaml/opam#2065]
When I set `LC_ALL=C` in the environment, `opam` should stick to the ASCII character set and give up all the fancy UTF-8.

This would help me greatly when scripting `opam` invocations.

**Comment by dbuenzli** [comment]
If you need a fix immediately `OPAMUTF8MSGS=no` should help. This will get rid of the fancy icons, but note that even with this it's hard to be UTF-8 clean since the fields of opam files are UTF-8 encoded so you cannot rule out that all invocations will never output UTF-8.

**Comment by AltGr** [comment]
There are two levels actually now:
* the former `OPAMUTF8MSGS` is enabled by default on OSX, it enables the action arrow characters (↻, ↗, ⊘ etc.) AND the camel emoji (🐫) (those are often unavailable while arrows are, so they are disabled by default)
* the newer `OPAMUTF8` enables just the action arrow characters, and defaults to `auto` which _should_ use the locale for detection. So that may be a bug. Maybe allowing from either `LANG` or `LC_ALL` is wrong ?

You may also set these in `~/.opam/config`

**Comment by planar** [comment]
According to `man 7 locale` on Linux:
> The details are implementation-dependent. For glibc, first (regardless of category), the environment variable LC_ALL is inspected, next the environment variable with the same name as the category  (LC_COLLATE,  LC_CTYPE, LC_MESSAGES, LC_MONETARY, LC_NUMERIC, LC_TIME) and finally the environment variable LANG.  The first existing environment variable is used.

I was expecting `opam` to use the same algorithm (thus having `LC_ALL` override `LANG`) but the first sentence means that I can't really call this an `opam` bug after all.

**Comment by AltGr** [comment]
Worth following anyway -- currently it's (LANG contains "UTF-8" OR LC_ALL contains "UTF-8"), whether they are defined or not.
