### ISSUE TITLE
More expressional power in optional dependencies

### ISSUE THREAD

**Issue by hannesm** [ocaml/opam#2074]
Hi,

I would like to package `gmp-crosscompiled-for-xen` as an opam package (let's name it `gmp-xen`).  "Normal" users should not bother to install this, but install the usual `conf-gmp`, and `zarith`. If there's a `mirage-xen` package installed on the host, I'd like to depend on `gmp-xen`. But it seems that `depopts` does not allow `formulas` (I'd really like to have `deptops: [ (mirage-xen & gmp-xen) ]` in `conf-gmp`. Is there any plan/idea to implement such a feature? Or am I too blind to find documentation how to fulfill such a use-case?

**Comment by hannesm** [comment]
can be solved by extending `conf-gmp` directly -- but atm this depends only on an external package. Extending would require to retrieve the gmp source (and I don't think there's a way to have optional urls) and also build with specific flags if `mirage-xen` is present.

**Comment by AltGr** [comment]
There are two parts to the answer:
* `depopts:` _used_ to be formulas, however with ill-defined semantics. Rather than change the meaning of things, I preferred to restrict them at least until the transition is done -- esp. since the worst consequence of the lack of expressivity is only extra rebuilds. There is a long history on this, you may for example at #1310.
* Normal formulas just compute a boolean result from an environment: the constraint is satisfied or not, allowing installation or not. Dependency formulas, though, are also used to compute recompilations -- in that case it is the packages they mention that we're interested in, not the end result. We do actually hit the same issue with a normal dependency to `a | b`, in which case we trigger recompilation whenever `a` or `b` changes, which is an over-estimate of the requirement -- but we can't do better (in this case).

Follows that allowing formulas for depopts, in the current state, wouldn't change anything. We could somehow reduce the over-estimate above, though, which is quite unrelated but could make it worthwile.

We could for example use an algorithm like this to extract meaningful dependencies from the formula rather than take all atoms:  (writing on the fly)
1. Convert the formula to DNF
2. Take all atoms in each conjunction **iff** the conjunction holds (in at least one of the _starting_ state and the _final_ state).

Don't think we can do much better (we can't decide which of the conjunctions is meaningful), and that would give the expected result in your case: with `deptops: [ (mirage-xen & gmp-xen) ]`, the depopt on mirage-xen is ignored if gmp-xen is absent (and unchanged), and conversely. Note also that top-level elements in `depends:` are implicitely linked by AND while top-level elements in `depopts:` are linked by OR.

**Comment by AltGr** [comment]
> can be solved by extending conf-gmp directly -- but atm this depends only on an external package. Extending would require to retrieve the gmp source (and I don't think there's a way to have optional urls) and also build with specific flags if mirage-xen is present.

There are no optional URLs, or even support for multiple URLs for a single package at the moment.

You may change your `./configure` flags depending on the current state though, using filters (http://opam.ocaml.org/doc/Manual.html#Filters). Even more advanced usage will be made possible with the `features:` field (see at the very end of the same page) -- but it's not allowed yet on opam-repository.

**Comment by samoht** [comment]
Would it be possible to add a `true` predicate in the syntax of formula? So we could write:

```
foo.opam:
[...]
depends: [
  "bar"
  (true | ("mirage-xen" & gmp-xen))
]
```

so that `opam install foo mirage-xen` will be forced to bring `gmp-xen`. We could also have a better syntax for that, say extending the `deptopts` field to allow arbitrary formulae :p

**Comment by samoht** [comment]
[I've edited my previous message]

**Comment by AltGr** [comment]
I'm pretty sure that's beyond the scope of our solvers: [Cudf](http://www.mancoosi.org/reports/tr3.pdf) only allows conjunctions and disjunctions of packages, and version constraints. Also, what would be the meaning of _e.g._ `! "mirage-xen" {> "1.2"}` ? In short, conflicts can't be expressed through depends.

We could, indeed, simulate it using  a `no-mirage-xen` package that conflicts with `mirage-xen`, then depend on `("no-mirage-xen" | ("mirage-xen" & "gmp-xen"))` ; then discard the `no-mirage-xen` package after solving. The issue with such tricks being they somehow break the solver criteria¹. My understanding is that it's not allowed directly in Cudf for fear of combinatory explosion ? @rdicosmo, @abate may have more precise answers.

IMHO, the good behaviour would be to depopt on either, and ignore them if you don't get them both. The only downside is some possible extra recomplations (which would be probably easier to fix). It seems weird to have your package _conflict_ with `mirage-xen` when `gmp-xen` is absent, should'nt it rather just not use it ?

¹ Well actually it might be possible to have them weight 0 and others weight 1, and change all criteria to count weight rather than number of packages. But well...

**Comment by abate** [comment]
I've already commented somewhere else. In debian they solved a similar problem by adding the so called build profiles. Dependencies are annotated with a tag and (I think the syntax is something like : depends: foo [arch1] {!profile1} | zut {profile2}, bar ) and are activated only when this tag is passed on the command line. You basically want the solver to figure out the state of the machine and choose one package or the other (foo or zut) . With build profiles instead you live this choice to the user or maybe to a higher level script that will activate a profile or not based on some conditions. 

The advantages of using this approach is that we do not change the nature of the underlying SAT problem (adding negation to the dependency clauses can open a can of worms and make it very difficult for our solver to give a timely answer. You will need a fully flavored sat solver instead of a specialized solver as aspcud or the internal solver of dose), and reduce the problem to a simple preprocessing phase. 

I think adding a simple feature like this one has potential to create problems in the future and it should be carefully considered.

**Comment by AltGr** [comment]
Actually, given the syntax, that would indeed be easy to do : we already have variables that can be used as filters, e.g. in build scripts; those are already restricted to global variables in the `available` field. This would be very useful for choosing dependencies depending on the OS, for example (#1993). The need above seems more complex, though, because we can't _statically_ decide the value of the variable.

**Comment by hannesm** [comment]
our current workaround is a virtual `mirage-no-xen` package (which conflicts with `mirage-xen`), and then such a dependency expression mentioned earlier: `(mirage-no-xen | (mirage-xen & foo))` (see https://github.com/mirage/mirage-dev/blob/2ead8d0032a85b8bf555b476d10d7b686a6dd656/packages/zarith/zarith.1.3/opam#L12)

**Comment by abate** [comment]
> The need above seems more complex, though, because we can't statically decide the value of the variable.

I don't understand why. These two approaches seems equivalent to me. instead of installing the package mirage-no-xen and let the solver do the rest, we could just add a dependency like `(mirage-xen & foo) {xen-enable}` and a conflict `xen-mirage {!xen-enable}`and let the user to decide whether this dependency should be used or not. the latter solution seems a bit more elegant to me as it does not force the user to install an additional virtual package only to force a dependency...

**Comment by AltGr** [comment]
The trick is that `mirage-no-xen` will get installed automatically: with this trick, there is no need for the user to explicitely specify anything.
- If `mirage-xen` is present:
    - either `gmp-xen` must get installed
    - or `mirage-no-xen`, and `mirage-xen` removed because of the conflict
  The solver criteria minimise removals, so the first option will be chosen.
- if `mirage-xen` is absent:
    - either the virtual `mirage-no-xen` is installed
    - or both `mirage-xen` and `gmp-xen` get installed
  The first will be chosen because it minimises the number of extra packages.

**Comment by samoht** [comment]
> The solver criteria minimise removals, so the first option will be chosen.

and because `mirage-xen` is explicitly added by the configuration tool.

> The first will be chosen because it minimises the number of extra packages.

and on some platform `mirage-xen` is not available, so `mirage-no-xen` will be selected and the installation will still succeed.

**Comment by AltGr** [comment]
Closing for now as no clear course of action emerged from the discussion.
