### ISSUE TITLE
opam still tries to delete `state.cache` on every invocation

### ISSUE THREAD

**Issue by samoht** [ocaml/opam#2077]
#2001 seems not to work properly. On a fresh clone I get:

I still see that error on a fresh cline

```
$ opam list --debug
00:00.005  SYSTEM                  locking /Users/thomas/.opam/lock
00:00.006  STATE                   LOAD-STATE(list)
00:00.010  CUDF                    Checking version of criteria accepted by the external solver
00:00.013  SYSTEM                  [log-23169-4438d8] (in 0.001s) aspcud -v
00:00.013  CUDF                    Solver is aspcud > 1.9: using latest version criteria
00:00.013  SYSTEM                  error: Wrong magic string in the cache (actual:1EAB7BBF expected:22EDDC0B).
00:00.013  STATE                   Invalid cache, removing: # opam-version    1.2.1 (55611833a7fa68ca48ff3e9944637c9f015162b4)
# os              darwin
Wrong magic string in the cache (actual:1EAB7BBF expected:22EDDC0B).
00:00.014  SYSTEM                  rm /Users/thomas/.opam/state.cache
00:00.327  STATE                   ROOT      : /Users/thomas/.opam
...
```

**Comment by AltGr** [comment]
On every invocation ? Do you get the same magic strings on the subsequent ones ?
Worrying :/

**Comment by samoht** [comment]
Yes

**Comment by AltGr** [comment]
WOW! found out... polymorphic functions are dangerous...
`OpamVersion.full` used to be a value, and is now a function from unit.
Alas, I failed to update the magic which was computed from `Hashtbl.hash full` :anguished: -- and the typer didn't help.

What is actually fun is that it more or less worked on Linux: any change to the binary was very unlikely to keep the same address for the function, but it was stable otherwise. OSX must have some stack randomisation into place, which made it always fail...
Crazy bug...

**Comment by avsm** [comment]
Oh oh, does this affect 1.2.1?

**Comment by AltGr** [comment]
I'm afraid so. Guess we'll have to roll out a 1.2.2 soonish :/

@samoht That doesn't explain that you consistenty got `(actual:1EAB7BBF expected:22EDDC0B)` though -- is that really the case?

**Comment by samoht** [comment]
Actually I just noticed that the hash changes on every invocation, so your diagnostic is right.
