### ISSUE TITLE
Different repositories for one package ?

### ISSUE THREAD

**Issue by Aaylor** [ocaml/opam#2087]
Is possible to have different git repository for one package, and make opam installing the correct repository according the compiler's version ?
I don't see any explanation about that on the documentation of opam. If it's not possible, it should be a great feature !

The use should be to maintain some package tools working for different compilers.
For example, with [ppx_tools](https://github.com/alainfrisch/ppx_tools), where it should be great to maintain to different version of ocaml compilers. Because it's using the AST itself, it's almost impossible to maintain the tool for old compilers (or experimental compilers) without breaking compatibility.

**Comment by AltGr** [comment]
It's not possible at the moment: since package sources can be relocated (using `opam pin`) and the archives cached, handling this would open several issues (with respect to metadata and definitions).

You can work around it, though, but you'll need to define multiple packages (possibly duplicating the `descr`, and the package metadata -- on the latter, duplicating build instructions for different sources makes sense actually).

Here is how you could do it:
* Define multiple packages _with different names_, e.g. `foo_3_12`, `foo_4_01` (each with their own versions). `foo_3_12` would have `available: ocaml-version = "3.12.0"` or similar, etc.
* Define a virtual package `foo` that has `depends: [ "foo_3_12" | "foo_4_01" | ... ]`

This way, `opam install foo` will get the right implementation for the compiler. If the versions are synchronised, you would give a bit more control (with the cost of extra work to maintain) by creating a version of the virtual package for each version of the implementation packages, with strict dependencies towards that version (e.g. `foo.12.1.opam > depends: [ "foo_3_12" {= "12.1"}...]`). This would give a nicer behaviour with `opam upgrade foo` for example.

Note that there should be a bit less burden once we get the `provides:` field (see the [preliminary specification](https://github.com/ocaml/opam/blob/master/doc/design/provides.md)), since you would just add `provides: "foo"` to your implementation package without defining the virtual package explicitely.

**Comment by samoht** [comment]
You can also just keep the same package name but provide a patched version. The upside is you don't have to have a virtual package, the downside is you have to release a new version of your patched package on every new release of `foo`:

```
foo.<version>+3.12
foo.<version>+4.01
...
```
