### ISSUE TITLE
Pin override pkg.install?

### ISSUE THREAD

**Issue by dsheets** [ocaml/opam#2095]
I'm working on a package that has a file `files/pkg.install` in the opam-repository but this install file is out-of-date with respect to the head of development but is correct for the last released version.

Is there something clever I can do to override this file? In the worst case, I can mess with opam remotes or make dummy packages or whatever but there doesn't occur to me a simple, 1-2 command way to override the incorrect install file. Ideas?

**Comment by AltGr** [comment]
There is! :)

If you place an `opam/` _directory_ at the root of your source, rather than an `opam` _file_, it will override all of OPAM's metadata, and not only the `opam` file. This is documented in the manual [here](opam.ocaml.org/doc/Manual.html#Metadataprecedence).

In your case you probably just have to do:
```
mv opam opam_
mkdir opam
mv opam_ opam/opam
```

**Comment by dsheets** [comment]
Doh! I knew there was a feature I was forgetting. Thanks!
