### ISSUE TITLE
Opam reinstall is not the same as uninstall followed by install

### ISSUE THREAD

**Issue by michipili** [ocaml/opam#2101]
While working on the next version of a pinned package (github) I need to reinstall the package to test my changes. I would like to use `opam reinstall github` which suggests the following plan:

```console
% opam reinstall github

=-=- Synchronising pinned packages =-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=  🐫 
[github.0.9.4] Synchronizing with /Users/michael/Workshop/ocaml-github
The following actions will be performed:
 - install   base-bytes.base                       [required by base64]
 - downgrade cmdliner from 0.9.7 to 0.9.5          [required by github]
 - install   ppx_tools.0.99.1                      [required by lwt]
 - downgrade type_conv from 112.01.01 to 109.53.02 [required by ipaddr]
 - downgrade ssl from 0.4.7 to 0.4.6               [required by github]
 - downgrade re from 1.2.2 to 1.2.0                [required by cohttp]
 - downgrade camomile from 0.8.5 to 0.8.3          [required by zed]
 - upgrade   stringext from 1.1.0 to 1.2.0         [required by github]
 - upgrade   ocplib-endian from 0.4 to 0.6         [uses base-bytes]
 - upgrade   base64 from 1.0.0 to 2.0.0            [required by cohttp]
 - downgrade sexplib from 112.24.00 to 111.11.00   [required by cohttp]
 - recompile fieldslib.109.20.03                   [uses type_conv]
 - upgrade   lwt from 2.4.5 to 2.4.6               [required by github]
 - downgrade zed from 1.3 to 1.2                   [required by lambda-term]
 - downgrade uri from 1.7.2 to 1.7.0               [required by github]
 - upgrade   ipaddr from 2.5.0 to 2.6.0            [uses base-bytes]
 - downgrade js_of_ocaml from 2.5 to 2.4.1         [required by github]
 - downgrade cstruct from 1.5.0 to 1.0.1           [required by conduit]
 - downgrade lambda-term from 1.8 to 1.6           [required by github]
 - recompile conduit.0.7.2                         [uses ipaddr]
 - upgrade   cohttp from 0.14.0 to 0.15.0          [required by github]
 - recompile github.0.9.4*
=== + 2   ↻ 3   ↑ 6   ↓ 11 ===
Do you want to continue ? [Y/n] n
```

If instead I uninstall the package and install it, nothing of that plan happens:

```console
%opam uninstall github
The following actions will be performed:
 - remove    github.0.9.4*
=== ⊘ 1 ===

=-=- Removing Packages =-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=  🐫 
Removing github.0.9.4.
  ocamlfind remove github
opam install github 

=-=- Synchronising pinned packages =-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=  🐫 
[github.0.9.4] Synchronizing with /Users/michael/Workshop/ocaml-github
The following actions will be performed:
 - install   github.0.9.4*
=== + 1 ===

=-=- Synchronizing package archives -=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=  🐫 
[github.0.9.4] Synchronizing with /Users/michael/Workshop/ocaml-github

=-=- Installing packages =-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=  🐫 
Building github.0.9.4:
  ocaml setup.ml -configure --enable-unix --enable-js --prefix /opt/opam/system
  ocaml setup.ml -build
  ocaml setup.ml -install
Installing github.0.9.4.
```

Should not `opam reinstall` really be the same than `opam uninstall` followed by `opam install`? What is the best way to reinstall a package when developing it?

**Comment by AltGr** [comment]
The first solution is quite weird indeed (esp. since it contains quite a few downgrades). Do you have aspcud installed, if so what version ?  It is recommended to have at least version 1.9 for the best resolutions.

If you do have aspcud installed, I'd like to have a look at the solver queries to debug (run with option `--cudf foo` then attach the `foo*` files) -- thanks.

This is indeed the right way to test your package. You may also use `opam upgrade` on source-pinned packages, in which case the package won't be rebuilt if no changes are detected in the source.

Also, this doesn't apply to your case, where they should be equivalent indeed, but `uninstall` followed by `reinstall` are not equivalent in general: the former will remove all packages dependent on the removed package, and the latter won't reinstall them.

**Comment by michipili** [comment]
I do not have aspcudf explicitly installed. I have opam 1.2.0, if that helps.

I prepared a [gist](https://gist.github.com/michipili/d76bfd056d308a0a775c) with the dotfile resulting from running `opam reinstall --cudf … github` (this was the only file). I also added my package list, I think there is very little more than what a `opam install github` on a bare blank system would produce.

**Comment by AltGr** [comment]
Thanks. Please install aspcud if possible -- solving installation problems is a difficult, np-complete problem, and dedicated solvers do a good job at it. OPAM includes some heuristics to fill the gap when no solver is available, but it's not on par and has its quirks. This case is a bit weird though, since the solution is simple ; it's probably not properly limited to the requested packages (the solver interface includes specific criteria for different request types, the internal solver doesn't; it probably tries to optimise all versions, and fails due to timeout -- you may want to try setting OPAMSOLVERTIMEOUT to a value greater than the default 5 seconds)

If you can't install aspcud nor packup and have a network connection available, you may want to consider using the [IRILL's solver farm](http://cudf-services.irill.org/index.html).

**Comment by michipili** [comment]
Installing aspcud solves it, thanks!
