### ISSUE TITLE
compute reverse dependency cone with --depends-on

### ISSUE THREAD

**Issue by avsm** [ocaml/opam#2124]
From opam-devel and @AltGr 

> Good point -- I'm looking for all the reverse dependency package cone of
> Cohttp that are installable for a particular version of Cohttp.  I will
> then install each of them separately, so there's no requirement for the
> results to all be coinstallable.
> 
> If you really just need this, you could:
> - get the reverse dependency cone, as before
> - try the coinstallation of cohttp and each member of this cone. If the solver returns no solution, just > skip, otherwise check that all goes well:
>   
>   COHTTP=cohttp.0.15.2
>   for p in $(opam list --rec --short --sort --depends-on $COHTTP); do
>    if opam install --show $COHTTP $p; then opam install $COHTTP $p; fi
>   done
> 
> Note that not specifying the version will just make OPAM choose the installed version, or failing that the highest available: it won't aggregate results for all versions. 
> 
> The `--short` format doesn't print any version numbers: if it's a shortcoming that should be fairly easy to improve; also, as Roberto said, any package that has a (possibly transitive) dependency to cohttp that may include that version will be included, even if it's not coinstallable.
> 
> To resolve in one step, I guess we could compute the set of packages coinstallable with this version of cohttp using Dose, and then take the intersection. (Or rather, the packages _not_ coinstallable and the difference ?)

It turns out that the latter suggestion is pretty essential, since on ARM calling the solver multiple times takes forever...

**Comment by AltGr** [comment]
Hm, I think we need to rebuild a more complete and consistent `opam list` CLI for this kind of advanced queries.
I just added `--resolve`, which computes a real solution (from scratch or current state, depending on `--installed`, which is a bit inconsistent thinking about it) ; since it uses the criteria, the above could be approximated with something like:

```
opam list --resolve cohttp.0.15.2 --criteria='+count(new),-sum(solution,version-lag)' --rec --depends-on cohttp --short
```
which would compute a solution installing cohttp.0.15.2 and as many packages as possible, then intersect with packages depending on cohttp, giving a version of the above reverse dependency cone. It's not perfect since it optimises the number of packages overall, not the ones in the cone we're interested in -- also, at the moment, the dependency options can't be stacked as intersecting filters, although that would be nicer.

It would require pushing functionalities to opam's cudf layer, but using the same mechanism as for limiting downgrades, it is possible to maximise the number of package within a set without failing if some can't be installed together (add a field "wished: 1" to the cudf, and criterion `+sum(solution,wished)`)

As always, there is an ugly shell hack that can be used to workaround, computing the intersection using grep:

```
opam list --resolve cohttp.0.15.2 --criteria='+count(new),-sum(solution,version-lag)' --short | grep -f <(opam list --rec --depends-on cohttp --short)
```
Also, this works because `--resolve --short` prints versions, while `--rec --depends-on` doesn't -- in my current PR anyway. Which makes some kind of sense, but nonetheless... yummy :)

Wish-list for `opam-list` ? Some ideas:
- consider `--installed`, `--available`, `--depends`, `--resolve`, `--matches` etc. as equivalent filters
- combine filters consistently (with AND, possibly adding an option to OR them ?)
- specifying at least one of `--installed`, `--available`, `--unavailable` disables the default filter (currently, `--available`, except in the no argument case, which lists installed packages)
- currently, anonymous arguments are considered as package patterns ANDed with the other filters, and e.g. `--required-by` takes a comma-separated list ; I'm afraid that might be a bit misleading. Only allow anon arguments when there is no other filter, and otherwise require them to be passed through a `--matches` option for consistency ?
- we have two listing formats, full and short. Only the full format lists version numbers, but it's currently only the highest version in the matching range -- or the installed version, if any and in the matching range (or `--`, actually, when not installed and no dependency criteria are specified). It would probably be useful to have an option to list all matching versions in the `--short` format (or make that the default and add a `--names). In the `--resolve` case, there is by definition only one matching version and we need it, so I changed the `--short` format, but it's not very consistent.

Last, but not least: do we need or want any of this on the 1.2 branch ? The `--resolve` is actually over 1.2.2 at the moment (with its current interface quirks).

**Comment by AltGr** [comment]
Another possibility would be to _pipe_ between filters rather than AND them:
```
opam list foo bar --depends --resolve
```
would compute the depends of packages matching `foo` `bar`, then resolve the installation of those dependencies.
Hm, probably, if you need that kind of flexibility, you'd be better off using the API.

**Comment by dsheets** [comment]
1. `opam list --rec` is undocumented except in the FAQ about how to find missing depexts.
2. I believe finding the fastest revdep install schedule is equivalent to TSP (with directed edges and edge weight computation that requires a solver!) and so we should look at computing these schedules offline and loading them during testing.

**Comment by AltGr** [comment]
1. I took the habit of writing `--rec` but the real option is `--recursive`:

             --recursive
                 With `--depends-on' and `--required-by', display all transitive
                 dependencies rather than just direct dependencies.
 2. Solving the installation problem in general is, so I guess this is the same. Unless you mean another stage, I am not sure exactly what you expect by `revdep install schedule`. A coverage of reverse dependencies in a minimal number of `opam install` commands ?

**Comment by AltGr** [comment]
@avsm: Since this is heading towards a larger refactoring of `opam list`, what parts would be needed in 1.2 ? Should I merge #2117 ?

**Comment by avsm** [comment]
Yep #2117 would be useful for 1.2.2, with a larger refactoring delayed till 1.3.0

I agree with:
> Hm, probably, if you need that kind of flexibility, you'd be better off using the API

**Comment by dsheets** [comment]
`revdep install schedule` = coverage in minimal number of commands/actions

**Comment by AltGr** [comment]
Ok, for that my first idea of approach would be to
 1. take the set of reverse dependencies (names only ?)
 2. run the solver, asking to maximise installation of packages from that set
 3. remove the packages in the solution from the set and get back to 2 if it's not empty yet

it's a bit dumb, but I doubt we'll ever need more than two or three steps in practice, so that could do the trick nicely. Note that we _don't_ have 2. in our solver interface though, but as I mentionned, it can be added.

**Comment by dsheets** [comment]
That sounds like a nice heuristic. It would be excellent to have the ability to get the `name.version` of the latest satisfying package (e.g. if B.1.x needs A but B.2.x doesn't then B.1.9) and maybe the earliest satisfying package. These can then easily be used in subsequent invocations to ensure that we are testing what we believe we are testing.

**Comment by dsheets** [comment]
Would this criteria syntax and these features (some of which will be in 1.2.2) work with aspcud 1.8?

**Comment by AltGr** [comment]
The cudf isn't changed depending on the solver, and I have been told 1.8 handles `sum(xxx,version-lag)` just fine -- it just lacks the `request` selector, if I remember correctly. So this all should work.

There are only two levels for the default, built-in criteria though, basic (compatibility) and aspcud 1.9: so you won't in general benefit from the new `version-lag` feature with 1.8 unless you use custom criteria.

**Comment by AltGr** [comment]
I believe the new `--soft-request` argument provides a solution to this.

- You can get the reverse cone (now with much more flexibility, e.g. all versions or not): `opam list --rec --depends-on cohttp.0.21.0 --short --all-versions`
- You can use `opam list --resolve=PACKAGES --soft` to get a maximal subset of installable packages within PACKAGES.

There is no clean way to pipe the two, though, a wee amount of shell trickery is still needed:
```
opam list --soft -s --column package --resolve="$(opam list --rec --depends-on cohttp.0.21.0 -s --all-v | xargs printf %s,)"
```
This is only one maximal subset, though, you would still require to recurse into its complement to cover all reverse dependencies. Not sure it could reasonably be handled by opam directly, though, and I won't insult you with a bash implementation of this, but doing the set operations with a little bit of OCaml code should be easy enough (it pre-dates `--soft` and could be much simplified, but there is the [couverture script](https://github.com/ocaml/opam/blob/master/admin-scripts/couverture.ml) that did something like that).

Getting back to the original request, where you don't require coinstallability of the resulting package set, though, that would require an additional `opam list` filter. I have just added that so you should soon be able to write:
```
opam list --rec --depends-on cohttp.0.21.0 -s --column package --coinstallable-with cohttp.0.21.0
```

It's quite slow, though, about 20 seconds on my desktop. Can't be helped, installability requests are difficult.
