### ISSUE TITLE
-I +directory no more working

### ISSUE THREAD

**Issue by UnixJunkie** [ocaml/opam#2149]
I heard some users in my team being unhappy about their Makefiles
(not using ocamlfind and pre-opam era) not working anymore when
the library they need are installed via opam.
I wonder if a fix to satisfy these users wouldn't be to create a symbolic
link upon installation of a library so that old time users still have their old Makefiles working.
For example, let's say library x was just installed in directory x via opam.
Maybe, we could create a symbolic link in stdlib_dir/x pointing to x ?

**Comment by AltGr** [comment]
Half-joking, but `sed s%-I +%-I +../%g` on their Makefiles would probably work. Yes, you can do `+../lib`, isn't it beautiful ?

But yes, symlinking would work; an easier way would be to make lib/ocaml a symlink to its parent to begin with... That sounds like a bit of a dirty hack to include into opam, though, and I am not sure how to discriminate "library [...] that old time users still have [in] their old Makefiles" :)

Note that this won't work for system switches, which is one of the reason we don't merge the two by default. Adding an option `opam switch install --with-dirty-links` would be possible though.

**Comment by dbuenzli** [comment]
> That sounds like a bit of a dirty hack to include into opam,

It also seems to go against opam becoming agnostic to ocaml.

**Comment by UnixJunkie** [comment]
@AltGr: thanks for the sed workaround. However, people have a right to expect upward compatibility: things that were working in the past should also work in the future. Good things work out of the box: you don't have
to mangle (sed) with them so that they start to work. Some people who use opam are not programmers: they
are just users who need to install some things with opam.
@dbuenzli if you really want something agnostic to ocaml: use pkgsrc.

**Comment by dbuenzli** [comment]
> However, people have a right to expect upward compatibility: things that were working in the past should also work in the future.

Where is that *right* defined and who enforces it ? In technology there's a good balance to find between remaining compatible and moving forward by providing upgrade paths (which @AltGr gave you). Trying to remain compatible forever with legacy technology leads to confusing, bloated, buggier and over-complex software which punishes everyone in the end.

Regarding agnosticity this is explicitely part of the 1.3 roadmap https://github.com/ocaml/opam/wiki/1.3-Roadmap#agnosticity

**Comment by UnixJunkie** [comment]
@AltGr the fix should work with switches

**Comment by samoht** [comment]
> But yes, symlinking would work; an easier way would be to make lib/ocaml a symlink to its parent to begin with... That sounds like a bit of a dirty hack to include into opam, though, and I am not sure how to discriminate "library [...] that old time users still have [in] their old Makefiles" :)

yes please don't do this.

**Comment by antoinemine** [comment]
Hi, chiming in, as one of the unhappy person. While it is of course very easy to modify our Makefiles, (preferably to use ocamlfind directly), it will make the build fail on older systems. These systems still exist and are not mine to update. For the time being, I have to support in my OCaml software both methods in the Makefile and a way to choose the correct one.
Installing an ocaml library X in .opam/caml-version/lib/ocaml/X instead of .opam/caml-version/lib/X (i.e., installing it in `ocamlc -where` alongside its binary as it used to be) would keep the compatibility with the use of "-I +X" and would be ocaml-agnostic. I am sure there are good reasons I don't see for moving ocaml-specific files outside of the ocaml directory, though.

**Comment by samoht** [comment]
A possible work-around (I've tested it very lightly and it seems to work) is to edit `~/.opam/<switch>/config/global-config.config` and add an `/ocaml` at the end of `lib`.

If this work properly then I think that's fine to add an option to the switch command to set-up the name of the `lib` directory:

```
opam switch old-makefiles -A 4.02.1 --lib=lib/ocaml
```

or something similar. This will obviously not work with the system compiler.

**Comment by dbuenzli** [comment]
This is brittle, it will break packages that do relative tricks in their `.install` file (OTOH they shouldn't do this, but there are published ones that do this for wrong reasons, I hope that eventually `.install` file will forbid this). 

It seems to me that it would be better to check in your Makefile whether you have you have opam or not and adjust the variables accordingly.

**Comment by samoht** [comment]
Actually my brittle workaround doesn't seem to work when things are installed using `.install` (for instance `cmdliner`). I think it's best to update your Makefiles ...

**Comment by AltGr** [comment]
@samoht: yes, that `~/.opam/<switch>/config/global-config.config` file is made of stuff that can also be computed using the functions from `OpamPath`, and it's not clear in the code when one or the other is used. I think it could be removed altogether, or reserved to specific cases, if we find precise needs.

Actually, I don't think it would be too much to ask users who want compatibility with older Makefiles to run a few lines of bash to install some compatibility hacks on their opam switch (that could be added to the opam [tricks page](https://opam.ocaml.org/doc/Tricks.html), or [FAQ](https://opam.ocaml.org/doc/FAQ.html)):

```
opam switch compat-switch-hack --alias-of 4.02.1
eval $(opam config env)
cd $(opam config var lib)
mv ocaml/* .
rmdir ocaml
ln -s . ocaml
```

This, of course, under the responsibility of the person running the script :)
It seems to work however, and ocamlfind won't complain about it. Users needing the compatibility can simply set it up, and no dirty hacks have to be included in OPAM.

**Comment by UnixJunkie** [comment]
@AltGr would it be OK if I create an opam package to do this commands:

    cd $(opam config var lib)
    mv ocaml/* .
    rmdir ocaml
    ln -s . ocaml

it could be named minus-I-compat or the like and users who install
it would not suffer anymore from opam having broken that good old behavior

**Comment by dbuenzli** [comment]
> @AltGr would it be OK if I create an opam package to do this commands:
> 
> cd $(opam config var lib)
> mv ocaml/* .
> rmdir ocaml
> ln -s . ocaml
> it could be named minus-I-compat or the like and users who install
> it would not suffer anymore from opam having broken that good old behavior

I would rather be against having this in the official opam repository. This will encourage people to stick to  their old practice instead of enticing them to adapt. Package usage in general will not be tested using this mode operation and it will multiply the number of scenarios we have to consider when problems are being reported. The end result will be a waste of time for everybody both the users of the package (using things that are not tested) and people who are in charge of responding to package problem reports.

**Comment by UnixJunkie** [comment]
@dbuenzli nobody will force you to install or depend on that package

**Comment by UnixJunkie** [comment]
leave people their freedom, don't dictate them

**Comment by dbuenzli** [comment]
> @dbuenzli nobody will force you to install or depend on that package

You don't understand. Since this is an untested hack this will be more work and or possibilities to consider for the opam repository and package maintainers whenever problems are being reported.

> leave people their freedom, don't dictate them

That's exactly what I do: I don't dictate them to use opam. In contrast *you* are dictating us that people have the *right* (your words) to use their old modes of operation in opam.

**Comment by UnixJunkie** [comment]
I fight for users.
Users have a right to have things working out of the box and not need to patch old Makefiles.
If opam will not be fixed, then having a package that anyone can install in a glimpse
without having to add an exotic opam repository is the best way.

**Comment by dbuenzli** [comment]
> I fight for users.

Noble goal. We are two then. Users of the opam system have a *right* to have a clean and non confusing system whose semantics doesn't change by installing a single package resulting in a system that has the potential to create more problems than it solves *for everybody* using the system, even those that will not install the package.

> Users have a right to have things working out of the box and not need to patch old Makefiles.

Ah but don't pick up the wrong fights. In your fight for users do what is actually best for them in the long-term. Admit it, isn't updating `Makefile`s a beautiful fight ? Help them to tame that one, you may get knighted by your team !

Finally don't be selfish in your fights. There are other opam users out there than just those of your team. So try to think about the implications and costs of what you propose for *everybody* in the system and not only the effects it will have in your tiny world.

**Comment by lefessan** [comment]
Note that this issue was raised very early in OPAM's development, cf #249. I think it was a mistake, but anyway, it's a bit late to fix things, as some packages are now making the assumption that they are installed in `lib/` instead of `lib/ocaml`, and would be broken by the change. A "workaround" would be to create symlinks automatically from `lib/ocaml/PACKAGE` to `lib/PACKAGE` (OPAM could do it as post-installation hook).

**Comment by UnixJunkie** [comment]
@lefessan I vote for the post-installation hook fix.

**Comment by AltGr** [comment]
The main grudge I have against installing in `~opamswitch/lib/opam` is that it will make `-I +lib` work _in some cases_, but not always, which is the worst possible behaviour -- I test my package, it works, somewhere else with a different setup, it doesn't. It can't work in general, because OPAM handles the case where you are using a "system" OCaml compiler and libraries, e.g. from `/usr/lib/ocaml`, and OPAM libraries in `~opamswitch/lib`. This doesn't seem compatible with `-I +lib`, at least in the way it is currently handled by OCaml. That was the reason to handle things this way from the beginning.

So, if you want to submit the linking hack as a package, you should probably specify `available: !preinstalled`. OPAM's intended lack of restrictions on what packages can do makes this possible, however, I think that having packages that implement hacks changing the structure and behaviour of the installation is a very bad idea -- there are no implemented restrictions, but the repository maintainers still enforce some rules: It's up to them to decide what gets included, but I am pretty sure their opinion will be the same.

Other issues include providing a clean way to revert on `opam uninstall`, and the fact that this will likely break when we implement tracking of package files (although other existing packages may do so as well, and we may need to implement a workaround). 

I am sorry I can't find a better way to support your users' case, but we had to make some compromises during the design stage of OPAM, and I can't think now of anything lighter than the few lines of shell-script I proposed above. It's always the conflict between supporting legacy and consistency of a new design...

**Comment by UnixJunkie** [comment]
I thought @lefessan 's fix is clean: after installation of a package a link is created from
lib/ocaml/PACKAGE to lib/PACKAGE. Upon uninstall of PACKAGE, the link just needs to be removed.

**Comment by lefessan** [comment]
My idea was even simpler: (1) for every directory in lib/, create a link in lib/ocaml/, (2) remove any link in lib/ocaml/ that has no matching directory in lib/. This way, a package could install several directories in lib/, and uninstall them as easily.

**Comment by db4** [comment]
My idea is the simplest ever :-) -- just configure OCaml compiler properly (see also https://github.com/ocaml/opam-repository/issues/4825):
```
["./configure" "-prefix" prefix "-libdir" lib]
```
This way both OCaml standard libs and packages go to `$opam/$SWITCH/lib` without any additional efforts.

**Comment by UnixJunkie** [comment]
So your idea is to change how compiler switches are configured?
That looks very nice.

**Comment by AltGr** [comment]
Closing, as this is not actually related to anything specific _the opam tool_ does. It's more of a repository / findlib / organisation issue. With opam 2, you could even have a custom switch that initialises the lib/ocaml symlink for your users. Or a post-install hook that does it for each lib install.
