### ISSUE TITLE
Can't obtain (reverse) dependencies garded by a filter and can't view them with show.

### ISSUE THREAD

**Issue by Drup** [ocaml/opam#2152]
The test case is the following:

```
$ opam list --depends-on=alcotest --depopts
# Available packages directly depending on alcotest.0.3.1 for 4.02.1:
irmin  0.7.0  Irmin, the database that never forgets
```

But cohttp has a test dependency on alcotest. 

I didn't found a command line option to get the all the dependencies regardless of the filters (and I'm not completely convinced the default behavior is the right one). 

Also note that show don't actually show these dependencies ...

Both bugs logically affect [the](http://opam.ocaml.org/packages/cohttp/cohttp.0.17.1/) [website](http://opam.ocaml.org/packages/alcotest/alcotest.0.3.1/).

**Comment by AltGr** [comment]
Indeed, these options are missing from `opam list` (which needs to be [redesigned](https://github.com/ocaml/opam/issues/2124#issuecomment-94339104)) ; you can work around it for now by defining `OPAMBUILDTEST=1 OPAMBUILDDOC=1`.

Since the default on `opam install` is to ignore these dependencies, unless you gave the appropriate flags, the `opam list` default seems consistent. `opam show` should definitely show them, though!

**Comment by AltGr** [comment]
`opam list` has been refactored and now accepts `--test`
