### ISSUE TITLE
Getting rid of relative tricks in `.install`

### ISSUE THREAD

**Issue by samoht** [ocaml/opam#2153]
It would be nice to either have a way to install files in other package directory (that's not very safe) or a way to install stuff in `lib/pkgconfig` (which quite useful when you cross-compile C libraries for Xen).

**Comment by samoht** [comment]
See https://github.com/ocaml/opam-repository/pull/4088/files#diff-b651b9b2642368268a76ecfd23cd35cbR11 and https://github.com/mirage/mirage-dev/pull/56/files#diff-11028286507e34ac2b269d02c63a092aR3 for where it could be useful

**Comment by dbuenzli** [comment]
Shouldn't we try to come up with a system that is more scalable ? 

I'm thinking about something like the [`misc`](https://opam.ocaml.org/doc/Manual.html#packagenameinstall) section but relative to the existing other fields.

In any case it seems that we need something if we want to get rid of `.install` files making relative tricks.

**Comment by samoht** [comment]
> Shouldn't we try to come up with a system that is more scalable ?

Agreed. I was just reporting my uses of relative tricks to see how we can remove then. If you want to report your tricks here, I'm fine to change the issue title to something a bit more generic (ie. "Getting ride of relative tricks in the `.install` files).

**Comment by dbuenzli** [comment]
I only had one in an unpublished package (`ppx_utf8_lit` because I blindly c&p the `topkg` specification from some other `ppx`). In fact it was sufficient to use the  `libexec` field (this may however pose `opam` version problems see https://github.com/whitequark/ppx_import/issues/5). So on my side nothing to report.

**Comment by dbuenzli** [comment]
So having a look at the `.install` file spec one obvious way is to change 

> ```field: [ <string> { <string> } ]```
> [...] An optional relative path and destination filename can be given using the postfix braces syntax.

to "an optional ~~relative~~ path" which: 

1. If *relative* expresses a path relative to the package prefix for the section. This relative path is not allowed to escape the package prefix.
2. If *absolute* expresses a path relative to the section prefix (i.e. dirname of the package prefix) and `opam` should be vocal and/or confirm when things are being installed that way.

**Comment by AltGr** [comment]
@dbuenzli's idea sounds convenient, would it be easy enough to explain to newcomers (and understand by looking at a file) ?
Another thing is that I would actually like a `misc` to be relative to the prefix rather than the root.

**Comment by dbuenzli** [comment]
Wait wait wait in fact I think my last message is a very very very bad idea since what we get is package themselves deciding where something should be installed which I claim goes against the `.install` philosophy which is semantic based. For example this leads to packages assuming `pkg-config` things will necessarily be in `lib/pkgconfig`. This is very wrong and stupid.

Having a `pkgconfig` field as @samoht initially suggested in the title of the issue allows `opam` to attribute *meaning* to the files of the section and possibly install them to more appropriate places.

So here's a much better proposal,

1. We keep all the standard fields as they exist but restrict their destination paths to be like in 1. in my last message (i.e. no package prefix escapes).

2. We make the `.install` file format extensible by allowing any field of the form `x-$ID:` (e.g. `x-pkg-config:`, `x-emacs:`) to exist. Having the `x-` prefix allows to report errors on typos of the standard fields, so that e.g. `libxec` can be classified as typo rather than a new kind of field. 

3. We introduce a configuration mechanism in `opam` to be able to associate install path to these `x-$ID` field. These `x-$ID` install paths have two properties:
  * exec, a boolean that indicates that installed files will have the executable bit set.
  * package-prefixed (or a better name), a boolean that indicate whether each package installs in its own unescapable prefix or not (e.g. this would be `false` for `x-pkg-config:`.)

This is certainly much more involved to implement but I think it's the right way to respect the `.install` philosophy and it seems to me that it plays well with agnosticity.

**Comment by dbuenzli** [comment]
> Another thing is that I would actually like a misc to be relative to the prefix rather than the root.

In `misc` absolute and relative paths destination could be allowed. Relative would mean relative to the prefix, absolute relative to the root. Or maybe deprecate `misc` and introduce two specific fields.

**Comment by AltGr** [comment]
A possible fix for compatibility with older OPAMs could be to package a stand-alone opam-installer, and have something like:
```
depends: [ "opam-installer" {build & >= "v"} ]
install: [
  [ "opam-installer"
      "--prefix=%{prefix}%" "--libdir=%{lib}%" "--mandir=%{man}%"
      "--docdir=%{doc}%" "--stubsdir=%{stublibs}%" "--topdir=%{toplevel}%"
      "%{name}%.install" ]
    { opam-version < "1.2.2" }
  [ "rm" "-f" "%{name}%.install" ] {opam-version < "1.2.2" }
]
remove: [
  [ "opam-installer" "-u"
      "--prefix=%{prefix}%" "--libdir=%{lib}%" "--mandir=%{man}%"
      "--docdir=%{doc}%" "--stubsdir=%{stublibs}%" "--topdir=%{toplevel}%"
      "%{name}%.install" ]
    { opam-version < "1.2.2" }
]
```
A bit verbose though. And we can't yet make the dependency optional depending on the opam version.

**Comment by samoht** [comment]
An other (bad) trick, but still useful as a workaround for installing cross-compiled C stubs:

https://github.com/ocaml/opam-repository/blob/master/packages/zarith-xen/zarith-xen.1.3/opam#L8

The original META file is patched and a new C object file is installed in the original dir.

**Comment by dbuenzli** [comment]
If the library has its own suffix, then why not install it in its own prefix ?

**Comment by samoht** [comment]
Because you don't want to release all the intermediate "pure-OCaml" libraries: if you have something like `zarith -> nocrypto -> tls -> conduit -> git`,  you don't want to release a separate`git-xen` package just because some of your deep dependencies needs `zarith-xen`. It's better to be a link time option (ie. we use some ocamlfind predicates to choose the right C libraries to link with -- we could maybe replace that later by a proper pkgconfig invocation).

But maybe there's an easier way!

**Comment by dbuenzli** [comment]
> It's better to be a link time option (ie. we use some ocamlfind predicates to choose the right C libraries to link with -- we could maybe replace that later by a proper pkgconfig invocation).

Why can't this link time option reside in another package ?

**Comment by hannesm** [comment]
the missing piece is cross-compilation. the (current) hackish solutions are bad: building another package universe with pkg_config is awful, having XXX behave differently if `compiled for xen` or `compiled for unix` shouldn't be too omnipresent. I can see a cleaner solution only if opam/OCaml have a proper concept of cross-compilation.

**Comment by samoht** [comment]
> Why can't this link time option reside in another package ?

What do you mean? In my example, you only specify the dependency between `git` and `conduit` and you rely on ocamlfind to tell you that you need `zarith` at link time. So you either need to patch `zarith` to expose the new linking option, or to release of new `-xen` package for every **user** of `zarith` to make it depend on `zarith-xen` and so on. This is not really scalable.

I agree that the proper solution for that is related to cross compilation. I don't know exactly how, though :p

**Comment by dbuenzli** [comment]
> What do you mean? In my example, you only specify the dependency between git and conduit and you rely on ocamlfind to tell you that you need zarith at link time.

Well the usual trick of `zarith` being only interfaces and you simply need to use another package to link in the right backend. 

> I agree that the proper solution for that is related to cross compilation.

Not necessarily (at least if you mean in a different opam switch). You have the same kind of problems with JavaScript compilation and yet for many reasons you may not want to expose `js_of_ocaml` as a separate switch.

**Comment by AltGr** [comment]
These tricks shouldn't be allowed anymore

**Comment by hannesm** [comment]
@AltGr since there was some discussion about this issue in other repos ([mirage](https://github.com/mirage/mirage/pull/669#issuecomment-260201832) and [mirage-solo5](https://github.com/mirage/mirage-solo5/pull/15#issuecomment-260204425), as well as on the [mirage mailing list](https://lists.xenproject.org/archives/html/mirageos-devel/2016-11/msg00047.html)), could you please explain how this issue was solved?

There seems to be the need to install pkg-config files into `../lib/pkgconfig`.  Will opam2 just reject these violations (AFAIU the opam spec packages should not install to `../lib/X` (unless `X` == `pkgname`))?  Is there a way (e.g. look at [Daniel's proposal](https://github.com/ocaml/opam/issues/2153#issuecomment-101869375) above) to install to `../lib/pkgconfig`?

**Comment by dbuenzli** [comment]
Note that we could also solve the problem by simply having a `lib_root` like `share_root`. 

Would be less semantic but sometimes you do have to install in other packages (we agree it's not a good thing but for example `odig`, like `ocamlfind` needs to install a file in `ocaml` so that it can be loaded via a simple `#use`). 

Having `lib_root` allows consumers of `.install` file to easily see that the package is doing something fishy and implement their own policies.

**Comment by AltGr** [comment]
@dbuenzli's suggestion above seems nice, if many have use for it, I could implement it later on.
For now I just added `lib_root` and `libexec_root` in 905d6258c803b6f306a34d78c7f776357795c0eb, which was the quick solution.
