### ISSUE TITLE
Solaris 10 patch command doesn't get file to patch

### ISSUE THREAD

**Issue by alanfeldstein** [ocaml/opam#2160]
After editing
opam-full-1.2.2-rc2/src_ext/Makefile
to remove suppression of recipe echoing:

...
if [ -d patches/cmdliner ]; then \
          cd cmdliner && \
      for p in ../patches/cmdliner/*.patch; do \
        patch -p1 < $p; \
      done; \
        fi
  Looks like a unified context diff.
File to patch: 

That is, the patch command prompts the user.

opam-full-1.2.2-rc2/src_ext/patches/cmdliner/backport_pre_4_00_0.patch

diff -Naur cmdliner-0.9.7/src/cmdliner.ml cmdliner-0.9.7.patched/src/cmdliner.ml
--- cmdliner-0.9.7/src/cmdliner.ml  2015-02-06 11:33:44.000000000 +0100
+++ cmdliner-0.9.7.patched/src/cmdliner.ml  2015-02-18 23:04:04.000000000 +0100
...

See the man page for the Solaris 10 patch command.
http://docs.oracle.com/cd/E19253-01/816-5165/6mbb0m9n6/index.html
In particular, we are interested in the "File Name Determination" section of that document.

If no file operand is specified, patch performs the following steps to obtain a path name:

If the patch contains the strings **\* and - - -, patch strips components from the beginning of each path name (depending on the presence or value of the -p option), then tests for the existence of both files in the current directory ...

src/cmdliner.ml
src/cmdliner.ml

"Both" files exist.

If both files exist, patch assumes that no path name can be obtained from this step ...

If no path name can be obtained by applying the previous steps, ... patch will write a prompt to standard output and request a file name interactively from standard input.

One possible solution is for the makefile to read the patch file, extracting the path name using the Linux patch command algorithm. Then feed that path name to the patch command explicitly.

Alan Feldstein
Cosmic Horizon
http://www.alanfeldstein.com

**Comment by dbuenzli** [comment]
@AltGr if you'd like `cmdliner` to remains `3.12` compatible please file an issue and the next release will be. The patch doesn't look unreasonable.

**Comment by AltGr** [comment]
@dbuenzli, thanks, done.

@alanfeldstein thanks for your efforts on having OPAM compile on Solaris ! It's appreciated, and if you have working fixes, feel free to submit pull-requests (I will do the patches myself otherwise, but it may take longer, and I don't have access to Solaris to check that they fix the issues).

On the patches, woul'nd it be easier to rely on `git apply` ? The patches were generated with git, and it's sure to be consistent accross systems. Of course, this would add git as a build dependency, even when you downloaded the full archive... but who doesn't have git these days ?

Another option would be to include the unpacked and patched sources in `src_ext` rather than the tarballs when generating the "full archive" at https://github.com/ocaml/opam/releases/download/1.2.2/opam-full-1.2.2.tar.gz

**Comment by alanfeldstein** [comment]
@AltGr I don't have a working fix for this. But I would be happy to verify for you on Solaris 10 any proposed fix that you do.

**Comment by dra27** [comment]
Is this is still an issue on Solaris? For Windows, it's also looking like using `git apply` in preference to `patch` (but still falling back to `patch` when git isn't installed) will be necessary - perhaps it would be a good strategy on all platforms.

**Comment by rjbou** [comment]
What is the status of this issue ?

**Comment by dra27** [comment]
The `git apply` strategy I mention in https://github.com/ocaml/opam/issues/2160#issuecomment-302955154 I subsequently found is not a good idea, and shouldn't be done. However, since then #3349 means that `opam` has a way to normalise patches to deal with any idiosyncrasies we can think of (we talked this week about using it to deal with patches which rename files, for example, simplifying them to a "new" file and a "delete" file diff)

**Comment by rjbou** [comment]
Closing this issues, feel free to reopen it if needed.
Thanks!
