### ISSUE TITLE
Curl %{http_code} error

### ISSUE THREAD

**Issue by braibant** [ocaml/opam#2189]
Continuing my attempt to compile opam on Windows on the `master` branch.

I managed to get the proper filename for the calls to `downloas_as` (using "/" as a separator for the url rather than `Filename.dir_sep` . However, there is an issue with the interpretation of % in the string 

```
let curl_args = [
  CString "--write-out", None;
  CString "%%{http_code}\\n", None;
  CString "--insecure", None;
  CString "--retry", None; CIdent "retry", None;
  CString "--retry-delay", None; CString "2", None;
  CString "--compressed",
  Some (FIdent (OpamFilter.ident_of_string "compressed"));
  CString "-L", None;
  CString "-o", None; CIdent "out", None;
  CIdent "url", None;
]
```

Using 

```
$ curl https://opam.ocaml.org/urls.txt --write-out %{http_code}
```

The return code is valid (200)

Using 

```
$ curl https://opam.ocaml.org/urls.txt --write-out %%{http_code}
```

The return code shows up as `%{http_code}`.  (Which is what shows up when I try to use OPAM.)

I am a bit unsure about what is the issue here. I would have expected the code that is present to work out of the box, reading the documentation of curl 

```
              NOTE: The %-symbol is a special symbol in the win32-environment,
              where all occurrences of %  must  be  doubled  when  using  this
              option.
```

Is there some pre-processing of the `CString` s done somewhere? What am I missing?

**Comment by avsm** [comment]
Is it worth just linking Cohttp into OPAM to do an inline fetch rather than shelling out and debugging the cross-platform issues?

-anil

**Comment by braibant** [comment]
Am I right to assume that linking Cohttp would solve both issues I reported?

**Comment by avsm** [comment]
It might introduce more too ;-) But it strikes me as far simpler to just do the HTTP fetch inline and have the response available as an OCaml datastructure rather than going through OS-specific temporary file handling.

**Comment by braibant** [comment]
I do not think it's an issue related to OS-specific temporary files. Rather, it look likes the query is processed by OpamFilters, which interprets the curl variable. I have tried various ways to escape it, to no avail. I must be missing something here.

**Comment by AltGr** [comment]
Handling the various options and parsing the return values of download tools is indeed a bit heavy and error-prone (we had e.g. errors with the compression flags returning uncompressed tar files when we downloaded a .tar.gz, I remember; and issues with certificates and Curl and osx more recently).

Doing the download in a sub-process, though, is good and is our granularity for parallelism.
Another issue: pulling cohttp into opam means pulling its dependencies with it, which gets us well above 10 packages. That would probably require a proper bootstrap for opam: for now, we use a custom build system for included packages, and rebuild them all as local libraries, which works quite well but would cost too much, I think, if we want to scale that far.

Using a custom download tool written in OCaml+cohttp, on the other hand, would give us a consistent, reliable interface, and ease the portability issues ; on the process and temp file handling, we already have everything in place and use it for much more than downloads, so that sounds OK to me. Remain the questions of how and when we would compile and install it...

**Comment by avsm** [comment]
On 12 Jun 2015, at 02:19, Louis Gesbert <notifications@github.com> wrote:
> 
> Using a custom download tool written in OCaml+cohttp, on the other hand, would give us a consistent, reliable interface, and ease the portability issues ; on the process and temp file handling, we already have everything in place and use it for much more than downloads, so that sounds OK to me. Remain the questions of how and when we would compile and install it...
> 
> 

I'm agreed with all of this!

**Comment by dra27** [comment]
Is it definitely necessary to switch to a totally external tool? I'm pouring some effort into re-basing and completing the Windows-patches I started last winter - I'd done an experiment using ocurl which seemed to work very well (no need to worry about temporary files or anything else - you can even do the checksum validation as the download proceeds, obviously). ocurl only depends on libcurl, which appears to have been designed for just about every OS ever invented (even the mingw32 build was painless!)
I'm working in https://github.com/dra27/opam in branch windows (though I reserve the right to rebase at this stage!!). It's not desperately exciting at the moment - I'm working towards getting ./configure --prefix=C:/OCaml && make lib-ext && make && make install to work but I was going to pull in ocurl once I'd done that, if you're interested to see how it shapes up?

**Comment by AltGr** [comment]
Closing this specific issues in favour of more recent discussions on @dra27's Windows porting work and generally using internal tools rather than external ones.
