### ISSUE TITLE
Add a way to install the tests dependencies without running the tests

### ISSUE THREAD

**Issue by samoht** [ocaml/opam#2190]
Currently:

```
opam install <foo> --deps-only -t
```

Will install the test dependencies **and** run the tests of these dependencies. Would be nice to have a way to just install the dependencies without running any tests.

**Comment by samoht** [comment]
This is extra annoying.

**Comment by samoht** [comment]
See https://travis-ci.org/mirage/irmin/jobs/69374275

**Comment by talex5** [comment]
Another example here:

http://lists.ocaml.org/pipermail/opam-devel/2015-July/001143.html

**Comment by dsheets** [comment]
Is `opam install <foo> --deps-only` followed by `opam install -t <foo>` insufficient? It seems like perhaps this is an ocaml-travisci-skeleton issue?

**Comment by samoht** [comment]
@dsheets  `opam install -t` also installs the `test` dependencies. Travis scripts do: `opam install --deps-only -t`.

**Comment by dsheets** [comment]
My understanding is that you want the test dependencies installed and tests run for the package under test and otherwise only the dependencies installed. Are you saying you want to have test dependencies installed but *not* have *their* tests run?

How about something like `--with-deps test` to provide dep flags. Then you can do `opam install <foo> --deps-only --with-deps test` followed by `opam install -t <foo>`?

**Comment by samoht** [comment]
Yea, `opam install <foo> --deps-only --with-deps test` would be ideal.

**Comment by samoht** [comment]
ping. This would be quite convenient. Or at leat to have a mechanism to only test the packages mentioned on the command-line and not its dependencies.

**Comment by AltGr** [comment]
ack
