### ISSUE TITLE
OPAM init with multiple repositories

### ISSUE THREAD

**Issue by chambart** [ocaml/opam#2202]
Currently `opam init` only accepts a single repository. For compiler testing it would be easier to be able to directly init with the default repository with an overlay containing the compiler description.

```
opam init first_repository first_repository_url --additionnal-repository second_repository second_repository_url
```

**Comment by AltGr** [comment]
This makes the interface a little complicated. For more control, I would advise:
- either the use of a [`.opamrc`](http://opam.ocaml.org/doc/2.0/Manual.html#opamrc) file, which allows to pre-define any repository setup
- or `opam init --bare`, followed by the sequence of `opam repository add` commands.

One of the issues with the proposed syntax is that it's not obvious which repository would get the highest priority. Since we are adding trust anchors, that multiplies the number of parameters required for each repository, too.
