### ISSUE TITLE
Clarification about the "name" and "version" fields

### ISSUE THREAD

**Issue by Chris00** [ocaml/opam#2243]
It has [been](https://github.com/ocaml/opam-repository/pull/4360#discussion_r33887345) [argued](https://github.com/ocaml/opam-repository/pull/4380) [lately](https://github.com/ocaml/opam-repository/pull/4386#discussion-diff-33896450) that the `name` and `version` fields should not be part of the `opam` files, mostly—as I understand it—for cut and paste reasons.  On the other hand, the signed repository will require this metadata.

My questions:
- Please confirm (and motivate some more) that the `name` and `version` should not be part of the `opam` description.  My `opam` files are generated, so lack of synchronization with the directory name will not happen.  
- Will this policy change in the future?
- Just to be perfectly sure: `opam` files included in repositories should contain the name and version (since there is no way to guess them), right?

**Comment by dsheets** [comment]
See also: https://github.com/ocaml/opam-repository/pull/4190#issuecomment-110321314

**Comment by dsheets** [comment]
See also: https://github.com/OCamlPro/opam-publish/issues/28

**Comment by AltGr** [comment]
In the opam-repository format, a package is described by a directory, whose name dictates the package name and version -- so specifying the name and version in the opam file there is unneeded, and can only result in a mismatch (which is treated as an error).

We still want to allow name and version fields in general, though, because indeed opam files can live standalone for pinned packages and in project sources. It's a bit annoying to handle actually as we have a `OpamFile.OPAM.t` type that doesn't match exactly the contents of the file (causing trouble e.g. when implementing opam-lint).

To be consistent, it was proposed to clearly separate the two cases above, and to make sure we _don't_ have the fields in opam files from the opam repository -- which I think is a good idea, for cut-and-paste, easier new releases, and just avoiding an error case that is not really needed.

Signing the repository doesn't really affect this: we'll be adding a signed file, containing cryptographic hashes of the `opam`, `descr`, `url` and anything in `files/`, as well as of the upstream archive(s). All the redundant information is stored there, and it seems natural to add `name` and `version` fields to this file rather than `opam`.

There's no super-strong argument in favor of (not) having the fields, or forbidding them, but that's where I stand at the moment.

**Comment by hannesm** [comment]
@AltGr sounds good to me.

**Comment by Chris00** [comment]
@AltGr OK, thanks for the explanation.

**Comment by Chris00** [comment]
As mentioned by @sawja-admin the manual says that [the `version` field is mandatory](https://opam.ocaml.org/doc/Packaging.html#Thequotopamquotfile).  This should be clarified.

**Comment by dra27** [comment]
Late to the party on this, but referencing https://github.com/ocaml/opam/issues/2320#issuecomment-154657852 with a possible restricted use-case for having name and version being different in opam files.
