### ISSUE TITLE
The dev manual is wrong regarding config files

### ISSUE THREAD

**Issue by samoht** [ocaml/opam#2245]
http://opam.ocaml.org/doc/manual/dev-manual.html#sec40 says `$prefix/config/$name.config` but it should be `$prefix/lib/$name/opam.config`. I am not sure that's the best name ever (as we already have `opam`, `$name.install` and now `opam.config`) so this should also be re-design properly -- as there is no user yet, that's a good time.

Moreover, few people have expressed an interest in having an `opam config set <var> <value>` or something similar. I think that's a good idea.

**Comment by dbuenzli** [comment]
@samoht do you suggest then that  `$prefix/config/$name.config` would be better ? (unclear from your message).

**Comment by samoht** [comment]
I came up with the 2 names so I have no opinion on which one is best. But we should be at least consistent ... there's also `<pkg>.opam` instead of `opam` who works if you have multiple opam packages in your repository, so `lib/<pkg>/<pkg>.config` could also work.

**Comment by samoht** [comment]
Note: storing the config file in the directory is good because that's less implicit installation magic (although we already move the `.install` in some other dir). Storing the file in `config` might be good if we want to persist data across reinstallation.

**Comment by hannesm** [comment]
since it is user-defined and should imho be persistent across reinstallations (otherwise, `opam update && opam upgrade` doesn't work intuitively, and not reset all user-configured flags), it'd be great to have it in `$prefix/config/`.

I'm not sure whether there should be a single file (and variables being prefixed by package name), or one file per package (slightly prefer the former).

**Comment by dbuenzli** [comment]
> Storing the file in config might be good if we want to persist data across reinstallation.

I don't think it makes sense to persist the data across reinstallation. The `config` file is supposed to give information about *the* installation. If you want to use this as a way to configure the installation then I think another mechanism should be provided.

**Comment by hannesm** [comment]
@dbuenzli right, these are two different things, and information about the installation should be kept in `$prefix/lib/<pkg>/somewhere`.

**Comment by dbuenzli** [comment]
> information about the installation should be kept in $prefix/lib/<pkg>/somewhere.

Yes,  the rationale for this was made [here](https://github.com/ocaml/opam/pull/1361#issuecomment-41314299).

So this means that maybe we could use the `$prefix/config/$pkg.config` for the persistency of per package variables. But still I think the design needs more work, mainly I would like to be able to document and declare the variables in the `opam` files themselves, so that we can actually advertise their existence in e.g. `opam info PKG` and have `opam config set $PKG $var $value` provide good errors message (e.g. if you are trying to set an inexisting variable).

**Comment by dbuenzli** [comment]
> I would like to be able to document and declare the variables in the opam files themselves

and provide a default value. 

I'm writing up a proposal and thinking this with assemblage in mind in the sense that theses new variable declarations could be automatically added during `opam` metadata sync from assemblage configuration keys (they do have all the required info a name, a default value and a doc string, let's be DRY).
