### ISSUE TITLE
managing optional dependencies

### ISSUE THREAD

**Issue by zoggy** [ocaml/opam#2251]
Hello,

The `configure` script of Stog will detect whether some libraries are available. Some of these libraries are required, while others are optional. When all the optional libraries are installed, the `configure` script will define variables so that `make all` and `make install` will also install stog server in addition to the other stog tools.

In the `opam` file of the stog package, I used to put constraints on version numbers of the optional libraries, in the `depopts` field. This is not possible anymore.

I cannot put these constraints as conflicts, because installing one of the optional libraries in a version number not matching the constraints will not prevent stog from being compiled and installed. It's just that, when a set of libraries with given version numbers are installed, stog can compile and install more stuff.

I do not know how to specify this in the `opam` file. I'm thinking about adding an "empty" stog-server package, which would require both stog and the optional libraries. The `build` and `install` fields would do nothing.

Would this work ?

**Comment by AltGr** [comment]
The constraints in optional dependencies _should_ work the way you want -- unfortunately, for legacy reasons and past broken semantics, we thought it was better to disable them altogether during the transition, rather than change their semantics (which was, more or less, equivalent to adding conflicts as advised in the manual. Only less consistent)

The issue you are facing, however, is mostly a `./configure` issue, that is solved within your package. By not putting the version constraints to the optional dependencies, you will only lose in that any change in these optional dependencies will trigger a recompilation, even if it was'nt getting used.

If you want other packages to be aware of the installation of your optional features, it gets a bit more complicated. There is the experimental [`features:`](http://opam.ocaml.org/doc/Manual.html#opamfield-features) field to that end, but it may [get replaced](https://github.com/ocaml/opam/issues/2247).

**Comment by zoggy** [comment]
Thanks for your response. I will wait for things to stabilize.
