### ISSUE TITLE
Lock while switch install

### ISSUE THREAD

**Issue by Drup** [ocaml/opam#2259]
The lock during switch compilation feels a bit overly restrictive. 
- It is impossible to install in another switch
- It is impossible to read anything (list, show ..)

This is the case even for `opam switch install --no-switch`.

**Comment by Drup** [comment]
(It seems to me lock issues/inconsistencies are quite common, maybe it would benefit for having a good plan drawn out and a bit of testing)

**Comment by Drup** [comment]
Probably worse: launching emacs with user-setup while `opam switch install --no-switch` craps out. :)

**Comment by AltGr** [comment]
Indeed, it seems the different locks aren't perfectly adequate: we have currently
* a global lock for ~/.opam, used for manipulation of global conf files and the repositories
* a per-switch lock
Both may be either `write` (_i.e._ exclusive) or `read`. Since a global write lock prevents from reading `~/.opam/config` and knowing which switch you're in, not much can be done. And `user-setup` calls `opam list` to know what tools are available.

Installing a switch requires changing the global conf files, and may need a rollback in case of trouble, so it keeps a global write lock to avoid any deadlock. (Note, though, that base package installation is already done afterwards with only a switch lock, so that would be less of an issue with _compilers-as-packages_).

I "fixed" the lock system that was in place because it didn't seem to do what it was advertising (read locks were actually ignored in 1.1, IIRC) ; but I am starting to think this creates more problem than it solves. If the goal is just to prevent inconsistent files to be read while they are being written, a small-grained per-file lock built into `OpamFile` IO would be simpler and fully up to the task. Trying to avoid all cases of deadlocks or races might be too restrictive and unneeded for a single-user, interactive program...

Yet most commands load state first and save it back last, without checking for changes. So two concurrent calls to `opam install` in the same switch, for example, can't be allowed (if only for solver and conflicts reasons...) Just locking the files that will need to be written in advance, _e.g._ `switch/installed`, would do though. Two concurrent calls to `update` are probably a bad idea too.

You mention inconsistencies, though I thought the current system was annoying but safe: can you elaborate ?

**Comment by samoht** [comment]
Having a `compare_and_set` in `OpamFile` could makes sense to remove these locks.

**Comment by AltGr** [comment]
It would actually be nice to change the interface of writes in OpamFile to force getting a write-lock when you read a file, if you are going to write it back afterwards ; a run-time check would imply much less changes though. This should make it completely safe, deadlocks apart of course.

A big benefit is that any other tool using opam-lib would be safe wrt concurrency, which is not currently the case.

**Comment by Drup** [comment]
I mean inconsistencies between commands, like two similar commands taking different locks, I reported bugs like that at least once

I don't know much about the internals of opam, so I can't really comment. It would be interesting to keep things like https://github.com/ocaml/opam/issues/1991 in mind. The whole thing boils down to "being loose with locks during long operations".

If you are to introduce something finer grain that would potentially lead to deadlocks, make it easier to report/debug, I remember getting race conditions in opam once, it was impossible to report properly (and I kept getting it until you completely rewrote the download engine).

**Comment by AltGr** [comment]
The finer-grained idea would have:
 1. low-level file locks that just prevent a file to be read while it's being written. The write lock is only kept while the file is being written, _i.e._ very shortly. The reading process should be able to pass after some delay and a retry, without the user even noticing.
 2. longer-term locks that mean that the file is going to be written by a running process, and can't be written or similarly locked by another process.

The interface for 2. and writing could be something like:
```
val read_and_lock: filename -> t * locked_file

val write: locked_file -> t -> unit
```
The first function might create an empty locked file if not existing, or this could be done by another function...

**Comment by AltGr** [comment]
Locks should be much better, and have been completely rewritten in 2.0
