### ISSUE TITLE
Pin: remove before installing new package description from

### ISSUE THREAD

**Issue by Chris00** [ocaml/opam#2264]
When a pinned package is *reinstall*ed, the package description is updated before removing the package.  However, the instructions for removing a package may change between versions, so the package should first be removed (using the old `opam` file).

**Comment by AltGr** [comment]
Yes, this is a limitation; however, since the change to the opam file might be a fix to the uninstall instructions, I am not sure there is a way to handle it properly.
This and the fact that this would be quite painful to handle (update and action processing are two completely separate steps. The only way I see would be to keep the old pinned description around as a fake, older version, and advertise as an upgrade to the solver...) led me to think it wasn't worth handling.
Another solution would be to force removing the package before updating its metadata. Probably nobody wants this ;) -- esp. as you'd lose all dependent packages.

**Comment by dbuenzli** [comment]
One more reason for packages to use `.install` files.

**Comment by Chris00** [comment]
@AltGr I unfortunately do not have a solution.  Only wanted to make sure that the problem is known.  Maybe a mention of the behavior in the manual is enough.

**Comment by AltGr** [comment]
One remark: with the new layout of files, we always keep both versions of the package definition at hand (the one it was installed with, and any more current one).unknown
So this would now be straight-forward to implement. I think it's a better behaviour even if it may prevent hot-fixing of the `remove` commands. Who's against ?
(note that however it won't be that important anymore once we register installed files properly, which is soon).
