### ISSUE TITLE
Opam overrides MAKEFLAGS variable which changes the behaviour of make -e

### ISSUE THREAD

**Issue by mechtaev** [ocaml/opam#2299]
Opam overrides `MAKEFLAGS` variable in `~/.opam/opam-init/variables.sh` which changes the behaviour of `make -e` (`--environment-overrides`). Since `~/.opam/opam-init/variables.sh` is activated from `~/.bashrc`, it can break compilation of other projects.

**Description:** The flag `-e` causes make to use empty `MAKEFLAGS` in the top Makefile, so `-e` is not propagated to sub-Makefiles. For example, if I want to substitute the compiler using `CC=clang make -e`, `clang` will be used only in the top Makefile and not inherited by the sub-Makefiles due to the overwritten `MAKEFLAGS`.

**Related issue:** https://github.com/ocaml/opam/issues/1617

**Possible solution:** changing `MAKEFLAGS=; export MAKEFLAGS` to `unset MAKEFLAGS` solves the problem.

**Comment by michipili** [comment]
I am also baffled by this too. Environment sanitisation is desirable but should happen within **opam** rather than discarding user environment.

In my working environment I defined a shell function `opam`

```
opam()
{
  unset MAKEFLAGS
  unset MAKEOBJDIR
  unset MAKEOBJDIRPREFIX
  /opt/local/bin/opam "$@"
}
```

This allows me to work without reading the `~/.opam/opam-init/variables.sh` but only having relevant parts in my profile.

Also I note that while Linux and BSDs implement an `unsetenv` function, it is not exposed in  *Unix* bindings. As long as it is so, we could provide a simple C-binding for Opam or opt for the easier solution to wrap the call to opam in a shell script.

**Comment by avsm** [comment]
The root cause of this was to fix #1617.  However, it should only be set in commands invoked by OPAM and not trickle out to the `variables.sh` and bashrc.  This seems to be confirmed by looking at the source -- `compilation_env` (that sets MAKEFLAGS) is only called from the build/install/remove sources.  I'm not sure why it leaks out to variables.sh for you.

My own `variables.sh` is:

```
PATH="/Users/avsm/.opam/system/bin:$PATH"; export PATH;
OCAML_TOPLEVEL_PATH="/Users/avsm/.opam/system/lib/toplevel"; export OCAML_TOPLEVEL_PATH;
PERL5LIB="/Users/avsm/.opam/system/lib/perl5:$PERL5LIB"; export PERL5LIB;
MANPATH="$MANPATH:/Users/avsm/.opam/system/man"; export MANPATH;
OPAMUTF8MSGS="1"; export OPAMUTF8MSGS;
CAML_LD_LIBRARY_PATH="/Users/avsm/.opam/system/lib/stublibs:/usr/local/lib/ocaml/stublibs"; export CAML_LD_LIBRARY_PATH;
```

**Comment by mechtaev** [comment]
I reinstalled opam, and `MAKEFLAGS` indeed disappeared from `variables.sh`. So seems like it is already fixed in the current version.

**Comment by michipili** [comment]
Same for me, my infos are a bit outdated! The latest `variables.sh` file is fine.

**Comment by avsm** [comment]
Thanks for checking!
