### ISSUE TITLE
(*.opam  and  *.descr) => *.json

### ISSUE THREAD

**Issue by klartext** [ocaml/opam#2307]
parsing the opam-file would need writing a custom parser for it (AFAIK there is no library for parsing opam-files).
Using json-format would make it so much easier to have access to the content of the*.opam-files.

If that's too much of a change, at least an option for exporting/converting *.opam together with *.descr to *.json via command-line switch would be helpful.

**Comment by dbuenzli** [comment]
> (AFAIK there is no library for parsing opam-files).

See the `OpamFile` module in [`opam-lib`](https://opam.ocaml.org/packages/opam-lib/opam-lib.1.2.2/).

**Comment by klartext** [comment]
My goal was to crreate atool that converts opam-files to other packaging mechanisms.
One reason: less dependencies (from opam and other libs).
But that opam-lib has so many dependencies, that it would need to install many dependencies to have a tool that makes it possible to reduce dependencies.
Looks like no making sense.

Is there a way to reduce most of the dependencies, when I only want to read the information from *.opam and *.descr?

**Comment by AltGr** [comment]
First, a note of caution: the opam-lib has been thoroughly cleaned up and reorganised since 1.2 -- we'll release a new version to the opam repository soon to allow tools to use it, as this doesn't need to wait for the next release of opam itself.

With the new layout, you'll only need to depend on `opam-lib.core` and `opam-lib.format`. Although they aren't yet packaged separately, the dependencies for just these are:
* unix
* ocamlgraph
* re
* jsonm

re and jsonm being really small, that's really not much. The larger batch of dependencies are needed for `opam-lib.solver`, which depends on the dose3 solver library (itself depending on extlib and others).

**Comment by klartext** [comment]
Even though the problem may become solved one day ("soon"), you closed the ticket already.
How do I now when things are solved as mentioned?
IMHO closing the ticket *after* releasing the slim version would make sense more...
Would be nice to become triggered, because "soon" is a source of interpretation....

**Comment by dbuenzli** [comment]
> IMHO closing the ticket after releasing the slim version would make sense more...

The vast majority of free software projects close tickets when they are fixed, not on releases. It seems that @AltGr considers this problem to be fixed.

**Comment by lefessan** [comment]
Since the beginning, I have been a strong advocate of having a library to handle OPAM files (parsing/printing) with as little dependencies as possible. Why would such a library depend on jsonm, ocamlgraph and re ?

**Comment by avsm** [comment]
> My goal was to crreate atool that converts opam-files to other packaging mechanisms. One reason: less dependencies (from opam and other libs).

That's reasonable.  One solution is to bootstrap the command-line tool using something similar to `opam-boot` (which builds a local OPAMROOT, as Npm or Go do) and then builds the standalone binary command-line tool that does the OPAM->JSON conversion.

**Comment by klartext** [comment]
@Dbuenzli: Well, with "releas" I meant public availability. If it's in the public github-repo it would already be helpful (together with a tag to find it). A release (tar.gz) would be fine but not necessary.
"it is fixed" could mean "it is fixed in my local repo". And "released to github, publically available" would fir into my interpretaton of "released".
From the information provided by AltGr I don't see that stuff already is available publically.
And without event-driven / message-driven approach ("ticket closed because problem fixed available on github") it would need me (and possibly others) to poll and ask again.
IMHO closing a ticket with automatical email provided by github is a good way of event-/message-passing.

**Comment by klartext** [comment]
@lefessan, @ avsm: Well, if jsonm already is used by the tool, I wonder, why *.opam to *.json is not possibly via cli-switch by that tool already.

$ opam -export json <package-name>

If that's not planned or avoided because of philosopjhical issues, the question from lefessan, about usage of jsonm makes sense to me. (I had that question already in mind, but thanks for mentioning it, lefessan.)

(Also I wonder (curiosity) what are the reasons to not use json-format and develop opam-fileformat as a new one. Both look very similar, and I don't see a reason, why json-format would not working. were there certain ideas behind it? Or was it just "let's develop our own thing."?)

**Comment by klartext** [comment]
... just to fetch status of this issue and maybe remember that it's open...
... what about the easy export / api-access without many dependencies?
Any progress on this issue?

**Comment by AltGr** [comment]
I am sorry if I closed prematurely: as I understood it, you were asking for a library for parsing opam files, and that's actually already provided (although, as I mentionned, there are ongoing changes).

I am not very keen on either changing the internal format to Json nor writing and maintaining a bidirectional conversion for opam <=> json, mainly because of our limited resources. This said, you are very welcome, would you be ready to invest the time into such a conversion, or even re-use the code from our parsers/printers for an external conversion tool.

On the question of dependencies, which may be another issue, these are the dependencies of our basic standard library, which the parser depends on: it uses our basic types, including maps and sets functors with json converters. It's always possible to lower the granularity, for e.g. ocamlgraph isn't directly needed, but the issue hasn't been raised before, and I actually already reduced the dependencies a lot for the core of our libraries since 1.2.

Also note that jsonm is just below 650 lines of ml, and re around 3000, so it's nothing heavy really.

**Comment by klartext** [comment]
@AltGr @lefessan @agarwal 
Which parts do I need to parse the opam-files, and what are the dependencies, after the mentioned changes?
The reason to have a conversion to other formats (json would be intermeidary) is, to write converters from opam to e.g. PKGBUILD for Arch. If it needs many dependencies just to build the converter, it does not make sense so much to write such a converter, because one reason to write it, is to reduce dependencies from opam, and to create "stand-alone"-PKGBUILDs.
If there is some news to report here, please let me know about the current status.

**Comment by agarwal** [comment]
Hi @klartext, you mentioned me but I haven't participated in this conversation. Let me know if you have a question specifically for me. Maybe mentioning me was an auto-completion error.

**Comment by klartext** [comment]
I found no `OpamFile.OPAM`, but there is a file `opamFile.mli` from `opam-format` lib, which I hope will offer me what I'm looking for.
