### ISSUE TITLE
build opam_admin_top.cmx

### ISSUE THREAD

**Issue by gasche** [ocaml/opam#2371]
In the context of my ocamlbuild-add-dep script, I am experimenting with @Drup's [suggestion](https://github.com/ocaml/opam-repository/pull/5140#issuecomment-161098410) to detect ocamlbuild plugins (full dependency rather than build-time-only dependency) by looking in all files for the ocamlbuild library modules `Ocamlbuild_plugin` (or `Ocamlbuild_pack`).

This means running an ocaml-re on all files of each package archive, and this is quite CPU-intensive (I'm thinking of trying to restrict it to files with name `*.ml*` to avoid processing binary data). It becomes fairly important to be able to compile native-code versions of my script.

Unfortunately, the build rules in opam only build opam_admin_top.cmo, not opam_admin_top.cmx. I have tried to fix this, but they are very obscure to me. I was able to build the file by manually running the command below from `src/tools`:

```
ocamlfind ocamlopt -package re -I ../client -I ../core -I ../format -I ../repository -I ../state -c opam_admin_top.ml
```

**Comment by AltGr** [comment]
Only the cmo is built because the only dependent of opam_admin_top is the opam-admin.top toplevel. It could be a good thing to compile it as an independent library (just similar to `solver`, `repository`, `state` or `client`; although these have their own directory. See src/Makefile).

Note also that there are actually _two_ build systems. Makefiles are really for bootstrap and compatibility -- extremely slow and requiring cleaning all the time -- use `make fast`, which relies on `ocp-build`, if you value your time and sanity.

**Comment by gasche** [comment]
I plan to be lazy on this one: I'm fine with my local hack, and I won't try to patch the build system to send you a pull request (understanding random build machinery gets old after a while). Feel free to change it yourself if you feel it could be useful for others in the future.

P.S.: I plan to eventually submit by add-ocamlbuild-dependency script for inclusion in upstream OPAM in `admin-scripts`, hoping that it could be of use to others to implement similar scripts in the future. I'm still refining the ocamlbuild-detection logic and I'll only submit when I feel the result is stable.
