### ISSUE TITLE
`opam pin add .` doesn't preserve symlinks

### ISSUE THREAD

**Issue by jvillard** [ocaml/opam#2374]
Some of the executables in [this repository](https://github.com/facebook/infer) are python scripts that rely on being symlinked to the location where a specific python module lives. The structure looks like this:

```
bin/infer -> ../lib/python/infer
lib/python/infer
lib/python/inferlib/
```

and infer imports the inferlib module.

After `opam pin add .`, however, `.opam/4.02.2/build/.../bin/infer` is a regular file and thus running `infer` crashes as it cannot find the inferlib python module.

You can reproduce the problem by running:

``` sh
git clone https://github.com/facebook/infer
cd infer/
opam pin add .
```

The compilation error is then:

```
### stderr ###
# Traceback (most recent call last):
#   File "/home/jul/.opam/4.02.2/build/infer.0.4.0/infer/bin/infer", line 12, in <module>
#     from inferlib import analyze, config, utils
# ImportError: cannot import name analyze
```

Would it be possible for opam to preserve these symlinks?

**Comment by AltGr** [comment]
Local pinning uses the `rsync` command with arguments: `-rLptgoDrvc`. (use `-vv` to show the commands)
There was lots of trial and error involvedd to find a set of argumeents that is reasonably reliable across platforms. See part of the discussions at #1158 -- in this case, `-L` had been chosen over `-l` because  of lack of compatibility on certain filesystems. Not sure if we can easily find a workaround, or on which limitation affects the most people.
