### ISSUE TITLE
line added to .profile is not safe with dash and non existent init.sh

### ISSUE THREAD

**Issue by gares** [ocaml/opam#2375]
Premise: if .profile fails then you can't really login (at least not with gdm3)
Problem: one does rm -rf .opam but has in his .profile ". ....opam/..../init.sh || true" as the last line
Suggested solution: use an explicit test instead of "|| true"
Test:
gares@gargamel:~$ bash
gares@gargamel:~$ . not-there || true
bash: not-there: No such file or directory
gares@gargamel:~$ echo $?
0
gares@gargamel:~$ exit
gares@gargamel:~$ dash
$ . not-there || true
dash: 1: .: not-there: not found
$ echo $?
2

**Comment by AltGr** [comment]
Hm, annoying indeed. So this should be I guess e.g.:
```
test -x file && . file || true
```

**Comment by gares** [comment]
Looking at what linux distributions put in the .profile, an "if then else" would be more appropriate.  My understanding is that the logic of boolean operators does not work for the . builtin.  E.g. the .profile in Debian contains:

    if [ -f "$HOME/.bashrc" ]; then
	. "$HOME/.bashrc"
    fi

**Comment by salty-horse** [comment]
Another fix would be to change ~/.bashrc instead of ~/.profile if bash is detected as the shell. It's already done for csh, zsh and tcsh (that is, loading their ~/.*rc file). I'm not sure why bash is handled differently, where opam attempts to edit any of the existing login shell scripts, instead.

This would also fix the issue of opam not being immediately available after installing in Ubuntu, where ~/.bashrc doesn't source ~/.profile by default.

**Comment by salty-horse** [comment]
64c6e37d5f9cdc331da4b6b46e6f66efee127b2a explain the reasoning behind trying to edit ~/.profile instead of ~/.bashrc - When run as a login shell, ~/.bashrc is skipped.

For one, it's a non-issue in Ubuntu, whose ~/.profile loads ~/.bashrc if it knows it's running bash. Perhaps other distros behave similarly?

Second, if that's the right approach, why is ~/.zshrc loaded in case of zsh, instead of ~/.zprofile, which follows the same logic as bash, and won't be loaded for login shells? The "opam init" behavior should be consistent among shells.

BTW, the test for Bash in ~/.profile is different than @gares' comment above:
```bash
if [ -n "$BASH_VERSION" ]; then
    if [ -f "$HOME/.bashrc" ]; then
	. "$HOME/.bashrc"
    fi
fi```

**Comment by AltGr** [comment]
Changed to `test -x file && . file || true` a while ago, and it seems fine. Thanks for reporting!
