### ISSUE TITLE
opam pin is broken in master

### ISSUE THREAD

**Issue by rgrinberg** [ocaml/opam#2383]
For example:

```
$ opam pin add pgocaml --dev-repo
```

Seems like this is caused by opam failing to guess that this is a git repo.

**Comment by AltGr** [comment]
Indeed, thanks for reporting.

This is caused by [`OpamUrl.of_string`](https://github.com/ocaml/opam/blob/1afc97504249b87a380fa02fc6b85cd5278b7c9a/src/core/opamUrl.ml#L151) being used instead of [`OpamUrl.parse`](https://github.com/ocaml/opam/blob/1afc97504249b87a380fa02fc6b85cd5278b7c9a/src/core/opamUrl.mli#L38) in [the `dev-repo:` field](https://github.com/ocaml/opam/blob/1afc97504249b87a380fa02fc6b85cd5278b7c9a/src/format/opamFile.ml#L1644) -- the difference being that `of_string` doesn't handle VC suffixes. I tried to remove any ambiguity in URL parsing & printing with correct support for VCs and backends, and keeping backwards compatibility -- and while using suffixes and alike magic is fine for ambiguous command-line options, it could lead to problems when opam parses and prints its own files (opam prints the unambiguous git target as `git+https://xxx.git`, so it assumes `https://xxx.git` is the https target; otherwise even when explicitely http-pinning a `xxx.git` target, it would end up being understood as git on the next run).

In this case, it should be fine though, since `dev-repo:` _must_ be a VC target. Just another backwards-compatibility hack ;) (we can now easily rewrite the repository to get rid of those anyway).

**Comment by rgrinberg** [comment]
@AltGr thanks for the detailed reply, speaking of the doc for `parse`

https://github.com/ocaml/opam/blob/9c54ffdc80611b1237819f8fdb954b7b431ec54e/src/core/opamUrl.mli#L35

Seems like `of_string` isn't actually exposed anywhere.

I've changed `handle_suffix:true` in `of_string` for myself now until this is fixed properly

**Comment by AltGr** [comment]
Ah, it's part of `include OpamStd.ABSTRACT`

Yup, I have the fix but need to rebase it properly on master, so will push it later on. Thanks for reporting!
