### ISSUE TITLE
.install: two binaries into the same name

### ISSUE THREAD

**Issue by gasche** [ocaml/opam#2392]
We are in the process of writing an `.install` file for the separate ocamlbuild package ( see ocaml/ocamlbuild#29 ). OCamlbuild produces an `ocamlbuild.byte` file and, if it is available, and `ocamlbuild.native` file. We want to install those binaries in `bin/`, and also copy the fastest one of them as `ocamlbuild`. However, neither I nor @rgrinberg know how to express this using the `.install` file. @rgrinberg currently used

```
bin: [
  "?ocamlbuild.native" { "ocamlbuild" }
  "ocamlbuild.byte" { "ocamlbuild.byte" }
]
```

but that will never rename `ocamlbuild.byte` into `ocamlbuild`.

Is this possible to do this with `.install` files, using some implicit priority semantics? If so, I would be glad to send a PR against the documentation to explain this. If not, maybe it would be nice to add this possibility in future opam versions? For example, it would be simple to specify that, if two files are given the same destination name, then the latest (the latest available if `?` modifiers are used) wins.

**Comment by dbuenzli** [comment]
This already came up e.g. in https://github.com/ocaml/opam/issues/2242 . I think it's a bad idea, let's keep the `.install` files purely declarative and avoid introducing any kind of sequential/imperative/overriding behaviour. 

You should not think about `.install` files in static terms (especially it should not be in the opam repository), you should think of it as a manifest. It should be generated precisely at the toplevel of the distribution according to what your build procedure actually built and needs to install. For example in `topkg` an `auto` [binary declaration](https://github.com/dbuenzli/topkg/blob/master/pkg/topkg.ml#L91-L95) will automatically build and install the `.native` if native code is available or `.byte` if the latter is not.

**Comment by gasche** [comment]
Fair enough.

(As a matter of fact I thought a bit more about generating `.install` files from ocamlbuild; that looks rather difficult to do in the general case, but I'll try to think more about it.)

**Comment by dbuenzli** [comment]
> (As a matter of fact I thought a bit more about generating .install files from ocamlbuild; that looks rather difficult to do in the general case, but I'll try to think more about it.)

The problem is that 1) you don't want to install everything that is being built which means that you need a way to specify what you want in your .install file 2) you need a way to specify in which section (directory) you want to have the build artefacts, which can't necessarily be derived from the extension of the build artefacts. I suspect that once you have solved 1) + 2) you'll have something that's pretty near from what `topkg` is. 

Maybe we could look into integrating `topkg` a bit better in the eco-system (versioning the script, avoid to add it to the package themselves, handle meta file generation from a topkg specification) and we'd have a very lightweight package builder to go in hand with ocamlbuild. I always saw `topkg` as a kind of hack but OTOH it seems to work very well in practice is quite unobtrusive.

**Comment by gasche** [comment]
Could we move this discussion to a more suitable place? For example maybe you could create an issue on [the new ocamlbuild issue tracker](https://github.com/ocaml/ocamlbuild/issues/) to discuss `.install`. (We're planning to port the Mantis issues onto the github issue tracker, so the original .install feature request will end up there. We can also go discuss there but maybe you prefer the github interface?)

**Comment by dbuenzli** [comment]
Now that being said 2 could maybe simply be solved via the `_tags` file. A file tagged with `install_lib` goes into the `lib` section, one of the problem though is to handle possible renaming of artefacts and you still need a way to know what needs to be built according to the build environment (i.e. 1).

Yes we can discuss this somewhere else feel free to ping me in the discussion.
