### ISSUE TITLE
--depends-on sometimes incomplete?

### ISSUE THREAD

**Issue by dsheets** [ocaml/opam#2393]
``` sh
$ opam list --depends-on posix-time
$
```

but

``` sh
$ opam show -f depends posix-clock
result & base-unix & posix-time & ocamlfind >= 1.5 & ocamlbuild
```

which, to my eye, contradict each other.

**Comment by AltGr** [comment]
`opam list` by defaults only lists available packages (or just installed when it has no further argument); I guess you may be on OSX, since `posix-clock` has `available: os != "darwin"`. I get:
```
% opam list --depends-on posix-time
# Available packages directly depending on posix-time.0.3.0-0 for 4.02.3:
posix-clock      0.3.0-0  POSIX clock
posix-mqueue     0.7.2-0  POSIX message queues
posix-semaphore  0.3.0-0  POSIX semaphore
```
You may want `opam list -A --depends-on posix-time` to include unavailable packages.

This has already been mentionned in the trackert, but it's planned at some point to refactor `opam list` to make it more consistent and more flexible w.r.t. combinations of filters ; so do speak up if you have suggestions for making the UI better!
