### ISSUE TITLE
`opam update` on mixed-pinned package adds files but doesn't remove them

### ISSUE THREAD

**Issue by talex5** [ocaml/opam#2404]
~/t/test-pkg (master) $ opam --version
    1.2.2

If I add a file `bar` to my pinned (mixed mode) project and reinstall, opam (correctly) adds the new file:

    ~/t/test-pkg (master) $ ls ~/.opam/4.02.3/packages.dev/test-pkg
    foo  opam
    ~/t/test-pkg (master) $ touch bar
    ~/t/test-pkg (master) $ git add bar
    ~/t/test-pkg (master) $ opam reinstall test-pkg
    ~/t/test-pkg (master) $ ls ~/.opam/4.02.3/packages.dev/test-pkg
    bar  foo  opam

However, if I remove a file, reinstalling does not remove it from opam:

    ~/t/test-pkg (master) $ git rm -f bar
    rm 'bar'
    ~/t/test-pkg (master) $ opam reinstall test-pkg
    ~/t/test-pkg (master) $ ls ~/.opam/4.02.3/packages.dev/test-pkg
    bar  foo  opam
    ~/t/test-pkg (master) $

**Comment by AltGr** [comment]
Interesting. We call `rsync` with `--delete`, so the file should be properly removed... however, since this is in mixed mode, rsync doesn't treat untracked files, which I guess includes not removing them. We should probably remove all untracked files by hand before `rsync`ing in this case (note that this applies to the current interface as well as if we replace the functionality offered by the 'mixed mode' by `update --dirty` as advised by @dbuenzli)

**Comment by AltGr** [comment]
This has been fixed since. Thanks for the report!
