### ISSUE TITLE
~/.opam/current

### ISSUE THREAD

**Issue by dbuenzli** [ocaml/opam#2419]
Should be a symlink to the current switch. This e.g. allows to keep bookmarks to the files of the current switch.

**Comment by AltGr** [comment]
This has been asked plenty of times already. While there are no real difficulties, I am very reluctant to add it because it will encourage tool writers to use the symlink rather than go through the opam command-line or lib, breaking the consistency of switch setup when the switch is locally set through the OPAMSWITCH variable.

In short: this seems to likely to end up breaking selecting different switches in different shells using `eval $(opam config env --switch xxx)`

**Comment by dbuenzli** [comment]
Maybe it should just symlink the `doc` directory then, but we can review this once we have figured out a `.cmti` html generation strategy.
