### ISSUE TITLE
"link" kind for opam pin

### ISSUE THREAD

**Issue by lpw25** [ocaml/opam#2465]
When working on a package I've often already built it at the point when I decide to test it out with some other packages. I think it would be useful if at this point I could do `opam pin . -k link` which would then create symbolic links for all the things in my `.install` file (and I guess fail if no such file exists) into the appropriate place in my opam root and mark the package as installed.

If I `opam reinstall` the pinned package it should check if the `.install` file has changed and if so update the links. It should probably also reinstall anything which depends on the package.

I don't know what the status of "compilers as packages" is, but the compiler itself is where I would probably get most benefit for this. Having to rebuild the compiler again  to test opam packages is a major pain. Currently I have to push the compiler source somewhere specific, create a new switch using that source (which requires me to create my own little repository) and then rebuild the compiler. Every time I then fix a bug in this compiler I have to create a new switch and rebuild it all over again.

**Comment by AltGr** [comment]
> I don't know what the status of "compilers as packages" is

On the `next` branch, compiler definitions have completely been removed in favor of package definitions with the proper options. This would indeed make your setup much easier, since you can use `opam pin` on your compiler and have all the switch update with it. Indeed, that's how the [flambda benches](https://flambda.opam.ocamlpro.com) are run.

As you mention, though, this still needs a rebuild. Installing by hand (i.e. `make install`) then `opam install --fake` can be used in some cases, but it's dangerous as it will fake _all_ of its removals/installs/reinstalls, not just the wanted package's.
A possible interface that would, I think, fit your use-case, would be `opam (re)install --skip-build <package>`, which would probably only make sense for path-pinned packages, and only run the install instructions.

Note that, as pinnings allow you to locally edit the metadata, you could also use `opam pin edit` and just remove the build instructions. If your package is path-pinned, and assuming the source directory was properly built, that would work on `next`.

**Comment by lpw25** [comment]
> opam (re)install --skip-build <package

That would indeed be similar to having a "link" kind. A "link" kind feels more natural to me as the kind is what describes how to tell when there have been changes and when to rebuild the package, and for "link" the answer is to never rebuild the package.

**Comment by AltGr** [comment]
I believe either `--keep-build-dir`/`--reuse-build-dir` or `--inplace-build` provide a solution to this ?
Otherwise, pinning as `file://` would keep the artifacts from the source tree and may work too.
