### ISSUE TITLE
Is there a way to make opam use a solver that will find a solution

### ISSUE THREAD

**Issue by UnixJunkie** [ocaml/opam#2467]

**Comment by UnixJunkie** [comment]
I mean, a dependency resolution solver that will find the solution if it exist.
I wonder if camelus is not using one such algorithm.
That could be an option when you are not amused anymore about trying to solve a constraint by hand.
@abate

**Comment by UnixJunkie** [comment]
opam --no-deps-heuristic some_package

**Comment by samoht** [comment]
I'm not sure to understand your queston. Have you tried using aspcud?

**Comment by AltGr** [comment]
External solvers like aspcud are supposed to find the solution if it exists. There is no upper bound on the time it may take though.
camelus only checks for satisfiability, without looking for a solution. Note that it may not be overstimating installability since it ignores OS and compiler constraints.
