### ISSUE TITLE
Make "pin add" the default pin action

### ISSUE THREAD

**Issue by lpw25** [ocaml/opam#2487]
I constantly write this:

```
opam pin foo .
```

instead of

```
opam pin add foo .
```

could `add` be made the "default" for `opam pin` much like `install` is the "default" for `opam switch`?

**Comment by Drup** [comment]
It was the case originally, and it was changed later. It was considered that the behavior would be too unreliable, given that there are subcommands to `pin`, contrary to `install`.

But I keep getting wrong too ...

**Comment by lpw25** [comment]
> given that there are subcommands to pin, contrary to install

Do you mean contrary to `switch` -- in which case there *are* subcommands for `switch`? Or do you mean subcommands for `pin add` (and so contrary to `switch install`) -- in which case "oh, what are the subcommands for `pin add`"?

**Comment by dbuenzli** [comment]
@lpw25 the more ambiguous the command line becomes the less easy it becomes to give good error messages. 

E.g. your proposal would prevent the use of all subcommands as package names for pinning without the `add` which is a little bit ugly. Or you would have context-dependent command line parsing (e.g. `opam pin list` is the `list` command but `opam pin list dir` is pin package `list` to `dir`) which I'm not sure is a good idea. 

Regarding `switch` I guess the problem has been less acute since the `SWITCH` arguments have only been version numbers so far.

What could maybe be done however is that `opam pin` without subcommand and positional arguments tries to pin to `.` and has an heuristic to guess the package name e.g.: 

1. Look into a toplevel `opam` file if there's a `name:` mentioned
2. If not look for the `dev-repo:` field and try to get the basename of the last segment without the vcs extension (this won't work with `ocaml-` prefixed packages though so it may not be a good heuristic)
3. Finally if nothing was determined yet use the current working directory's basename.

**Comment by lpw25** [comment]
> your proposal would prevent the use of all subcommands as package names for pinning without the add which is a little bit ugly

I would instead simply ban packages with those names from repositories. That seems a pretty small cost to make the interface easier to use and it can be checked statically by the `opam admin` tools.

`pin` is possibly the most frequently typed command so there really is a cost to the extra `add` (not to mention the extra `opam pin foo . ^M` and the couple of seconds to realise what has happend).

**Comment by dbuenzli** [comment]
> I might instead simply ban packages with those names from repositories.

Imposing restrictions on package names because of the cli seems rather artificial to me. Not to mention that you want to be free to add new subcommands in the future without getting a chance to disturb existing repos.  

Note that in this case the mind slip is likely that `pin` is both a verb and a noun so the need to specify the add feels unnatural or redundant. Contrast e.g. with the `repo` command. 

Personally since the way to get a decent behaviour on a `pin` at the moment is so involved (`opam pin add -kgit PKG PKG#master`), I think I got over this.

**Comment by dbuenzli** [comment]
> Note that in this case the mind slip is likely that pin is both a verb and a noun so the need to specify the add feels unnatural or redundant.

In case it's not clear I said this to counter your claim "there is really is a cost to the extra add". I think that from an UI point of view that cost is completely negligible; the problem is really the above verb/noun confusion which makes our minds slip.

**Comment by lpw25** [comment]
> Imposing restrictions on package names because of the cli seems rather artificial to me. Not to mention that you want to be free to add new subcommands in the future without getting a chance to disturb existing repos.

Yeah it probably is going a bit too far. I think the version you mentioned where such packages must use the full `opam pin add` form would be fine though.

> Personally since the way to get a decent behaviour on a pin at the moment is so involved (opam pin add -kgit PKG PKG#master), I think I got over this.

We should really be trying to make `opam pin foo .` have the most commonly desired behaviour for pinning.

**Comment by AltGr** [comment]
Yup, I was convinced by @dbuenzli's arguments for removing the `opam pin pkg` syntax, but keep tripping on this too...

**Comment by AltGr** [comment]
Re-added it :p
