### ISSUE TITLE
conf-* packages should be installed before other packages are uninstalled

### ISSUE THREAD

**Issue by lefessan** [ocaml/opam#2488]
conf-\* packages are supposed to check for external dependencies to be available, before installing a package. Thus, I would suggest that they should be installed before other packages are uninstalled, i.e. a package should not be removed when it conflicts with another package that cannot finally be installed because one of its external dependencies is not available.

For example, when calling opam, opam could divide the set of packages to be installed into two sets: conf-\* packages and other packages. opam would then install all the conf-\* packages, and if it does not fail, it would try to install the other packages, removing conflicting packages if needed.

**Comment by AltGr** [comment]
I really would like to avoid having a specific treatment for `conf-` packages; I think there are more generic solutions though:

- #2319, #2326 (which is incomplete, but @hnrgrgr has pending improvements) may provide a more generic solution to this, by _always_ doing the removals as late as the dependencies and conflicts allow
- otherwise, we could imagine having a more generic way to detect exernal features that runs before we actually start the installation process ; this kind of is the idea of the plans for integrating depexts, but `conf-$*` packages are more generic in expressing their checks.

**Comment by AltGr** [comment]
This is a nice consequence of our new, clever ordering of actions.
