### ISSUE TITLE
Removing a package should not remove packages that only `{build}` depend on it.

### ISSUE THREAD

**Issue by dbuenzli** [ocaml/opam#2494]
E.g. 

```
opam remove ocamlbuild
```

**Comment by AltGr** [comment]
This limitation was decided when build-deps were implemented. In short, the problem is that, by allowing removal of build-deps, we would lose the ability to `switch export/import`.

Why ? Because a given state could be unreachable in a single step (or even in any given number thereof). Imagine that `a` build-depends on `b`, and `c` conflicts with `b`. You could have both `a` and `c` installed, but they're not installable in a single step, you would need to first install `b` and `a`, then remove `b`, then install `c`. Computing such multi-stage installation scenarii didn't seem worth the effort (although I read a paper from the Debian team where they resolve a similar problem for bootstrapping their distribution).

So, as documented, build-deps only affect recompilation for now.

**Comment by dbuenzli** [comment]
I see, thanks for the explanation.
