### ISSUE TITLE
Idea for aliases

### ISSUE THREAD

**Issue by fxfactorial** [ocaml/opam#2504]
Sorry if this is already the case, i looked through issues and the package for this but couldn't find it.

I'd like it if `opam` packages could also have aliases for packages. For example, my package is called `usbmux` but it comes with a binary called `gandalf`. The people that use this program might get confused and do `opam install gandalf` instead of `opam install usbmux`. 

`opam` files could add another field, `aliases` that takes a list of strings. These aliases could live in a different namespace from proper names, and we could limit number of aliases to two.

**Comment by hannesm** [comment]
I dislike this proposal.  the scarce resource of package names (due to being a single namespace) should not be filled with packagers who cannot decide on the name of their library/application.  how could a `different namespace` work? `opam install --alias-namespace gandalf`? looks pretty fishy to me.

**Comment by fxfactorial** [comment]
@hannesm other package managers are able to do this just fine, for example on `OS X` there's `brew install ocaml` and `brew install objective-caml`

**Comment by dbuenzli** [comment]
It's in general not a good idea to multiply names for the same thing, it gets quickly confusing (e.g. in deps specification, in communication among users, etc.). Also you should realize that your proposal doesn't scale at all, what if my package installs a dozen of executable ? 

If you really want something like this a better idea for this would be to use the sorely needed opam extension fields (https://github.com/ocaml/opam/issues/2254) where you could declare binary names installed by packages in say a `x-installed-binaries` field. You could then perfectly have a hypothetic opam plugin that install things based on what it reads from that field. Unfortunately due to the very slow release cycle of opam, this feature, which I'm looking forward to abuse, is still not available to us.

**Comment by fxfactorial** [comment]
Its a little interesting how this is instantly a "can't scale" issue when brew is doing just fine with many tens of thousands more users....

In any case I guess this is of little interest to anyone else.

**Comment by dbuenzli** [comment]
> Its a little interesting how this is instantly a "can't scale" issue when brew is doing just fine with many tens of thousands more users....

The scalability issue is not about the number of users. It's the mecanism itself that you propose that doesn't scale and brings noise into the system. 

I'm looking forward to your pull request to `brew` that aliases the following names: 
```
ocaml              ocamldebug         ocamllex.opt       ocamloptp
ocamlbuild         ocamldep           ocamlprof
ocamlbuild.byte    ocamldep.opt       ocamlmklib         ocamlrun
ocamlbuild.native  ocamldoc           ocamlmktop         ocamlrund
ocamlc             ocamldoc.opt       ocamlobjinfo       ocamltags
ocamlc.opt         ocamlopt           
ocamlcp            ocamllex           ocamlopt.opt       ocamlyacc
```
to the package name `ocaml`.

**Comment by AltGr** [comment]
@fxfactorial see the proposal for a `provides:` field, which is more or less the same as what you propose. There was the beginning of some discussion long ago [here](https://github.com/ocaml/opam/issues/314), and there is a preliminary design document [here](https://github.com/ocaml/opam/blob/master/doc/design/provides.md) (this is already a bit old, though, I have been working on a new version just in the last few days but it's not ready yet).

@dbuenzli yes, yes, next version coming, sorry for the delay!
