### ISSUE TITLE
Supplying -y to opam pin in wrong directory is difficult to cancel.

### ISSUE THREAD

**Issue by jordwalke** [ocaml/opam#2505]
Sometimes, I'll accidentally `pin` the wrong directory, one that doesn't have an `opam` file in it, which causes `opam` to prompt me for a new `opam` file in my editor (which is a GUI app (macvim)). But at this point, I realize I want to cancel the pinning, and I cannot easily. `ctrl+c` doesn't work on the command line. There's no way to break out of this flow. If I simply try to save an empty file in the editor that had popped up, opam will just reopen the editor.

The only way to break out of this cycle, is by `ps`ing, finding the `pid` and killing it.

**Comment by dsheets** [comment]
This may be the same as #2401 but I'm not sure what commit fixed #2401 so the issue may still exist (in trunk) in some configuration.

**Comment by AltGr** [comment]
It's similar, but I only fixed #2401 by stopping if the editor returns non-zero, which doesn't really help here. Since it requires interactive mode anyway, the retry message may probably ignore `--yes` (or fail if set). `ctrl-c` not working is the responsibility of macvim, but the problem is there also with terminal editors anyway.
Another solution would be to wait for user input before starting the editor in all cases, which would allow the user the time to read what's going on (in case it's in console mode).

**Comment by jordwalke** [comment]
I like git interactive rebase's behavior:  if you delete all of the text in the editor that pops up it cancels the original attempt.  You could include a comment in the dummy opam file template  that informs the user of this behavior. It's not the best solution but I imagine it's very easy to implement.

**Comment by AltGr** [comment]
Now implemented (ask for input before starting the editor, abort on empty file, better behaviour depending on whether there is a terminal).
Thanks for reporting!
