### ISSUE TITLE
opam pin fails 

### ISSUE THREAD

**Issue by neolem** [ocaml/opam#2516]
I am getting the error below while trying to `opam pin add --dev utop`,
https://github.com/diml/utop/issues/165#issuecomment-209937298

```
utop is now git-pinned to git://github.com/diml/utop.git

[utop] git://github.com/diml/utop.git updated
[utop] Installing new package description from git://github.com/diml/utop.git

utop needs to be installed.
Your request can't be satisfied:
  - utop.1.19 is not available because the package is pinned to git://github.com/diml/utop.git, version 1.19.

No solution found, exiting
[NOTE] Pinning command successful, but your installed packages may be out of sync.
```

**Comment by AltGr** [comment]
Note that, as the last message mentions, the pinning didn't actually fail. But the package install did.

The message "not available because the package is pinned" is indeed a bit off; the package was found unavailable but this isn't the proper reason ; master utop's opam file mentions `available: ocaml-version >= "4.01"` -- do you have at least that ?

Otherwise, try `opam install utop` by hand to see if you get a better message; adding `--verbose --debug` might give more clues.
I'd be interested in the real reason this wasn't available in order to fix the message.

Thanks for reporting!

**Comment by neolem** [comment]
I have `ocaml 4.03.0+beta2`. `opam install utop` gives the error below.
```
'opam install utop --verbose --debug' failed.
Fatal error:
OpamFormat.Bad_format(_, 0, "'+' is not allowed in compiler versions")
```

**Comment by AltGr** [comment]
Ok, thanks a lot for reporting. This is due to the combination of a packaging error for the beta compilers, and bad handling of this error by opam; see https://github.com/ocaml/opam-repository/issues/6250 for details.

Just updating once the above PR has been merged should be enough to fix the error for you (or if you can't wait, try editing `~/.opam/compilers/4.03.0/4.03.0+beta2/4.03.0+beta2.comp` to remove the `+...` part in the `version:` field.)
