### ISSUE TITLE
Bad error message "No package matches ..."

### ISSUE THREAD

**Issue by mshinwell** [ocaml/opam#2526]
I don't think an error message saying "No package matching foo" should be emitted when the package "foo" exists.  If the problem is that "foo" exists but there is some further problem making it inadmissible for installation, then the error should say what that problem is.

For example:

```
$ opam install ... conduit ...
Your request can't be satisfied:
  - No package matches conduit.

No solution found, exiting
$ opam info conduit
             package: conduit
             version: 0.11.0
...
```

**Comment by AltGr** [comment]
Thanks for reporting. This is indeed what should happen, could you give some more details so that I can attempt to reproduce ? (What opam version, and the specifics of your `conduit` package, esp. availability constraints).

**Comment by ngzhian** [comment]
I found a similar error message as well, while trying to install `jingoo`.
```
$ opam --version
1.2.2

$ ocaml --version
The OCaml toplevel, version 4.03.0

$ opam install jingoo                                                                                                                                                                                               
Your request can't be satisfied:
  - No package matches jingoo.
 
  No solution found, exiting

$ opam install --debug jingoo
 ...
00:01.741  HEURISTIC               state-of-request: install:(base-bigarray & base-bigarray (= 1) & base-threads & base-threads (= 1) & base-unix & base-unix (= 1)) remove:() upgrade:(jingoo) criteria:"-removed,-notuptodate,-changed" CONFLICT!
00:01.741  CUDF                    resolve request=install:(base-bigarray & base-bigarray (= 1) & base-threads & base-threads (= 1) & base-unix & base-unix (= 1)) remove:() upgrade:(jingoo) criteria:"-removed,-notuptodate,-changed"
00:01.741  CLIENT                  conflict!
Your request can't be satisfied:
  - No package matches jingoo.
...
 
  No solution found, exiting
```
while googling around I found this https://github.com/ocaml/opam/issues/2010 which mentioned installing `aspcud`, I'm on Ubuntu 16.04 so I did
```
$ apt install aspcud
```
That fixed that error (I still couldn't install jingoo but it was because it depended on batteries which was not compatible with my installed ocaml version, so it's separate).

**Comment by AltGr** [comment]
Ah, I see ; I have indeed found cases where the internal solver mistakenly reported no solution, and pretended there were conflicts with an erroneous message: this may be another instance of that, I'll dig further.

**Comment by ngzhian** [comment]
@AltGr I'm not sure if this is a good place to ask, but I'm recently picking up OCaml, and would like to learn by contributing. If you find that this task can be scoped pretty nicely I would love to tackle this task with your guidance, thanks!

**Comment by AltGr** [comment]
@ngzhian thanks a lot for proposing your help!

You'd be very welcome and I would be glad to help you through. However, tinkering with the so-called "internal solver" isn't the task that I would choose to begin with: it's complex, not very pretty, not really documented, and doesn't work well. It's rather well delimited, but the interface itself (shared with the external solvers) is'nt easy to grasp either.

If you'd rather be directed towards something that may be a smoother start, there is plenty to do -- I just finished big reorganisations and API rehauls that made integrating change difficult, but it should now be easier than ever.

For directions, you should start from https://opam.ocaml.org/doc/2.0/api/

And if the above didn't drive you away and you want to have a look at the internal solver, that would actually be very useful. It's in `src/solver/opamHeuristic.ml`.

One last think: it shouldn't be a bother, but I must mention that there is currently a bug in the opam license (exception put on the wrong article due to a version mismatch). Discussions are underway to fix this, but I prefer to let you know before you work on this that there _might_ be a different license to accept and maybe a CLA to sign. Most likely, it'll just be LGPL2 rather than 3 though.

**Comment by tomsib2001** [comment]
Hi,
I have instances of this problem on opam 1.2.2, Ubuntu 16.04. Steps to reproduce:
```
opam repo add coq-released https://coq.inria.fr/opam/released
opam show coq-coqeal-refinements
opam install coq-coqeal-refinements
```
and the output is 
```
Your request can't be satisfied:
  - No package matches coq-coqeal-refinements.

No solution found, exiting
```
I have the same problem with the package `coq-math-comp`.

**Comment by AltGr** [comment]
Please try out opam 2.0.0, which should fix this and much more. It's still in beta but getting stable, and should be released in the coming weeks.
