### ISSUE TITLE
Next: `opam list --rec --required-by ` is a bit confusing

### ISSUE THREAD

**Issue by Drup** [ocaml/opam#2536]
On stable opam (thx @dbuenzli):

```
% opam list --rec --required-by oasis
: # Available packages recursively required by oasis.0.4.5 for 4.02.3:
base-ocamlbuild           base  OCamlbuild binary and libraries distributed with
base-unix                 base  Unix library distributed with the OCaml compiler
camlp4                  4.02+7  Camlp4 is a system for writing extensible parser
conf-m4                      1  Virtual package relying on m4
conf-ncurses          1+system  Virtual package relying on ncurses
conf-which                   1  Virtual package relying on which
fileutils                0.4.4  Library to provide pure OCaml functions to manip
ocaml-data-notation     0.0.11  Store data using OCaml notation
ocamlbuild                   0  Build system distributed with the OCaml compiler
ocamlfind                1.6.2  A library manager for OCaml
ocamlify                 0.0.1  Include files in OCaml code
ocamlmod                 0.0.8  Generate OCaml modules from source files
ounit                    2.0.0  Unit testing framework loosely based on HUnit. I
type_conv            113.00.02  Library for building type-driven syntax extensio
```

On next opam:

```
% opam list --rec --required-by oasis -s
base-bigarray           
base-bytes              
base-metaocaml-ocamlfind
base-threads            
base-unix               
batteries               
camlp4                  
camomile                
conf-libpcre            
conf-m4                 
conf-ncurses            
conf-pkg-config         
conf-which              
expect                  
extlib                  
fileutils               
lwt                     
oasis                   
ocaml                   
ocaml-data-notation     
ocamlbuild              
ocamlfind               
ocamlgraph              
ocamlify                
ocamlmod                
ounit                   
pcre                    
ppx_tools               
type_conv
```

On the other hand, `resolve` (it's new ?) returns what I would expect.

```
% opam list --rec --resolve oasis -s
base-bigarray      
base-ocamlbuild    
base-threads       
base-unix          
camlp4             
conf-m4            
conf-ncurses       
conf-pkg-config    
conf-which         
oasis              
ocaml              
ocaml-data-notation
ocamlbuild         
ocamlfind          
ocamlify           
ocamlmod           
type_conv   
```

Is it expected ? It's a bit confusing. The result from --required-by are quite nonsensical.

**Comment by AltGr** [comment]
I re-implemented the whole "list" command module to be much more generic and flexible, then tried to bind the old API on top of it, as a first step before providing a better CLI. So thanks for reporting on the issues so far!

I think the issue here is the expectation on specifying `oasis`, which 1.2.2 interprets as `oasis.<current>` (where `<current>` is the installed version if any, the maximum available version otherwise) while 2.0 interprets it as `oasis.*`. What's troubling you is then that you get all dependencies for _any_ version of oasis. Ideally we should provide a way to specify either, and `<current>` should probably be the default.

The recursive behaviour should also be specified. The problem is that by arbitrarily choosing versions, we may be missing dependencies (that would be needed to actually install the package on the system), but by including all we are likely to include unwanted stuff. The only thing to do, I guess, is to try to be as consistent as possible and be clear in the specification: that's why I added the leading comments in 1.2.2: `# Available packages recursively required by oasis.0.4.5 for 4.02.3`
The problem is that, with the newer more flexible API, the description is actually the filter used itself, and can't be so easily printed in English. We could actually output the filtering formula used though.

`resolve` is not new, and is a bit different (from `opam.1.2.2 list --help`):

       --resolve=PACKAGES
           Restrict to a solution to install (comma-separated) PACKAGES, i.e.
           a consistent set of packages including those. This is subtly
           different from `--required-by --recursive`, which is more
           predictable and can't fail, but lists all dependencies
           independently without ensuring consistency. Without `--installed`,
           the answer is self-contained and independent of the current
           installation. With `--installed', it's computed from the set of
           currently installed packages. `--unavailable` further makes the
           solution independent from the currently pinned packages,
           architecture, and compiler version. The combination with
           `--depopts' is not supported.

**Comment by AltGr** [comment]
(cont)

To be more explicit: if you add the oasis version, the result may be closer to what you expected:
```
% opam list --rec --required-by oasis.0.4.5 -s
base-bigarray           
base-metaocaml-ocamlfind
base-ocamlbuild         
base-threads            
base-unix               
camlp4                  
conf-m4                 
conf-ncurses            
conf-pkg-config         
conf-which              
fileutils               
lwt                     
oasis                   
ocaml                   
ocaml-data-notation     
ocamlbuild              
ocamlfind               
ocamlify                
ocamlmod                
ounit                   
ppx_tools               
type_conv               
```

With `--debug`, you actually get the filter used:
```
opam list --rec --required-by oasis -s --debug
==> available & rec-required-by(oasis)
```

**Comment by Drup** [comment]
@AltGr Thanks for the detailed answer!

> What's troubling you is then that you get all dependencies for any version of oasis. Ideally we should provide a way to specify either, and <current> should probably be the default.

I agree, the default should clearly by <current>, but in fact, I'm wondering if the behavior of `resolve` should not be the default one. The only downside is that calling the solver can be slow, but the information provided seems much more in line with what I would expect.

**Comment by AltGr** [comment]
I don't know: if you have alternatives, e.g. `"async" | "lwt"`, `resolve` will arbitrarily choose one, while `required-by` will list both, which I think is better. Also, `resolve` is more sensitive to the current context.
