### ISSUE TITLE
Next: Assertion failure during opam install

### ISSUE THREAD

**Issue by Drup** [ocaml/opam#2546]
```
% opam config report
# OPAM config report
# opam-version    2.0~alpha (abbc828de87d32c774f1e30bf830144b44a06048) 
# self-upgrade    no
# os              linux
# external-solver aspcud $in $out $criteria
# criteria        -count(removed),-notuptodate(request),-sum(request,version-lag),-count(down),-notuptodate(changed),-count(changed),-notuptodate(solution),-sum(solution,version-lag)
# jobs            4
# repositories    1 (http), 3 (version-controlled)
# pinned          0
# current-switch  4.01.0
% opam list
# Packages matching: installed
ocaml 4.01.0 Official 4.01.0 release
% opam install -debug -vvvv lwt
'opam install -debug -vvvv lwt' failed.
Fatal error:
File "solver/opamCudf.ml", line 182, characters 22-28: Assertion failed
Backtrace:
  Raised at file "state/opamSwitchState.ml", line 456, characters 60-61
  Called from file "state/opamRepositoryState.ml", line 218, characters 14-18
  Re-raised at file "state/opamRepositoryState.ml", line 219, characters 38-39
  Called from file "state/opamGlobalState.ml", line 517, characters 14-18
  Re-raised at file "state/opamGlobalState.ml", line 518, characters 38-39
```

This is one of the old switches. It's reproducible with some other old switches.

**Comment by AltGr** [comment]
Ah, this is annoying. Could you get the cudf file and log for me ? (Oh, and an export file too would be perfect).

There is actually [code to handle this case](https://github.com/ocaml/opam/blob/667eacd9e75940e8eb5247d726054383ec68bf77/src/solver/opamCudf.ml#L182-L210), but __it shouldn't be needed anymore__ :/
This assert means that the solver reported a (package, version) that can't be found in the conversion maps. The mapping is kind of complex because you can reference non-existing versions (e.g. `"ocaml" >= "3.15"` is valid), and it's best to keep those as specified in the error messages.

Thanks a lot for reporting!

**Comment by Drup** [comment]
I think you solved this, one way or another. Closing!
