### ISSUE TITLE
"opam update foo" is unreasonably slow

### ISSUE THREAD

**Issue by mshinwell** [ocaml/opam#2548]
I think it took more than a minute on a fast machine for "opam update foo" to run on my personal opam-repo-dev, which is tiny, and contains only a few compiler descriptions.  The slowness can waste time when trying to get compiler descriptions correct.

**Comment by AltGr** [comment]
Thanks for reporting. This is due to #2534 : after doing the actual update, opam simulates an update just to show some statistics on changes and this actually what takes (wastes) time. We could easily add an option or even disable this by default, but the priority is to actually fix #2534 

In the meantime, you can safely press `C-c` once the `[repo] synchronised from xxx` is printed if you can't wait. Time before that should really only be used by the download.
