### ISSUE TITLE
"opam switch list" should use a better ordering

### ISSUE THREAD

**Issue by mshinwell** [ocaml/opam#2549]
Whenever I run "opam switch list", I never see the compiler that I would like, and always have to run it again a second time with "--all".  The reason for this is that the compilers listed first seem to be ancient (e.g. 3.07).

In general I find it frustrating when tools designed to be run from the shell, such as opam, insist on arbitrary limits as to what they output to the terminal.  There are plenty of Unix tools for dealing with output that doesn't fit on one's terminal.  If there really must be a limit, I think a better sort order should be chosen.  Or perhaps I am missing something here.

**Comment by AltGr** [comment]
Compiler versions are split into "official" ones and branches. Only the official releases are shown by default, beside of course what is already installed.

The reason for this behaviour is that the vast majority of users are only concerned with normal OCaml versions, so spamming them with screenfuls of `ocaml.4.04+prXX` wouldn't provide a nice experience.

**Comment by amirmc** [comment]
I concur with @AltGr but I also find it unhelpful that versions older than `4.01` are shown by default.  Do we really need versions as far back as `3.07` to be displayed by default?

**Comment by AltGr** [comment]
Hmm, but then, on what criteria would you want opam to base the version displayed ? An additional package flag ? Limit the display to a fixed number of versions ?
(the current criterion is just "version without any funny characters in them", which matches official releases pretty well)

**Comment by fxfactorial** [comment]
Rolling on past three years of compiler years is something decent maybe

**Comment by Drup** [comment]
That issue is even more striking with the last dev version, the default list is very long and quite unreadable.

**Comment by AltGr** [comment]
The proper solution would probably be to remove the arbitrary split done by opam, but move dev compiler branches to their own repo.

**Comment by AltGr** [comment]
I believe the listing has been improved and should now be OK ; splitting would further improve, but is a repository matter.
Note that `opam switch list` now only lists the installed switches, while `opam switch list-available` lists the available ones -- merging switches and compilers no longer makes sense in opam 2. The completion scripts have also been improved so that you may not even need to list (just `opam switch create <TAB><TAB>`).

A pending patch also removes the need for `--all` and the limitation of the default `list-available` to "official" switches (defined as the ones with only number and dots in their versions), which should complete solving this.
