### ISSUE TITLE
opam show is verbose

### ISSUE THREAD

**Issue by Drup** [ocaml/opam#2617]
Opam now tracks installed file. This is *great*. However, `opam show` shows all the files by default, which tends to be a lot. I suggest a new option, `--files` that will shows only the installed files. 

Additionally, I think `opam show` shouldn't show empty fields.

Finally, the way format boxes are arranged is not very nice, in particular for the description field, where it causes a huge left margin.

**Comment by AltGr** [comment]
There is already `--field installed-files`, so I don't know if `--files` is required, but maybe a shortcut would be nice ?

Otherwise changing the default set of displayed fields is [trivial](https://github.com/ocaml/opam/blob/5aa25f5e3f583166ac9a71a55076d71365dc1415/src/client/opamListCommand.ml#L633-L651). Filtering empty fields is slightly more complicated, since we probably don't want to do it when they have been specified explicitely through `--field`.

**Comment by Drup** [comment]
I was thinking `--files` would show only the files, actually. And yes, I think you should have a dedicated option, if only for discoverability purposes.

**Comment by AltGr** [comment]
Adde `opam show --list-files`
