### ISSUE TITLE
Options to navigate versions of a package. 

### ISSUE THREAD

**Issue by Drup** [ocaml/opam#2618]
With the brand new repository format, the `ocaml-variants` package has many version. `opam show` is not very appropriate to explore this and `opam switch list` has limited search capabilities.

Apparently, `opam list` now has the `--all-versions` flag (Is that new ? I was going to suggest it, and discovered it buried in the doc, I think it should just be `--versions`). We also have the `--compilers` option, but it doesn't seem to do what I would expect (it also show the `base` packages).

So all we need are new filters on versions, such as ">=4.03" or "~=4.01", or maybe regex for after the `+` (to list all prs, for example). 

Note that `--compiler` and `all-versions` are not available on `opam search`, not sure why.
I think we should aim to make `opam switch list -a` an alias of `opam list` with some arguments (which does not seem to be exactly the case, right now).

This is partially related to https://github.com/ocaml/opam/issues/2549

**Comment by AltGr** [comment]
Thanks for the review, there are many new capabilities in the `OpamListCommand` module, but the CLI should be perfected yet.

- `--all-versions` is indeed new, and is more accurate since listing without it will just pick a version for showing the details of each package (installed, or failing that, highest).
- `--compilers`: indeed, I overlooked that it might be misleading. This is to be compared with `--installed` and `--roots`, and will filter the packages that are _installed as compiler in the current switch_. What you want is filtering packages that have the `compiler` package flag, which it seems I forgot to bind in the CLI yet, but should look like `--has-flag=compiler` (you can resort to the textual `--field-match=flags:compiler` but it's ugly and would match `notacompiler`)
- you can filter with globs, but only on package names at the moment with the normal selector. Allowing version constraints, or a combination of that and globs would indeed be nice (the implementation already allows matching name+version constraint, like e.g. `opam install`, but that's not available yet in the CLI). Note that you can already resort to e.g. `--field-match=version:'*+pr*'.
- indeed, it's not done yet but one objective was to merge the output formats of `opam list` and other listings. It's already the case for `search`, and `show` has a different output format but uses the same selectors. `opam switch` and `opam pin` still are separate, the trouble being, for `switch` that it also has the purpose of listing _installed_ switches, which don't exactly match with packages although the two are listed together.

**Comment by Drup** [comment]
My issue with some of those is that they are basically impossible to discover; someone need to told you. Even the manpage doesn't help that much, that's why I would prefer dedicated CLI options. 

About `compiler`, maybe `--base-packages` instead ? (I still find the notion of "installed as compilers" quite weird, instead of just "base packages", especially given that, in practice, half of them starts with `base-`).

By the way, there is both a notion of "column" and "field" in the manpage, that are close but not equals. And there is no list of the available fields available directly there.

**Comment by AltGr** [comment]
> About compiler, maybe --base-packages instead ? (I still find the notion of "installed as compilers" quite weird, instead of just "base packages", especially given that, in practice, half of them starts with base-).

Hmm, I think you are right, best avoid this ambiguity which isn't needed.

> By the way, there is both a notion of "column" and "field" in the manpage, that are close but not equals. And there is no list of the available fields available directly there. 

Ah, that one I thought would be clear. A column is just a column that you want displayed in the output table. A field is just an [opam-file field](http://opam.ocaml.org/doc/2.0/Manual.html#opam). I think this _should_ be clear but I apparently didn't explain it well :)

Splitting the options into different sections for package selection and output format would probably make things much clearer already

**Comment by AltGr** [comment]
I think we should split up `opam switch list` into
- the default option showing only installed switches (possibly with the current output format)
- an option to show available compiler packages, i.e. packages that you are allowed to `switch` to

as the two are fairly different, have different purposes and their information doesn't even match anymore -- I usually want the first and don't care to have all OCaml versions listed. Not sure what arguments would be best CLI-wise though.

**Comment by AltGr** [comment]
Maybe we should rework how the option works overall, though -- I have until now been extending it only incrementally. The confusion above also results from the fact that `opam switch SWITCH_NAME` and `opam switch COMPILER_PACKAGE` both work (because, in the second case, the package is actually "inferred" from the specified name -- even using a bit of magic...)

It might be cleaner to force the users to name their switches (like is the case for repos, `opam repo add NAME URL`). Name is important since you'll use that to refer to your switch forever.

Who is for dropping `opam switch 4.03.0` in favor of `opam switch create work ocaml-base-compiler.4.03.0` (or `opam switch create work --version 4.03.0` to match more closely) ?

As you don't create switches that often, it would probably also be nicer to have `opam switch SW` fail if `SW` doesn't exist already, and force `opam switch create` to install a new switch.

**Comment by Drup** [comment]
I'm totally on board with showing only installed switch by defaults and having a more verbose option.

I have no opinion, almost all the switch I create are aliases, but apparently I have an unusual workflow. Although forcing people to name their switches may encourage them towards a better workflow. 

`opam switch create work ocaml-base-compiler.4.03.0` is a bit verbose though. And I don't feel like exposing people to the weird scheme that we use to encode ocaml version/variants, so I think we still should have the "short name" that switches currently have. 

How is the switch name determined currently ? You mention some magic.

**Comment by AltGr** [comment]
The specified name is looked up, in this order:

1. among full names (`name.version`) of packages that have the `compiler` flag set
2. among names of packages with the `compiler` flag set
3. among _versions_ of the same set of packages. In case of multiple matches, print an error showing the choice.

That last part is a bit magic, but it avoids hardcoding any package name into opam. And with the new layout, it will make `opam switch 4.02.3` install `ocaml-base-compiler` if only that is available, or ask to choose between that and `ocaml-system` if it's at the right version.

One artifact from the latest rewrite is that the virtual `ocaml` package is not even part of the "base" packages anymore (could make it so for consistency, but not sure about the gain). Anyway, that should be a `provides:`; but that's another problem.

**Comment by Drup** [comment]
Would it be possible to add a field "compiler-name" that is only valid for packages with a flag "compiler" ? The field would contain a name of the form "ocaml.4.03.0". This would probably help reduce the magic and be more compatible with non-ocaml repositories. 

I think it's acceptable to say "opam switch install ocaml.4.03.0" instead of "opam switch install 4.03.0".

**Comment by AltGr** [comment]
Most of the requests have been discussed, and the interface much improved as a result: thanks!
Thus, I'm closing, but feel free to ask again if you still find stuff missing or inconvenient in the new version.

**Comment by Drup** [comment]
One of the wishes was to be able to do something like `opam list --all-versions ocaml-variants~=4.03`. Is that possible now ?

**Comment by AltGr** [comment]
Only as `opam list --all-versions ocaml-variants --field version:4.03`. I'll add `--version` as a shortcut to `--field version` and/or split the supplied name at the dot.
Related, there is now `opam switch list-available`, but it doesn't yet allow a pattern, which it should.

**Comment by AltGr** [comment]
You can now use globs against name and version. So the above could be written
```
opam list --all-versions 'ocaml-variants.4.03*'
```

Also, `--all-versions` is made implicit when querying a single package name without further filters, so you could even skip it in this case.
Hope this finally fits your use-cases well!

**Comment by Drup** [comment]
Looks good, thanks!
