### ISSUE TITLE
Opam should try next highest level of constraint

### ISSUE THREAD

**Issue by fxfactorial** [ocaml/opam#2620]
say a package cannot install because of version constraints. Then opam should prove a prompt that asks to let it install the next set of highest version numbers that won't conflict.

**Comment by AltGr** [comment]
With a solver installed and a recent enough version, the default criteria should make it so that the latest possible versions are installed if the latest is unavailable, in the absence of version constraints.

This is done by adding a `version-lag` information to every package, which is the number of newer available versions. Then e.g. the criterion `-sum(request,version-lag)` minimises the sum of that value for packages mentionned in the request.

Is this different from what you would expect ? You can check your active criteria with `opam config report`.
