### ISSUE TITLE
add a `compiler-bundle:` field

### ISSUE THREAD

**Issue by AltGr** [ocaml/opam#2649]
This arose from a discussion with @dra27 who implemented something similar for handling the installation of flexlink/flexdll on Windows.

The idea is that when you install a compiler, it may "come with" other packages that get installed along with it: `opam switch create foo` would create the switch, and then attempt to install `foo` and all its `compiler-bundle` packages (including, of course, all dependencies); the bundled packages don't force any direction of dependency, and are afterwards marked as part of the compiler¹.
It may seem a bit ad-hoc, but actually solves a couple issues:
- Legacy compiler definitions came with packages `base-xxx` that mostly had this semantics. I replaced them with `depends:`, which works only because they are actually dummy packages, and is not very pleasant.
- In the current state, the actual compiler is _e.g._ `ocaml-base-compiler`, and `ocaml` a virtual package. What is weird is that it won't get installed together with the compiler (only when other packages "pull" it), and is not actually part of the "base packages"; putting it in `compiler-bundle` might help reduce the confusion.

A more generic field name could be `recommends:`, which kind of fits with these semantics, but there will be no handling of that for normal packages for the moment.

¹ that may differ from @dra27's idea of the field; would it still be OK for your use ?

**Comment by dbuenzli** [comment]
> It may seem a bit ad-hoc

I don't think it only seems. Wouldn't that be solved naturally by the named constraints sets I have been arguing for initializing switches ?

**Comment by dbuenzli** [comment]
> Well, I guess, an ad-hoc file works as well as an ad-hoc field...

As I said repeatedly it's precisely not an ad-hoc file. It's a general concept --- a way to define and record the (possibly partial) state of a switch and refer to it via a name --- useful in many situations, this one included, and that *can* exist as a file but should precisely not be limited to it.

> Joke aside, I don't mean to discard the idea: I think we will need to go in that direction at some point, but current ideas involve too much machinery to my taste.

So you prefer to introduce various ad-hoc bits here and there an have broken clis that will have to be changed if you want to provide a good unified user experience for this concept. Sorry to say this but I don't think this way of proceeding will serve the project and its users well.

**Comment by AltGr** [comment]
I think the concept is great, and clearly having a more powerful and unified experience with what is now limited to "export files" is something we want. I still see this as a different layer that shouldn't be included in the opam repository, though. About the above proposal,

**Comment by dbuenzli** [comment]
> I still see this as a different layer that shouldn't be included in the opam repository, though.

I don't understand this reticence. You prefer to have to juggle with files in order to exchange constraint in a dev team ? You don't see the advantage to be able to distribute setups through the official ocaml OPAM repository ? You don't see the advantages of them being signed ? 

> About the above proposal, the data included in compiler-bundle: is really related to the properties of the concerned package, and how it is intended to be used, so lifting this information to an upper layer of package preselections doesn't seem to fit.

Well somehow I disagree. But maybe it's just that I disagree with the whole compiler as package design (but since I was never shown a proper design document on how these things work I'm left a bit guessing on how all this works). In any case if I go back what you said here: 

> opam switch create foo would create the switch, and then attempt to install foo and all its compiler-bundle packages (including, of course, all dependencies); the bundled packages don't force any direction of dependency, and are afterwards marked as part of the compiler¹.

and take what you describe up to the last sentence you have exactly what a constraint set should do (i.e. `foo` should be the name of a constraint set, not a compiler package). The last think "being marked as part of the compiler" seems a dodgy thing to me but that may be related with the compiler as package notion I possibly disagree with.

**Comment by dra27** [comment]
Marking the packages installed via `compiler-bundle` as part of the compiler is not how I'd done it, but I have no issue with that change - it's probably more consistent to have it that both flexdll and flexlink must be explicitly upgraded (through being part of the compiler).

**Comment by AltGr** [comment]
> > I still see this as a different layer that shouldn't be included in the opam repository, though.
> I don't understand this reticence.

Well, it's natural for a package to include different kinds of references to other packages, and on the other hand, a constraint set doesn't have to be bound to a single repository.
Besides, if constraint sets can be conveniently encoded as packages (packages being, basically, some constraints + an optional source URL + some scripts), I don't see the need to add another mechanism + layer + namespace and all the implied complexity.

Granted, the two could benefit from having a different level of expressivity, and package's {depends+depopts+conflicts} differ from "import file"'s {set of compiler+base+installed packages}, and I admit there is room for improvement regarding this.

Another more indirect reason could be that I am convinced I did the right thing by removing `.comp` files, which led to much simplification and the removal of many slightly different duplicates in the code, since most of the functionality was shared between the two -- with handling of `.comp` generally sub-par. It's also one less file format to understand for users which is, in my opinion, a win.

> The last think "being marked as part of the compiler" seems a dodgy thing to me but that may be related with the compiler as package notion I possibly disagree with.

By "part of the compiler", I meant "part of the base packages", i.e. the ones that won't upgrade automatically. It felt more consistent that way, but this behaviour is not actually required.

**Comment by dbuenzli** [comment]
> Besides, if constraint sets can be conveniently encoded as packages

At the moment, they can't, pin state being the first thing you'll hit. But then, they should not. It doesn't make any sense if you think about them in terms of snapshots and moving constraints between switches. Neither would it make sense for an `.opamswitchinit` file. 

They key difference is that constraint sets do not live in the switch and maintain their restrictions after having been applied. They are basically a way to automate a set of `opam repo`, `opam pin` and `opam install` commands in order to bring or restore a switch to a known (sub)state.

Having this will give you a good story for the end-user to manage the multiplication of switches that we will see once opam moves to more localized switches (especially since these switches can't in general e.g. share a common `merlin` install). 

Names of the constraint sets will also give you a good story to initialize switches now that compilers are packages. This without having to introduce ad-hocness in the system or have the terrible `opam local` cli that was proposed at some point.

> Another more indirect reason could be that I am convinced I did the right thing by removing .comp files, which led to much simplification and the removal of many slightly different duplicates in the code,

I'd say this is unrelated to the discussion. `.comp` files were very similar to package files. Constraints sets are not (see above). 

> It's also one less file format to understand for users which is, in my opinion, a win.

The loss being a system totally inconvenient to use. There's absolutely no win: you are not solving the problems users will face with the multiplication of switches. 

Besides there's no reason to use another syntax than OPAM files for these and if you provide a good cli (e.g. `snapshot`, `union`, `export`, etc.)  end-user shouldn't have to fiddle too much with those directly.

**Comment by AltGr** [comment]
Thinking more about this (in the context of https://github.com/ocaml/opam-repository/issues/10238), I have another possible definition that would be mostly equivalent to this, and maybe more pleasant. We could define dependencies that are active at the __solver__ level, but _not_ at the __opam__ level. Since the solver doesn't mind cycles, that would mean that whenever `compiler` is installed, `flexlink` needs to be installed too (possibly with version constraints), but `flexlink` can still depend on `compiler`, and get installed after it.

What do you think ? This could even be defined as a dependency flag (if we can find a good name for it):

    depends: [ "flexlink" { >= "1.0" & reverse } ]

One (minor ?) side-effect is that we lose the invariant that an interrupted build results in a consistent installed universe (we could build `compiler`, then fail to build `flexlink`). But `opam` will try to recover on the next action anyway.

**Comment by AltGr** [comment]
Actually these would even have been already possible without additions. Indeed, `build` dependencies are active for the resolution of opam actions and not for the solver — and since it was turned into a variable, I had overlooked that you can now write `depends: [ "foo" { !build }  ]` (`!` being "not"), hence a dependency that is active for the solver but not for action resolution. This could confuse functions that are supposed to gather all dependencies, though, so I'll check that.
