### ISSUE TITLE
OpamStd dependency-free opam file format parser

### ISSUE THREAD

**Issue by avsm** [ocaml/opam#2677]
It would be useful for ecosystem bootstrapping to have an OPAM file format codec that is independent of OPAM itself.

See ocaml/opam-repository#7446 for discussion on the topic. @AltGr said:

> opam-format uses opam-core.OpamStd a lot, and includes high-level i/o functions that do e.g. proper locking of the files to prevent concurrent writes, and that relies on opam-core.OpamSystem too. Also, the types returned make use of the base types in turn using the modules of opam-core and their json serialisation functions.
> In short, OpamParallel and the ocamlgraph dependency could be lifted, but otherwise, a large refactoring would be needed; not sure it is worth it, and at this stage, that wouldn't be before 3.0 anyway.

**Comment by AltGr** [comment]
I guess you mean opam core rather than OpamStd ? OpamStd is just a small extension to stdlib, and removing the dep would just mean duplicating the code (it has stuff like the missing string functions from the stdlib, stringmaps...)

as I said, the dependencies towards OpamParallel could be removed, but otherwise, I don't see how a parser could return the expected high-level structures (like formulas, filters...) without having the modules containing their constructors.

In practice, the opam-format library already has pretty minimal dependencies:
- opam-core: arguably, this library is already independent of opam
- re: this is used here and there, and makes sense as a dependency
- ocamlgraph: used by OpamParallel; that could be lifted with a little work, not really used here (it's used for action resolution in opam-client, and in opam-state just for parallel downloads (that could be lifted as well) ; opam-solver works a lot on the action graphs, but without needing the parallel engine, too)
- jsonm: only the base json type (which is a polymorphic variant) is used below opam-client, so that could be lifted as well

So a little refactoring (putting OpamParallel in its own library ?) could get us an `opam-format` with only dependencies on `opam-core` and `re` (and `unix`); but removing the dependency on opam-core makes no sense to me.

Also, I am not quite happy with the current `OpamFilename` interface (from opam-core), but this used throughout (and based on `OpamProcess` + `OpamSystem`) ; I don't see how this would be a problem though.

If you have doubts on what is what, the doc is here:
https://opam.ocaml.org/doc/2.0/api/index.html

**Comment by dbuenzli** [comment]
> could get us an opam-format with only dependencies on opam-core and re

What does `opam-core` depend on ? and why do you need regular expressions ?

**Comment by AltGr** [comment]
> What does opam-core depend on ?
ocamlgraph, jsom, re, unix, as mentionned
> and why do you need regular expressions ?
is this the Spanish Inquisition ? I need them to process strings, in particular in the `OpamUrl` module.

**Comment by dbuenzli** [comment]
> is this the Spanish Inquisition ?

Ok I'm out of this discussion. Good luck.

**Comment by AltGr** [comment]
To explain my reaction above: I am prompted with a sensible request, and study it seriously, explaining how 90% of it could be done reasonably with some work; and without making a single statement on that, you agressively point to the remaining 10%, without even justifying your point.

So, yes, after some more discussion, I get that these 10% can matter and make the difference. The 90% still do as well, though.

On regexes, well, I guess you never actually _need_ them. Given how the stdlib lacks in the string processing area, though, a lot of less readable low-level index-processing code would be needed to replace them (see the OpamUrl module).

**Comment by AltGr** [comment]
`opam-file-dormat` is there!
