### ISSUE TITLE
`opam pin remove` vs `opam remove && opam pin remove`

### ISSUE THREAD

**Issue by dannywillems** [ocaml/opam#2678]
(OPAM version : 1.2.2 and the example OPAM repository is [this one](https://github.com/besport/ocaml-jwt))

How does the command `opam pin remove` work?
Does it unpin the repository and remove it (by calling `opam remove`) if the package is installed? Or it's something completely different?

When I use:
```
opam pin add jwt https://github.com/besport/ocaml-jwt.git
opam remove jwt
opam pin remove jwt
```
I have no problem but with:
```
opam pin add jwt https://github.com/besport/ocaml-jwt.git
opam pin remove jwt
```
I have the following error:
```
[WARNING] failure in package uninstall script, some files may remain:
          # opam-version 1.2.2
          # os           linux
          # command      make remove
          # path         /home/dannywillems/.opam/os-perso-4.03.0/build/jwt.0.1
          # compiler     4.03.0
          # exit-code    2
          # env-file     /home/dannywillems/.opam/os-perso-4.03.0/build/jwt.0.1/jwt-21618-42bb52.env
          # stdout-file  /home/dannywillems/.opam/os-perso-4.03.0/build/jwt.0.1/jwt-21618-42bb52.out
          # stderr-file  /home/dannywillems/.opam/os-perso-4.03.0/build/jwt.0.1/jwt-21618-42bb52.err
          ### stderr ###
          # make: *** No rule to make target 'remove'.  Stop.

[WARNING] Directory /home/dannywillems/.opam/os-perso-4.03.0/lib/jwt is not empty, not removing
```

The remove target is `ocamlfind remove jwt`.

Is there something wrong with the opam file or the makefile?

**Comment by AltGr** [comment]
What happens is that in the second case, opam will first unpin the package _then_ try to remove it. However, at that point, it does not have the package definition (opam file) corresponding to the pin, and will try to apply the removal instructions from the corresponding package definition dound in the repository.

This is already fixed in opam 2.0 (preview release) though, which always keeps a copy of the definition a package was installed it, and uses that for removal.

Thanks for reporting!
