### ISSUE TITLE
Constrain package names to a reasonable set

### ISSUE THREAD

**Issue by dbuenzli** [ocaml/opam#2683]
I think package names are not constrained enough at the moment. For various reasons (one being that these names do show up in filesystems) I think it would be wiser to constrain them to lowercase US-ASCII identifiers. This means something like `[a-z][a-z_\-]*`

**Comment by AltGr** [comment]
This sounds sensible, although we may want to be a little less restrictive (e.g. I think we need numbers); for the record, at the moment, the following is [allowed](https://github.com/ocaml/opam/blob/831760cf09887877492ab0b321f337c7194bbb8d/src/format/opamPackage.ml#L51):
```
["#$%&'()*+´0-9:;?@A-Z[]^_`a-z{|}~-]+
```
Yes, this is absurd, esp. since we need to be able to name files after them. All packages currently in the official repository seem to respect [0-9a-zA-Z_-]+. Unofficial repositories might use more ?

Some symbols like `#$%&+` could be allowed for special uses, but even if that is a possibility, we can reserve them for later.

**Comment by dbuenzli** [comment]
> e.g. I think we need numbers

Yes of course. 

> [0-9a-zA-Z_-]+

I'd rather avoid uppercase letters. Some file systems are case insensitive.

**Comment by AltGr** [comment]
> I'd rather avoid uppercase letters. Some file systems are case insensitive.

Package names are compared case-insensitively, so that should not be a problem. Forbidding capital letters, on the other hand, would force a massive rename of packages and break existing installation on case-sensitive fs.

I finally settled for `[a-zA-Z0-9_+-]+`, which all current packages on opam-repository match.

**Comment by dbuenzli** [comment]
Given https://github.com/ocaml/opam-repository/pull/7568 shouldn't you drop `+` from the set aswell ?

**Comment by AltGr** [comment]
Clearly. I noticed the problem afterwards. #2702 may not get merged, but it has some useful bits -- including this change -- that should be backported anyway. It changes package names to `{ <identchar> }* <letter> { <identchar> }*`, where `<identchar>` is `<letter> | <digit> | "_" | "-"`. I.e. the above, minus `+`, and with at least one letter.

I should also probably extend the lowercase matching so that `-` matches `_`: who wants two packages with the same name up to dash/underscore ?

**Comment by dbuenzli** [comment]
Are you still positive that you want to keep uppercase letters ? 

In `odig` I'm using the file system as the package index and it makes things a bit more involved than if they weren't here (e.g. to see if a package `p` exists I need to readdir `$LIBDIR` convert the elements to lowercase and then check for existence of `p` in the list, rather than just check for  `$LIBDIR/p`. Also in my datastructures I then need to keep track both of the normalized and unormalized name for disk accesses.

I have the impression that this decision is in general going to make the systems more prone to odd bugs than needed.

**Comment by dbuenzli** [comment]
Just note the issue here is not *keep uppercase letter* but keep uppercase letters *and* be case insentitive.

**Comment by AltGr** [comment]
Hmm, indeed, my explanation above was kind of wrong, in fact opam _is_ case sensitive, but matches packages listed on the command-line case-insensitively, and doesn't allow different packages with the same name up to case. This way, just checking for the file name is the right way to go, and shouldn't be a problem across case sensitive or insensitive systems.

This could lead to an issue in case the FS mangles the capitalisation in addition to being case-insensitive (then reading the package from the repository could lead to a different name) -- but nobody is using such FSs anymore right ?

**Comment by dbuenzli** [comment]
Ok, I think I'm fine with the idea of having package names being case sensitive but disallow two different package names to only differ in their casing. 

Though this is OCaml specific and unclear whether desirable or not, there's one final thing you might want to consider: disallow packages that start with a number. That way you would match OCaml's convention for compilation units --- this may be useful (or not) in the future for libdir and namespacing.

**Comment by dbuenzli** [comment]
> disallow packages that start with a number.

Well you'd also need to disallow `-` so maybe forget about this point.
