### ISSUE TITLE
opam silently drops all dependencies when an undefined variable is encountered

### ISSUE THREAD

**Issue by yallop** [ocaml/opam#2703]
e.g. if the `opam` file has

```
depends: [ "foo" bar]
```

when `bar` is undefined then the whole dependency list is silently discarded

**Comment by AltGr** [comment]
Not sure what exactly is the issue, there may actually be several:
- Variables in the dependency list are not allowed, you should write either `depends: ["foo" "bar"]` for two package names or `depends: [ "foo" {bar} ]` for toggling the dependency on package `foo` depending on variable `bar`
- In the latter case, having `bar` undefined ignores the dependency on `foo`, which is the expected behaviour but might be error-prone... I am open to suggestions in that case (maybe undefined vars should retain the dependency instead ?). It should certainly not ignore the whole list
- in case of errors in a field (like would be the case with the `depends:` field given above), unless `--verbose` or `--strict` were used, the field is generally silently ignored; the idea is to avoid bugging users with thousands of warnings that don't concern them just when reading the package repository; but we should certainly improve on this. One possibility would be to show such warnings only when the file is going to be used for actions (e.g. the package installed) ; another, to do so when the package is pinned, as that should be the case on the developper's side.

**Comment by yallop** [comment]
The problem is that the error is never reported, and OPAM continues silently, right up to the point where installing the package fails because the dependencies have been deleted.  Since variables are not allowed in the dependency list the user has clearly made a mistake and should be notified.

If a fatal error were reported on `opam update` or `opam install` then the user could fix the problem.

> One possibility would be to show such warnings only when the file is going to be used for actions (e.g. the package installed) ; another, to do so when the package is pinned, as that should be the case on the developper's side.

I think either of these is reasonable, but in this case the diagnostic should probably be a fatal error, not just a warning.

**Comment by hannesm** [comment]
IMHO this is evidence that variables should be explicit (`$foo` or `%foo%`), then e.g. package names&versions in the constraints would not need to be escaped (which is a breaking change, but should be considered for 2.0)

**Comment by AltGr** [comment]
Error reporting has been fixed. Regarding hannes's suggestion, I have POC PRs waiting for feedback
