### ISSUE TITLE
Should /usr/local should be included in the compiler CFLAGS on osx?

### ISSUE THREAD

**Issue by UnixJunkie** [ocaml/opam#2705]
cf. https://github.com/ocaml/opam-repository/issues/4238#issuecomment-251846242

**Comment by dra27** [comment]
This issue came up pre opam-2.0. 4 years on, this can be batted back to opam-repository and fixed via `set-env` in a base package. This may well happen naturally in opam 2.2 as we anticipate a restructuring of the packages _before_ `ocaml-base-compiler` to include a package holding the C compiler configuration (for MSVC, etc.) and a macOS-specific patch to `CFLAGS` would sensibly go there.
