### ISSUE TITLE
building opam from source on Alpine Linux

### ISSUE THREAD

**Issue by sevenEng** [ocaml/opam#2738]
As there is no opam from Alpine's package manager `apk`, I tried to build it from source. And here are some problems that encountered with `make lib-ext`.

* for branch 1.2.2, [the source of extlib](https://github.com/ocaml/opam/blob/2.0-alpha4/src_ext/Makefile#L84) will result in an invalid MD5 checksum. If modify the expected checksum, the make will fail at [L39](https://github.com/ocaml/opam/blob/1.2.2/src_ext/Makefile#L39) with `no rule to make extlib/enum.cmo, requierd by extlib/enum.cmi`

* if using the Makefile from branch master or 2.0-alpha4, the build will result in a seg fault at a [`ocamlopt` command](https://github.com/ocaml/opam/blob/2.0-alpha4/src_ext/Makefile#L84)

**Comment by avsm** [comment]
Which CPU architecture?

**Comment by avsm** [comment]
There are Dockerfiles available for most of the combinations on Alpine; e.g. see https://hub.docker.com/r/ocaml/opam/builds/bjotlbtoyk6ock736fmehpy/

https://github.com/ocaml/opam-dockerfiles/blob/alpine-3.4_ocaml-4.03.0/Dockerfile

I need to build ARM APKs and submit them upstream..

**Comment by sevenEng** [comment]
Oh sorry to include this, it's armv7 on a cubietruck

**Comment by AltGr** [comment]
Thanks for reporting. For building 1.2, please try the 1.2 branch (58ef3b8), that had some fixes backported since 1.2.2 (including remote source hashes that were changed in the meantime).

There is also a pre-built [arm `opam` binary](https://github.com/ocaml/opam/releases/tag/1.2.2) for 1.2.2 that should work on any distribution. You could also use that to install the dependencies and bootstrap opam, if you want to compile it yourself.

> if using the Makefile from branch master or 2.0-alpha4, the build will result in a seg fault at a ocamlopt command

ouch; no idea what might cause this. You don't have any remaining artefacts from a previous compilation around ? What OCaml version ?

**Comment by avsm** [comment]
FYI there are now OPAM packages in Alpine Edge: 

- http://fr.alpinelinux.org/alpine/edge/testing/x86_64/
- http://fr.alpinelinux.org/alpine/edge/testing/aarch64/

There are some test failures for armhf that I'm investigating; any help appreciated reproducing the build failures (see alpinelinux/aports#26)
