### ISSUE TITLE
non-empty directory warning seems to trigger too often

### ISSUE THREAD

**Issue by avsm** [ocaml/opam#2774]
```
-> removed   ocamlfind.1.6.2
[NOTE] While removing ocamlfind.1.6.2: not removing non-empty directories:
         - man/man3 /home/opam/.opam/ocaml-base-compiler.4.03.0/man
```

In this case, it's not ocamlfind's fault -- the ocaml-base compiler has installed these man files I think?

**Comment by AltGr** [comment]
Yes, that happens whenever the directory was created during the installation of `ocamlfind` ; even if some other packages are using it. We could of course check all install files to detect that another package still has files in that directory, but that would be somewhat costly.

Maybe we should just remove the warning, since it's opam job to remove files anyway, unless they have been created from outside of opam of course. A better solution would be to have a different command that would gather the known state of all packages and analyse your switch prefix compared to that, reporting untracked files, missing files, changed files, files changed by multiple packages, and possibly offering a cleanup command.

We already have `opam search --owns-file FILE`, and there shouldn't be much technical difficulties

**Comment by AltGr** [comment]
(note: it's already only shown with `--verbose`)

**Comment by AltGr** [comment]
(actually, it wasn't due to a bug: fixed)
