### ISSUE TITLE
archive-mirrors: look in `cache/` directory in opam-repository?

### ISSUE THREAD

**Issue by avsm** [ocaml/opam#2794]
I ran `opam admin make` in OPAM2 and it created a `/home/opam/opam-repository/cache` directory as expected.  It is only actually used when `archive-mirrors: [ "file:///home/opam/opam-repository/cache" ]` is manually set, whereas in OPAM1 the presence of an `archive/` directory was sufficient.  Should there be a default entry for the `cache/` directory in OPAM2 as well?

**Comment by AltGr** [comment]
This is by design, because it seems a good idea to actually place the cache in a different tree or server. The previous setting caused opam to make requests to `archives/` all the time, not knowing in advance if it would find cached archives or not (except when it could know in advance, for the http backend, by using the `urls.txt` file, but that no longer exists).

I think the issue is actually with `opam-admin`, that lets you generate the cache at that place without configuring it, or even checking and advising you to do it.

**Comment by avsm** [comment]
Agreed. Reducing the amount of redundant checking of filesystem areas is a useful speedup.

Once we have a CLI mechanism to configure `~/.opam/config` this will get easier anyway.

**Comment by AltGr** [comment]
New `opam admin cache` takes care of updating the `repo` file automatically (unless you specify `--no-repo-upgrade`)
