### ISSUE TITLE
`ocamlfind remove` shouldn't be called in parallel

### ISSUE THREAD

**Issue by ygrek** [ocaml/opam#2815]
See https://gitlab.camlcity.org/gerd/lib-findlib/issues/9
Arguably, this should be fixed on ocamlfind side, but with the current state of things I believe opam should avoid calling `ocamlfind remove` in parallel.

**Comment by AltGr** [comment]
opam 2.0 makes all install/remove operations mutually exclusive (which is needed anyway for the way we snapshot the prefix and diff to track what is installed). This should avoid such issues.

Indeed I had similar issues with concurrent calls to ocamlfind, but couldn't reproduce them enough to easily track it down. Thanks!

**Comment by ygrek** [comment]
Is there any workaround for opam 1.2.2 short of setting `jobs: 1` in config?
What is the ETA for opam 2?

**Comment by samoht** [comment]
@AltGr is this a regression somewhere? I remember that I tried to make the install/uninstall step sequential in the initial design, because of that issue with ocamlfind. Could it be that the `light-uninstall` packages got "optimised" the wrong way?

**Comment by AltGr** [comment]
You mean regression from 1.1 to 1.2 ? No idea! But since build and install were the same step before 1.2.2, I doubt it. What probably happened is that earlier versions of opam just wiped the package's `lib/<package>` directories on uninstall, but I was told that was too brutal ;)
 
So, let's see about a workaround... apart from wrapping `ocamlfind remove` calls in mutexes, or having instructions removing the stuff by hand ahead of `ocamlfind remove`, I don't see one. A new version of ocamlfind that is concurrency-safe would really be best.
