### ISSUE TITLE
.install file in a repository is used for pins

### ISSUE THREAD

**Issue by yomimono** [ocaml/opam#2818]
`lwt.2.7.0` in opam-repository includes a `files/lwt.install` referring to `lwt.opam`.  On a switch which knows about `lwt.2.7.0`, attempting to pin an earlier version of `lwt` fails:

```
$ opam pin add lwt 2.6.0
[NOTE] lwt is currently git-pinned to https://github.com/mirage/lwt.git#tracing.
Proceed ? [Y/n] y
lwt is now version-pinned to 2.6.0

[lwt] https://github.com/ocsigen/lwt/archive/2.6.0.tar.gz downloaded

lwt needs to be installed.
The following actions will be performed:
  ∗  install lwt 2.6.0*
Do you want to continue ? [Y/n] y

=-=- Gathering sources =-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=
[lwt.2.6.0] https://github.com/ocsigen/lwt/archive/2.6.0.tar.gz downloaded

=-=- Processing actions -=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=
[ERROR] Installation of lwt.2.6.0 failed
Processing  1/1: [lwt: ocamlfind remove]
#=== ERROR while installing lwt.2.6.0 =========================================#
Some files in ~/.opam/fresh-v1-rename/install/lwt.install couldn't be installed:
  - /home/user/.opam/fresh-v1-rename/build/lwt.2.6.0/lwt.opam to /home/user/.opam/fresh-v1-rename/lib/lwt



=-=- Error report -=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=
The following actions failed
  ∗  install lwt 2.6.0
No changes have been performed
[NOTE] Pinning command successful, but your installed packages may be out of sync.
fresh-v1-rename🐫  (master) mirageos:~/lwt.dev$ 
```

If I replace the `default` repository with one where the `lwt.install` in `packages/lwt/lwt.2.7.0/files` has been removed, I can pin and install lwt 2.6.0 successfully.

**Comment by talex5** [comment]
That's pretty strange. I wonder how opam decides which version of lwt in the repository to look at when pinning something.

**Comment by AltGr** [comment]
What opam version please ?

**Comment by yomimono** [comment]
Locally,

```
$ opam --version
1.2.2
```

We noticed this initially because we pin a fork of `lwt` for the MirageOS integration tests: https://travis-ci.org/mirage/mirage-skeleton/jobs/190749804#L788 , which uses the avsm/ocaml42+opam12 ppa: https://travis-ci.org/mirage/mirage-skeleton/jobs/190749804#L215

**Comment by AltGr** [comment]
opam 1.2.2 considered the metadata in a project source as an "overlay", put on top of the repository metadata, if any. If I remember correctly, it would take the highest version availlable that was below the expected version of the pinning.

This means it was taking the full metadata dir from the repo, then overwriting the opam file with the one from the pinned-to source, while keeping the `descr` and `files/` intact. You could avoid this behaviour by putting a an `opam/` _directory_ in your package source, that would in this case override the whole metadata (i.e. use `<project>/opam/opam` instead of `<project>/opam`).

In your case above, there seems to be another bug mingling in, as the older overlay is not cleaned properly upon re-pinning to a new target.

I can confirm opam 2 doesn't do this overlaying thing anymore, and that this behaviour is fixed :)

NOTE: The above behaviour was very shortly described in opam 1.2.2's `pin` man page:
> If a file `NAME.opam` with NAME matching the package name, or just `opam`, is found at the root of the pinned source, it will be used as the package's definition, overriding its previous definition if any. If a directory by one of these names is found, its contents will be used, also overriding other package metadata (`descr`, extra `files` subdirectory...)
