### ISSUE TITLE
opam init should append to PATH not prepend

### ISSUE THREAD

**Issue by willnix** [ocaml/opam#2828]
I found that after installing opam (and running opam init) my PATH has been modified to include `~/.opam/system/bin`. However, said directory was inserted at the beginning of the previous PATH. 
This is bad practice!
Executables in directories like /usr/bin should - with very few exceptions - precede binaries in my home folder. If I run `sudo openvpn` I want to know it is "/usr/bin/openvpn" I'm granting root privileges to - and not some script in my home folder.

**Comment by dbuenzli** [comment]
So how do we use the compilers installed in a switch instead of the ones that are installed system wide ?

**Comment by AltGr** [comment]
Lots of systems include an older version of `ocaml` intalled by the system. To be able to switch compilers, the version installed within opam needs to take precedence over that one — so appending would not work.

I didn't know this was considered bad practice, and had no complaints so far. I believe you can configure `sudo` itself to reset PATH before searching for commands, which would be the best way to avoid this security issue.

**Comment by willnix** [comment]
If it is just about `ocaml` how about an alias?

**Comment by corrupt** [comment]
A better solution than to prepend diretrories to PATH is to define a separate environment variable containting opam's directories and work with that. It's what go does. At that point it becomes optional for a user to include that variable to their own PATH and whether to pre- or append it. 

> To be able to switch compilers, the version installed within opam needs to take precedence over that one — so appending would not work.

I can't imagine a situation in which this is really a problem. Usually, when installing a separate package manager for language-specific packages, one would uninstall any packages possibly conflicting with it from the system repositories. In the unlikely event a user finds themselves working on a machine where they cannot modify the system's installed packages, I'd say they could be burdened with setting their PATH manually. This would additionally signify to them that they are taking a non-standard action. Modifying PATH for users who run an otherwise sanely configured system doesn't sound like a good idea.

**Comment by dbuenzli** [comment]
> If it is just about ocaml how about an alias?

It's neither a single binary nor a single package; there may be other packages that install switch specific versions of software that may already be installed by your os (e.g. `ocamlfind`). Also for the compiler package the set of binaries changes with compiler versions (e.g. `ocamlbuild` got out recently).

> A better solution than to prepend diretrories to PATH is to define a separate environment variable containting opam's directories and work with that. It's what go does. At that point it becomes optional for a user to include that variable to their own PATH and whether to pre- or append it.

Note that nothing prevents you from not using these facilities. You can prevent the line 

```
# OPAM configuration
. ~/.opam/opam-init/init.sh > /dev/null 2> /dev/null || true
```

of being written in your `.profile` and you can avoid calling `eval $(opam config env)` after having `opam switch`ed and define your own scheme for this (e.g. by calling `$(opam config var bin)` to update your PATH the way you want)

However while I do understand your concern I suspect that you will run in more problems than you'd like by not prepending and we would get significantly more problems with end-users and weird behaviours if that wasn't the default. So regarding security, @AltGr's suggestion about `sudo` seems more sensitive.

> Usually, when installing a separate package manager for language-specific packages, one would uninstall any packages possibly conflicting with it from the system repositories.

That seems rather unrealistic, besides `opam` actually allows you to work with a system wide install of the OCaml compilers (a so called `system` switch).

**Comment by AltGr** [comment]
> NOTE: that message got stuck but was written before I could read @dbuenzli's, sorry if it seems to repeat parts of it
.
> If it is just about ocaml how about an alias?

"just ocaml" means a bunch of executables, so that would be a lot of aliases:
```
% dpkg -L ocaml-nox |grep /bin/
/usr/bin/ocamldoc
/usr/bin/ocamldebug
/usr/bin/ocamldep
/usr/bin/ocamlmktop
/usr/bin/ocamlc
/usr/bin/ocamlyacc
/usr/bin/ocamlmklib
/usr/bin/ocamlobjinfo
/usr/bin/ocamlbuild.byte
/usr/bin/ocamlopt
/usr/bin/ocamloptp
/usr/bin/ocamlprof
/usr/bin/ocamlbuild.native
/usr/bin/ocamllex
/usr/bin/ocamldumpobj
/usr/bin/ocamlcp
/usr/bin/ocamlbuild
```
Not counting other packages that contain e.g. `ocamlrun`. Also, opam is not specific to OCaml, so handling that in a generic way would mean automatically spamming aliases for anything that installed to `<local-prefix>/bin` ?

> Usually, when installing a separate package manager for language-specific packages, one would uninstall any packages possibly conflicting with it from the system repositories.

One point of opam is that it can handle multiple "switches", containing different compilers, compiler versions, sets of packages, etc. These switches _can_ be based on a system-global installation of the compiler (to avoid recompiling), or on a custom, locally compiled compiler. So you don't actually want to wipe your system OCaml to use opam, in general.

Note also that opam is quite forward about the changes it does to your init files, and doesn't do them by default. It will work fine without changes to your environment, you will just have to remember to:
- use `opam config exec -- COMMAND` to run a command installed within opam, or any command with the environment for the current opam "switch" (e.g. `opam config exec -- make`)
- or use `eval $(opam config env)` to set your current shell to work with the opam environment

It is in practice quite convenient to be able to mask commands from e.g. `/usr/local/bin` with more recent, local versions when developping.

>  This is bad practice!

> Modifying PATH for users who run an otherwise sanely configured system doesn't sound like a good idea.

Could you elaborate ? Or do you have references on this ?
Forgive me if I seem unconvinced, but this hasn't been raised before (although we've had complaints about the original way `opam init` worked and usage of the shell's `eval`).

**Comment by ultimatespirit** [comment]
@AltGr Apologies to comment on an old issue, but landed here from similar concerns and wondering why the heck it was done this way. Reading this thread I can see and understand what opam's reasons are but would like to provide that elaboration you requested about why it would be bad practice to globally mask executables with a user writable directory.

For developers who constantly remain vigilant about their environment variables and path directory contents there really is no risk. However such people are rare to nonexistent. For everyone else the biggest problem, something that even well tuned sudo (which most systems do not have) can't prevent, is the fact that many user executed tasks can be compromised now by a malicious program in ways not immediately obvious. Here's a simple example in bash (the functionality of which could be sneaked in to any closed source program of course).

    if [ -w "${PATH%%:*}" ];then
        # we now know the top of path is writable
        # go ahead and install compromised executables of common names
        # any execp family function will now prefer those executables over trusted ones
        # (without other OS sandboxing at play)
    fi
(This problem isn't unique to just the top, but is most easily exploitable if it is the top of the PATH. Really it is a problem if any user writable directory is in front of a non-writable directory on the PATH).

Of course you could say the root problem there is allowing the execution of a malicious program in the first place, and you'd be right. However it's still true that to an extent having the top of PATH be write protected is a useful security measure to have (really a consequence of properly segregating tasks based on users)

It would be slightly more intrusive to the system but one thing that could be done about this would be to have opam create a new user for itself and make the .opam directory only writable to that user. That way trusted opam files and programs could still be installed without the use of sudo (as the opam executable would have access to opam user directories), but non-opam programs would not be able to write without sudo.

**Comment by AltGr** [comment]
Indeed, that does give some substance to the criticism above. I don't really see an easy way to fix it, though: having an `opam` user, which I considered for sandboxing builds, would be an option, but is not doable in practice on a multi-user setup — and makes opam's initial setup impossible without admin rights.

Really, the only place where I see this could be fixed is `sudo`. I remain open to ideas to mitigate this, though!

**Comment by rgrinberg** [comment]
One idea would be to have 2 tiers of PATH directories that opam uses:

* `~/.opam/<switch>/ocaml-bin`
* `~/.opam/<switch/package-bin`

The former would be prepended while the latter would be appended. Since the latter would only contain the OCaml executables, it would be much less of an annoyance than potentially any opam package shadowing some key binary.

**Comment by ultimatespirit** [comment]
@AltGr Perhaps I'm just missing something but why exactly would it not work on a multi-user system? Totally agree that it makes initial setup more cumbersome, could perhaps be done as a more secure option, similar to the current option to add it to the path.

@rgrinberg Doing so would only help the original problem if the `package-bin` directory were owned by root (well, not writable), which perhaps would be acceptable? I don't really know what sort of philosophy the opam group has with regards to when an action should require root or should not. If `package-bin` were made to be owned by root then it could be implemented along the lines of "This opam command will globally shadow a system installed executable, to do so we require elevated permissions" for anything that needs to be installed in `package-bin`. Of course figuring out what needs to be there or not is its own extra complexity (most system agnostic way would require parsing the local PATH variable to figure out the priority of any already installed executables)

**Comment by dra27** [comment]
@ultimatespirit - I think @rgrinberg meant *former* rather than *latter* (i.e. `ocaml-bin` would be the prepended directory containing only OCaml executables). I expect @AltGr is to referring to the problem of multiple users all using the *same* `opam` user for sandboxing/security, as in a lot of setups that would give opam cross-user access to `.opam` directories, I think.

@rgrinberg's suggestion of two `bin` directories doesn't work for the simple reason @dbuenzli mentioned earlier in the thread - commands like `ocamlbuild` are provided by the compiler in some versions of OCaml and by a package in others. So, for example, if you create a 4.01.0 switch on a system with a 4.02.3 system-installed compiler (several LTS systems still have this), you'd get ocamlbuild from 4.01.0 but if you create a 4.06.1 switch and install ocamlbuild then you'd get ocamlbuild from 4.02.3. Those bug reports will be really fun...

I wonder if the simplest thing here is just to have an option, either at `opam init` or even per-switch which specifies that the user wants the `PATH` change to be appended, rather than prepended? The ultra security-conscious may then use this. `opam init` could even verify the lack of a system compiler in this mode.

**Comment by ultimatespirit** [comment]
@dra27 re: @AltGr's comment, I see now that makes sense. In such a case it isn't necessarily impossible to still use a single opam user, the sticky bit executables would just have to be (usually non-trivially) modified to ensure that user `foo` executing `opam` is only attempting to modify `foo/.opam` and not `bar/.opam`. Of course doing that is understandably cumbersome and most likely unwanted.

Having an extra option for the ultra security-conscious does seem to be the simplest solution here by far. Though with how breaking it seems appending to PATH would be to the normal `opam` workflow, I wonder if at that point it would be better to simply include a note about it and then those that do care will setup their path environments appropriately / use the `opam config exec` method talked about before... If anything the `opam init` ultra security conscious mode could perhaps be to simply include something like `alias opamdo='opam config exec -- '`, since evidently appending to PATH would not actually help all that much regardless.

**Comment by dra27** [comment]
@ultimatespirit - moving security features into opam itself is not great - opam's trying to use sandboxing technologies, not write them. The test would also need to be more complex than that - `~/.opam` is simply the default opam root - it's not unheard of to have more than one. I agree it could be made to work, but I'd worry at that amount of security-critical code in opam.

Appending to `PATH` would be fine as long you rule out system-installed packages (indeed, there was a point where it was debated whether system switches should be dropped entirely). Obviously, anyone's entitled to whichever workflow they choose, but I'd find one where I had to prefix every interaction with an OCaml command with another command pretty tedious! However, I could cope with one where the only limitation was a lack of a system compiler (although my response on such a system would be `export PATH=~/local/bin:$PATH` in my bashrc, followed by a locally-compiled system compiler... :wink:)

**Comment by AltGr** [comment]
The latter would just amount to replacing the operator with `PlusEq` on [this line](https://github.com/ocaml/opam/blob/927252c167540a3789e9debf53cb2c2201688964/src/state/opamEnv.ml#L186) based on some condition, with a preliminary warning on the option that this can break if you have OCaml stuff otherwise in your PATH (typically, system ocaml packages, but not only).
