### ISSUE TITLE
Install instructions for Fedora, CentOS and RHEL don't exist

### ISSUE THREAD

**Issue by Richard-Degenne** [ocaml/opam#2953]
I noticed the [install instructions for Ferdora, CentOS and RHEL](http://opam.ocaml.org/doc/Install.html#FedoraCentOSandRHEL) redirects the reader [here](http://software.opensuse.org/download.html?project=home%3Aocaml&package=opam), which doesn't exist anymore.

**Comment by avsm** [comment]
OpenSUSE deprecated that repository, and I don't have time to build the RPMs manually any more.  Figuring out what the state of RPM builders these days and building OPAM RPMs would be very a very useful contribution. 

Also prodding Fedora to upstream this series https://bugzilla.redhat.com/show_bug.cgi?id=1093522 would also help reduce our maintenance burden

**Comment by Richard-Degenne** [comment]
Hmm, I see. I guess I could do without an officially-supported package, but I'd like to have to `opam-installer` binary, and AFAIK, pre-compiled binaries don't embed it.

I'm not sure I can be of any help regarding RPM packages, but I still can bump the linked issue to see what can be done about aspcud.

**Comment by plafer** [comment]
It took me quite a while to discover what this `opam-installer` tool `jbuilder` was complaining I didn't have was, and googling for `opam-installer` didn't give me anything. I finally realized that the 

    wget https://raw.github.com/ocaml/opam/master/shell/opam_installer.sh -O - | sh -s /usr/local/bin 

command I had used only installed the `opam` binary, and that if I wanted this `opam-installer` tool, I had to install `opam` from sources.

The install page doesn't mention the `opam-installer` tool anywhere. Maybe just a note somewhere on the website that in order to get accompanying tools (`opam-installer` and `opam-admin`), you need to install from sources unless your distribution has a package for it.

**Comment by TC01** [comment]
I thought I should comment on this ticket: opam is now in the official Fedora repositories, for Fedora 27 and up. Would it be possible to update the install instructions on [this page](https://opam.ocaml.org/doc/Install.html) to reflect this?

**Comment by maxeywen** [comment]
> I thought I should comment on this ticket: opam is now in the official Fedora repositories, for Fedora 27 and up. Would it be possible to update the install instructions on this page to reflect this?

still not updated I believe

**Comment by TC01** [comment]
Indeed. Is there someone I could ping about this?

**Comment by rjbou** [comment]
The doc has been updated, but with blank instruction for [`Fedora, Centos and RHEL`](opam.ocaml.org/doc/Install.html#Fedora-CentOS-and-RHEL).
Would you be happy to propose a PR with the good install instructions? It is in `doc/pages/Install.md`.

**Comment by TC01** [comment]
Sure, no problem!
