### ISSUE TITLE
Can't install lwt.

### ISSUE THREAD

**Issue by pe200012** [ocaml/opam#2977]
When I install lwt, opam gives me the error message below:

=== ERROR while compiling lwt.3.0.0 ==========================================#
 command      make build
 path         /home/pe200012/.opam/4.04.1/.opam-switch/build/lwt.3.0.0
 exit-code    2
 env-file     /home/pe200012/.opam/log/lwt-16841-c61e7b.env
 output-file  /home/pe200012/.opam/log/lwt-16841-c61e7b.out
--- output ---
 [...]
 ./setup.exe -build 
 W: Cannot find source file matching module 'Lwt_unix' in library lwt-unix.
 W: Use InterfacePatterns or ImplementationPatterns to define this file with feature "source_patterns".
 W: Cannot find source file matching module 'Lwt_unix' in library lwt-unix.
 W: Use InterfacePatterns or ImplementationPatterns to define this file with feature "source_patterns".
 ocamlfind ocamlopt -package unix -package ocamlbuild -linkpkg -package cppo_ocamlbuild myocamlbuild.ml /home/pe200012/.opam/4.04.1/lib/ocamlbuild/ocamlbuild.cmx -o myocamlbuild
 + ocamlfind ocamlopt -package unix -package ocamlbuild -linkpkg -package cppo_ocamlbuild myocamlbuild.ml /home/pe200012/.opam/4.04.1/lib/ocamlbuild/ocamlbuild.cmx -o myocamlbuild
 ocamlfind: Package `cppo_ocamlbuild' not found
 Command exited with code 2.
 E: Failure("Command ''/home/pe200012/.opam/4.04.1/bin/ocamlbuild' src/core/lwt.cma src/core/lwt.cmxa src/core/lwt.a src/core/lwt.cmxs src/logger/lwt-log.cma src/logger/lwt-log.cmxa src/logger/lwt-log.a src/logger/lwt-log.cmxs src/unix/liblwt-unix_stubs.a src/unix/dlllwt-unix_stubs.so src/unix/lwt-unix.cma src/unix/lwt-unix.cmxa src/unix/lwt-unix.a src/unix/lwt-unix.cmxs src/simple_top/lwt-sim[...]
 Makefile:33: recipe for target 'build' failed
 make: *** [build] Error 1

Why?

opam version = 2.0.0~beta3

**Comment by bram209** [comment]
`ocamlfind: Package `cppo_ocamlbuild' not found`

Can you try to install: `opam install cppo_ocamlbuild`
And after that try again?

**Comment by jlargentaye** [comment]
I had the same issue, and doing `opam install cppo_ocamlbuild` fixed the issue.

I assume this is an issue in the reported dependencies of Lwt (or some sub-dependency)? How can I help track this down and report it appropriately?

**Comment by dra27** [comment]
It's not clear to me how you managed to trigger this error on June 26th, as cppo_ocamlbuild didn't become a separate package until later. I expect this has gone away for most userse because lwt 3.1.0 uses jbuilder.

@pe200012 - out of curiosity, what version of cppo did you have installed at this point? Was it pinned?

The correct tracker for packaging problems is https://github.com/ocaml/opam-repository/issues. What needs to change for lwt.3.0.0 is either a build dependency on cppo_ocamlbuild or a version constraint holding cppo < 1.6.0. In the meantime, you can fix it either by manually adding cppo_ocamlbuild or by pinning cppo to version 1.5.0.

**Comment by Khady** [comment]
I had the same error this morning. I don't know why it installed on old version of lwt. It was on a new switch.

https://paste.isomorphis.me/MbC

**Comment by pe200012** [comment]
> opam install  cppo_ocamlbuild

It works! It solved the problem.

**Comment by pe200012** [comment]
@dra27 I just updated the cppo, and the problem solved.

**Comment by aantron** [comment]
This is caused by https://github.com/ocaml/opam-repository/pull/10047, where we mentioned that Lwt 3.0.0 and 2.7.0 need to be updated ([link](https://github.com/ocaml/opam-repository/pull/10047#issuecomment-321994913)), but I guess it wasn't followed up on. I'll submit a pull request to the opam repo.
