### ISSUE TITLE
opam2+beta3 More information on install errors

### ISSUE THREAD

**Issue by dbuenzli** [ocaml/opam#2982]
It seems the tool no longer reports when repos were last updated. I think it would be good if t`opam config report` could list all repos and if available the git hash at which they are. This will help to triage `opam-repository` reports. 

```
opam config report
# opam config report
# opam-version    2.0.0~beta3 (651f82c00070c05304c44b3ee21ab3002d2bb147) 
# self-upgrade    no
# os              linux
# external-solver aspcud $in $out $criteria
# criteria        -count(removed),-notuptodate(request),-sum(request,version-lag),-count(down),-notuptodate(changed),-count(changed),-notuptodate(solution),-sum(solution,version-lag)
# jobs            1
# repositories    1 (http), 1 (local)
# pinned          0
# current-switch  ocaml-base-compiler.4.03.0
```

**Comment by dbuenzli** [comment]
In fact I think it would be better if install error report would report all the relevant information. So I changed the title of the issue and I think this is currently missing: 

1. The opam version (regression from 1.2.2)
2. The os variable (regression from 1.2.2).
3. The set of compiler packages and their version should be added. (regression from 1.2.2)
4. The set of repositories added to the switch and their last update should be added.

Here's an example of what opam2+beta3 gives:

```
#=== ERROR while compiling imagemagick.0.34 ===================================#
# command      make
# path         /home/opam/.opam/ocaml-base-compiler.4.03.0/.opam-switch/build/imagemagick.0.34
# exit-code    2
# env-file     /home/opam/.opam/log/imagemagick-599-e7966f.env
# output-file  /home/opam/.opam/log/imagemagick-599-e7966f.out
### output ###
# [...]
# Use String.lowercase_ascii instead.
# File "magick.ml", line 953, characters 4-22:
# Warning 3: deprecated: String.set
# Use Bytes.set instead.
# File "magick.ml", line 1777, characters 8-24:
# Warning 3: deprecated: String.lowercase
# Use String.lowercase_ascii instead.
# gcc -fPIC -c -I"/home/opam/.opam/ocaml-base-compiler.4.03.0/lib/ocaml"  imagemagick_wrap.c
# imagemagick_wrap.c:60:32: fatal error: magick/ImageMagick.h: No such file or directory
# compilation terminated.
# Makefile:45: recipe for target 'imagemagick_wrap.o' failed
# make: *** [imagemagick_wrap.o] Error 1
```

**Comment by AltGr** [comment]
About `opam config report`: I attempted to make sure that the report doesn't leak any local information (your local pins or enterprise repositories could be sensitive, for example), which is why I limited to displaying their numbers (with a `*` indicating use of the default repository). But since this is manually posted anyway, not sure it was worth the trouble: people concerned can as easily remove the sensitive parts upon posting.
The last update date was temprarily removed because it's not as straight-forward to implement with the new update protocol (we used to be just reading the timestamp of a given file). Also, the githash is not available when updating through https (although it may be a good idea that `opam admin` publicizes it through the repo manifest)

About the error report: my reason to shorten the header was that it cluttered the backlog and made different errors harder to scan through and read. When locally debugging, there really is no value in repeating your opam version on every error, and that is the primary purpose of these messages. I missed the _other_ target, though, which is people copy-pasting the message on the `opam-repository` tracker without context. Not sure what the best compromise would be, adding a one-line summary of the context might be a good idea.

**Comment by dbuenzli** [comment]
> About opam config report: I attempted to make sure that the report doesn't leak any local information

I think this is a good idea but maybe should not be the default (or could be configured to be the default). Why not provide an `opam config report --anon` option ? Also in that vein then maybe the paths prefixs be elided.

> The last update date was temprarily removed because it's not as straight-forward to implement with the new update protocol (we used to be just reading the timestamp of a given file). Also, the githash is not available when updating through https (although it may be a good idea that opam admin publicizes it through the repo manifest)

Whenever we need to figure out what people are doing I'm not sure we care about the date at all. The git hash seems more precise and easier to check.

> About the error report: my reason to shorten the header was that it cluttered the backlog and made different errors harder to scan through and read. When locally debugging, there really is no value in repeating your opam version on every error, and that is the primary purpose of these messages.

I think here are a few arguments that could revert that position: 

1. The header makes the report longer but somehow your brain get used to ignore the extra bits. 
2. When we get to a more localized development it may no longer be that evident which set of compiler/repos you are using so I think it's good to have the info there in the failure, it may immediately make you realize you are for example acting on the wrong repo.

**Comment by AltGr** [comment]
I hope this is a good compromise: #2985 
Sample:
```
#=== ERROR while compiling ocp-indent.1.5.3 ===================================#
# command      /home/lg/local/bin/wrap-build.sh ./configure --prefix /home/lg/.opam/4.03.0
# path         /home/lg/.opam/4.03.0/.opam-switch/build/ocp-indent.1.5.3
# context      2.0.0~beta3 | x86_64 | linux | ocaml-base-compiler.4.03.0 | pinned(git+file:///home/lg/ocamlpro/ocp-indent#rewind#d3f250b6)
# exit-code    1
# env-file     /home/lg/.opam/log/ocp-indent-19715-6cc03f.env
# output-file  /home/lg/.opam/log/ocp-indent-19715-6cc03f.out
### output ###
# unshare: unshare failed: Opération non permise
```

**Comment by dbuenzli** [comment]
Looks good to me !

**Comment by dbuenzli** [comment]
But... I would maybe move things around to group all the things that are related to the command execution.
