### ISSUE TITLE
2.0.0: use my system compiler instead of trying to install another copy

### ISSUE THREAD

**Issue by infinity0** [ocaml/opam#2988]
It seems like 2.0.0 lost the concept of a "system" switch and instead now we have a "default" switch which will download the latest ocaml into it whenever I try to do anything.

Could the previous functionality be added back in? I don't really need a whole identical second copy of ocaml installed in my home directory.

**Comment by AltGr** [comment]
Fear not, the concept has not been lost, it's just handled a bit differently ☺.
Since compilers are now handled as packages, you have two different ones, `ocaml-base-compiler`, and `ocaml-system`, for handling the two cases (the first being recompiled locally — there is also `ocaml-variants`).

So you can manually choose the system with e.g. `opam switch create ocaml-system`. What happens otherwise, e.g. on `opam init`, is that the compiler to use is determined by a configurable formula (see `opam init --help for details) which defaults to:

         [ "ocaml-system" {>= "4.01.0"}
           "ocaml-base-compiler" ]

the first one from the list that is available will be chosen, so `ocaml-system` is still the default, unless it is very old.

**Comment by infinity0** [comment]
I get this:
~~~~
$ opam2 switch create ocaml-system
[ERROR] No compiler matching 'ocaml-system' found, use 'opam switch list-available' to see what is available
exit code 66
~~~~
I remember this working last night on 4.04.0, however now I have 4.05.0+rc1 installed as the system compiler. Is it failing to detect this?

**Comment by infinity0** [comment]
OK, reverting back to 4.04.0 as my system compiler allowed me to install an `ocaml-system` switch, which was the point I got to last night. The issue I was having, was that if I tried to install anything, I would get this:

~~~~
$ opam2 install base
The following actions will be performed:
  - install ocaml     4.04.0                            [required by base]
  - install conf-m4   1                                 [required by ocamlfind]
[..]
~~~~

which looks like it's trying to install another copy of the ocaml compiler. After actually running through this however, it looks like all it does is install a shell script into `$OPAMROOT/ocaml-system/bin/ocaml` that calls the system compiler, so I simply got the wrong impression on what was happening. (I'm fairly sure there is no virtual "ocaml" package in the 1.x series.) Anyway, thanks for the help and explanation!
