### ISSUE TITLE
Remove the internal solver (or make its use explicit)

### ISSUE THREAD

**Issue by dbuenzli** [ocaml/opam#2989]
It seems that the internal solver is no longer able to operate in a meaningful way of the current state of the `opam-repository`. 

I think that it should be either removed or it's use should be made explicit on the command line (without any hint that you can actually do so).

Letting end-users (and especially newcomers) believe they can get along with it only seem to result in intense frustration and a bad first impression of the eco-system.

**Comment by Drup** [comment]
Is there a deep reason why we can't just bundle packup ? (aspcud seems highly non-bundlable).

**Comment by dra27** [comment]
@Drup - Windows, though packup may compile easily (however, aspcud is packaged for Windows)

**Comment by Drup** [comment]
@dra27 It's worth a shot trying to compile it. Moving forward, I believe the only solution is to provide a package with the solver inside it. Aspcud is too much of a moving (broken) pieces.

**Comment by dra27** [comment]
I'm not a fan of the internal solver, but hasn't this issue sprung from opam 1? opam 2 uses a (much) newer version of dose, IIRC?

@Drup - indeed, although so far I've had no problems with aspcud's Windows packaging! Unusually, it seems to be more of a pain elsewhere...

**Comment by Drup** [comment]
@dra27 In the windows version, is aspcud bundled with opam? Maybe we should provide things like that for the unix version too ...

**Comment by dbuenzli** [comment]
> I'm not a fan of the internal solver, but hasn't this issue sprung from opam 1? opam 2 uses a (much) newer version of dose, IIRC?

I'm not sure I understand this @dra27. Do you suggest that v2's internal solver is suddently automagically usable due the use of a newer version of dose ? If that is the case, is there at least a way of making sure this assertion holds ?

**Comment by dra27** [comment]
It is my intention that binary builds of Windows opam would bundle aspcud, yes - but that's much more common (and reliable, I think) on Windows, than on Linux.

**Comment by dra27** [comment]
@dbuenzli - dose is the internal solver (plus a few heuristics), so it may well do. My dev machine has aspcud, so I haven't been playing with it since it jumped to dose3 v5 - I don't know if that upgrade was applied to the v1.2 branch

**Comment by Drup** [comment]
As far as I know, no, the internal solver is not up to the task, particularly because of compiler-as-packages.

**Comment by AltGr** [comment]
Haven't touched the "internal solver" since opam 1.2 : I don't think it's a reasonable approach anymore. What it does is enumerate installation possibilities, and check their consistency using `dose`, which is very fast at that. This explains that it could work well at the beginning, but got broken at some point, and we are too far past that point: I don't think improving the enumerating order heuristics would help much. In addition, that approach doesn't support any form of "selection criteria" (e.g. you can't ask for a partial upgrade).

Thus, I am in favour of dropping (or hiding) it; we could advertise use of remote-hosted solvers instead (the Inria is sadly terrible at hosting reliable services, which hindered the "solver farm" at http://cudf-solvers.irill.org/ . But we already have other options.) I would prefer [`mccs`](http://www.i3s.unice.fr/~cpjm/misc/mccs.html) over [`packup`](http://sat.inesc-id.pt/~mikolas/sw/packup/), as it has support for more advanced criteria¹ (also, I have seen `packup` hang forever on some problems).

It seems the broken aspcud shipped by Arch brought a lot of frustration, which is blamed on us 😞


¹ it supports the "version-lag" weighting, which avoids getting randomly old versions as soon as the _latest_ version can't be installed — as was the case in opam 1.1 IIRC. It's a one-shot ~6000loc C++ project that hasn't seen an update since 2011 and doesn't have an online repository, though. The different solutions are described in some details in [this paper](http://www.mancoosi.org/reports/d4.3.pdf)

**Comment by Drup** [comment]
@AltGr I think bundling/vendoring the solver (be it mccs or other) inside opam would solve a lot of packaging issues. We already vendor lot's of things, why not that one too ? I wouldn't prevent customizable solvers, just ensure that there is always a good one available and control how it is built.
