### ISSUE TITLE
v2: status of `base` packages

### ISSUE THREAD

**Issue by dbuenzli** [ocaml/opam#2996]
I think that the v2 migration could be an opportunity to review these `base` packages. Here are a few things: 

1. The `base-` prefix should be dropped. We should try to converge to a system where library, package and `ocamlfind` names do coincide.
2. Why are `unix`, `bigarray` and `threads` treated specially ? I think these should just be packages to be installed that depend on the `ocaml` package. 

Other packages already work the way I suggest `uchar`, `result`, `base-bytes` (well that `base-` prefix should die).

**Comment by dra27** [comment]
There's a certain amount of history with these - they're partly a workaround for `provides:`. `unix`, `bigarray` and `threads` get special treatment to allow for exotic compiler switches which do not build these libraries - you can't express that in a dependency (at least today).

`uchar` and `result` are slightly different because those packages actually have build systems which take compiler version into account and which build something if the compiler requires it (cf. the ocamlbuild package and ocamlbuild.base for the other way of doing it). `base-bytes` similarly can work as meta-package because bytes is always built - it's just a version constraint on the compiler.

So at the moment the `base-` packages are meta-packages a little like `conf-`

**Comment by dbuenzli** [comment]
> There's a certain amount of history with these - they're partly a workaround for provides:. unix, bigarray and threads get special treatment to allow for exotic compiler switches which do not build these libraries - you can't express that in a dependency (at least today).

Why not ? The `graphics` package does exactly that.

**Comment by dra27** [comment]
Sure, you can feature-probe instead (though I think that `graphics` package is a bad way of doing it - I would have noticed that when I finally get to doing the others...).

The weakness of that is that you get a poorer user experience - opam declares that you can install a whole load of packages and then that only fails when it can't install `unix`, for example. With the base packages, you get a solver error which, IMO, is rather better - the solver tells you that you can't do it, rather than waiting for an artificial package failure.

**Comment by dbuenzli** [comment]
> The weakness of that is that you get a poorer user experience - opam declares that you can install a whole load of packages and then that only fails when it can't install unix, for example. With the base packages, you get a solver error which, IMO, is rather better - the solver tells you that you can't do it, rather than waiting for an artificial package failure.

Well is that really worth the price of having ad-hoc support for this ? From an end-user experience, in both cases you end up with an error that tells you that a package can't be installed; no big-deal. Not to mention that almost all supported platform does support these libraries. So for now I'd rather have `graphics`-like packages with the correct names and `provides:` once this get implemented.

I'm not sure how this is implemented but this may also affect the (currently weak in my opinion) opam switch init story.

**Comment by Drup** [comment]
As a user, I much prefer a solver error than a build error. With a solver error, the dependency chain is clearly explained. Also, the technique of compiler-provided packages is rather useful (when opam 2 gets around, I plan to introduce something similar for metaocaml, so that a metaocaml-only library can be added to opam and properly exports its dependency).

The technique used internally is rather independent from the name, though, and on that, I agree with @dbuenzli.

**Comment by dbuenzli** [comment]
> Also, the technique of compiler-provided packages is rather useful

Is that clearly documented somewhere ?

**Comment by Drup** [comment]
I'm not sure. @AltGr did you documented the current scheme for the OCaml compilers in 2.0 somewhere ?

**Comment by dbuenzli** [comment]
I'm asking because it just feels that this is `features:` specialized on compiler packages, since `features:` would be more generally usefull why not directly go for this (solver state explosion could of course be a legitimate answer).

**Comment by AltGr** [comment]
The point that would make me in favour of this is that the way it's handled now is a poor workaround: `ocaml-base-compiler` actually declares a _dependency_ towards `base-unix`, etc.
It works since the packages are actually virtual, but they do get installed _before_ the OCaml compiler does. Also, the actually important part is that compilers that do not support them define a conflict towards the `base-*` packages, otherwise they could get installed separately.

On the upper side, the above allowed to remove any special treatment for `base` packages from opam itself. @dra27 also proposed a different solution, where the compiler could promote packages to be installed together with it (but as _reverse_ dependencies), at compiler installation time. The mechanism for switch-preselections of packages proposed by @dbuenzli could help here as well.

However, since the compilers already need to define what they provide, couldn't we simply let the virtual `base-*` packages get installed lazily, and define compilers that _do not_ support them using conflicts ? That would also greatly reduce the amount of added data since they're supported almost everywhere.

About `features:`/`provides:`, the latest idea, which I would like to implement, is to amend the unused `features:` field so that it has a format similar to e.g. `depends:` (package specs, and switch-global variables allowed). You would then be able to depend on them, but with an unambiguous namespacing, like `ocaml#unix`. Allowing to "provide" raw package names would open too many security issues.

The last resort, if dynamic polling + static solving is the only option, is to use the same mechanism that is used to determine what version of `ocaml-system` is locally available: a (lazy) global variable bound to the output of a system command, and defined in `~/.opam/config` (and its [default](https://github.com/ocaml/opam/blob/a16ff0354b0e8ef9f1dff9bdea05e489e8565b0e/src/client/opamInitDefaults.ml#L31-L32))

**Comment by dbuenzli** [comment]
@dra27, @drup I now fully agree that an error is not a good solution: errors should denote problem with the repository itself and should be reported to the repository maintainer, it's not a good idea to use this mecanism to denote configuration availability (though maybe a special flag in the metadata could indicate that this is not an install error, but it feels a bit ad-hoc).

> However, since the compilers already need to define what they provide, couldn't we simply let the virtual base-* packages get installed lazily, and define compilers that do not support them using conflicts ? That would also greatly reduce the amount of added data since they're supported almost everywhere.

This could be an idea.

> The mechanism for switch-preselections of packages proposed by @dbuenzli could help here as well.

I'm not sure it would be a good fit. But note that if you are interested, as a preparation for a chat I had with @dra27 I wrote a little bit about it [here](https://gist.github.com/dbuenzli/961a71b18600156ec704b465e89d7dc7).

**Comment by dbuenzli** [comment]
> It works since the packages are actually virtual, but they do get installed before the OCaml compiler does.

I'm not sure if that's related but it also seems that the way compiler variants are installed is a bit confusing. If you create a switch with a variant, the first time you install something it will tell you it is going to install the corresponding ocaml version the first time you install something which is [confusing](https://discuss.ocaml.org/t/dynamically-link-native-code-into-utop/793/15).

```
> opam switch create a 4.05.0+ocamlnat

=-=- Gathering sources =-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=
[ocaml-variants.4.05.0+ocamlnat] found in cache

=-=- Processing actions -=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=
-> installed base-bigarray.base
-> installed base-threads.base
-> installed base-unix.base
-> installed ocaml-variants.4.05.0+ocamlnat
Done.
# Run eval `opam env` to update the current shell environment
> eval $(opam env)
> opam install owl
The following actions will be performed:
  - install ocaml           4.05.0                      [required by owl]
  - install result          1.2                         [required by topkg]
  - install ocamlbuild      0.11.0                      [required by owl]
  - install conf-pkg-config 1.0                         [required by ctypes]
  - install conf-m4         1                           [required by ocamlfind]
  - install conf-gsl        1                           [required by owl]
  - install ocamlfind       1.7.3                       [required by owl]
  - install topkg           0.9.0                       [required by integers]
  - install plplot          5.11.0                      [required by owl]
  - install ocamlmod        0.0.8                       [required by oasis]
  - install ocamlify        0.0.1                       [required by oasis]
  - install gsl             1.19.3                      [required by owl]
  - install dolog           3.0                         [required by owl]
  - install base-bytes      base                        [required by ctypes]
  - install integers        0.2.2                       [required by ctypes]
  - install oasis           0.4.10                      [required by owl]
  - install ctypes          0.12.1                      [required by owl]
  - install eigen           0.0.4                       [required by owl]
  - install owl             0.2.6
===== 19 to install =====
```

**Comment by dra27** [comment]
My probably-to-be-renamed `also-install` field which @AltGr mentioned above solves this - it means that `ocaml` is always installed

**Comment by dbuenzli** [comment]
> My probably-to-be-renamed also-install field which @AltGr mentioned above solves this - it means that ocaml is always installed

Maybe with the current way things are organized, but, sorry to repeat myself, I would rather challenge the organization than adding features to "solve" this.

**Comment by dra27** [comment]
Possibly - but the feature is there for something else, and it solves it too!

**Comment by dbuenzli** [comment]
> Possibly - but the feature is there for something else, and it solves it too!

What is "the feature" exactly, `provides:` ? And was is that "something else" it solves ? I have the impression that `provides:` would not be needed in a world where `features:` exists.

**Comment by dra27** [comment]
`also-install` provides a series of packages were are installed after the given package. In particular, they install as roots, but not as base (compiler) packages, so you can uninstall/upgrade them. For the Windows ports, it automates the installation of native code flexlink. It's not dissimilar to the idea of a suggested package in apt

**Comment by dbuenzli** [comment]
> For the Windows ports, it automates the installation of native code flexlink.

I thought this was supposed to be solved by [`compiler-bundle:`]( https://github.com/ocaml/opam/issues/2649) (not that I think this is a good idea, I really think we are just circling around the opam switch initialization problem here).

**Comment by dra27** [comment]
That is indeed the one - I'd forgotten there was already an issue tracking that too

**Comment by AltGr** [comment]
I believe the `{post}` dependency flag nicely solves this issue on the opam side. Remains the repository convention issues, but that's not for this tracker :)

Remember, though, that if e.g. `ocaml-base-compiler.4.06.0` has `depends: "bytes" {= "builtin" & post}`, the `bytes.builtin` package will always be installed just after `ocaml-base-compiler.4.06.0`, but nothing will prevent it from being installed with other compilers that don't have this `{post}` dependency as well. So you also need to add either:
- a requirement in the definition of `bytes.builtin`, e.g. `depends: "ocaml" {>= "4.03.0"}`
- a conflict in _all_ compilers that don't provide it.
