### ISSUE TITLE
opam2: build with `make cold` failing randomly

### ISSUE THREAD

**Issue by avsm** [ocaml/opam#3055]
Looks like there is a race condition somewhere in the post-jbuilder build that is causing make cold to fail. Some of the builds fail, e.g.:

https://hub.docker.com/r/ocaml/opam-dev/builds/bxnbfnvvykyvjtrpaezbm5u/

You can see some of the more recent ones at:

https://hub.docker.com/r/ocaml/opam-dev/builds/

This is blocking container rebuilds for opam CI, so any help appreciated.

**Comment by AltGr** [comment]
Ah, I think I know what happens.

```
src_ext/jbuilder/_build/install/default/bin/jbuilder build opam.install [91mVariable "cmt_magic_number" not found in the output of `/usr/bin/ocamlc.opt -config` 
```

jbuilder is looking for `ocamlc.opt` at the wrong place. The `cold` target actually calls `make` commands as `env PATH="`pwd`/bootstrap/ocaml/bin:$$PATH" $(MAKE) ARGS` ; the Dockerfile, though, calls `make` without specifying the PATH. Previously this worked, because we didn't need `ocaml` at that point, but it seems `jbuilder` needs it for some checks at installation time too. We could provide a target `cold-install`, or save the coldness status somewhere to have the `install` target get the `PATH` back properly.

**Comment by AltGr** [comment]
(of course, you can also work around it by manually using ``PATH=`pwd`/bootstrap/ocaml/bin:$PATH make install``)

**Comment by AltGr** [comment]
I added `make cold-install`, so you should just need to replace `make install` in the Dockerfile.

**Comment by avsm** [comment]
Thanks! This fixes the build problem -- I'm rolling this out.
