### ISSUE TITLE
On linux but not mac, "Package 'Str' not found" error

### ISSUE THREAD

**Issue by cdstanford** [ocaml/opam#3075]
**Summary of error:** Given a one-line program containing `let s = Str.regexp "hi" in s`, `ocamlbuild myfile.native -pkgs Str` raises error: `Package 'Str' not found` (same with -use-ocamlfind tag). This command runs correctly on a mac machine but errors on linux (!). (On the other hand, if it is named in lower-case, it works: `ocamlbuild strbug.native -pkgs str`.)

The error is present on my machine, with clean opam installation, on linux running ubuntu 16.04 LTS.

**Steps to reproduce:**
Install opam and ocaml with
`wget https://raw.github.com/ocaml/opam/master/shell/opam_installer.sh -O - | sh -s /usr/local/bin`
Then run
`opam install ocamlbuild`, `opam config env`
In a working directory, make a single file
`let s = Str.regexp "hi" in s`
and compile it with 
`ocamlbuild strbug.native -pkgs Str` (error) and then 
`ocamlbuild strbug.native -pkgs str`.

**Comments:**
I am not experienced with opam and ocaml. I do not know if this is a bug in opam, ocaml, ocamlbuild, or what specific tool, so please direct me elsewhere if this is the wrong place for the bug. Had I been more knowledgeable about opam and ocaml, perhaps this would not have caused months of being stuck for me, but the fact that it works on apple and not linux seems like a problematic inconsistency.

**Comment by AltGr** [comment]
I would say the issue is probably in `ocamlfind`. The ocamlfind package is what you specify through option `-pkgs` of ocamlbuild, and is normally lowercase. Here package `str` contains an OCaml module `Str` (it could contain others as well). So the correct command-line is `-pkgs str` : I guess this works on your mac because you are on a case-insensitive filesystem, and ocamlfind bases itself on the directory name to guess the package name (have a look at `~/.opam/system/lib/str/META`, which defines the package).

Also, `opam config env` prints the required environment, but you need to eval it (`eval $(opam config env)`) to set it in your shell.

**Comment by cdstanford** [comment]
Thanks! I think that clears this up.

caleb
