### ISSUE TITLE
opam 2.0~beta3.1 root upgrade does not work on macOS

### ISSUE THREAD

**Issue by jbulow** [ocaml/opam#3091]
installed opam 2 using "opam install opam-devel"

then

>opam list
This version of opam requires an update to the layout of /Users/jonas/.opam from version 1.2 to version 2.0~beta, which can't be reverted.
You may want to back it up before going further.
Perform the update and continue ? [Y/n] y
Fatal error:
opam: "open" failed on /Users/jonas/.opam/log/command-/opt/local/bin/ocamlc-6358-b22031.out: No such file or directory

**Comment by AltGr** [comment]
The opam-devel package is lagging behind a bit, this has been fixed since. A new beta is coming, I'll make sure to have it released as `opam-devel`.
Thanks for reporting. In the meantime, if you don't want to wait, you could either:
- let the new opam version recreate an opam root from scratch, by moving `~/.opam` away
- use our binaries for a more recent version (https://github.com/ocaml/opam/releases)
- compile opam master (or at the beta4 tag) yourself from this repository

Thanks for trying our beta version and reporting!

**Comment by jbulow** [comment]
I used a binary from a more recent version ( 2.0.0~beta4 ) and it worked fine. 

A minor observation:

> % opam2 list
> This version of opam requires an update to the layout of /Users/jonas/.opam from version 1.2 to version 2.0~beta, which can't be reverted.
> You may want to back it up before going further.
> Perform the update and continue ? [Y/n] y
> Update done, please run 'opam update' and retry your command

The last line should refer to "opam2" and not just "opam". It is usually a good practice to use argv[0] when referring to the name of the executable itself in order to be consistent.

**Comment by jbulow** [comment]
..and opam should not refer  to itself as simply "opam" because it will create problems in a multi-version transition:

> >opam2 user-setup install
> # opam-version    1.2.2
> # os              darwin
> File /Users/jonas/.opam/4.05.0/config/global-config.config does not existFatal error: exception Failure("Bad answer from 'opam config var os'")
>

**Comment by AltGr** [comment]
Indeed, thanks for the suggestion. Note that, since the format of `~/.opam` needs to be upgraded for opam 2, running the two side by side would be a tad more involved anyway. You could, for example, use `alias opam2="OPAMROOT=~/.opam2 /path/to/opam2".

We have been considering using `~/.opam2` by default for opam 2, to avoid these issues, but the thing is you can't really use both at the same time, since there is still a single PATH, and you would risk mixing binaries from the opam 2 switch and the opam 1 switch — so switching to opam 2 completely, while providing a safe way to roll back seemed a better solution.
