### ISSUE TITLE
opam2: beta5 regression: command not found when installing packages

### ISSUE THREAD

**Issue by Leonidas-from-XIV** [ocaml/opam#3132]
Hi!

I've updated to 2.0.0~beta5 and when I try to install `amqp-client.1.1.4` after building sucessfully it fails to install with 

```
"": command not found.
```

This happens on both GNU/Linux and macOS. The earlier version, beta4, worked just fine so I am reporting this as a regression.

**Comment by AltGr** [comment]
Probably because of #3109: there is a change in how undefined variables are handled in commands.

Looking at the definition for `amqp-client.1.1.4`, it contains:
```
build: [
  ["jbuilder" "build" "-p" name "-j" jobs]
  ["jbuilder" "runtest" "-p" name "-j" jobs] {with-test}
]
install: [jbuilder install]
remove: [jbuilder uninstall]
```

There is clearly some quotes missing in the `install:` and `remove:` lists. Now it resolves to `["" ""]`, which leads to a failure, while previous versions of opam resolved to `[]`, which is just ignored, and made the error silent. I am guessing, since the package uses jbuilder, that there were `.install` files around that worked anyway, so the commands weren't needed to begin with.

Could you please report to opam-repository ?
Thanks!

**Comment by Leonidas-from-XIV** [comment]
Thanks for your quick response, much appreciated!

Is there a way to be warned about this? Because executing it and getting a puzzling error made me believe there was an error in OPAM and not in the package description.

I'll submit a PR to opam-repository and upstream to fix it.

**Comment by AltGr** [comment]
It would be best to have the possibility to detect this with `opam lint` ; the trouble is that in theory, any variables could be defined on the client side, so undefined variables can't be analysed a priori.

Maybe we could still have a warning with global variables not belonging to the set of pre-defined ones, though: other cases require the users to `opam config set VAR` manually, so they are limited to users who know what they are doing.

There are still variables that are defined through (the default) configuration, like `sys-ocaml-version`, though.
