### ISSUE TITLE
"provides" field for opam files

### ISSUE THREAD

**Issue by vbmithr** [ocaml/opam#314]
Some linux distribution allow to mark a package as a "provider" of another package. It is useful when multiple packages provide the same functionality.

It would be nice to have such feature in opam: it would allow for example to fork a package and use the fork to provide the forked package.

cryptokit-sha512 is an example of a package that would require that feature. It extends cryptokit with sha512 primitives, so it’s a drop in replacement for cryptokit. Yet packages depending on cryptokit will not accept being installed if cryptokit-sha512 is installed.

**Comment by AltGr** [comment]
Design documented at https://github.com/ocaml/opam/blob/master/doc/design/provides.md

**Comment by AltGr** [comment]
Gathering here various related thoughts on what we need, should, and can do. I'm still gathering ideas on this and didn't yet find a perfect design choice. I am sure the mirage team has related use-cases and may want to drop in (ccing @avsm, @hannesm)

### Summary

- `provides:` is _one way_ to handle "families" of packages.
- we need some related features to more nicely have compilers-as-packages (e.g., many different providers for `ocaml`)
- the current `provides:` field proposal doesn't play well with the security framework we have in mind (it allows dependency injection, i.e. by providing a widely used feature I can make users install my malicious package)

This last point adds a lot to the various design question the [current design document](https://github.com/ocaml/opam/blob/d89082db4ba75eeaf47817533670603ffd29ab56/doc/design/provides.md) already leaves open.

### The need

Some packages are related, and should still be treated, in some ways, as a single package. In other words, there may be several _variants_ of the same package. For example, we have completely different packages under the name `camlp4`, tailored for the different ocaml versions. With compilers-as-packages, we have different versions of the OCaml compiler, like the MetaOCaml variant, but all of them fulfill the same role.

### Current ways to deal with (or around) it

The most common way currently is to use a single package, but with specific versions, e.g. `<variant>+<version>`, or like in `camlp4.4.02+6`, `camlp4.4.02.0-1modular-implicits`. While we don't care about version ordering between the versions corresponding to different variants, this is not a problem if we assume the variants all have a disjoint set of constraints (`available:` and `conflicts:`/`depends:`).

This properly makes all the variants exclusive of each other, and allows to depend on any of them. Depending on a specific variant, though, is more tedious, and the weird versions are difficult to make sense of for the users -- this can lead to unclear error messages, too. Moreover, this doesn't allow to easily define ownership of the different variants, which is a problem for signing the package (it might be possible using [delegation of version ranges](https://github.com/ocaml/opam/wiki/Signing-the-OPAM-repository---draft#delegation-files), but it doesn't get very readable or convenient). Also, depending on the versionning scheme, only one of `depend on any variant at version v`, and `depend on this given variant, at any version` can be expressed, because of the one-dimensional ordering of versions+variants. This is a big problem for e.g. the ocaml package.

The other way around is to use a pseudo-virtual package, i.e. a package without code that depends on a disjunction of the variants. This makes it easy to depend on either the general package or a given variant, is easier to read on the repository, and allows clear package ownership and errors. However, it may be tedious to maintain, as the virtual package needs to register all possible variants (and conflicts between the variants would need to be completely explicit, which implies quadratic metadata duplication!)

As for "package replacements", we simply can't allow them (other than with the current, explicit package pinning) with security constraints in mind: you need to be an owner of package `foo` to be able to provide a replacement for it, so there is no value in allowing that without changes to `foo`'s metadata.

### Problems of `provides:`

Besides the problems cited in the proposal, it's precisely the fact that we don't want to allow package replacements, for safety reasons. Adding `provide:`-aware mechanics to the signing mechanics  would be heavy-weight and extend the attack surface, and needing to sign for the provided package defeats some of the purpose of the `provides:` field.

### Possible solutions

What we want is to be able to define a package "family". Several tracks could get us there:
* based on the current workaround, give first-class existence to package "variants", e.g. as a prefix to the versions.
* other ideas revolve around some definition of virtual packages. Some problems are alleviated by doing it the other way around, and defining a `provided-by:` field -- meaning that any of the cited providing packages can be installed instead of this one. This would allow for (or possibly, force) variants to conflict with all the other variants, and solves the security issue. Remains the question of what version is provided (does it need to be always explicit, which means the virtual provided package needs to have one instance per version ? Do we propagate the version of the providing package ?)

I tend to think the second solution would be better in terms of readability and maintenance of the repository; I am not sure yet which one involves the biggest changes code-wise.

**Comment by hannesm** [comment]
@AltGr thanks for raising and describing this issue in depth!

I like to have a `virtual` package which explicitly lists all possible real candidates.  Each real package can have independent maintainers, and in order to add another instance, the `virtual` one has to be modified (thus, no implicit `provides` done by an adversary).  I'd not explicitly list any version numbers in the `virtual` package (doesn't give you much for the signing at least).

**Comment by AltGr** [comment]
After lots and lots of discussions and thinking, I think this can be closed.
The current solution is to provide:
- `conflict-class:` to easily allow family of providers to be mutually conflicting
- a concrete wrapper package depending on the disjunction (listing the disjunction explicitely is _good_ for security)

The upcoming refactored version of `features:` could also help with some use-cases, where you will be able to depend on a given `package/feature`
