### ISSUE TITLE
opam2 built-in os detection sets `os` to `macos` instead of `darwin`

### ISSUE THREAD

**Issue by avsm** [ocaml/opam#3148]
opam1 set the `os` variable in constraints to `darwin` (this is used in various opam packages for osx-specific config)

opam2 sets it to `macos`, which in turn causes build failures due to the package repository testing for `os = "darwin"`.

We should reconcile this to be consistent between opam1 and 2

**Comment by marco-m** [comment]
+1 for `darwin`, which is arguably the name to use (output of `uname`) and, if I understand correctly, would reduce the overall number of changes.

**Comment by dbuenzli** [comment]
This was discussed in https://github.com/ocaml/opam/issues/3058 I think `macos` is the right name especially since it is used with `sw_vers -productVersion` for `os-release`, which wouldn't make any sense for `darwin`.

You could argue to have `darwin` for `os` and `uname -r` for `os-release` but that's really not what you want from an end-user perspective: you want to constrain things by macOS versions.

**Comment by avsm** [comment]
I'm ok with using `macos` in opam2, as long as the repo rewriter logic also maps the variable name back to `darwin` for opam1 compatibility

**Comment by AltGr** [comment]
The rewriting should have accounted for that change, it seems like a bug.

**Comment by AltGr** [comment]
Ok, the rewriting was done properly for `depexts`, but not in other places (`available`, and filters). Fixing that.

**Comment by AltGr** [comment]
Now fixed in the repo. Note that we don't handle the cases where the `os` variable would have been used as a string (e.g. `make "%{os}%.target"`. But thankfully nobody is doing that !)
