### ISSUE TITLE
2.0.0~beta5: clarify semantics of setenv: in packages

### ISSUE THREAD

**Issue by dbuenzli** [ocaml/opam#3173]
Currently the documentation says:

> setenv: [ <environment-update> ... ]: defines environment variables updates that will be applied 
> upon installing the package. The updates will be visible to any dependent package, as well as 
> exported to the shell environment through opam env and ~/.opam/opam-init/ scripts.

In fact currently the variable updates seem to be visible to *any* packages and not only to *dependent* packages as documented. 

FWIW in my use case the current behaviour is what I need. In a "switch setup" package I'm updating a search path other packages might consult, but I don't want the latter to be made aware of the former and I also want these updates to be available in `opam env`.

Only affecting dependent packages could be a legitimate use though, so maybe we should have both `switch-setenv` and `setenv` ? What is a bit unclear to me though is that if you only want to update the environment of dependent packages, do you also really want to update `opam env` with these changes (i.e. somehow you make `opam env` dependent on the package) ?

**Comment by dbuenzli** [comment]
Another thing that would be nice to clarify in [this section](https://opam.ocaml.org/doc/2.0/Manual.html#Environment-updates) is that interpolation is available. It is at least for switch variables but I didn't check if package variables are (which could be interesting).

**Comment by AltGr** [comment]
> In fact currently the variable updates seem to be visible to any packages and not only to dependent packages as documented.

Actually, the correct wording would have been "the updates are only _guaranteed_ to be visible to any dependent package". What actually happens is that:
① during the session where you install the package, the changes are indeed only visible to its dependents
② but after that, they are visible throughout

The reason for ① is that it couldn't be made consistent otherwise, and would introduce potential race-conditions. The reason for ② is that the update will also affect `opam env`, where we can't reasonably filter.
So the only other option would be variables only visible to the dependents, and _not_ exported through `opam env`. Not sure if we want those (could lead to a package building in opam, but not manually, without an easy way to understand why).

Should the documentation specify the full details ?

**Comment by dbuenzli** [comment]
> Should the documentation specify the full details ?

I think it should. The "equation":

    install p1 p2 = install p1; install p2 = install p2; install p1

for two independent packages `p1` and `p2` somehow no longer holds with `setenv` and it is good to know.

Another thing that is missing from the spec (and implementation ?) is defining a deterministic order for environment updates, from to packages `setenv`ing the same variable.

**Comment by AltGr** [comment]
Related to #3181.

Actually, sorry, my comment above was largely inaccurate: there is no relation with running `eval $(opam env)`, which should actually be properly reverted in 2.0 (see #3181). The symptoms you are seeing are actually not specific to the environment, and due to the way opam computes the package universe visible to each package when processing actions. Basically, the "static" part of the universe, that remains untouched, is used as a common base universe for all actions, while any package changed by an action during this run is "seen" only by its dependents. The original reason for this was implementation related: we don't compute and extract a dependency cone for each package to build individual universes, however, we process a graph of actions that encodes all the dependencies _between modified packages_. To ensure consistency of actions, the universes have been tweaked to reflect those dependencies, but not all of them.

What this means is that the universe a package "sees" while building (which includes `setenv:`s) is a consistent subset of what is really installed, where the package itself is not installed (ergo, no dependents packages are installed). But unrelated packages may be installed or not (and seen as such or not).

I think this should be sufficient, but probably documented somewhere. In particular, your installation-equation doesn't really hold if the two packages overwrite the same file, or have a build somehow modified by files installed by the other — which is obvious since we don't have sandboxed builds.

This also reflects the fact that, for builds processed by the user outside of opam, the whole of `opam env` and the universe is visible. So really, we shouldn't allow any package to rely on _not_ seeing variables set by independent packages. (or conversely, allow packages to set variables that may affect independent packages). Otherwise, I predict `setenv:` will make us go insane. This is the same implicit package guideline that actually applies to installed files...
