### ISSUE TITLE
local opam switch create could use better compiler selection logic

### ISSUE THREAD

**Issue by avsm** [ocaml/opam#3205]
With a local switch:

```
$ opam switch create .
[NOTE] Converting format of /Users/avsm/src/git/avsm/ocaml-dockerfile/dockerfile-cmd.opam from 1.2 to 2.0~beta5
[NOTE] Converting format of /Users/avsm/src/git/avsm/ocaml-dockerfile/dockerfile-opam.opam from 1.2 to 2.0~beta5
[NOTE] Converting format of /Users/avsm/src/git/avsm/ocaml-dockerfile/dockerfile.opam from 1.2 to 2.0~beta5
[WARNING] No possible installation was found including a compiler and the selected packages.
Create the switch with no specific compiler selected, and attempt to continue anyway ? [Y/n] 
```

Selecting yes will result in 4.07.0+variants+trunk or something like that being selected, rather than the latest stable compiler.

Then

```
$ opam switch create . 4.06.0
[ERROR] Compiler selection '4.06.0' is ambiguous. matching packages: { ocaml-base-compiler.4.06.0, ocaml-system.4.06.0 }
```

fails due to the ambiguity, and then

```
$ opam switch create . ocaml-system.4.06.0
```

finally works.  These all seem like common failure scenarios -- having multiple compilers installed, not specifying a default and so on.  Shouldn't the local switch create default to the system compiler instead, for example?

**Comment by AltGr** [comment]
> `[WARNING] No possible installation was found including a compiler and the selected packages.`

Hmm, this sounds like a bug, I'll check. I doubt it's true :), and if it's not, opam should automatically choose that compiler.

> ```
> $ opam switch create . 4.06.0
> [ERROR] Compiler selection '4.06.0' is ambiguous. matching packages: { ocaml-base-compiler.4.06.0, ocaml-system.4.06.0 }
> ```

This one I don't see how to avoid. Remember that specifying a version with `opam switch create` is a semi-hack for backwards compat, what opam needs is a package name(.opt version) that has the `compiler` flag set.

Thanks for reporting, the above bug seems annoying indeed!

**Comment by AltGr** [comment]
Ok, I finally understood what happens, and it's trickier than what I expected (I suspected the compiler-choosing mechanics in opam but it's actually not directly that part where the problem lies).

Your repository has 3 `.opam` files. The one for `dockerfile-cmd` exposes a dependency towards `dockerfile-opam=3.0.0`. However, none of the package definitions specify a version number, so opam fills the gap by using `~dev`. The result is that `dockerfile-cmd` is not installable since there is no `dockerfile-opam.3.0.0`, only a `dockerfile-opam.~dev`.

Consequently, the packages are not installable _at all_ as opam sees them, which of course means that no compiler is co-installable. So:

- opam should clearly check that, and tell you so, rather than print the compiler compatibility error in this case
- the easiest workaround (opam 2 only), would be to use `depends: "dockerfile-opam" {= version}` to bind the versions of the two packages.
- specifying the versions in the opam files would also work (and be accepted by opam 1.2 too). Since they are already specified at one point, it would only be consistent.

**Comment by AltGr** [comment]
What's fun is that a subsequent run actually works... because opam in that case will use the latest version from the repositories by defaul, rather than `~dev`. That's useful when pinning to master, but maybe we could remove that feature. Or use it consistently in pre-resolution of `opam install .`.

**Comment by AltGr** [comment]
(what happens normally is that the version is first initialised to `~dev`, then updated when the switch has been created. Used to think it was harmless...)
