### ISSUE TITLE
opam env is slow

### ISSUE THREAD

**Issue by jhjourdan** [ocaml/opam#3228]
```
$ time opam env
[...]
real	0m0,155s
user	0m0,109s
sys	0m0,045s
```

I configured my .bashrc to run `eval 'opam env'` after every command. This is very handy in conjunction with local switches, because I am sure my `PATH` is always set to the local switch. Having a 0.15s lag between every command is noticeable and sometimes not very comfortable.

I do not know what `opam env` is doing, but it seems pretty slow for what it should be doing. Therefore, I wonder whether you already tried to improve its performance. Perhaps there is a low-hanging fruit that could make my trick much nicer in practice.

**Comment by AltGr** [comment]
You can check what it is doing with `opam env --debug`. Basically, what takes time is loading the full switch-state (including the cached repository state which can be above 10MB). This is done now because, since any package can define its own variables using `setenv:`, you need to get all their definitions to compute the environment.

However, this can be cached, and actually already is: there is a file `<switch>/.opam_switch/environment` which contains the pre-computed environment updates. So it should be fairly easy to base `opam env` on that and make it instant.

One last note: I would suggest using the `--readonly` option for such use-cases. It will make sure opam doesn't attempt to get any locks, or doesn't start any interactive interaction.

**Comment by jhjourdan** [comment]
Sorry for the close/open noise.

Happy to see that this should not be too complicated! In my opinion, that should be an improvement. The lag is especially annoying when the machine is under load doing other things.

However, in practice, in my case, even though indeed significant time (40ms) is spent loading the switch state, it seems like loading the repository state is even slower (86ms). Does opam need this information?

**Comment by AltGr** [comment]
The timings displayed by `--debug` separate the two, but loading the repository state is a required  first stage of loading the switch state: I meant the total time of the two in my post above.

**Comment by AltGr** [comment]
Ok, using the cache seems to work consistently and pushes the delay back to 13 milliseconds, which should be acceptable. I'll push shortly.

**Comment by Drup** [comment]
@AltGr Do you think the documentation (and the setup) should tell users to run it after every command ? That would clearly make local switches easier to use.
