### ISSUE TITLE
opam does not always pick the latest version available

### ISSUE THREAD

**Issue by kit-ty-kate** [ocaml/opam#3229]
Given the following Dockerfile:
```
FROM ocaml/opam2:debian-9-ocaml-4.05.0
RUN git pull origin pull/11449/head
RUN opam update
RUN opam install -y opam-depext
RUN opam install -y --dry-run --cudf=backtrace pkcs11.0.15.0
```
the final command behave differently whether it is on a ARM64 machine or a x86_64 one (the two test machines that I could get my hands on for now).

The problem is that the ARM64 one tries to install ```ppx_deriving.4.2``` (older version) while the x86_64 one tries to install ```ppx_deriving.4.2.1``` (latest version available).
I'm not sure what could possibly be different on the two machines to experience such difference.

ARM64 cudf backtrace: [arm64.tar.gz](https://github.com/ocaml/opam/files/1740797/arm64.tar.gz)
x86_64 cudf backtrace: [x86_64.tar.gz](https://github.com/ocaml/opam/files/1740798/x86_64.tar.gz)

**Comment by AltGr** [comment]
Right, after some tests, the cause seems to be what I feared: _numerical instability_. In other words, we are hitting some numerical limits of the solvers, making them unreliable (they base their computations on floats, and by using too large values, we get bitten by rounding errors). This is in large part, if not entirely, due to #3170, for which I was already looking for a better solution.

Thanks for the detailed report, such test cases really help!

**Comment by Drup** [comment]
@AltGr glpk doesn't use arbitrary precision?!

**Comment by AltGr** [comment]
It can use GMP for some calculations, but the MIP solver, which is the part we use, is based on LP solving to find bounds in |R, then uses them to guide branch-and-bound to get an integer solution. Since the LP solving is based on floats, rounding errors can lead to problems if the values get too big. AFAIK it's the approach taken by all MIP solvers.

**Comment by dra27** [comment]
It's also worth noting that the bits of GLPK which use arbitrary precision always use arbitrary precision - it optionally uses GMP in order to make those operations faster.

**Comment by AltGr** [comment]
Removed the aforementionned hack, which should avoid this issue. Thanks!
