### ISSUE TITLE
opam update w/ Mercurial repository needs "hg update"

### ISSUE THREAD

**Issue by jhwoodyatt** [ocaml/opam#3281]
_hg pull_ is not _git pull_, and it does not update the working directory. Only _hg update_ does that.

Accordingly, when _opam update_ pulls from a repository using Mercurial, it is currently a necessary workaround to manually issue **hg -R ~/.opam/repo/*repository-name* update** before the operation is complete. This should instead be done by _opam update_ itself.

**Comment by jhwoodyatt** [comment]
Alternatively, the _hg pull -u_ command could be used.

**Comment by dra27** [comment]
Would you be happy to make a patch? It would be in `src/repository/opamHG.ml`

If you're feeling particularly adventurous, we should really add Mercurial to the testsuite (see `tests/Makefile`)

**Comment by jhwoodyatt** [comment]
Let me give it an eyeball.

**Comment by jhwoodyatt** [comment]
Grmf, this logic is more complicated than I was hoping it would be. I have a patch to propose, but it's not a trivial one. Not super involved, but it's no one-liner. I'll make a pull request.

**Comment by jhwoodyatt** [comment]
I did not feel sufficiently adventurous even to *look* at the test suite. I might be a bad person, and I should arguably feel ashamed. In my defense, it's a beautiful Sunday afternoon in San Francisco, and my girlfriend is making lasagne by hand. These are compelling distractions, and I have succumbed. Forgive me.

**Comment by jhwoodyatt** [comment]
Gah. Okay, some of the integration test builds fail. (I am unsurprised.) I'll investigate later.

**Comment by AltGr** [comment]
Thanks a lot. Indeed, our Mercurial backend is much less used than the git one, so there might be issues with it.
The expected code-flow, for all VCS backends, is as such (expecetd interface documented at https://github.com/ocaml/opam/blob/master/src/repository/opamVCS.mli) :
- `fetch` is used to get the new data from the network
- then in the case of a package:
  - `is_up_to_date` is used to check for changes
  - `reset` is used to actually apply the pending changes
- or in the case of a repository (this is new in opam 2.0)
  - `diff` is used to get a patch
  - (some security checks may be done on the patch)
  - the patch is applied using the `patch` command

so it is expected that the `fetch` function doesn't do the `update`, but it is done later on. The update of packages hasn't changed for a while and we haven't have reports about it, so I expect it works fine, but in your case you are using Mercurial for a package repository, which may not be so well tested, and was changed since opam 1.2. This would direct us to a bug with the `diff` command, and the expectations about how the patch can be applied.

So your feedback on this is very welcome, thanks for taking the time.

**Comment by AltGr** [comment]
Now merged, thanks again for helping with this!
