### ISSUE TITLE
md5 is probably a bad hashing scheme to depend on.

### ISSUE THREAD

**Issue by pmetzger** [ocaml/opam#3320]
The manual says that the `checksum:` field in the `url` file contains an md5 hash. md5 is, sadly, broken. It is now possible to produce multiple files with the same hash by exploiting a collision vulnerability in the hash function. This is not merely theoretical, you can actually do it in the real world, and it in fact has been used in real-world security attacks, including to forge sabotaged patches.

A mechanism should be adopted to allow the use of stronger hashes (SHA256 or SHA3), and that the `url` files be updated to this. A good scheme might allow the `checksum:` field to specify what the hash type is so that it can be updated incrementally, or perhaps a `hash:` field could be adopted to supersede the `checksum:` field that would provide for other (newer) hash functions.

**Comment by dbuenzli** [comment]
Given the way opam works for now you can only see the `checksum` field as a data integrity check a task for which `md5` is perfectly fine. There's no way changing the hash will bring you more security. See [this paper](https://www.cl.cam.ac.uk/~hm519/ocaml2016.pdf) if you are interested in the latter.

**Comment by pmetzger** [comment]
@dbuenzli This can't be right. `opam` downloads the file and checks the hash to see if it should proceed. compressed tar files already have integrity protection, so if this really isn't intended to provide any security at all, then there's no need for it and the feature should be removed. That said, one can demonstrate two tar files that have the same md5 hash, one without malicious contents, and one with. Most package managers I know use hashes for security reasons, and do not use md5 any longer.

**Comment by dbuenzli** [comment]
> opam downloads the file and checks the hash

That's truly great but you need to be able to trust *that hash* in the first place...

> That said, one can demonstrate two tar files that have the same md5 hash, one without malicious contents, and one with.

I think most people nowadays are well aware of this. It even teaches you a lesson in designing standards for reasons other than [purely technical](https://www.xml.com/axml/notes/TrailingMisc.html).

**Comment by pmetzger** [comment]
> That's truly great but you need to be able to trust that hash in the first place...

Correct. I'm trusting that the fairly small community of OPAM committers didn't have bad intent when they put that `url` file in the repository. That's quite different from assuming no one anywhere has bad intent.

**Comment by dbuenzli** [comment]
> Correct. I'm trusting that the fairly small community of OPAM committers didn't have bad intent when they put that url file in the repository.

Oh you are trusting more than that, a lot of package devs rely on github to produce their tarballs whose signature is not stable (e.g. w.r.t. repo moves). Hence changing footprints of a published tarball is nowadays no longer seen that suspicious even from the package devs themselves; quite a few commits on the `opam-repository` will witness that. (That's one of the reason why the `topkg`'s release workflow produces its own *reproducible* tarballs).

So to get back on topic yes, md5 is not what you want here, but the problem is elsewhere anyways.

**Comment by dra27** [comment]
Note that opam2 supports other hashes, so we're well on the way towards deprecation of md5 completely.

Checking the integrity of a tarball before extracting means you don't waste time starting to extract from a corrupted download. The level of checking provided in the format is also very limited - IIRC tar has no integrity checking *of the files themselves* and gzip is only CRC.

I echo @dbuenzli's comments and references about trusting checksums - we could be using SHA65536 and opam-repository would still be completely untrustworthy.

**Comment by hannesm** [comment]
@pmetzger thanks for opening this issue.  Since opam 2 is on the horizon, similar issues have been closed (please read up on #1370 #261 #2423 for similar issues).  opam 2 also provides [hooks for verification of package signatures](https://opam.ocaml.org/doc/2.0/Manual.html#configfield-repository-validation-command) (see @dbuenzli paper mentioned above, as well as https://opam.ocaml.org/blog/Signing-the-opam-repository/ and #423) -- I currently develop the third iteration of conex (it's latest release in opam-repository implements what is discussed in [my blog post](https://hannes.nqsb.io/Posts/Conex) mainly to realise it on top of [TUF + TAP8](https://ssl.engineering.nyu.edu/blog/2017-05-15-conex)), atm at a rather low speed (due to constraints of time, money, and other projects) - most recent code in the new-conex branch at https://git.robur.io/?p=conex.git;a=shortlog;h=refs/heads/new-conex

If you're as well interested in "opam 1.2.2 insecurity" (which calls out to `curl --insecure` or `wget --no-check-certificates`), take a look into #2006 and #2460.

Your suggestion to encode the hash algorithm and the hash value has been implemented in opam 2, as seen in the 2.0.0 branch of opam-repository (a concrete example is at https://github.com/ocaml/opam-repository/blob/2.0.0/packages/0install/0install.2.10/opam#L39).

@dra27 I really don't know what SHA65536 should be.  And "opam-repository would still be completely untrustworthy" <- this depends very much on your threat model.  If you trust GitHub to only allow modifications/pushes by authenticated users, and do not themselves modify git repositories, opam-repository should be sufficiently trusted.  Now, opam 1.2.2 downloads some re-packaged tarballs from opam.ocaml.org (not sure whether there are hashes provided and checked) -- which is a single point of failure.

My goal with Conex to push the trust to (a) the authors of packages (who cryptographically sign their) and (b) to the opam-repository maintainers (who vouch for which packages an author is responsible for).  Now there are various complications: if a single opam-repository maintainer can modify such a reponsibility, they are way too powerful (a compromise of a (or maliciously behaving) single maintainer leads to a full compromise of the opam-repository) - thus there's always a quorum (`n` out of `m` need to sign this).  Another aspect of the opam-repository is that various packages are maintained by a team of people (e.g. most of the mirage-* packages) -- instead of listing all mirage people for each package, a useful abstraction is a set of people (again, with the ability of requiring a quorum), which then (thanks to justin and my work on tap8) can modify (extend and shrink) themselves (without interference of the maintainers).

**Comment by dra27** [comment]
@hannesm - I meant only that however strong the hash algorithm you use, there are still other considerations for trust. Similarly with opam-repository, I say only "untrustworthy" to mean there's more to consider - if I install a package via apt, say, I have certain expectations about how scrutinised that package will have been in terms of what it does by the maintainer of that package. That's lacking in opam-repository. That's not necessarily bad, of course - my only attempt at a point is that you can spend a lot of time focusing on the trustworthiness of the delivery mechanism, and end up happily trusting a dangerous package (whether intentionally or accidentally dangerous).

**Comment by hannesm** [comment]
> install a package via apt, say, I have certain expectations about how scrutinised that package will have been in terms of what it does by the maintainer of that package

if I remember correctly, in the apt setting all the debian developers (i.e. every key part of the public keyring) are trusted for every package.  (but I may be wrong since it's been some years since I read up on the trust story of apt and it may have changed in between).

**Comment by dra27** [comment]
> > install a package via apt, say, I have certain expectations about how scrutinised that package will have been in terms of what it does by the maintainer of that package

> if I remember correctly, in the apt setting all the debian developers (i.e. every key part of the public keyring) are trusted for every package. (but I may be wrong since it's been some years since I read up on the trust story of apt and it may have changed in between).

Sure - as, at present, it is for opam-repository. But in the Debian case, it's reasonable to assume that the package maintainer has gone to a certain level of trouble to check *what* the package is doing, whereas our wonderful opam-repository maintainers, with the aid of all our lovely CI, etc., are essentially verifying installability only.

**Comment by pmetzger** [comment]
I think having the hashes does indeed make it harder for people to fiddle with packages silently, but never mind. So long as OPAM 2 allows for other hashes and MD5 is eventually going to be obsolete, I'm happy. Should I close this?

**Comment by AltGr** [comment]
yup, we now [support](http://opam.ocaml.org/doc/2.0/Manual.html#Checksums) `md5=xxx`, `sha256=xxx`, `sha512=xxx` anywhere where opam 1.2 had md5s, for the very reasons stated above.
