### ISSUE TITLE
feature request: verbose filter

### ISSUE THREAD

**Issue by jhwoodyatt** [ocaml/opam#3330]
I would like to be able to pass the _--verbose_ flag to **omake** in various command lists, e.g., build, install, remove, et cetera, when the _-v_ flag is given to the **opam** command.

I was expecting something like this to work:

`build: [ "omake" "--verbose" { verbose } ]`

Any chance this is an easy thing for a newbie to contribute?

**Comment by dra27** [comment]
I like the sound of that - the machinery which does the evaluation is `OpamFilter.commands` - you'll need to engineer so that the `verbose` variable is in `env`. IIRC the `-v` flag is cached globally, so you shouldn't need to alter anything other than the global environment in `OpamPackageVar`.

Say if more detail than that would he handy!

**Comment by AltGr** [comment]
Exposing a `verbose` variable as part of the "opam environment" would indeed be rather easy: add it to `OpamPackageVar`, and refer to `OpamConsole.verbose ()`.

I am a little wary, though, that packages referring this variable could use it to trigger different behaviour depending on the opam flag, which could make certain things quite painful to debug from opam (e.g. a package failing without the flag, but building successfully with `--verbose`). Is it costly to always enable omake's `--verbose` flag, since the messages won't be seen anyway by the user (except when looking at the logs) without the opam flag ?

Another option would be to use the `{with-test}` variable: although not completely correct, that would enable to only have omake's verbose mode when requested. Note that it is always possible to refer to any variable name, optionally defining it through `opam config set VAR VALUE`.

**Comment by jhwoodyatt** [comment]
Let me give that some thought. I'll mess around with the alternatives you suggest, and see if one of them feels like an adequate solution. My hunch is you're right.

**Comment by jhwoodyatt** [comment]
I'm in agreement now. Withdrawing.
