### ISSUE TITLE
opam is too slow on top of NFS

### ISSUE THREAD

**Issue by UnixJunkie** [ocaml/opam#3352]
Hello,

Probably, some operations should be done in /tmp instead of assuming
that the user's home (under ~/.opam) is a fast filesystem.

I guess that the assumption that /tmp is fast should always be true (for example,
that could be where the builds are done, but not only builds are slow. opam update is super slow, almost to the point where opam is unusable).

Regards,
F.

**Comment by UnixJunkie** [comment]
$ opam init repo_name repo_git_clone_path_on_fs
is also super slow

**Comment by AltGr** [comment]
yes, the repository is 9000+ files in many directories, and that's extremely slow on NFS — so although we could move e.g. builds to `/tmp`, I am not sure it would be sufficient in the end. I guess running over NFS is just unsupported at the moment, not sure exactly how much work would be needed to improve that, but it doesn't seem easy...

#1854 has some ideas on this; closing this one as duplicate.

**Comment by UnixJunkie** [comment]
````
I have an idea.

Let's say the syntax of the command would be:
opam --tmp-root [directory] # directory is optional

And the semantic:
If directory was provided, we rsync ~/.opam to that directory prior to opam
starting to do any (file-intensive) work (we have to lock ~/.opam also).
Then, opam has to work like if --root <directory> was used.
Once opam is done with its job, it synchronizes back from <directory> to ~/.opam (and unlocks ~/.opam).
If <directory> was not provided, we use the system command mktemp to create one (we don't have mktemp in the stdlib for directories?!).

If you reopen the issue, I might help with it if people are interested.

I guess that the scheme I propose will be slow the first time you invoke opam during a session where your $HOME is stuck on NFS. However, thanks to rsync, subsequent opam calls during the same session should be much faster.

Of course, I assume that /tmp is always a fast, local file system.

Regards,
F.
````

**Comment by AltGr** [comment]
Before embarking on this, it would probably be worth investigating where exactly the costs lie. Also, using `/tmp` could cause trouble with relocation for the installation part... We could try to use symlinks to make it transparent, but opam has a tendency to resolve all symlinks, so that probably wouldn't work.

The following could be tested to see how much they improve the situation:
- symlink `~/.opam/repos` to a local dir
- symlink the whole of `<switch-dir>/.opam-switch` to a local dir
- symlink `<switch-dir>/.opam-switch/{build,remove}` to local dirs. The bonus is that these don't need to be permanent

**Comment by UnixJunkie** [comment]
In the past, I managed to survive by moving my whole ~/.opam in /tmp/${USER}_dot_opam (so, out of the NFS).
Then, symlinking ~/.opam to /tmp/${USER}_dot_opam.
However, that doesn't survive a reboot (or several) of the machine because /tmp might be cleaned at some point.
