### ISSUE TITLE
Build fails when adding "test" tag

### ISSUE THREAD

**Issue by bruce-ricard** [ocaml/opam#3384]
Hello,

I am trying to add my alcotest dependency as a test dependency but I cannot make it work. Here is my [opam file](https://github.com/bruce-ricard/glicko2/blob/1cd5842dceff6f9f3a48ce747b85c8536ad8f638/opam#L19) .  When I remove the "test &" from the `alcotest` package, everything runs [smoothly](https://travis-ci.org/bruce-ricard/glicko2/builds/385467030). But when I put it back, it [fails](https://travis-ci.org/bruce-ricard/glicko2/jobs/386445955). What troubles me even more is the error I get, Travis fails with 
`Cannot find findlib package logs.fmt`, which has nothing to do with alcotest. Moreover, I can see in the logs of the failing job 
```
∗  installed logs.0.6.2
Done.
```
But somehow `logs.fmt` is missing.

I am using the `build` tag for `ocamlfind`, and that seems to be working fine.

Please let me know if I'm doing something wrong.

Here is the opam config report:

```
# OPAM config report
# opam-version    1.2.2 
# self-upgrade    no
# os              linux
# external-solver aspcud $in $out $criteria
# criteria        -count(removed),-notuptodate(request),-sum(request,version-lag),-count(down),-notuptodate(changed),-count(changed),-notuptodate(solution),-sum(solution,version-lag)
# jobs            4
# repositories    1* (http)
# pinned          2 (path)
# current-switch  4.02.3
# last-update     2017-12-30 04:42

```

**Comment by rjbou** [comment]
The problem here is about dependencies. According logs, and [setup](https://github.com/bruce-ricard/glicko2/blob/master/_oasis#L13) your package should depends on `fmt` package. This package is an optional dependency of [`logs`](http://opam.ocaml.org/packages/logs/), and a mandatory dependency of [`alcotest`](http://opam.ocaml.org/packages/alcotest/alcotest.0.8.3/).
So, when you restrain `alcotest` to the test step, it's not installed for build, neither its `fmt` dependency.

**Comment by bruce-ricard** [comment]
Doh, transitive dependencies will always get me... Thank you so much, adding fmt seems to have fixed it.
I wasn't aware of the optional dependency thing.
