### ISSUE TITLE
does 'opam switch list-available' still works?

### ISSUE THREAD

**Issue by UnixJunkie** [ocaml/opam#3396]
For me, on Debian with 2.0.0~beta5, it does not work.

**Comment by UnixJunkie** [comment]
```
opam switch list-available base
# Listing available compilers from repositories:
# No matches found
```

**Comment by AltGr** [comment]
It appears that your list of repositories is empty, which results in no compilers being available!
Try `opam repository --all` and `opam repository list --set-default` to check.
`opam repository add REPO --set-default` to fix!

**Comment by AltGr** [comment]
(would probably be better if the empty list after the colon in the message you posted wasn't printed as an empty string)

**Comment by UnixJunkie** [comment]
My list of repos is not empty.
But I never used --set-default very probably.
Shouldn't the behavior be that if there is a single repo, then it is the default one?

**Comment by UnixJunkie** [comment]
I confirm that 'opam switch list-available' doesn't work even when there is a single repo available.
One (strangely) has to say
```
opam repo add --set-default default
```
So that it starts to work...

**Comment by UnixJunkie** [comment]
It would be nice if there were no syntax changes between opam commands in future releases. Breaking the user experience is not nice. Also, if a new syntax really has to be adopted, then supporting the old one for some time would lessen the pain. Thanks! :wink:

**Comment by AltGr** [comment]
Adding per-switch configurable repositories was quite a big change, and I tried to break the interface as little as possible, but it just didn't match the features anymore — sorry for the trouble.
In this case, it's weird that you got into this situation in the first place, because on `opam init`, the initial repository is configured as default for any newly created switches. Maybe you removed it and added it again ? In that case, opam should have warned you about the new behaviour to avoid the confusion, but that warning was added fairly recently so you might note have seen it if you tried the betas:
```
[NOTE] Repository foo has been added to the selections of switch 4.05.0 only.
       Run `opam repository add foo --all-switches|--set-default' to use it in all
       existing switches, or in newly created switches, respectively.
```

**Comment by UnixJunkie** [comment]
yes, sometimes I remove the default repository to force using a git-enabled one (where updates are faster)

**Comment by rjbou** [comment]
Closing this issue, feel free to reopen it if needed.
Thanks!
