### ISSUE TITLE
`opam pin add -k git` in 1.2.2 vs 2.0

### ISSUE THREAD

**Issue by jberdine** [ocaml/opam#3477]
Testing with 2.0 rc2, a workflow involving locally pinning a package during development doesn't work in 2.0. I'm not sure if I'm currently abusing 1.2.2 or if this is unintended behavior of 2.0.

With 1.2.2, I pin packages with:
```
$ cd /path/to/git/clone/root
$ cd my-lib-subdir
$ opam pin add -n -k git my-lib .
```
and opam happily reports:
```
my-lib is now git-pinned to /path/to/git/clone/root/my-lib
[NOTE] Pinning in mixed mode: OPAM will use tracked files in the current working tree from /path/to/git/clone/root/my-lib. If this is not what you want, pin to a
       given branch (e.g. /path/to/git/clone/root/my-lib#HEAD)
```

But with 2.0 the analogous attempt fails:
```
$ opam pin add -n -k git my-lib .
[ERROR] Could not synchronize /Users/jjb/.opam2/4.07.0/.opam-switch/sources/my-lib from "git+file:///path/to/git/clone/root/my-lib#master":
        "git fetch -q file:///path/to/git/clone/root/my-lib" exited with code 128
[ERROR] Error getting source from git+file:///path/to/git/clone/root/my-lib#master
[Exit 40]
```

It seems that 1.2.2 is able to git pin a subdirectory of the git repo, while 2.0 isn't.

I tried without `-k git`, but then `opam` copies the entire directory, which is very slow and heavy as usually there are many and large files not under source control (build and test artifacts).

I also tried `opam install ./my-lib.opam --inplace-build` which initially seems to do what I'm after, but also sets up an `rsync` pin, which hits on the next e.g. `opam upgrade`.

User error?

**Comment by AltGr** [comment]
Ha, interesting... We have a branch that supports pinning sub-directories of git repositories, but it's not in 2.0.0 yet. In fact it looks like you were exploiting a bug, or rather, an unexpected behaviour :D 

I guess this was working because `git ls-files` from a subdirectory works transparently, and since the deprecated `mixed-git` backend was using `rsync` based on the results of `git ls-files`, it happened to work on subdirs.

The solution, at the moment, requires to put the opam files at the root of the git (you can do so in `opam/PKGNAME.opam` files in order not to clutter the root), and then pin the package to the git root.
You'll also need to adjust the opam files so that they execute correctly from the root.

**Comment by jberdine** [comment]
Heh, ok, so almost user error then. :-)  Take this as a request for supporting pinning subdirs then.

**Comment by AltGr** [comment]
There is #3174, but there has been more (yet unpublished) work since then. @rjbou could probably tell you more!

**Comment by jberdine** [comment]
Interesting, thanks. I worry about having to sync the whole repo, and use the whole repo when determining if an update is needed. I am not sure that it should be opam's responsibility to handle these cases though. For local development within a big (multiple millions of files) repo, perhaps the build system should be used instead of pinning. And for publishing packages from such a repo, some other system to extract a subdir is probably needed. On the other hand, the current example of what the llvm bindings package does shows there is room for improvement, as there the entire sources of llvm are downloaded only to build and install a small subdir containing the ocaml bindings.

So just to be clear: this is currently not a priority / timely need. It may make sense to consider this more broadly as a "how to make opam convenient to use in a monorepo". I am a bit surprised at how tightly integrated opam and git are though (e.g. also what happens if I want to use hg? :-) ).

**Comment by rjbou** [comment]
@jberdine #3499  in the continuation of the previous recursive pin PR.  I'll answer there, in order to keep the discussion on one place.

> For local development within a big (multiple millions of files) repo, perhaps the build system should be used instead of pinning

It is also possible with options [`--working-dir` && `--assume-built`](https://opam.ocaml.org/doc/2.0/man/opam-install.html). The first one to get opam retrieve uncommited changes and the second one to use the already local build and install package via opam.
