### ISSUE TITLE
opam/lwt - incomplete environment

### ISSUE THREAD

**Issue by houndofsound** [ocaml/opam#3492]
although lwt as a dependency of utop installed fine, there seems to be a missing lib/lwt from
CAML_LD_LIBRARY_PATH.

$ opam config exec -- utop -emacs 
Fatal error: cannot load shared library dlllwt-unix_stubs
Reason: No such file or directory

I corrected my .bash_profile but how to go about correcting opam's idea of the environment?
.opam/opam-init/init.sh?
.opam/<switch>/.opam-switch/environment?
I looked at opam config --help et al but it's all gobbledygook to me.

**Comment by AltGr** [comment]
`opam env -v` will give you some documentation of all the variables that are set (and in particular, if they were set/updated by core opam or by a specific package).

Don't edit `.opam//.opam-switch/environment`, it will be overwritten as soon as you install something. `CAML_LD_LIBRARY_PATH` is expected to be defined by the wrapper package `ocaml`, through its config file at `$(opam var prefix)/.opam-switch/config/ocaml.config`. If broken, that would be fixed by re-installing the `ocaml` package. The file should look something like:
```
opam-version: "2.0.0~rc3"
variables {
  native: true
  native-tools: true
  native-dynlink: true
  stubsdir: "[...]/lib/ocaml/stublibs:/home/lg/ocamlpro/learn-ocaml/_opam/lib/ocaml"
  preinstalled: false
  compiler: "4.05.0"
}
```

**Comment by houndofsound** [comment]
sorted. thanks!

**Comment by rjbou** [comment]
It was related to the `ocaml.config` file?

**Comment by houndofsound** [comment]
yes, ocaml.config
