### ISSUE TITLE
opam repository add silently fails if init.templatediris set in global git config

### ISSUE THREAD

**Issue by arichardson** [ocaml/opam#3493]
When I use opam repository add I get a very unhelpful 
`[ERROR] Could not fetch repo` message without any explanation and even --debug doesn't show anything else.

To debug this If I look at the strace -e execve output:

```
[pid  3454] execve("/usr/bin/git", ["git", "init"], [/* 86 vars */]) = 0
...
[pid  3455] execve("/usr/bin/git", ["git", "remote", "add", "origin", "https://github.com/rems-project/opam-repository.git"], [/* 86 vars */]) = 0
...
[pid  3456] execve("/usr/bin/git", ["git", "commit", "--allow-empty", "-m", "opam-git-init"], [/* 86 vars */]) = 0
strace: Process 3457 attached
[pid  3457] execve(".git/hooks/pre-commit", [".git/hooks/pre-commit"], [/* 91 vars */]) = 0
strace: Process 3458 attached
[pid  3458] execve("/usr/lib/git-core/git", ["git", "config", "--local", "user.email"], [/* 91 vars */]) = 0
[pid  3458] +++ exited with 1 +++
[pid  3457] --- SIGCHLD {si_signo=SIGCHLD, si_code=CLD_EXITED, si_pid=3458, si_uid=3375, si_status=1, si_utime=0, si_stime=0} ---
[pid  3457] +++ exited with 1 +++
[pid  3456] --- SIGCHLD {si_signo=SIGCHLD, si_code=CLD_EXITED, si_pid=3457, si_uid=3375, si_status=1, si_utime=0, si_stime=0} ---
[pid  3456] +++ exited with 1 +++
```

It turns out that opam is attempting to create an empty commit when creating the repository.

I have a global git templates dir that adds a pre-commit hook into every new repository I create. This hook checks that I have set a sensible email address for the repository and is failing for this new repo.

If I manually run these commands
```
git init
git remote add origin https://github.com/rems-project/opam-repository.git
git commit --allow-empty -m "opam-git-init"
```
I see the pre-commit hook error ouput:
`ERROR: [pre-commit hook] Aborting commit because per-repo user.email is missing.`
It would be nice if opam could print the stderr from git commit or at least print which command failed in --debug output so that I can fix the issue.

Even better, adding `-c init.templatedir=` to the git command will ignore user defined .git templates and makes it work for me: `git -c init.templatedir= init`

The other workaround is to comment the init.templatedir setting every time I use opam but it would be very nice if this could be fixed.

**Comment by rjbou** [comment]
Thanks for reporting!
Actually, there is no perfect configuration opam/git. Using global configuration can avoid having this kind of git lock/fail, but ignoring it can also causes other failures (e.g. proxy setting).
In order to avoid commenting/uncommenting at each opam call, you can use the environment variable [`GIT_TEMPLATE_DIR`](https://git-scm.com/docs/git-init#_template_directory) when using opam, or even set an alias
```alias opam="GIT_TEMPLATE_DIR= opam"```

> To debug this If I look at the strace -e execve output

opam has two mode to give more information to user: verbose (`-vv`) and debug (`-debug`). Debug mode displays opam internal states, while verbose mode displays commands output. In your case, it would be better to use the verbose mode to see git commands and errors. Much easier than `strace` ;)

**Comment by arichardson** [comment]
Hmm indeed it does report the error message it now with -vv. I was certain I tried that yesterday (possibly it was hidden by all the --debug output). Thanks for the alias suggestion!
