### ISSUE TITLE
`opam pin add` fails but `opam pin add -n ...; opam install ...` succeeds

### ISSUE THREAD

**Issue by jberdine** [ocaml/opam#3507]
Should pinning be equivalent to separately pinning and then installing?

I encountered a case where pinning fails but separately pinning and then installing succeeds:
```
$ opam pin add --edit --dev conf-llvm
conf-llvm.6.0.0] synchronised from git+https://github.com/ocaml/opam-repository.git
Press enter to start "/Users/jjb/.local/bin/emacsclient" (this can be customised by setting EDITOR or OPAMEDITOR)...
Waiting for Emacs...
# I edited the version, but don't think that mattered
[WARNING] The opam file didn't pass validation:
  warning 47: Synopsis should start with a capital and not end with a dot
Proceed anyway ('no' will re-edit)? [Y/n] y
You can edit this file again with "opam pin edit conf-llvm", export it with "opam show conf-llvm --raw"
[WARNING] Overlay file of conf-llvm
          /Users/jjb/sat/sledge/_opam/.opam-switch/overlay/conf-llvm/files/configure.sh not found,
          ignoring
conf-llvm is now pinned to git+https://github.com/ocaml/opam-repository.git (version 7.0.0)

The following actions will be performed:
  ∗ install conf-llvm 7.0.0*
Do you want to continue? [Y/n] y

<><> Processing actions <><><><><><><><><><><><><><><><><><><><><><><><><><>  🐫
[ERROR] The compilation of conf-llvm failed at "/Users/jjb/.opam/opam-init/hooks/sandbox.sh build bash
        -ex configure.sh 7.0.0".

#=== ERROR while compiling conf-llvm.7.0.0 ====================================#
# context     2.0.0 | macos/x86_64 |  | pinned(git+https://github.com/ocaml/opam-repository.git#5c74be12)
# path        ~/sat/sledge/_opam/.opam-switch/build/conf-llvm.7.0.0
# command     ~/.opam/opam-init/hooks/sandbox.sh build bash -ex configure.sh 7.0.0
# exit-code   1
# env-file    ~/.opam/log/conf-llvm-97144-d0f245.env
# output-file ~/.opam/log/conf-llvm-97144-d0f245.out
### output ###
# bash: configure.sh: No such file or directory
```
Note that opam reports that the overlay file `configure.sh` is not found, and then compilation fails for that reason.

But pinning separately and then installing works:
```
$ opam pin add conf-llvm --dev-repo --edit --no-action
[conf-llvm.6.0.0] no changes from git+https://github.com/ocaml/opam-repository.git
Press enter to start "/Users/jjb/.local/bin/emacsclient" (this can be customised by setting EDITOR or OPAMEDITOR)...
Waiting for Emacs...
[WARNING] The opam file didn't pass validation:
  warning 47: Synopsis should start with a capital and not end with a dot
    error 53: Mismatching 'extra-files:' field: "configure.sh"
Proceed anyway ('no' will re-edit)? [Y/n] y
You can edit this file again with "opam pin edit conf-llvm", export it with "opam show conf-llvm --raw"
conf-llvm is now pinned to git+https://github.com/ocaml/opam-repository.git (version 7.0.0)
$
$ opam install conf-llvm

<><> Synchronising pinned packages ><><><><><><><><><><><><><><><><><><><><>  🐫
[conf-llvm.7.0.0] no changes from git+https://github.com/ocaml/opam-repository.git

The following actions will be performed:
  ∗ install conf-llvm 7.0.0*

<><> Processing actions <><><><><><><><><><><><><><><><><><><><><><><><><><>  🐫
∗ installed conf-llvm.7.0.0
Done.
$
```
Note that there is still an error reported about `configure.sh` when pinning, but installation succeeds.

Is `opam pin` handling the files in the `files` directory adjacent to the `opam` file in the package repo as expected?

This is with opam 2.0.0~rc4 (actually no, with #3499).

**Comment by rjbou** [comment]
It's problematic, I can't reproduce the missing file problem (tried both with master and the rec PR), but it permits to see some inconsistency on the `conf-llvm` package definition (ping @kit-ty-kate).

As no url is defined on the [opam file](https://github.com/ocaml/opam-repository/blob/2.0.0/packages/conf-llvm/conf-llvm.6.0.0/opam), and it is required to pin  dev repo, opam takes as upstream  `dev-repo` field, which is opam repository (git+https://github.com/ocaml/opam-repository.git). So, when you do the `opam pin --edit -dev conf-llvm`, opam download first the upstream (opam repo), then ask you to edit the file. When you end editing, a lint is performed, which check for defined extra-files. As it is the opam repo which is in the internal dev copy, the files `configure.sh` is not found, raising the `error 53: Mismatching 'extra-files:' field:` error. Then, opam can get the extra-files from different places to prepare the build: global repo definition (`~/.opam/repo/packages/conf-llvm/conf-llvm.6.0.0`), switch packages definition (`~/.opam/myswitch/.oam-switch/packages/conf-llvm.6.0.0`). It then do a copy of extra-files to be able to build / install the package. When you unpin or remove a package, not all copies of basic information packages are deleted, that's why sometimes you can be able to already have the `configure.sh` present. Note that In my reproduce attempt, I tried with my current state & after cleaning everything.

You can see all those internal copy of extra-files with option `--debug` and `-vv`, it's quite over verbose, but sometimes useful to follow some internal mechanism.

If you can reproduce, could you give us the full log  (debug & verbose) of the first command?

**Comment by kit-ty-kate** [comment]
Not sure to understand completely this issue but I just made a PR to at least remove the incorrect dev-repos from opam-repository. Is that sufficient or has `conf-llvm` other flaws?

**Comment by rjbou** [comment]
@kit-ty-kate It was something that I detected while looking into the internal mechanism of this issue, but I don't think `conf-llvm` is the main point of it. Thanks for the fix!

**Comment by jberdine** [comment]
Hmm, ok, I can't repro any more either. Sorry for the noise. I'll close this and reopen if I find a repro. The only thing I can think of is if I had some remnants of a previous attempt to pin lying around my opam dirs somewhere.
