### ISSUE TITLE
Trouble when using Opam local switches

### ISSUE THREAD

**Issue by RogerTarani** [ocaml/opam#3573]
1/ Problem with `$ opam switch` command with local switches

Creating a local switch is working:
```
$ opam switch create ./ ocaml-base-compiler.4.06.1  # from within the targeted project tree
$ ls
_opam
$ opam switch
(normal display of available Opam switches)
```

But now selecting a switch is no more possible with the following command:
`$ opam switch <switch-name>  # e.g. 4.02.3`  

Finally, the following command works:
```
$ eval $(opam env --switch=4.06.1 --set-switch)  # for global switch
$ eval $(opam env --switch=./ --set-switch)  # from within the project tree where there is a local switch
```
But it's not elegant.

Is it normal? 
How to get back to the simple `$ opam switch [name]` command?
How to give a name to a local switch in order to select it like any other switch (and not only when being in project tree)?

2/ Broken switch
When only working with `$ opam switch` and `$ opam pin` commands, I encountered several times the following problem in some switches (local or global):

```
$ ocaml
Fatal error: cannot load shared library dllunix
Reason: /home/test/Documents/project2/_opam/lib/ocaml/stublibs/dllunix.so: undefined symbol: caml_ba_element_size
```
and Ocaml is no more available:
```
$ ocaml
Fatal error: cannot load shared library dllunix
Reason: ~/.opam/4.06.1/lib/ocaml/stublibs/dllunix.so: undefined symbol: caml_ba_element_size
```
What is broken?
What could cause this problem?
How can I repair this broken switch instead of removing and reinstalling it from scratch? ($ opam switch remove project2 && opam switch create ./ <package-or-version> fixes the problem but gives no explanation)
Right now 3 out of my 5 switches are broken that way. So it's a crucial issue for me if I want to keep on using Opam.

```
$ opam config report
# opam config report
# opam-version      2.0.0 
# self-upgrade      no
# system            arch=x86_64 os=linux os-distribution=debian os-version=9.5
# solver            builtin-mccs+glpk
# install-criteria  -removed,-count[version-lag,request],-count[version-lag,changed],-changed
# upgrade-criteria  -removed,-count[version-lag,solution],-new
# jobs              4
# repositories      1 (http) (default repo at eeb7eb22)
# pinned            2 (rsync)
# current-switch    4.02.3
```

**Comment by AltGr** [comment]
Thanks for reporting

1/ The easiest now is to use the automatic shell hooks. Just run `opam init -ni --enable-shell-hook` (or just see the instructions from `opam init`).
This way, you won't ever need to `eval $(opam env)`, and the switch will be selected whenever you are in the appropriate directory. It also guarantees that the shell environment (`PATH`, etc.) match the switch selected by opam.

`opam switch <switch-name>` is still available to select the globally active switch, but that is superseded by any local switch found. Also, it only affects opam, not the environment, and as such doesn't replace running `eval $(opam env)`. What `--set-switch` does is that it sets the `OPAMSWITCH` variable, which overrides switch selection (both from PWD and the globally selected switch), for the current shell. It has been made non-default because of this: it disables automatic switch selection based on PWD in a silent way, that could be confusing. You can use it to select a local switch from outside of its directory, though (e.g. `eval $(opam env --switch ../project1 --set-switch)`). Also see `opam switch link` for a more convenient way to share local switches among projects.

> How to get back to the simple `$ opam switch [name]` command?

The only possible answer is "don't use local switches" :/

> How to give a name to a local switch in order to select it like any other switch (and not only when being in project tree)?

You can refer to a local switch using its `PATH` from anywhere, and select it using `OPAMSWITCH` (or equivalently `opam env --set-switch`). Alternatively, you can define a global switch and link it so that it is used automatically when in your project (modulo either running `eval $(opam env)` or using the shell hooks).

---

2/ I am not sure, but this looks like `CAML_LD_LIBRARY_PATH` is not properly defined.

1. check that you have correctly run `eval $(opam env)` in the expected switch
2. I believe there was  a bug in the `ocaml` package at some point in time which led to such a bug. First make sure that you are using 2.0 repositories (`opam repo`). Then you can check the results of `opam env -v`, and it should include something like:
    ```
    : Updated by package ocaml;
    CAML_LD_LIBRARY_PATH='/home/lg/ocamlpro/learn-ocaml/_opam/lib/ocaml/stublibs:/home/lg/ocamlpro/learn-ocaml/_opam/lib/ocaml'; export CAML_LD_LIBRARY_PATH;
    : Updated by package ocaml;
    CAML_LD_LIBRARY_PATH='/home/lg/ocamlpro/learn-ocaml/_opam/lib/stublibs:/home/lg/ocamlpro/learn-ocaml/_opam/lib/ocaml/stublibs:/home/lg/ocamlpro/learn-ocaml/_opam/lib/ocaml'; export CAML_LD_LIBRARY_PATH;
    ```
   If it doesn't, you are probably hit by this issue. Please check: `opam show ocaml -f setenv:`, which should yield:
    ```
    [CAML_LD_LIBRARY_PATH = "%{_:stubsdir}%"]
    [CAML_LD_LIBRARY_PATH += "%{lib}%/stublibs"]
    [OCAML_TOPLEVEL_PATH = "%{toplevel}%"]
    ```
   If it doesn't, you need to `opam update`. If it does, check `_opam/.opam-switch/environment`. If it doesn't contain the definition, remove it, and run any package (re-)installation to let it be recreated correctly. You may also want to check that the `stubsdir` variable is correctly defined using: `opam var ocaml:stubsdir` (if it isn't, check `_opam/.opam-switch/config/ocaml.config`).

Hope this helps!

**Comment by RogerTarani** [comment]
> > How to get back to the simple `$ opam switch [name]` command?
> 
> The only possible answer is "don't use local switches" :/

Using local switches vs. global switches : 
even if local switches management features are now clearer, I feel like it's better to define a global switch per project, say switch named `4.06.1-project2` for project2 or switch named `4.06.1-project-foo-type` for all projects of type `foo-type`.

Do you see any drawback with managing switches and projects this way? (all the Opam stuff is kept in ~/.opam and not spread in several project trees).

**Comment by RogerTarani** [comment]
I'm still having trouble with several "broken switches" as described before.
How can we identify the cause, fix that and as a priority avoid it in the future?

**FYI : I've not reproduced a broken switch with the following:**
This was more probably caused when playing with `$ eval $(opam env --switch=(DIR |<switch>) --set-switch)`
- - - - - -
I've created new global switches from a directory where there is NOT a local switch, in one command or two:
`$ opam switch create foo.4.06.1 ocaml-base-compiler.4.06.1`

```
$ opam switch create bar.4.06.1 --empty
$ opam install ocaml-base-compiler.4.06.1
```
I've created a global switch when in a directory where there IS a local switch, in one command or two:
`/project2$ opam switch create baz.4.06.1 ocaml-base-compiler.4.06.1`

```
/project2$ opam switch create switch-test --empty
/project2$ opam install ocaml-base-compiler.4.06.1
```
- - - - - -

**Pls.find a few questions:**

1/ When we first use `$ opam switch create switch-test --empty` the compiler description does not appear:
```
$ opam switch create bar.4.06.1 --empty
$ opam install ocaml-base-compiler.4.06.1
$ opam switch list
   bar.4.06.1                                      bar.4.06.1
   foo.4.06.1        ocaml-base-compiler.4.06.1    foo.4.06.1
```
How can we add the compiler description? 
This is a useful information and this would bring consistency in the presentation.
I just found how to create a switch description:
`$ opam switch --description=STRING`

2/ Strange behaviour when selecting system switch:
```
$ opam switch system && opam switch list
#  switch                                                compiler                    description
...
→  system                                                ocaml-system.4.02.3         

$ ocaml --version
The OCaml toplevel, version 4.07.0
```
Ocaml 4.07.0 is selected whereas system is 4.02.3.
This is not blocking because the system compiler is not used, but have you any clue?

**Comment by rjbou** [comment]
> Is it opam 2 repo? (should be)

Yes, the default one is in 2.0 format.

> The 4.06.1 MANPATH and PATH have some 4.02.3 paths inside:

Values here are present twice, opam behavior is to replace one value from it current switch to have the new `PATH`. cf. explanation https://github.com/ocaml/opam/issues/3512#issuecomment-415728048.

> Do you see any drawback with managing switches and projects this way?

No, the only thing is that you just have to change switch when you change project. 

> 1/ When we first use $ opam switch create switch-test --empty the compiler description does not appear

This column shows the locked base of the switch. When you install a compiler after creating an empty switch, it doesn't lock it as the base of the switch.
So you can add the compiler description by locking it:
```
opam switch
       set-base PACKAGES
           Sets the packages forming the immutable base for the selected
           switch, overriding the current setting.
```

> Ocaml 4.07.0 is selected whereas system is 4.02.3.

> Broken 4.07.0 switch

Seems another environment variable setting issue.

**Comment by rjbou** [comment]
What is the status of this issue?

**Comment by RogerTarani** [comment]
I didn't know the cause of the trouble. But all is fine now. 
I don't use opam local switches. And I read 'opam --help' with care.

I just had a problem today that make me struggling quite a long time with opam. In fact it was not caused by opam. But the problem looked like the one that made me open this issue. And it brought us some explanation for that kind of trouble.

After the creation of a new switch, I got the same kind of error message related to ~/.opam/4.07.0/lib/ocaml/stublibs/dllunix.so : 
```
$ ocaml
Fatal error: cannot load shared library dllunix
Reason: ~/.opam/default/lib/ocaml/stublibs/dllunix.so: undefined symbol: caml_sigmask_hook
```
The point is that my '~/.bashrc' was also updated at the same time with the following alias for ocaml:
```
alias ocaml='ledit ocaml'
```
ledit is fine for basic line edition when I quickly use the toplevel. 
Also, ledit was installed via the package manager (apt) and I suspected some evil interaction between the system and the opam repository
The trouble was fixed simply by unaliasing ocaml. Then ledit could trigger its error alone and let ocaml be fine.

I removed ledit from the system via apt and  tried to install it  via opam.
I go a hint with that incompatibility error message (ocaml 4.07.1) :
 ```
$ opam install ledit
The following dependencies couldn't be met:
  - ledit → camlp5 → ocaml < 4.08.1
      base of this switch (use `--unlock-base' to force)
  - ledit → ocaml < 4.06.0
      base of this switch (use `--unlock-base' to force)

No solution found, exiting
```
All this brought us some light on what probably happened with the local switch experiment.

BTW regarding the "shell-hook" (setup with 'opam init --enable-shell-hook' or through interactive setup with 'opam init') :
1- it's fine because shell and opam keep in sync
2- it's disturbing because the switch selected in a shell is immediately propagated in every opened terminal (if there is an ongoing compilation it creates problems because the expected switch suddenly disappears: interface mismatch, etc.)

The need is to avoid to do 'eval $(opam env)' each time a terminal is fired.
Is there a simple way with opam to protect a terminal from that and keep it isolated in its opam switch state?

Also, is there a simple way to get the full status of an opam setup?
For testing if opam shell hook is enabled, I usually do 'set -x' and use an opam command:
```
$ opam switch 
+ opam switch
#  switch          compiler                    description
 →   4.08.1          ocaml-base-compiler.4.08.1  4.08.1
   default         ocaml-base-compiler.4.08.1  default
++ _opam_env_hook
```
Thanks.

**Comment by dra27** [comment]
The `dllunix` error happens when `CAML_LD_LIBRARY_PATH` points to the stub libraries of a different version of the compiler from the one which the program was linked against. Often this "just works" because the stubs don't change, but recent versions have introduced some new ones, so if `CAML_LD_LIBRARY_PATH` ends up pointing to an older directory, then you see this error. It's a problem with OCaml, though, and one we've got a proposal in progress to deal with.

**Comment by RogerTarani** [comment]
Ok. Thanks.
