### ISSUE TITLE
silent failure for variables `{test}` and `{doc}` in dependencies

### ISSUE THREAD

**Issue by c-cube** [ocaml/opam#3580]
Apparently in opam 2.0.0, I'm supposed to use `"alcotest" {with-test}` to specify a test dependency. However, the old syntax `"alcotest" {test}` is silently ignored, even by `opam lint`. I think there should be a warning or even an error in the linter for that?

context: https://github.com/ocaml/opam-repository/pull/12746 where travis failed mysteriously.

**Comment by rjbou** [comment]
I quote my answer from [opam-repository issue](https://github.com/ocaml/opam-repository/issues/12729#issuecomment-427307249):
_The `test` issue is more complicated because of [variables handling](https://opam.ocaml.org/doc/Manual.html#Package-variables). Some variables are opam defined  but user can also defines its own. Plus, as variables can be undefined, and filter expressed according, we can't raise an error if `{test}` is present (while packager meant `{with-test}`), or if the `test` variable is null._

_Note that the opam package upgrader rewrite `test` and `doc` variables into `with-test` and `with-doc`._

**Comment by dra27** [comment]
It doesn’t work in general, but in the interests of ease of use for opam-repository, perhaps Camelus could prohibit user variables called `test` and `doc` and so consider them as a linting failure?

This doesn’t prevent anyone in another repo avoiding this, it’s just an extra “standard” for opam-repository.

**Comment by rjbou** [comment]
I quote here @c-cube answer in https://github.com/ocaml/opam-repository/issues/12729#issuecomment-427392410:
>A warning (in the linter) would still do the trick, right? if someone wants to define `test` nonetheless they would be able to, but for most users using `{test}` is probably a mistake. Also, it's the first time I hear of a package upgrader, which is why I was confused by the same problem.

Indeed, It would be possible, at least the time of opam2 transition for the packagers.

> Also, it's the first time I hear of a package upgrader

When mentioning a package upgrader, it is all the tooling to automatically upgrade opam1.2 files (e.g. in [manual](http://opam.ocaml.org/doc/Upgrade_guide.html#File-formats)). They all uses the same opam1.2 -> opam 2.0 upgrade function, offered by the opam library: package `opam-state`, `OpamFormatUpgrade.opam_file` and `OpamFormatUpgrade.comp_file` for opam1.2 compilers files.

**Comment by c-cube** [comment]
So there's `opam-package-upgrade`, neat. Thank you @rjbou .

**Comment by rjbou** [comment]
Thanks for reporting!
