### ISSUE TITLE
opam install script does not contain earlier checksums

### ISSUE THREAD

**Issue by utdrmac** [ocaml/opam#3643]
The install script, ocaml/opam/master/shell/install.sh, installs 2.0.1 by default. If a user wishes to install 2.0.0 (by changing the variable on line 8), you get a failed checksum error because the install script no longer contains 2.0.0 checksums.

Please add in proper logic and checksums for all GA releases. It might be more scalable if you just added a "checksums.txt" file with each release and had the install script download this file for comparisons, rather than hardcoding checksums into the installer.

**Comment by dra27** [comment]
This would be a good idea for opam 2.1, but I can't see why we would want to encourage the installation of 2.0.0 instead of its bug-fix release 2.0.1? The purpose of this script is to install the latest opam - if you particularly need a specific version, you can refer to a different ref from `master` (e.g. https://raw.githubusercontent.com/ocaml/opam/7385f0/shell/install.sh for 2.0.0)

**Comment by utdrmac** [comment]
@dra27 Right now, the Tezos developers have their env pinned to 2.0.0. If you try to install 2.0.1 it throws and error saying it's expecting 2.0.0. So that's the only reason I can think of at this time for people needing to install 2.0.0. I'll open a bug with them about 2.0.1 support.

**Comment by rjbou** [comment]
Since few releases, they are kept. Thanks!
