### ISSUE TITLE
feature request: instead of hardcoding curl and wget, allow to specify a download-program at configure-time

### ISSUE THREAD

**Issue by hannesm** [ocaml/opam#3735]
curl and wget are atm hardcoded into opam. They are widely deployed. But FreeBSD (or OpenBSD, likely others) distribute a fine download-program with their base system (`fetch` on FreeBSD, `ftp` on OpenBSD). If opam would allow to specify the download command during configuration time (as in `.opam/config`), this would allow us on BSD to use the builtin binary, and not require an external program to be installed via ports.

WDYT? I can try to come up with a PR if you agree that this would be a good idea. Another option may be to detect and use `fetch` / `ftp` on the specific systems.

**Comment by dra27** [comment]
I think it's possible to do this already with `OPAMFETCH` but it'd be good to improve the default on BSDs (it could also allow Windows to use powershell's `Invoke-WebRequest`, with the same benefit for all modern Windows systems of not needing a dependency to be installed).

**Comment by hannesm** [comment]
@dra27 `OPAMFETCH` sounds like an environment variable!? I wouldn't know how to pass this during a port build on FreeBSD. I suggest a configure argument. :)

**Comment by dra27** [comment]
@dbuenzli beat me to it! `wget` is difficult to portably have not follow redirects (and the default `curl` invocation includes `-L`) so it would be good if the docs specified that the command should follow redirects, yes.

**Comment by hannesm** [comment]
@dbuenzli I'm aware of this, and already use it on my computer. What I ask in this issue is to have a configure-time way to specify this. I couldn't find a way to modify `.opam/config` system-wide.

**Comment by dra27** [comment]
Ohhhh, sorry @hannesm - I'd completely misread the feature request.

This can be done now by overridding `src/client/opamInitDefaults.ml`, but at the moment that would have to be done by patching it, but local patches are presumably OK in ports? You want the `dl_tool` function to return `Some [(CString "fetch ..."), None]` in the `None` case so that `.opam/config` always has `download-command` on BSD. You can either use `OpamStd.Sys.os ()` to determine if it's OpenBSD or FreeBSD or just have a different patch, as I assume they use different package repos?

For the feature request itself, as I said initially, I think it would be better to alter the defaults rather than require it to be specified at `configure`-time.

**Comment by rjbou** [comment]
It is possible to add in *BSD package install of an `/etc/opamrc` file containing the `download-command` field, it will be taken into account at opam init or reinit, and then automatically added in the opam config file.
If changing system package is not possible, it can be added in opam code directly in [`OpamInitDefaults`](https://github.com/ocaml/opam/blob/master/src/client/opamInitDefaults.ml#L87), using an os filter.
I'm not a bsd user, are these commands recommended to be used instead of wget/curl? Because by changing this in opam itself would result on imposing these commands from opam, which is different from a package maintainer who configure the package to its distro.

**Comment by rjbou** [comment]
What is the status of this issue?

**Comment by hannesm** [comment]
> are these commands recommended to be used instead of wget/curl?

yes, FreeBSD ships `fetch` in the base system -- used for downloading any ports etc. (and OpenBSD ships ftp). wget and curl are available as additional packages (i.e. are atm a dependency of opam).

both @dra27 and @rjbou point to `OpamInitDefaults` and `dl_tool` / `dl_tools` -- but I fail to understand how this is used inside opam, mainly how are arguments passed? I use at the moment `download-command: ["fetch" url "-o" out]` in my `.opam/config`. if someone can guide me how `dl_tool` and `dl_tools` are invoked / supposed to work (esp. what's the difference between the two, and how are command line arguments added?), I'm happy to work on a PR.

NB: `fetch` follows redirects by default.

I'd appreciate to have this in opam instead of patching the port for opam on Free/OpenBSD.

**Comment by dra27** [comment]
@hannesm - yeah, it's really not well documented ☹️. So, `dl_tools` is the list of tools `opam init` will look for, in order. For FreeBSD, that wants to either just `["fetch"]` (assuming the user cannot remove it?) or `["fetch"; "curl"; "wget"]`. `dl_tool` is used to capture the `OPAMCURL` or `OPAMFETCH` setting during `opam init` and stores the command. I don't think that wants to be updated here (@rjbou?), because the idea is to add specific support to opam for the `fetch` command. I think what wants to change instead is `OpamDownload.download_args` which could have the support for `fetch` added (possibly only available on FreeBSD, or is the tool distributed separately?). Note that the command supports the possibility of variable expansion as well.

**Comment by dra27** [comment]
(sorry, I think that contradicts my previous pointer... `opam` has accidentally a lot in common with `git` these days... so/too many ways to do the same thing!)

**Comment by rjbou** [comment]
There is some naming that are not clear on their purpose: `dl_tools` is the for the required_tools field while `dl_tool` is for the download_command, if specified by user. The last one is specified in the [doc](https://opam.ocaml.org/doc/Manual.html#configfield-download-command).

Needed modifications are: 
- as pointed by @dra27, there is the need to adapt default `OpamRepositoryConfig.(!r.download_tool)` & `OpamDownload.download_args` in order to have `fetch/ftp` in case of `FreeBSD/OpenBSD`.
- also, adding them in the `OpaminitDefaults.required_tools` with a os filter to detect their absence.

I've made most of the changes in [init-fetch branch](https://github.com/rjbou/opam/tree/init-fetch), please complete`fetch` & `ftp` arguments in [`OpamDownload`](https://github.com/rjbou/opam/commit/3d0c2aab62bf8f6d3827fbf60cfa79d5e86510c6#diff-494a4e721d3935caf61abb2f87105785R44), it is  an [`arg list`](https://github.com/ocaml/opam/blob/master/src/format/opamTypes.mli#L314), with no `filter` (`None`),  `CString`  _string_ command option, and `CIdent`  _variable_ to be extrapolated, as defined in [`download_command:`](https://opam.ocaml.org/doc/Manual.html#configfield-download-command) doc. Feel free to adjust (for exe. default settings) and propose a PR.

On default init config, I've only put `fetch/ftp` as required tools, and in `OpamDownload`, I've set `fetch/ftp` as default command, `curl` as fallback. In that case, should we add `curl` in `recommended_tools:`?

**Comment by rjbou** [comment]
Fixed by #3904. Thanks!
