### ISSUE TITLE
Broken link in opam --help

### ISSUE THREAD

**Issue by OriginLabs-Iguernlala** [ocaml/opam#3743]
In section
```
--criteria=CRITERIA
           Specify user preferences for dependency solving for this run.
           Overrides both $OPAMCRITERIA and $OPAMUPGRADECRITERIA. For details
           on the supported language, and the external solvers available, see
           http://opam.ocaml.org/doc/Specifying_Solver_Preferences.html. A
           general guide to using solver preferences can be found at
           http://www.dicosmo.org/Articles/usercriteria.pdf.
```

The link http://opam.ocaml.org/doc/Specifying_Solver_Preferences.html is broken

**Comment by OCamlPro-Iguernlala** [comment]
Moreover, listing the criteria in the doc instead of putting and external link would be really better.

**Comment by AltGr** [comment]
Indeed, the page is now http://opam.ocaml.org/doc/External_solvers.html
The criteria are external to opam and depend on the solver, which explains it wouldn't be very consistent to list them here: e.g. `aspcud` and `mccs` have a slightly different format.

However:
- since we now have a built-in solver, the above argument no longer fully holds
- we could put one or two examples
- or at least document that `opam config report` displays the currently used criteria (or even include the default criteria in the manpage)

Thanks for reporting. We could take the chance to also improve the doc on `--cudf`, which outputs more than is actually documented.

**Comment by rjbou** [comment]
Since 2.0.2, opam manpages have been updated.

**Comment by aantron** [comment]
`opam install --help` still has the broken links in 2.0.3.

**Comment by rjbou** [comment]
This broken link specifically or another one ?

```
$ ./opam-2.0.3-x86_64-linux install --help | grep -C 3 "and the external solvers"
       --criteria=CRITERIA
           Specify user preferences for dependency solving for this run.
           Overrides both $OPAMCRITERIA and $OPAMUPGRADECRITERIA. For details
           on the supported language, and the external solvers available, see
           http://opam.ocaml.org/doc/External_solvers.html. A general guide to
           using solver preferences can be found at
           http://www.dicosmo.org/Articles/usercriteria.pdf.
```

**Comment by aantron** [comment]
My apologies, I was confused about which version of opam was installed. The links work in 2.0.3. Sorry for the noise.
