### ISSUE TITLE
Large switches: opam installs are very slow

### ISSUE THREAD

**Issue by dbuenzli** [ocaml/opam#3772]
Not sure it's worth optimizing anything for those but I thought I'd just mention it in case something evident can be done. Otherwise feel free to close, I think we are looking at a pathological case here.

On large switches (~1000 packages) opam installs/upgrades become unbeareably slow. It seems the install steps are taking ages and I'd blame the "file system check" to be slow (as mentioned before here https://github.com/ocaml/opam/issues/2857). 

This is on macos, with opam 2.0.3

**Comment by dbuenzli** [comment]
In fact it seems an update consisting of 1/3 of the switch (300 recompilation) is taking longer than installing from scratch :-(

**Comment by dbuenzli** [comment]
I guess people are constantly working on making things less slow :-) I don't think it's worth keeping this open.

**Comment by Qix-** [comment]
Even for small installs (maybe 10 packages) the process can take an upwards of 5 minutes. Opam is easily the largest bottleneck when it comes to deployments, testing, etc. Everything else runs almost instantly.

**Comment by kit-ty-kate** [comment]
@Qix- are you using opam 2.1? What are you installing?

**Comment by dra27** [comment]
@Qix- - the issue here is the time spent doing everything _except_ building the packages (the "make all" stage of frama-c takes about 50 seconds on the VM I just tried it on). There's work in #4494 which should improve the original issue, but I'm not sure what you're describing is strictly speaking the same problem.

**Comment by Qix-** [comment]
@dra27 it very well could be - I'm initializing an opam root (via `init`) and whenever I've gone to manually delete the folder before it always takes a long time due to the sheer number of files after all of this gets installed.

I've subscribed to that PR as it looks like it could be the culprit.

Thanks for the response :)
