### ISSUE TITLE
Should opam install --deps-only impose target package constraints?

### ISSUE THREAD

**Issue by maroneze** [ocaml/opam#3846]
I am trying the 4.08+rc1, and I'd like to do a `opam install --deps-only frama-c` to quickly obtain all dependencies. However, the `frama-c` package is marked as incompatible with 4.08 (it was released before 4.08 was out), so opam fails with:

```
The following dependencies couldn't be met:
  - frama-c → ocaml < 4.08.0
      base of this switch (use `--unlock-base' to force)
```

I agree this makes sense most of the time, but since the `frama-c` package will not be installed anyway, it could make sense to emit a warning saying "Unmet dependencies for target package, do you want to continue?" and allow the user to try it anyway.

By the way, `--unlock-base` does not help, it simply downgrades OCaml.

**Comment by rjbou** [comment]
The `deps-only` option installs the set of needed package in order to compile (or install later) the package. It is often used for local install & or switch creation `opam {install|create switch} .`. in order to have the current switch consistent with the package, constraints can't be dropped. In your case, if `frama-c` is incompatible with `ocaml.4.08.0`, you won't be able to compile `frama-c` if it is installed.
In some case, user can need to don't be restrained by constraints, you can use the option `--ignore-constraints-on`.

But you issue led to another one: conflicts are take into account when `deps-only` is used. It shouldn't be the case, as we don't want yet to install the package itself, but have an compliant environment.

**Comment by rjbou** [comment]
You can also change `frama-c` constraints with pin editing it:
`opam pin edit frama-c`.
Thanks for the report!
