### ISSUE TITLE
Improve script output for “opam env”

### ISSUE THREAD

**Issue by elfring** [ocaml/opam#3847]
The command “`opam env`” provides shell code for the exporting of five variables.
I see opportunities to improve it depending on system constraints.
* The shell commands should be concatenated by [the control operator “`&&`”](https://pubs.opengroup.org/onlinepubs/9699919799/utilities/V3_chap02.html#tag_18_09_03 "Description for command lists") (instead of using the semicolon).
* The desired variable values can eventually be set also by [a single call of the command “`export`”](https://pubs.opengroup.org/onlinepubs/9699919799/utilities/V3_chap02.html#export "Set the export attribute for variables.") (if the command length would be within acceptable limits).

**Comment by AltGr** [comment]
I agree this would make it more readable, but the current output was chosen for being simpler to generate, and, above else, compatibility with various shells. It also supports added comments when running with `-v`.

Please see [the generation function](https://github.com/ocaml/opam/blob/7a8c05ad74d7abf69a3f66857fa59bec530b5df5/src/state/opamEnv.ml#L414)

The same code is used to generate the `~/.opam/opam-init/variables.*sh` scripts, which can be more complex when it refers to existing variables (e.g.:  `MANPATH="$MANPATH":'xxx/man'; export MANPATH;`)

**Comment by elfring** [comment]
Can better exception handling and nicer run time characteristics become more relevant for these scripts?

**Comment by AltGr** [comment]
Sure, if there are cases where they can become a bottleneck. I am not aware of cases where setting a variable or running `export` could fail though ?

The main difficulty is testing on all the shells and their variants, and I remember that most changes made to this code ended up triggering issues here and there on the user side... that's why I am wary of making more changes if not strictly required. I otherwise agree with your recommendations :)

**Comment by elfring** [comment]
* Will it matter to replace “`;`” by “`&&`” for program robustness?
* Would you like to try any adjustments out as a compromise?
