### ISSUE TITLE
Determination of the selected OCaml standard library

### ISSUE THREAD

**Issue by elfring** [ocaml/opam#3856]
A well-known library manager supports [a command like “`ocamlfind printconf stdlib`”](http://projects.camlcity.org/projects/dl/findlib-1.8.0/doc/ref-html/r17.html#OCAMLFIND.PRINTCONF "Command description").
I would find it helpful if the software tool “`opam`” can provide the same [information for its switches](https://opam.ocaml.org/doc/Manual.html#Switches "Description for switches").

**Comment by dbuenzli** [comment]
opam is trying to be OCaml agnostic. But you can use:
```
$(opam var --switch $SWITCH bin)/ocamlc -where
```

**Comment by elfring** [comment]
Can it make sense to determine this information without calling the OCaml compiler additionally?

**Comment by dbuenzli** [comment]
What problem are you trying to solve ?

**Comment by elfring** [comment]
I am looking just for an efficient way to determine OCaml standard library by an OPAM command.
Are there any further software design possibilities to consider besides your command example?

**Comment by dbuenzli** [comment]
I don't think so. You can bet on `$(opam var lib)/ocaml` but that won't work for system switches.

**Comment by AltGr** [comment]
With opam 2.0, you can use the variables defined by the `ocaml` package, which is normally installed:
```
opam var ocaml:lib
```

This will always be equal to `$(opam var lib)/ocaml`, though. You can check `opam config list` and `opam config list ocaml` to see what is defined in the variables.

Another solution, to really check where the compiler points to, is to rely on opam's PATH-based resolution:
```
opam exec -- ocamlc -where
```
opam itself has otherwise no direct pointers to the original stdlib for system compilers, it relies on the OCaml compilers for that ; we do define the stubs directories for `CAML_LD_LIBRARY_PATH` and `OCAML_TOPLEVEL_PATH`, though (see the `ocaml:stubsdir` variable), so it would be possible to extend the `ocaml-config` package [here](https://github.com/ocaml/opam-repository/blob/68dbf571992ff279668596cb85913823c0734b4d/packages/ocaml-config/ocaml-config.1/files/gen_ocaml_config.ml.in#L47) to also define an `ocaml:stdlib` variable in the same way.

**Comment by elfring** [comment]
How do you think about the specification “`${OPAM_SWITCH_PREFIX}/ocaml`”?

**Comment by dbuenzli** [comment]
> How do you think about the specification “`${OPAM_SWITCH_PREFIX}/ocaml`”?

This won't work for system switches (or environments that set the `OCAMLLIB` variable). If you want to treat them correctly then `ocamlc -where` is the answer.
