### ISSUE TITLE
Better handling of `opam show` errors

### ISSUE THREAD

**Issue by nilsbecker** [ocaml/opam#3875]
hi, 

i just ran into problems with odoc/odig, and it turned out the cause was that `opam show` does not handle empty `.opam` files gracefully.  this is described here: https://github.com/b0-system/odig/issues/51

the way i got an empty opam file was by calling `dune install` in a small local project of mine which defines one executable, and had an empty opam file in the source directory.

is this a dune problem or an opam problem or is it as intended?

```
# opam config report
# opam-version      2.0.4
# self-upgrade      no
# system            arch=x86_64 os=macos os-distribution=homebrew os-version=10.14.5
# solver            builtin-mccs+glpk
# install-criteria  -removed,-count[version-lag,request],-count[version-lag,changed],-changed
# upgrade-criteria  -removed,-count[version-lag,solution],-new
# jobs              4
# repositories      1 (http) (default repo at 24059019)
# pinned            6 (git)
# current-switch    4.07.1+flambda
```

**Comment by nilsbecker** [comment]
as a side note, `opam list` does not show that installed executable either. (it works and it's located in my current opam switch)

**Comment by dbuenzli** [comment]
> as a side note, `opam list` does not show that installed executable either. (it works and it's located in my current opam switch)

`dune install` likely only install the package in your prefix, it does not register with `opam`. You should rather use `opam pin add .` for that.

**Comment by nilsbecker** [comment]
ah. so do i have to do both? or will `opam pin add .` install the package for me?

**Comment by nilsbecker** [comment]
(the answer is yes -- i tried that out but with other, dune-related problems that are irrelevant here)

**Comment by dbuenzli** [comment]
> i just ran into problems with odoc/odig, and it turned out the cause was that `opam show` does not handle empty `.opam` files gracefully. this is described here: [b0-system/odig#51](https://github.com/b0-system/odig/issues/51)

Just to make things a bit clearer here. `odig` is invoking `opam show` on the raw `opam` files installed in the library directory as [per convention](https://b0-system.github.io/odig/doc/odig/packaging.html#meta) to get metadata for installed packages. 

Since `opam show` does have some overhead (~200ms on opam 2.0.4) it does not do so individually on each `opam` file but on all the files at the same time ([here](https://github.com/b0-system/odig/blob/b9add704519889079dfb633d6ac1f5d1c9840683/src/odig_support.ml#L237-L267)) using the equivalent of:
```
'opam' 'show' '--normalise' '--no-lint' \
'--field=name:,authors:,bug-reports:,depends:,devrepo:,doc:,homepage:,license:,maintainer:,synopsis:,tags:,version:' \
$(LIBDIR)/*/opam
```
 `odig` is robust in case this invocation fails. However if a single of the files has a parse error (e.g. an empty `opam` file) then all the metadata for the others is lost because the tool just exits with 99 and for example:
```
[ERROR] At /private/tmp/opam:2:3:
        Parse error [skipped]

Fatal error:
At /private/tmp/opam:2:3:
Backtrace:
  Raised at file "src/format/opamPp.ml", line 76, characters 45-66
  Called from file "src/format/opamFile.ml", line 874, characters 45-76
  Called from file "src/format/opamFile.ml", line 130, characters 16-33
[...]
```
I think it would be nicer to output the data for opam files that do parse, to report those that do not with an error on stderr and eventually exit with 30 that did happen.

(N.B. in case you wonder why odig doesn't use the `opam` API, it's to avoid tight coupling of the tools -- that is `odig` can work even if `opam` is not there).

**Comment by rjbou** [comment]
Doesn't `--just-file` option #3729 solve this problem?

**Comment by rjbou** [comment]
Not solve, but at least is a solution, as querying using it much faster (no switch loading).

**Comment by dbuenzli** [comment]
Well I can't tell since I don't think `--just-file` made in into a release (it doesn't seem to be in 2.04). 

In any case even with `--just-file` I would batch the query: if your switch has 100 packages and that's 10ms per opam file (e.g. that's approx what an `opam var lib` takes), you already spent a second querying packages individually, I need that to be as fast as possible.

The above behaviour (i.e. report error gracefully for the files that do not parse, report the info for those that do and have a meaningful exit code) *along with* `--just-file` would be perfect.

**Comment by rjbou** [comment]
It can be handful, a better handling of erroneous cases . Note that by default, show internally pin all given packages, in order to infer some fields (var resolution, name, version, etc.), that's why if only on packages fails, listing/printing is not even called. In the other hand, as `--just-file` stateless process the files one by one, it fails at the first error. Not very consistent...

> Well I can't tell since I don't think --just-file made in into a release (it doesn't seem to be in 2.04).

yes, It's planned in next 2.1.0
