### ISSUE TITLE
OPAM does not compile with OCaml 4.08

### ISSUE THREAD

**Issue by Chris00** [ocaml/opam#3961]
See the following [AppVeyor build](https://ci.appveyor.com/project/Chris00/ocaml-appveyor/builds/26821655#L4654).

**Comment by dra27** [comment]
It's not OCaml 4.08 which is the problem, it's that the build is using Dune 2.0. You should be able to workaround it by adding `DUNE_ARGS=--promote-install-files` to the environment when running the opam build commands (or just doing `make DUNE_ARGS=--promote-install-files`).

I started working on a patch, but I'm loath to put too much effort into it at this stage, since I'd prefer it to be that Dune had sufficient support in the generation of the .install file to prevent the need for the post-processing which is being done.

**Comment by Chris00** [comment]
Thanks, that works indeed.

**Comment by XVilka** [comment]
So I guess this one can be closed now?

**Comment by rjbou** [comment]
Indeed, thanks @dra27 !
