### ISSUE TITLE
docker hub images too big

### ISSUE THREAD

**Issue by abate** [ocaml/opam#4027]
hello opam devs.

Not really a bug report, but more a feature wish.

I've created multi arch docker images for opam [3] that are considerably smaller than the one
listed on dockerhub [1] (~40M vs ~1GB) .  You might want to take a look here at the dockerfile [2] 

These are based on ubuntu-core.

Maybe you can take inspiration from those images to reduce the side of your multi arch images ?
I can also help to prepare an MR .

[1]: https://hub.docker.com/r/ocaml/opam2-staging/tags
[2]: https://gitlab.com/abate/easy-tezos/tree/master/docker/opam
[3]: https://hub.docker.com/r/nomadiclabs/opam/tags

**Comment by avsm** [comment]
Hi Pietro, thanks for getting in touch!

"Big" is somewhat in the eye of the beholder here,  think. The ocaml/opam2 CI images size are larger because they amortise multiple compiler versions in one image, which is very useful for some CI (e.g. you can use a single image to opam switch to multiple compiler versions for dune workspaces in a single build -- see an example in [ocaml-yaml's CI](https://github.com/avsm/ocaml-yaml/blob/master/.azure-pipelines.sh#L119)). 

The next iteration of the opam images drop this feature and are just straightforward single-installations of the compiler: they are staged in [ocurrent/opam](https://hub.docker.com/r/ocurrent/opam) but will be moving to the ocaml/ org on the Hub shortly.

There are smaller images generated in the existing infrastructure with just opam (see [this for example](https://hub.docker.com/layers/ocaml/opam2-staging/alpine-3.9-opam-linux-amd64/images/sha256-dd58b0c43219d00768eee5e87ceefa72f6c6013bbc5babefb4a9d58a96751a0a)) but they also include the build environment needed to make opam useful.  Is there a reason your images just have the `opam` binary but no build tools?  That would just lead to the CI installing those packages every time, which seems to defeat the point of having an image in the first place (to cache repeated computation).

Happy to try and merge features to satisfy your usecase for Tezos in these images -- any details on subsequent builds you do from your base images would be great.

**Comment by talex5** [comment]
Looking at the layer breakdown on hub, the sizes are roughly:

- 40 MB for opam itself (as in your image)
- 135 MB to install `build-essential curl git rsync sudo unzip nano libcap-dev libx11-dev`
- 75 MB for opam-repository
- 877 MB for the OCaml compilers

As @avsm says, the `ocurrent/opam` images are smaller, because they only include one copy of the compiler, and there are also versions without any compiler.

I would have thought we could lose the `libx11-dev` package though, at least. This is probably left-over from the days when OCaml included `Graphics`.

**Comment by abate** [comment]
thank you for feedback. 

I'll try the images in `ocurrent/opam` . Since we use opam as the step stone of our build toolchain, having a bare-bone opam images is handy . 

Adding these type of images in you CI pipeline would boil-down to add another stage to the Dockerfile and the copy of the opam binary.  

Our images are alpine based, but I'm also experimenting with debian and ubuntu-core base images for multi-arch builds. 

I understand you use these images for your CI, so you also need the rest. The smaller, the better :D

**Comment by avsm** [comment]
I see no problem with publishing an alpine opam-only image at the head of our build stage.  One thing to note is that (for CI) we try to compile opam on the actual OS we are testing, instead of using a statically linked alpine image that is re-used.  The reason for this is so that we test the actual OS that users will install on (which is obviously most often not musl-based and has different glibc versions and so on).

**Comment by abate** [comment]
For alpine, this might be a non issue as I've noticed you updated the alpine package. I haven't looked at it in quite a long time. Maybe it's time to have a fresh look at our tool-chain and use directly the alpine package.

**Comment by avsm** [comment]
The only issue with using the Alpine package directly is that you'll be pinned to that OCaml version. How often does Tezos bump the OCaml version required, and do you support a range of them?

**Comment by abate** [comment]
very rarely, we are using 4.07.1 at the moment, I I think we'll move to 4.08 sometimes next year. But since we create a new clean switch with all the dependencies from our own repository, this should not be an issue opam-wise that we use just to create the environment. I'm just in the process of upgrading from alpine 3.9 to 3.10
