### ISSUE TITLE
`opam install ...` invoke gringo which fills up RAM

### ISSUE THREAD

**Issue by firmart** [ocaml/opam#4077]
I first installed `opam` (without PPA) in Ubuntu

`apt install opam`

which has installed the version `2.0.3` of `opam`.

Then, I wanted to install `coq`, so I ran the following command as indicated in [Coq's documentation](https://coq.inria.fr/opam-using.html):
    
`opam install opam-depext`

However, at this step `gringo`, which I ignore what is used for, filled up my memory. 

![gringo](https://user-images.githubusercontent.com/20540328/73360170-a6df2b00-42a2-11ea-88f1-8beefd275694.png)

I tried to `opam install` other package, such as `z3`, etc. The issue still happens.  
I'll try the newest version of `opam` and come back.

`opam config report`

    # opam config report
    # opam-version      2.0.3 
    # self-upgrade      no
    # system            arch=x86_64 os=linux os-distribution=ubuntu os-version=19.04
    # solver            aspcud
    # install-criteria  -count(removed),-sum(request,version-lag),-count(down),-sum(solution,version-lag),-count(changed)
    # upgrade-criteria  -count(down),-count(removed),-sum(solution,version-lag),-count(new)
    # jobs              3
    # repositories      1 (http) (default repo at 203e326c)
    # pinned            0
    # current-switch    default

`gringo version 5.2.2` :
    
    Address model: 64-bit
    
    libgringo version 5.2.2
    Configuration: with Python 3.7.1, with Lua 5.3.3
    License: The MIT License <https://opensource.org/licenses/MIT>

`aspcud --version`

    aspcud version 1.9.4
    
    License: The MIT License <https://opensource.org/licenses/MIT>

**Comment by firmart** [comment]
Install `opam` with version `2.0.6` from source solve the problem.

**Comment by rjbou** [comment]
Thanks for the report!

Since opam 2.0, aspcud is no more used as an external solver, unless specified. It is replaced with a builtin mccs+glpk. There was some packaging complication on [debian](https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=908203), but they are fixed since opam_2.0.5-1, that is available on ubuntu since [eoan](https://packages.ubuntu.com/eoan/opam) (and then no more requires aspcud).

> However, at this step gringo, which I ignore what is used for, filled up my memory.

gringo is a dependency of aspcud.

**Comment by hartmut27** [comment]
instead of ubuntu's apt version of opam i am using the current version from `opam.ocaml.org` and the problem of `opam install xyz` hangs is gone

**Comment by sourcefrog** [comment]
> Thanks for the report!
> 
> Since opam 2.0, aspcud is no more used as an external solver, unless specified. It is replaced with a builtin mccs+glpk. There was some packaging complication on [debian](https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=908203), but they are fixed since opam_2.0.5-1, that is available on ubuntu since [eoan](https://packages.ubuntu.com/eoan/opam) (and then no more requires aspcud).
> 
> > However, at this step gringo, which I ignore what is used for, filled up my memory.
> 
> gringo is a dependency of aspcud.

It looks like Opam is pretty much broken on Debian Buster at the moment? (I just tried to install and ran into this fairly confusing situation of it just hanging.) Could you think about adding a temporary warning to https://opam.ocaml.org/doc/Install.html#Debian?

**Comment by rjbou** [comment]
Yes, there is a debian bug report, cf. discussion https://github.com/ocaml/opam/issues/3827#issuecomment-587321478.
Until it is resolved, we can add a warning / usability hint. Thanks!

**Comment by makeworld-the-better-one** [comment]
I also experienced this issue on Debian Buster. My solution was just to [install the binary directly](https://opam.ocaml.org/doc/Install.html) instead of from Debian. I deleted my `.opam` folder first, because there was a bunch of crud in it from trying to install stuff before, and after installing opam, I also needed to install the `bubblewrap` package from the Debian repositories.
