### ISSUE TITLE
`opam env` adds . to PATH in fish shell

### ISSUE THREAD

**Issue by bbc2** [ocaml/opam#4078]
When I execute `eval (opam env)`, I end up with `.` in my `PATH`.

I think the problem is caused by an extra colon in the output of `opam env`:

```
set -gx PATH ':/home/bertrand/.opam/4.07.1/bin' '/usr/local/sbin' '/usr/local/bin' '/usr/bin' '/usr/bin/site_perl' '/usr/bin/vendor_perl' '/usr/bin/core_perl';
```

It results in:

```
> echo $PATH
. /home/bertrand/.opam/4.07.1/bin /usr/local/sbin /usr/local/bin /usr/bin /usr/bin/site_perl /usr/bin/vendor_perl /usr/bin/core_perl
```

## opam config report

```
# opam config report
# opam-version      2.0.6 
# self-upgrade      no
# system            arch=x86_64 os=linux os-distribution=arch os-version=unknown
# solver            builtin-mccs+glpk
# install-criteria  -removed,-count[version-lag,request],-count[version-lag,changed],-changed
# upgrade-criteria  -removed,-count[version-lag,solution],-new
# jobs              7
# repositories      1 (http), 1 (version-controlled) (default repo at 203e326c)
# pinned            1 (git), 1 (rsync)
# current-switch    4.07.1
```

**Comment by rjbou** [comment]
It comes from #3878: for `MANPATH` that leading ':' is needed (#3878). Seems that should be restrained only to `MANPATH`, and not added for `PATH` & `CDPATH` as they are completely redefined.

**Comment by rjbou** [comment]
Thanks for the report!

**Comment by undu** [comment]
I've encountered this issue since I prefer per-session switches so I though sharing my workaround to whoever finds this thread.

I use a function to wrap switch activation (in `$XDG_CONFIG_HOME/fish/functions/oswitch.fish`):
```
function oswitch
    if test (count $argv) -lt 1
        echo "oswitch: expected a least an arg, got none"
        echo "Usage: oswitch <switch>"
        return -1
    end
    set switch "$argv[1]"
    if opam switch set --dry-run "$switch" 2> /dev/null > /dev/null
        eval (opam env --switch="$switch" --set-switch)
        # opam adds . to PATH, delete it if it's present
        if set -l i (contains -i -- '.' $PATH)
                set -e PATH[$i]
        end
    else
        # show output
        opam switch set --dry-run "$switch"
    end
end
```

The recommended way to add paths to fish is to append paths to $fish_user_paths instead of directly setting the $PATH, but I don't know how well that meshes with cross-shell handling in opam. Adding a path would be usually done with `contains $path $fish_user_paths; or set -a fish_user_paths $path`
