### ISSUE TITLE
opam repo add gives errors for file target where it should not

### ISSUE THREAD

**Issue by MSoegtropIMC** [ocaml/opam#4085]
This is tested with opam 2.0.5.

When I add a local repo to some switch as follows:
```
opam repo --this-switch add devel file:$HOME/Opam/devrepo
```
this works fine. But when I later add the same repo to a different switch I get the error message:
``` 
[ERROR] Repository devel is already set up and points to file:///Users/<me>/Opam/devrepo. To change that, use
        'opam repository set-url'.
```
This is not in line with the fact that I can add a git based repo to as many switches I want with e.g.:
```
opam repo add coq-released https://coq.inria.fr/opam/released
```
Also if I leave away the file url, it works fine:
```
opam repo --this-switch add devel
```
So I would say the behaviour is unexpected since adding the repo with explicitly giving an URL is a legitimate operation and also this is inconsistent between file:// and https://.

**Comment by rjbou** [comment]
The problem here is the url itself, and the error message. As you use the `$HOME` variable directly, the given url is `file:/home/<you>/Opam/devrepo`, and this url is parsed as an ssh one. So, as opam detects an url replacement, error as expected. Use `file://$HOME/...` instead.
You can find [here](https://opam.ocaml.org/doc/Manual.html#URLs) available url format (it's quite like git).

It can be helpful to add in the error message the parsed url, it'll help to understand the fail.
