### ISSUE TITLE
opam init failed (parallel build?)

### ISSUE THREAD

**Issue by morrocoya** [ocaml/opam#4112]
I am unable to finish opam installation on mac OS (4 core, I5).
`opam init` fails while building ocaml-base-compiler, apparently in relation with parallel building. `opam init --jobs=1` gives similar outcome.

```
#=== ERROR while compiling ocaml-base-compiler.4.10.0 =========================#
# context     2.0.6 | macos/x86_64 |  | https://opam.ocaml.org#f16912c3
# path        ~/.opam/default/.opam-switch/build/ocaml-base-compiler.4.10.0
# command     ~/.opam/opam-init/hooks/sandbox.sh build ./configure --prefix=/Users/aponte/.opam/default -C CC=cc ASPP=cc -c
# exit-code   1
# env-file    /var/folders/_z/gr_lx9n153vfqj45h36l25hw0000gp/T/opam-aponte-20461/ocaml-base-compiler-20461-736596.env
# output-file /var/folders/_z/gr_lx9n153vfqj45h36l25hw0000gp/T/opam-aponte-20461/ocaml-base-compiler-20461-736596.out
### output ###
# [...]
# checking sys/shm.h usability... yes
# checking sys/shm.h presence... yes
# checking for sys/shm.h... yes
# checking for dirent.h... yes
# checking for sys/select.h... yes
# checking for off_t... yes
# checking size of int... 0
# checking size of long... 0
# checking size of long *... 0
# checking size of short... 0
# checking size of long long... 0
# configure: error: Neither 32 nor 64 bits architecture.



<><> Error report <><><><><><><><><><><><><><><><><><><><><><><><><><><><><>  🐫 
┌─ The following actions failed
│ λ build ocaml-base-compiler 4.10.0
└─ 
<><> ocaml-base-compiler.4.10.0 troubleshooting <><><><><><><><><><><><><><>  🐫 
=> A failure in the middle of the build may be caused by build parallelism
      (enabled by default).
      Please file a bug report at https://github.com/ocaml/ocaml/issues
```

edit rjbou: formatting

**Comment by rjbou** [comment]
It is more an ocaml configure error of your system detection
```
# checking size of int... 0
# checking size of long... 0
# checking size of long *... 0
# checking size of short... 0
# checking size of long long... 0
# configure: error: Neither 32 nor 64 bits architecture.
```

**Comment by rjbou** [comment]
Any news on this one ?

**Comment by morrocoya** [comment]
Yes. The problem came after migrating data from an older computer and upgrading to OS Catalina. I suspect some spurious files (Homebrew related) remained after migration. I cleaned up and re installed brew and after everything went fine. I would have thought about this before posting an issue! Thanks

**Comment by rjbou** [comment]
Good to hear, thanks for the feedback

**Comment by SDSL-6864** [comment]
Hi everyone, I have the same issue with ocaml-base-compiler 4.13.1. I'm using an Ubuntu virtual machine on my windows PC.
I'm super new to this and have not been able to solve this for hours... Could anyone tell me what I should do? From the instructions above I did not get very far... Thanks in advance!

<><> Error report <><><><><><><><><><><><><><><><><><><><><><><><><><><><><><><>
┌─ The following actions failed
│ λ build ocaml-base-compiler 4.13.1
└─
┌─ The following changes have been performed (the rest was aborted)
│ ∗ install base-bigarray         base
│ ∗ install base-threads          base
│ ∗ install base-unix             base
│ ∗ install ocaml-options-vanilla 1
└─

<><> ocaml-base-compiler.4.13.1 troubleshooting <><><><><><><><><><><><><><><><>
=> A failure in the middle of the build may be caused by build parallelism
      (enabled by default).
      Please file a bug report at https://github.com/ocaml/opam-repository/issues
=> You can try installing again including --jobs=1
      to force a sequential build instead.
# Run eval $(opam env --switch=4.13.1) to update the current shell environment
Switch initialisation failed: clean up? ('n' will leave the switch partially installed) [Y/n] y

**Comment by kit-ty-kate** [comment]
@SDSL-6864 The error message says you don’t have GNU-Make on your system. Installing it will fix your issue.
Tools such as GNU Make and a C compiler are checked during `opam init` but you might have understandably missed the warning.

I’ve opened a PR to help make the error message you encountered more readable: https://github.com/ocaml/opam/pull/4971

**Comment by SDSL-6864** [comment]
@kit-ty-kate that did solve the problem, thank you so very much for your help! And I'm sorry I pasted it as a picture, I tried to do it in the way people normally do but didn't know how to :(
