### ISSUE TITLE
[Feature] with-dev to install packages required only while developing

### ISSUE THREAD

**Issue by dannywillems** [ocaml/opam#4175]
The options `with-test` and `with-doc` have been good changes in opam, adding the features often available in the package managers of other languages.
AFAIK, it is not possible to add a filter in the opam file to install dev tools, like ocamlformat/ocp-indent and utop.
In the Python ecosystem for instance, the option of dev packages is available, mixing docs, tests and local development tools (like a linter or an improved repl).

I would suggest to add a new filter in the opam file, called `with-dev` (or another name, because it might be confusing with the dev version) which would allow to specify dev-only packages, and it can be installed using `opam install . -y --with-dev`.

**Comment by Khady** [comment]
Are you aware of the {dev} annotation that you can put on deps? Deps marked with it are only installed during a pin or local installation

**Comment by avsm** [comment]
That's right; `{dev}` will just work on any pinned or local package; please see: https://opam.ocaml.org/doc/Manual.html#pkgvar-dev for the documentation.

Blog posts or manual PRs explaining the use of this are most welcome, as it's not obvious how to find it from `opam install --help` (as there no need for a CLI option for this, since it's inferred from the package source fetch method).

**Comment by dannywillems** [comment]
Won't the packages marked with `dev` be installed if another package use pin-depends? Imagine a package A, unpublished for some reasons, having a dev dependency on utop, and a package B using pin-depends with A.
When you pin a version, even a dev, you don't want to install the developer dependencies.

**Comment by rjbou** [comment]
The `dev` is true when a package is [not built from a archive](https://opam.ocaml.org/doc/Manual.html#pkgvar-dev), usually it is when the package is pinned (not archive or version pin), but also if the opam repository package contains a vcs url (it is permitted by opam, but forbidden in the main opam repository).
When you version pin you package A, `dev` dependencies won't be installed, because the version pin results to an archive build. But if you pin the package B, and its pin-depends are vcs urls, then your package A dev dependencies will be installed.

**Comment by dannywillems** [comment]
`But if you pin the package B, and its pin-depends are vcs urls, then your package A dev dependencies will be installed.`: that's not what we would expect I think?

**Comment by rjbou** [comment]
On the opam side, it is expected, as `dev` is defined as _package installed not from an archive_, which is not the same than your proposed `with-dev`, which is development tool dependency, without taking into account the way the package is installed.

**Comment by Khady** [comment]
This issue is another example of why a with-dev annotation or a different behavior of dev would make sense https://github.com/ocaml/ocaml-lsp/pull/171

Usually on a given project if I use ocamlformat and add it to the opam file, I will specify the exact version I want. But if someone wants to pin the project and has different version of ocamlformat installed, there will be a conflict.

**Comment by dannywillems** [comment]
I suppose it is now added in OPAM 2.2.0 :partying_face: https://opam.ocaml.org/blog/opam-2-2-0/
