### ISSUE TITLE
opam init/switch create with patch to base compiler

### ISSUE THREAD

**Issue by vsiles** [ocaml/opam#4210]
I'm currently blocked by https://github.com/ocaml/ocaml/issues/8648 : I need to pass some custom flags to ocaml-base-compiler.4.07.1 (some `-I` and some `-L` to correctly point to our 
 custom libc), and ideally I'd like to still be able to use `opam init` and `opam switch create`.

Is there a way to apply a patch to the base compiler of a switch using opam ?

**Comment by AltGr** [comment]
Since opam 2.0, compilers are normal packages, so you can use `opam pin ocaml-base-compiler 4.07.1 --edit`
Of course, you will need a switch, so you will want to start with `opam switch create <name> --empty` ;
and to setup the compiler afterwards, it's a good idea to run `opam switch set-base ocaml-base-compiler`.

**Comment by vsiles** [comment]
Thank you very much, I'll try to make it work with all that

**Comment by vsiles** [comment]
@AltGr What I'd like to patch is some `configure` file (to be able to pass in custom `CFLAGS` and `LDFLAGS`). `--edit` opens an editor to patch the .opam file. What would be the way to apply a patch/diff before the compilation takes place ?

**Comment by AltGr** [comment]
You can define patches in the `opam` file, but in your case, if specifying options to `./configure` is not enough, it will probably be much easier to clone the "ocaml" repository, patch there, commit and pin to that:
```bash
cd ~/src
opam source ocaml.4.07.1
cd ocaml.4.07.1
(do your edits)
opam pin ocaml-base-compiler.4.07.1 .
```

**Comment by vsiles** [comment]
Using `opam source ocaml.4.07.1`, I only get the opam file, so I don't know how to apply a .patch to the source repo. Maybe there's a way to bake that in the opam file ?
At the moment I use `opam source ocaml-base-compiler.4.07.1` to get the full source and do a `patch` on that. Improvement suggestions appreciated :D I'll post the full script once I'm sure it is working as expected.

**Comment by vsiles** [comment]
Ok, so overall my solution is the following:
```
# MINI_REPO_DIR is a local opam repo we keep versionned
# OCAML_PATCH is the .patch file I need to apply

opam init --disable-sandboxing --reinit offline_clone "$MINI_REPO_DIR" --no-setup --bare
opam switch create "$SWITCH_NAME" --empty
pushd "$OPAMROOT/repo/offline_clone" || exit 1
mkdir -p base-compiler-source
cd base-compiler-source
opam source "$OCAML_COMPILER_NAME" # ocaml-base-compiler.4.07.1 or ocaml-variants.4.07.1+fp
cd "$OCAML_COMPILER_NAME"
patchname="$OCAML_COMPILER_NAME.patch"
cp "$OCAML_PATCH" "$patchname"
patch < "$patchname"
opam pin "$OCAML_COMPILER_NAME" .
popd  || exit 1
opam switch set-base "$OCAML_BASE_NAME" # ocaml-base-compiler or ocaml-variants
# resume normal script using opam switch & opam install
```

Feel free to comment on it :D I'll close the task in a few days.

**Comment by AltGr** [comment]
Ah right, my bad, it's `ocaml-base-compiler` that you need to source, `ocaml` is just a wrapper. Glad you found a working solution :)
If you already have a patch file, you could use it directly without applying manually, through the `opam pin --edit` solution above, with the [`patches:`](http://opam.ocaml.org/doc/Manual.html#opamfield-patches) field. You'll need `extra-sources:` as well to retrieve it since it's not already in the source:
```
extra-source "mypatch.patch" { src: "file:///DIR/patch" }
patches: "mypatch.patch"
```

Last solution, which is how it's done for released compilers: clone `opam-repository`, setup a directory `packages/ocaml-variants/ocaml-variants.4.07.1+mypatch/`, put your opam file there (copy the one from another variant), copy your patch in a subdirectory `files/`, e.g. `files/mypatch.patch`, and make sure to have `patches: "mypatch.patch"` in the opam file. Don't forget to `git add` and commit.

Then, you can use your repository mirror on a given switch using `opam repo add myrepo DIR`, or even file a pull-request for the inclusion of your variant.
