### ISSUE TITLE
Release versioning in homebrew

### ISSUE THREAD

**Issue by hcarty** [ocaml/opam#4225]
It would be useful to keep previous versions around in homebrew so that users can pin to specific opam versions via `brew`.  I'm not sure if this is the right place to report this - if not, I'm happy to take this to wherever is appropriate.

**Comment by hcarty** [comment]
@pjhampton and I are willing to help with the homebrew packaging maintenance if that would help!

**Comment by avsm** [comment]
We don't maintain the Homebrew packages directly from here; it's more of a free for all there. So feel free to submit PRs upstream directly -- and of course, we're happy to help here if something specific comes up.   Your suggestion of having all the opam versions available sounds very useful indeed.

If its helpful, we have a tap here that is largely unused since the release of opam 2.0: https://github.com/ocaml/homebrew-ocaml. Can give you access to that to put your packages if upstream doesn't want it for some reason.

**Comment by rjbou** [comment]
Closing this one, feel free to reopen it if need be. Thanks!

**Comment by hcarty** [comment]
Thank you @avsm and @rjbou
