### ISSUE TITLE
[opam 2.1~alpha] Debian virtual packages are not taken into account

### ISSUE THREAD

**Issue by kit-ty-kate** [ocaml/opam#4251]
Currently the `conf-gsl.1` package in `opam-repository has the following depext on debian:
```
["libgsl0-dev"] {os-family = "debian"}
```
The package used to install fine with opam 2.0.
However with opam 2.1 (master), the package won't install:
```
[ERROR] Package conf-gsl depends on the unavailable system package 'libgsl0-dev'. You can use `--no-depexts' to attempt installation anyway.
```
This is because `libgsl0-dev` is a virtual package (see https://www.debian.org/doc/debian-policy/ch-relationships.html#s-virtual for more informations about virtual packages) so given that opam tries to figure out which external packages are available and uses `apt-cache search .*` which does not really deal with virtual packages all that well (i.e. does not display them, but will give their respective "normal" package on demand), this fails.

One possible fix would be to use `apt-cache depends --no-pre-depends --no-depends --no-recommends --no-suggests --no-conflicts --no-breaks --no-replaces --no-enhances ".*"` instead of `apt-cache search --names-only ".*"`. It prints almost the same list of packages but the former also gives all the virtual packages (but between brackets).

**Comment by rjbou** [comment]
On depext integration, debian virtual packages handling has been [disabled](https://github.com/rjbou/opam/blob/depext/src/state/opamSysInteract.ml#L170) because it takes ~25s (from memory) to retrieve all information, and it was not conceivable to have such a long time on switch loading. 
Using the command proposed command, it gives the information if a virtual package is available, but not if it is installed. For that we need to retrieve the corresponding package for each virtual package. It is is what was done in the depext plugin, for each not found package, check if is it virtual and check its install status. 
I've made some test, by retrieving the information only for found virtual package. In depext it was for all not found packages. It  takes: 
* `0.175s` on master (`apt-cache search` command)
* `0.416s` with the `apt-cache depends` command, without virtual package resolving
* `1.863s` with the virtual package resolving (a call to `apt-cache search` for each virtual package then one `dpkg` query).

Obviously, virtual packages resolving is more accurate. Results on my debian, my current switch, I have for system packages:
* 75 installed, 216 available, 46 not found on master
* 77 installed, 229 available, 31 not found with virtual packages resolving

Two second is more conceivable than 25s, but still too slow. We have to find a less slow way to resolve virtual packages.

**Comment by rjbou** [comment]
Other implementation details/tests on the PR https://github.com/ocaml/opam/pull/4268#issue-447065660

**Comment by rjbou** [comment]
Merged!
