### ISSUE TITLE
opam list --silent should be --check

### ISSUE THREAD

**Issue by dra27** [ocaml/opam#4323]
For better or worse, the option added in #3533 should more consistently have been `--check` (display nothing, communicate in exit code only). This can be renamed for 2.1 using CLI versioning.

**Comment by rjbou** [comment]
It should be `--check-[package-existence]`, because `opam list` isn't supposed to check things, it can be not obvious what is checked.

**Comment by AltGr** [comment]
Just to add some inputs, this is from the `grep` manpage:
```
       -q, --quiet, --silent
              Quiet; do not write anything to standard output.  Exit immediately with zero status if any match is found, even if an error was detected.  Also see the -s or --no-messages option.
       -c, --count
              Suppress normal output; instead print a count of matching lines for each input file.  With the -v, --invert-match option (see below), count non-matching lines.
```

**Comment by kit-ty-kate** [comment]
I think `--silent` is an ok name and i agree with @AltGr it matches up with `grep`.
In my opinion, `--check` would not be a good name because if I were just to read the command (e.g. `opam list --check --installable --depends-on pkg`) I would instinctively think the `--check` command is just there to do extra checks or something, not that it would not write anything to stdout.

Personally I would be in favour to close this issue.

**Comment by dra27** [comment]
I don't recall if this arose from a discussion, or just from the complete review of the CLI options added since 2.0 which I did when adding CLI versioning, but closing this doesn't resolve the inconsistency between `opam {update,install,env} --check` with `opam list --check` inexplicably called `opam list --silent`... for comparing other CLIs, cf. `*sum --check`, but the concern was having two names in different parts of the CLI for the same function.
