### ISSUE TITLE
`.opam-switch/environment` file format is ambiguous and can lead to errors

### ISSUE THREAD

**Issue by lefessan** [ocaml/opam#4325]
Currently, the `.opam-switch/environment` file is wrongly parsed by `opam` when the value of a variable is empty:

If my file is 
```
CPP     =               Updated\ by\ package\ ocaml-base-compiler
```
`CPP` will wrongly be set to `Updated by package ocaml-base-compiler`. This will prevent creating another switch after `eval $(opam env)` because ocaml will fail to compile with a wrong CPP var.

An immediate fix should be to stop writing these "Updated by package $name" comments. A long-term fix should be to use a more standard format.

**Comment by dra27** [comment]
Which version of opam?

**Comment by dra27** [comment]
This rang a bell, and some digging reveals that I hit this years ago and fixed it in https://github.com/dra27/opam/commit/246b518fdf79f4c7dd76e475fd45e553195a43db, however that commit seems to have got lost in my myriad rebasing during the opam 2.0 cycle. My solution in that was to encode `""` as `@` and `"@"` as `\@`. The lexer was updated to recognise the single token `@` as meaning `""` - no handling is needed for `\@` since that's dealt with automatically by the line lexer already.

**Comment by dra27** [comment]
I agree that the format could be changed; the comment is useful though.
