### ISSUE TITLE
Attempting to install an unreleased package

### ISSUE THREAD

**Issue by CraigFe** [ocaml/opam#4344]
Given the following set of Opam files in a local directory:

```markdown
# dependency.opam
opam-version: "2.0"
version: "0.1.0"

# unreleased.opam
opam-version: "2.0"
depends: [ "dependency" {= version} ]
```

Attempting to run a local install will fail:

```
❭ opam install --deps-only ./
The following dependencies couldn't be met:
  - unreleased → dependency < 0.1.0
      no matching version

No solution found, exiting
```

Pinning both packages to a common version such as `dev` fixes the problem (unfortunately, I don't think it's possible to do that in a single `opam` invocation). My questions are:

 - should it be possible to install a local `.opam` file without that file needing to be released in the repository? This is an issue when a new package has recently been added to a monorepo, but no release cycle has occurred yet. Perhaps `opam` should automatically pin such packages to `dev` when it encounters them?

- regardless, the error message for this install is a bit opaque. Could it be improved to something like "No version of `unreleased` is available to install"?

CC: @pascutto

**Comment by AltGr** [comment]
There is no problem with installing an unreleased package; let's first look at your error:
here, you specified in `unreleased.opam` a dependency to `dependency` at the same version, but without specifying the version of `unreleased` itself. Without any specific information to guess the version from, opam silently assumed version `~dev`, so the constraint was resolved to `"dependency" {= "~dev"}`. The version constraint appearing in the error message is unfortunately slightly different (hence the confusion) due to intermediate rewritings, but basically equivalent.

> Pinning both packages to a common version such as dev fixes the problem (unfortunately, I don't think it's possible to do that in a single opam invocation)

`opam pin --with-version` has just been added in #4301 for that purpose :)

> should it be possible to install a local .opam file without that file needing to be released in the repository? This is an issue when a new package has recently been added to a monorepo, but no release cycle has occurred yet. Perhaps opam should automatically pin such packages to dev when it encounters them?

It sure is: just use `opam pin <file>`; you can also use `opam pin --edit` to interactively edit the opam file.

**Comment by CraigFe** [comment]
> `opam pin --with-version` has just been added in #4301 for that purpose :)

Neat, thanks!

> Without any specific information to guess the version from, opam silently assumed version `~dev`, so the constraint was resolved to `"dependency" {= "~dev"}`.

> It sure is: just use opam pin <file>; you can also use opam pin --edit to interactively edit the opam file.

Indeed; I suppose my point was that if Opam is going to assume a version for unreleased / unpinned packages then it might make sense for it to also prompt me to pin at that version. I'm happy either way, since `pin --with-version` makes manually pinning much more convenient now than it used to be  :slightly_smiling_face:

> The version constraint appearing in the error message is unfortunately slightly different (hence the confusion) due to intermediate rewritings, but basically equivalent.

Do you think it's possible to alter the error message here so that the user is more aware of this intermediate step?

**Comment by AltGr** [comment]
Messages have improved and are still being worked on; the options to set the pinning version have been added so I think this can be closed. Thanks for reporting!
