### ISSUE TITLE
[opam-2.1~beta4] Automatically add OPAMCLI=2.0 when package has opam-version: "2.0"

### ISSUE THREAD

**Issue by kit-ty-kate** [ocaml/opam#4491]
Just an idea. This might be a blocker for beta4.
Idea brought up in https://github.com/ocaml/opam-repository/pull/17927#issuecomment-755055186

**Comment by dra27** [comment]
I think it's a good idea too, although we should do it _always_.

With the benefit of hindsight, the `opam-version` field is misnamed and would better have been `opam-format-version`. There isn't `opam-version: "2.1"` for `opam` files, because we didn't change anything in the end (indeed, `opam lint` should warn if you have an `opam` file with `opam-version: "2.1"`). Aside: if a package requires opam 2.1 (because it uses a CLI feature, or whatever) then that should be done using `available: opam-version >= "2.1"` as that causes opam 2.0 to gracefully refuse to process the package, as opposed to leaving it unable to parse it.

I can't remember if we already scrub `OPAM*` variables from the environment when building packages, but we should definitely be scrubbing `OPAMCLI` and there's no reason not to have `OPAMCLI=2.0` as the default environment for all builds. If a package requires 2.1 in its commands, then it should be using `--cli=2.1` which overrides the environment variable and then existing packages will work as expected.

beta4 was already blocked on updating the packages, so I agree this issue blocks it (but should be easy to deal with)
