### ISSUE TITLE
opam pin dismisses uncommitted changes when local path is a git repo

### ISSUE THREAD

**Issue by mimoo** [ocaml/opam#4652]
Hello,
when doing something like 

```
opam pin add some_package some/path
```

where `some/path` is a local git repository, opam automatically sets `--kind git` and dismisses any local changes that haven't been committed. I don't think this is the behavior that anyone would expect? At least I didn't and this bit me many many times.
I'd suggest not setting `--kind git` when passed a local path, and instead using `--kind path` by default for these.

**Comment by roddyyaga** [comment]
+1, I'd be interested to hear from anyone with a workflow where the current auto behaviour is desirable.

**Comment by dbuenzli** [comment]
We discussed this to death quite some time ago but I can't dig out the discussion. 

Basically as soon as you start juggling with many dependent pins and different git branches you'll understand that the default behaviour is what you want. 

Otherwise you need to be very careful about the state of your files (which may temporarily not compile) when you `opam upgrade` your pins.

**Comment by dbuenzli** [comment]
Found it, https://github.com/ocaml/opam/issues/2156

**Comment by AltGr** [comment]
Indeed, as @dbuenzli pointed out, we went through several iterations before agreeing on the current behaviour; the final decision was made because using path pinning, while apparently being generally what you want at first, pretty often comes back bitting you in vicious and unexpected ways afterwards.

We attempt to balance the default `git` behaviour by:
- detecting uncommitted changes and being explicit about them being left out on updates
- providing `--working-dir` to temporarily sync version-controlled files to their on-disk version

I wouldn't really advise it but you can try setting `OPAMWORKINGDIR=1` to always sync to the on-disk version, and see if that better fits your workflow. Compared to using `-k path`, it has the upside of only sync'ing source files and not build artifacts ; but the dowside that it may ignore new source files until you `git add` them.

**Comment by mimoo** [comment]
(interestingly I just run into the [dune-start project](https://github.com/mjambon/dune-starter/blob/master/proj/README.md#installation) that uses the default `$ opam pin add -k path proj .`)
