### ISSUE TITLE
[master] opam-devel does not install the opam binary anymore

### ISSUE THREAD

**Issue by kit-ty-kate** [ocaml/opam#4657]
Using master (https://github.com/ocaml/opam/commit/a70ed4f98a9f8bc462908dd12298281f8ea93c7d) installing opam-devel:
```
$ opam install .
[...]
∗ installed opam-devel.2.1.0~beta4
Done.

<><> opam-devel.2.1.0~beta4 installed successfully ><><><><><><><><><><><><><><>
=> The development version of opam has been successfully compiled into /home/kit_ty_kate/.opam/default/lib/opam-devel.
   You should not run it from there, please install the binaries to your PATH, e.g. with
       sudo cp /home/kit_ty_kate/.opam/default/lib/opam-devel/opam /usr/local/bin

   If you just want to give it a try without altering your current installation, you could use instead:
       alias opam2="OPAMROOT=~/.opam2 /home/kit_ty_kate/.opam/default/lib/opam-devel/opam"
```
However `/home/kit_ty_kate/.opam/default/lib/opam-devel/opam` is an (executable?!) opam file and not a binary:
```
$ ls -lh /home/kit_ty_kate/.opam/default/lib/opam-devel/opam
-rwxr-xr-x 1 kit_ty_kate kit_ty_kate 741 May 11 13:51 /home/kit_ty_kate/.opam/default/lib/opam-devel/opam
$ cat /home/kit_ty_kate/.opam/default/lib/opam-devel/opam
opam-version: "2.0"
version: "2.1.0~beta4"
synopsis: "Meta-package for Dune"
[...]
```
Its content is the same as `opam.opam` at a70ed4f98a9f8bc462908dd12298281f8ea93c7d

**Comment by dra27** [comment]
This is an inconsistency of opam-devel.install (which has been present for a long time, probably since the conversion to jbuilder) combined with a regression caused by #4494.

I'll sort out a fix to the opam-devel.install part - would you be able to look into the regression from #4494? The issue is that there an `opam` file mentioned in both the `lib` and `libexec` sections. opam should install the file twice which is what it was before #4494. I'm wondering if a list of files is being processed in the wrong order?

There's possibly an additional bug in the case of overwriting to check - the execute bit should have been cleared on overwriting it with the opam file.
