### ISSUE TITLE
Depexts detection does not work on CentOS when EPEL is involved

### ISSUE THREAD

**Issue by kit-ty-kate** [ocaml/opam#4669]
Detected in https://github.com/ocaml/opam-repository/pull/18704

The way things work in CentOS wrt opam is that when EPEL is needed, we install it first (through `epel-release`) then we install the package required. However the new depexts detection in opam does not find the package since it is not yet available (as it is in the EPEL repository) and thus mark it as unavailable.

I'm not entirely sure how to deal with that here..

**Comment by dra27** [comment]
Hmm. Depending on epel-release as a depext may work for CentOS, but that already doesn't work for RHEL (you're supposed to install the epel-release rpm explicitly to enable it, IIRC).

This can't be fixed in depext detection (at least quickly) - it's fundamentally about _configuring_ the package manager which is not what this is for. Essentially the OS package manager has not been "correctly" configured (it'd be like having the wrong apt repo configuration)

Practical thoughts, though:
- Change the default invariant to pull in `"epel-release"` on CentOS - i.e. effectively have `opam init` request to set that up - so we "kick" users to get EPEL enabled before it's definitely needed. However, I'm not convinced we _should_ do this - there's a reason EPEL exists, and doing this semi-automatically rather violates it.
- See what needs doing to get opam itself into EPEL. According to https://src.fedoraproject.org/rpms/opam, the opam package is orphaned. If the main way to install opam is via EPEL then most users are going to get it by default!
- Improve the error handling (possibly for Alpine's benefit too?) to make better suggestions when the packages can't be found - perhaps adding a concept of enabled repos to depext? It feels like a rabbit-hole in something that's already quite complicated, though!

**Comment by dra27** [comment]
Referencing all the relevant parts of this. This part, pulled in from https://github.com/ocaml-opam/opam-depext/pull/77, is not working (the special-casing needs to be lifted, executed - i.e. `epel-release` installed first, and then followed by a fresh query for the available package list for it to work):
https://github.com/ocaml/opam/blob/3cd0829538b90191bcd1c4eaa76c00d3d987b4ea/src/state/opamSysInteract.ml#L531-L547
There's also the original issues in https://github.com/ocaml-opam/opam-depext/issues/70 and https://github.com/ocaml-opam/opam-depext/issues/76.

I'm rather on @avsm's side in https://github.com/ocaml-opam/opam-depext/pull/77#issuecomment-326548524 - I'm not convinced opam-depext should ever have been doing this.
