### ISSUE TITLE
/tmp is mounted as read-only in the sandbox

### ISSUE THREAD

**Issue by psafont** [ocaml/opam#4774]
This, along with https://github.com/ocaml/opam/commit/36177cb44a2daddf6b8b3b49aab797b1834bc9c9 broke some configure scripts in xapi-project that tried to write to /tmp/.

Although @dra27 kindly proposed a workaround for our usecase it would still be good to take a look at having /tmp mounted as read-write instead of read-only.

**Comment by dra27** [comment]
Cross-referencing #4719 which proposes syncing the macOS and Linux sandboxes to make `/tmp` **read-only** on macOS (it's paused, pending a decision on this issue).

**Comment by dra27** [comment]
Relevant bits of POSIX: `TMPDIR` is covered in [1003.1-2017 Chapter 8](https://pubs.opengroup.org/onlinepubs/9699919799/basedefs/V1_chap08.html):

> _TMPDIR_
> &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;This variable shall represent a pathname of a directory
> &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;made available for programs that need a place to create temporary files.

`/tmp` is covered in [1003.1-2017 Chapter 10](https://pubs.opengroup.org/onlinepubs/9699919799/basedefs/V1_chap10.html):

> The following directory shall exist on conforming systems and shall be used as described:
> **/tmp**
> &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;A directory made available for applications that need a place to create temporary files.
> &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;Applications shall be allowed to create files in this directory, but shall not assume that such
> &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;files are preserved between invocations of the application.

So from a POSIX perspective, the sandbox change on Linux is not-compliant (just because we set `TMPDIR` does not mandate that applications should respect it and also doesn't lift the need for `/tmp` to remain writeable.

On the other hand, making `/tmp` read-only provides a principled (ish) way for state to be communicated into the sandbox, while preventing the sandbox from interfering with anything else in `/tmp`.

**Comment by avsm** [comment]
I think perhaps we should pull opam 2.0.9 and release a 2.0.10 without this change. It's a breaking change to the stable series (which was hard to predict before releasing 2.0.9; we don't have the luxury of much testing on these stable series'!)

**Comment by dra27** [comment]
@psafont - what else in 36177cb has caused issues? The change in handling of `TMPDIR` fixes a definite bug in the sandbox, but I'd been under the impression that the problem was solely that `/tmp` is read-only?

**Comment by dra27** [comment]
Testing would have picked this up if the packages were in opam-repository. @psafont - given that these repos are public, I think it would be good for all of us if we could work to update @kit-ty-kate's opam-health-check to include the Xen repositories 🙂

We definitely should _not_ revert this only in 2.0.10 and leave 2.1.1 series - that then makes some packages break depending on the opam client version.

Discussing this last Friday, our thinking was that the "only" objection here is the regression - in other words, if opam 2.0.0 had always done this, the package would just have been altered, rather than opam changed.

I think there are two options, therefore:

1. Restore `/tmp` to be rw in _both_ 2.0.10 and 2.1.1 (but still the _real_ `/tmp`, not `TMPDIR` as it was before).
2. Stick with it, either patching existing packages with `"sed" "-e" "s|/tmp|${TMPDIR:-/tmp}|g"` or releasing updated versions and constraining old versions with `available: opam-version < "2.0.8"`

It's a balance between having a slightly weaker sandbox and having older packages carry on working unaltered.

**Comment by avsm** [comment]
If we can patch the older packages to compile, then I'd prefer the stronger sandbox. The invariant that would be nice to preserve is that older packages could be compiled with a newer opam in a few years from now. That's generally true of older packages, but there is precedent for fixing (e.g.) OCaml compiler compilation issues on newer compilers or sandbox issues like this.

**Comment by avsm** [comment]
Note that restoring the real `/tmp` to be rw in both clients moving forward is also important I think. POSIX is fairly clear that a /tmp directory should exist. That doesn't preclude patching the xen packages to use TMPDIR, however!

**Comment by psafont** [comment]
The packages have been patched to use TMPDIR. idreay they would use dune's configurator, wich might happen soon-ish.

Only the old, but still supported versions of the packages need some care around this

**Comment by AltGr** [comment]
See 36177cb44a2daddf6b8b3b49aab797b1834bc9c9 for details on the change from `/tmp` to `TMPDIR`.
Il like the fact that `TMPDIR` points to a tmpfs within the sandbox; this doesn't prevent allowing write access to `/tmp`, but as pointed out it seem stronger to disallow it, if we can.
