### ISSUE TITLE
Strange display during opam install

### ISSUE THREAD

**Issue by vsiles** [ocaml/opam#4866]
On a fresh 4.12.1 switch, I'm seeing strange outputs of `opam install`:

```
 retrieved bcppo.1.6.8  (https://github.com/ocaml-community/cppo/archive/v1.6.8.tar.gz)
⊘retmovvd  bocaml.4.12.1
⊘retmovvd  bocaml-config.2
∗rinstalled ocaml-option-flambda.1
```

Full output can be found at https://pastebin.com/S8VaXdRm

I'm using opam 2.1.0 on a centos machine:

```
$ opam config report
# opam config report
# opam-version         2.1.0
# self-upgrade         no
# system               arch=x86_64 os=linux os-distribution=centos os-version=8
# solver               builtin-mccs+glpk
# install-criteria     -removed,-count[avoid-version,changed],-count[version-lag,request],-count[version-lag,changed],-count[missing-depexts,changed],-changed
# upgrade-criteria     -removed,-count[avoid-version,changed],-count[version-lag,solution],-count[missing-depexts,changed],-new
# jobs                 23
# repositories         1 (http), 1 (version-controlled)
# pinned               0
# current-switch       4.12.1
# ocaml:native         true
# ocaml:native-tools   true
# ocaml:native-dynlink true
# ocaml:stubsdir       /data/users/vsiles/opam/4.12.1/lib/ocaml/stublibs:/data/users/vsiles/opam/4.12.1/lib/ocaml
# ocaml:preinstalled   false
# ocaml:compiler       4.12.1+options+fp+flambda```

**Comment by dra27** [comment]
Is this repeatable if you use a tool like `script` to capture exactly what's going on?

**Comment by dra27** [comment]
Hmm - not sure if pastebin or GitHub is mucking around with newlines here or if there is something going on with opam. Running in a docker container, I for example did (interactively)

```
docker run --rm -it ocaml/opam
sudo ln -f /usr/bin/opam-2.1 /usr/bin/opam
opam update -y && script -c 'opam install -y core_kernel' log-file
sudo apt-get install -y vim
vim log-file
```
With line-wrapping off (should be default, but `:set nowrap` otherwise), there should be a very clear section of lines beginning:

```
^M^[KProcessing ...
```
but with no extraneous lines between. Each one of those lines may contain subsequent `^M^[KProcessing` segments but the final `^M^[K` should then be a "-> retrieved" or "-> installed" bit and there should only be one of those on each line. Is that what you see in the log? The raw pastebin output seemed to have extra lines in it

**Comment by vsiles** [comment]
Yes, most lines have multiple `^M^[KProcessing` but once I see the `-> retrieved` or `-> installed`, the next `^M^[KProcessing` is on a new line

**Comment by dra27** [comment]
Yeah, that log's as I expected. The pastebin one, for whatever reason, appeared to have chomped the `^M` in a strange way.

I'm afraid this does look entirely like the terminal is to blame 😕
