### ISSUE TITLE
Warn about actions on pinned packages

### ISSUE THREAD

**Issue by ulugbekna** [ocaml/opam#4925]
Currently, if a user has a package pinned, they can reinstall a certain version of the package, but they'll still have the pinned version. Say, I pin ocamlformat master, then reinstall 0.19.0 successfully as indicated by opam install, but I'll still have the master version of ocamlformat when I run it. Does it make sense to warn that the package being (re)installed is actually pinned and the reinstallation, for example, won't do anything? (it probably still changes versions for the solver to see)

**Comment by rjbou** [comment]
On its display opam already say you that it is synchronising pinned packages, even if there is not changes:

```
<><> Synchronising pinned packages ><><><><><><><><><><><><><><><><><><><><><><>
[name.version] synchronised (no changes)

The following actions will be performed:

```

**Comment by dra27** [comment]
Notes from dev meeting: we should change the display of pinned versioned so that instead of just being `version*` it is `version (pinned)`. Separately, we should also consider using a suffix on the version by default (although this may potentially break workflows, so it's worth considering the two changes separately)
