### ISSUE TITLE
a possible regression on macOS /var/folders permission problem

### ISSUE THREAD

**Issue by ivg** [ocaml/opam#4958]
It looks like that #3576 re-appeared in 2.1.2, we have the "operation not permitted" error on our [CI builds][1] after 2.1.2 has been released
```
 - make: error: couldn't create cache file '/var/folders/24/8k48jl6d249_n_qfxwsl6xvm0000gn/T/xcrun_db-cZTiPW1A' (errno=Operation not permitted)
```

Here's the [log][2] for the same action that passes without problems on 2.1.1 (and older versions), and here is the [action][3] itself for your reference. Any suggestions on workarounds are very welcome!

[1]: https://github.com/BinaryAnalysisPlatform/bap/runs/4473828489?check_suite_focus=true#step:3:397
[2]: https://github.com/BinaryAnalysisPlatform/bap/runs/4413569831?check_suite_focus=true
[3]: https://github.com/BinaryAnalysisPlatform/bap/blob/master/.github/workflows/build-dev-repo.yml

**Comment by kit-ty-kate** [comment]
This is puzzling. I’m not seeing anythin related change in 2.1.2 compared to 2.1.1: https://github.com/ocaml/opam/compare/2.1.1...2.1.2
Are you still having the issue? Was it reproducible?

**Comment by ivg** [comment]
Yep, it's reproducible on each run, and yes it's puzzling, as I checked every single line of the change and didn't find anything relevant.

**Comment by kit-ty-kate** [comment]
@smorimoto is there a related change in setup-ocaml by any chance?

**Comment by ivg** [comment]
Those error messages turned to be red herrings. Apparently, they existed all the time, even when we were passing the installation test. The true problem was the below those error messages and is a manifestation of the https://github.com/ocaml/ocaml/pull/9895 so the workaround is `rm $(opam var lib)/ocaml/VERSION`

P.S. it is still interesting what those messages mean and are they a problem or not, but closing for now.

**Comment by kit-ty-kate** [comment]
mmmh, it seems to be a manifestation of the problem that might be fixed by https://github.com/ocaml/opam/pull/4797: macOS tools have a bug in which it expects the cache directories to always be writable if it can read them (obviously not true when sandboxed). `xcrun_db-*` files seem to come from xcode so it seems that they all have common code with `/usr/bin/security`.
I’ve create a bug report on Apple’s bugtracker last year but I still did not get any answers.

Could you try https://github.com/ocaml/opam/pull/4797 to see if it removes the message? (backing-up then copying the sandbox file from this PR to `~/.opam/opam-init/hooks/sandbox.sh` should be enough)
