### ISSUE TITLE
Fail to swich newer opam versions

### ISSUE THREAD

**Issue by ryancaicse** [ocaml/opam#4980]
I use `opam switch ` to use the newer version
```
opam switch 4.07.0
```
I use `opam config env` and it shows
```
CAML_LD_LIBRARY_PATH="/home/rando/.opam/4.07.0/lib/stublibs"; export CAML_LD_LIBRARY_PATH;
MANPATH=":/home/rando/.opam/4.07.0/man"; export MANPATH;
PERL5LIB="/home/rando/.opam/4.07.0/lib/perl5:"; export PERL5LIB;
OCAML_TOPLEVEL_PATH="/home/rando/.opam/4.07.0/lib/toplevel"; export OCAML_TOPLEVEL_PATH;
```

However, I use 'opam --version' and it still shows the old version

`1.2.2`

How can I switch the old version to the new version? Thank you!

**Comment by rjbou** [comment]
Switches are used to have several installation of *compilers*, and from you `opam config env` output, it is well set to the switch named `4.07.0` (that usually corresponds to an `ocaml 4.07.0` compiler).
`opam --version` shows you the version of opam itself, not your current compiler version.
If you want to upgrade you opam installation (and I highly recommend you to do so, 1.2.2 is no more maintained and its repository is frozen since 3 years), you can see this [blog post](https://opam.ocaml.org/blog/opam-2-0-0).
If you want to upgrade you compiler, you want to create a new switch `opam switch create 4.08.0`, but higher one available is 4.08.0 on 1.2 deprecated opam repository.

**Comment by ryancaicse** [comment]
@rjbou Hi, thanks. It indeeds solves my problems.

However, when I install a package, which shows `opam install camlzip`. How t resolve this problem?

```
[atd.2.0.0] found in cache
[atdgen.2.0.0] found in cache
[atdgen-runtime.2.0.0] found in cache
[biniou.1.2.0] found in cache
[cmdliner.1.0.2] found in cache
[cppo.1.6.5] found in cache
[cudf.0.9] found in cache
[dose3.5.0.1] found in cache
[dune.1.2.1] found in cache
[easy-format.1.3.1] found in cache
[extlib.1.7.5] found in cache
[mccs.1.1+8] found in cache
[menhir.20180905] found in cache
[ocamlbuild.0.12.0] found in cache
[ocamlfind.1.8.0] found in cache
[ocamlgraph.1.8.8] found in cache
[opam-client.2.0.0] found in cache
[opam-core.2.0.0] found in cache
[opam-devel.2.0.0] found in cache
[opam-file-format.2.0.0] found in cache
[opam-format.2.0.0] found in cache
[opam-repository.2.0.0] found in cache
[opam-solver.2.0.0] found in cache
[opam-state.2.0.0] found in cache
[re.1.8.0] found in cache
[result.1.3] found in cache
[topkg.0.9.1] found in cache
[yojson.1.4.1] found in cache
[ERROR] The sources of the following couldn't be obtained, aborting:
          - camlzip.1.11
```

**Comment by kit-ty-kate** [comment]
You can upgrade opam to the latest version with:
```
bash -c "sh <(curl -fsSL https://raw.githubusercontent.com/ocaml/opam/master/shell/install.sh)"
```

**Comment by ryancaicse** [comment]
@kit-ty-kate Thanks!! My problem is addressed.
