### ISSUE TITLE
Question: is the config field archive-mirrors respected?

### ISSUE THREAD

**Issue by hannesm** [ocaml/opam#5272]
Hello,

in the manual I read that you can set `archive-mirrors: [ "<URL>" ... ]` in the opam configuration file. Now, setting it in ~/.opam/config doesn't seem to have any effect -- tarballs are still downloaded from opam.ocaml.org.

My test case was `opam source <package>`. I'm using opam 2.1.2.

Thanks for developing opam and have a nice weekend!

**Comment by hannesm** [comment]
NB: there's a separate repofiled `archive-mirrors` (as part of the `repo` file), but I'm asking about `#configfield-archive-mirrors`.

**Comment by dra27** [comment]
The website has too up-to-date documentation (it's display docs from opam master rather than latest stable release!). See also #4411 which has been fixed in #4830 which will be in 2.2 - so if you're happy to try opam master, this should be working (and please do re-open if that turns out not to be the case)

**Comment by hannesm** [comment]
Dear @dra27, thanks for your quick response. Maybe it would be worth to state in the documentation kind of "since 2.2.0" or similar then? Yes, I understand that this feature has been present for longer, but #4411 explains pretty well the confusion...
