### ISSUE TITLE
External dependencies listing all optional branches

### ISSUE THREAD

**Issue by toots** [ocaml/opam#5415]
There seem to be an issue with the external dependencies listing. The `conf-srt.2` package has two explicit options:
```
% opam info conf-srt.2

<><> conf-srt: information on all versions ><><><><><><><><><><><><><><><><>  🐫
name                   conf-srt
all-installed-versions 1 [4.13.1]  2 [5.0.0]
all-versions           1  2

<><> Version-specific details <><><><><><><><><><><><><><><><><><><><><><><>  🐫
version     2
repository  default
homepage    "https://srt.org/doxygen/trunk/index.html"
bug-reports "https://github.com/ocaml/opam-repository/issues"
authors     "srt dev team"
maintainer  "https://github.com/ocaml/opam-repository/issues"
license     "MPL-2.0"
flags       conf
depends     "conf-pkg-config" {build}
            "conf-srt-openssl"
              {os-distribution = "debian" | os-distribution = "ubuntu" |
               os = "macos" & os-distribution = "homebrew"} |
            "conf-srt-gnutls" {os-distribution = "debian" | os-distribution = "ubuntu"}
synopsis    Virtual package relying on srt
description This package can only install if the srt library is installed on the system.
```

But, when asking for external dependencies of `conf-srt.2` along with `conf-srt-openssl`, one also gets the other dependencies:

```
% opam list --short --recursive --external --vars os-distribution=debian,os-family=debian --required-by="conf-srt.2,conf-srt-openssl"
libgnutls28-dev
libsrt-gnutls-dev
libsrt-openssl-dev
libssl-dev
pkg-config
```

Same goes if no package is explicitly picked:
```
% opam list --short --recursive --external --vars os-distribution=debian,os-family=debian --required-by="conf-srt.2"
libgnutls28-dev
libsrt-gnutls-dev
libsrt-openssl-dev
libssl-dev
pkg-config
```

The solver should only list the external dependencies related to only one of the two possible dependent packages.

**Comment by dra27** [comment]
Instead of `--recursive --required-by="conf-srt.2"`, `--resolve="conf-srt.2"` will already give just one solution. The one it gives will depend on what's installed on your system - if you have `libgnutls28-dev` and `libsrt-gnutls-dev` installed, then it will suggest the `conf-srt-gnutls` version, otherwise it will suggest `conf-srt-openssl` (because it's first in the disjunction).

If you're using this in order to get a list of system packages to preinstall manually, bear in mind that there's always a risk that a subsequent `opam install` makes a different decision (this was the problem with `opam-depext` in opam 2.0 which was fixed by making depext processing internal). That can be mitigated by solving for the packages which are wanted first and then listing the external dependencies of those with `--resolve` (for example, `opam list --resolve="conf-srt.2,conf-srt-openssl"` will always give the depexts for openssl only)

**Comment by toots** [comment]
Thank you this is very useful. Should I close this ticket then?

**Comment by dra27** [comment]
Excellent - as long as that's fixed your issue, yes 🙂
