### ISSUE TITLE
Opam lint rejects zip archives

### ISSUE THREAD

**Issue by silene** [ocaml/opam#5447]
Opam lint (2.1.4) seems to reject any URL pointing to a zip file. For example, on https://github.com/ocaml/opam-repository/blob/master/packages/GT/GT.0.3.0/opam, one gets:

```console
$ opam lint
.../GT.0.3.0/opam: Errors.
    error 67: Checksum specified with a non archive url:
              "https://github.com/Kakadu/GT/archive/v0.3.0.zip -
              sha256=58aa09194..."
```

Replacing `.zip` with `.tar.gz` makes it succeed.

**Comment by kit-ty-kate** [comment]
I'm not able to reproduce this behaviour with master. Looking at the PRs I believe https://github.com/ocaml/opam/pull/4960 was the fix.

If you really need this fixed we can see if we can backport to the 2.1 branch it but otherwise it's probably worth waiting for opam 2.2.0~alpha1 coming in the next few weeks.
