### ISSUE TITLE
Add an option to easily configure an OPAM proxy

### ISSUE THREAD

**Issue by samoht** [ocaml/opam#548]
The proxy can mirror upstream archives (instead of the `+opam` ones)

**Comment by AltGr** [comment]
See #2449
The question is in the format the proxy/mirror should have. Since the repository's `archives/` directory format needs to be changed anyway (no more repackaging with `+opam`), we may try to have something consistent rather than define two layouts and formats.
Options:
- by-hash (as implemented in #2449): flexible, generic, naturally avoids duplication, but less readable, and maybe more difficult to GC. Some security concerns, but we will be allowing more hash formats (e.g. `md5/xxxxx`, sha1/xxxxx`...), and progressively migrating the repo to a more secure function. We only need to define a common hash <-> relative path bijection.
- by-URL: compatible with any proxying software
- by package hierarchy: closest to the current scheme and readable, but not as generic, and may lead to duplications.

**Comment by AltGr** [comment]
There is no command-line for that, but this can now easily be set up using the `archive-mirrors:` field (in `~/.opam/config`, `opamrc` or the `repo` file).
