### ISSUE TITLE
Unexpected behaviour when prepending/appending to initially empty variables multiple times

### ISSUE THREAD

**Issue by gridbugs** [ocaml/opam#5926]
When a variable is initially unset or empty, appending to it and then prepending to it using the colon operators (`:=` and `=:`) causes an unexpected leading colon in the result. Prepending to an unset variable followed by appending to it produces the same unexpected result.

Here is a package reproducing the problem:
```
opam-version: "2.0"

build-env: [

 [ X := "a" ]
# X should be "a:"
 [ X =: "b" ]
# X shoulde be "a:b"
# (assuming opam doesn't add a separator when appending to a variable which ends with a separator)
# X unexpectedly has the value ":a:b"

 [ Y =: "a" ]
# Y should be ":a"
 [ Y := "b" ]
# Y should be "b:a"
# (assuming opam doesn't add a separator when prepending to a variable which starts with a separator)
# Y unexpectedly has the value ":b:a"

]

install: [
    [ "bash" "-c" "echo X=$X >> %{lib}%/foo" ]
    [ "bash" "-c" "echo Y=$Y >> %{lib}%/foo" ]
]
```

Reproduce by running `opam install ./foo.opam && cat _opam/lib/foo` which will produce the output:
```
X=:a:b
Y=:b:a
```

But according to the documentation the output should be:
```
X=a:b
Y=b:a
```

I'm on linux. Reproduced on both 2.1.5 and opam-2.2.0-beta2.

**Comment by dra27** [comment]
As in #5935, cross-referencing:
- #3886 (fixing #3878, #2870 and #2255)
- #3404 (fixing #3391)
- #3325 (fixing #3319)

The documentation for `=:` and `:=` I think is not correct since #3404. I think the semantics of `:=` and `=:` should be as given for empty/unset values but also that they both preserve trailing and leading `:` in the current value.

Given those semantics:
- `[ X := "a" ]` with `X` empty gives `a:` (current behaviour is **correct**)
- `[ X =: "b" ]` with `X` set to `a:` gives `a:b:`, adding `b` at the end, but preserving the trailing colon (current behaviour is **incorrect** as `X=:a:b`)
- `[ Y =: "a" ]` with `Y` empty gives `:a` (current behaviour is **correct**)
- `[ Y := "b" ]` with `Y` set to `:a` gives `:b:a`, adding `b` at the start, but preserving the leading colon (current behaviour is **correct**)

So I _think_ that the treatment of `X` here is incorrect, but the treatment of `Y` is correct (but the documentation should be updated to reflect this).
