### ISSUE TITLE
error : [OPAM INIT] - Platform: Windows 11 HOME - Version: 23h2

### ISSUE THREAD

**Issue by BatmiBoom** [ocaml/opam#6120]
Steps:

- Install cygwin
- Install packages
 
![Packages](https://github.com/user-attachments/assets/8aa1922b-f230-4eba-ace4-aa5f5092fc3e)

- Download opam from releases
- Add to env
- Run 
```
opam init
```
![Error](https://github.com/user-attachments/assets/e5adde50-4605-4deb-9a29-d379f048e37b)

```
Can't execute opam config report becauses its not initialized
```

**Comment by dra27** [comment]
I'm unable to reproduce this - cURL docs say exit code 43 is an internal error. Is it repeatable? If so, what happens if you run the command directly? (from the shell you have there, that'd be `/cygdrive/c/Windows/system32/curl.exe --write-out '%{http_code}\n --retry 3 --retry-delay 2 --user-agent opam/2.2.0 -L -o index.tar.gz.part -- https://opam.ocaml.org/index.tar.gz`)

If it is a persistent problem, a workaround is almost certainly to install Cygwin's curl package, but it ought to be working with the Windows copy.

**Comment by BatmiBoom** [comment]
The first tip didn't work
The workaround worked: replacing the `C:\Windows\System32\curl.exe` with the Cygwin version

**Comment by dra27** [comment]
Glad that's worked around it (although I hope that was by shadowing `C:\Windows\System32\curl.exe`, not actually replacing files in the Windows system32 directory!).

**Comment by dra27** [comment]
I'm re-opening this as although I've not seen it do it at this point, I have seen Windows `curl` do this when downloading a series of packages and there are various reports in Discord seeing the same thing. In my particular instance _some_ downloads succeeded while most of them ended up with this cURL error. As it happens, I was also using Windows 11 22H2 (rather than Windows 10, as I use both).

**Comment by dra27** [comment]
I'm tempted to:
- Add `curl` to the required programs for `opam init` for Windows (internal installation would naturally then get it and opam will recommend it for external Cygwin/MSYS2 installs via depext). That would be for 2.2.1+ potentially
- Distribute opam with an internal download agent (something a la ocurl - the benefit of libcurl is that it can be compiled against Windows SSL). That's quite a chunk of maintenance work, though.

**Comment by kit-ty-kate** [comment]
I've opened https://github.com/ocaml/opam/pull/6142 as an implementation of solution 1

**Comment by kit-ty-kate** [comment]
For anyone reading this, if you encounter the same error during `opam init`, the fix is to instead call:
```
opam init --cygwin-internal-install --cygwin-extra-packages=curl
```
