### ISSUE TITLE
getconf: LONG_BIT: unknown variable

### ISSUE THREAD

**Issue by mndrix** [ocaml/opam#6215]
On OpenBSD 7.5 amd64 running opam version 2.3.0~alpha1, `opam upgrade` produces the following error:

```
getconf: LONG_BIT: unknown variable
'opam upgrade' failed.
Fatal error:
End_of_file
```

The output of `opam config report 2>&1` encounters the same error:

```
# opam config report
# opam-version         2.3.0~alpha1
# self-upgrade         no
getconf: LONG_BIT: unknown variable
# read-state           End_of_file
```

It doesn't look like I'll get around to sending a patch this week, but maybe this weekend :crossed_fingers:

**Comment by dra27** [comment]
Cross-referencing https://github.com/ocaml/opam/pull/5950

**Comment by kit-ty-kate** [comment]
It looks like OpenBSD is the only unix platform i could find where `uname -m` actually returns the "kernel architecture" instead of the "machine architecture" so the call to `getconf LONG_BIT` or equivalent is not required here.

Source:
- https://man.openbsd.org/uname.1 (tested in qemu)
- https://man.netbsd.org/uname.1
- https://man.freebsd.org/cgi/man.cgi?query=uname
- https://man.dragonflybsd.org/?command=uname&section=1
- https://man.archlinux.org/man/uname.1.en
- https://ss64.com/mac/uname.html

I'll open a PR in the next hour

**Comment by kit-ty-kate** [comment]
That took a bit longer than expected as i had an idea on how to improve related code and discovered a bug elsewhere.
Anyway, this hasn't been tested outside of Linux yet but i believe it should work so feel free to test it: https://github.com/ocaml/opam/pull/6217

**Comment by mndrix** [comment]
Confirming that #6217 fixes this problem for me
