### ISSUE TITLE
local cache of binary packages

### ISSUE THREAD

**Issue by UnixJunkie** [ocaml/opam#629]
Hello,

It would be nice if I build a package, then uninstall it,
then reinstall it, that the already built one is re-used
instead of recompiling everything again.

Thanks,
F.

**Comment by AltGr** [comment]
There is a prototype of this using hooks, see https://github.com/ocaml/opam/blob/master/shell/opam-bin-cache.sh

**Comment by Khady** [comment]
Is it possible to combine those cache hooks with the sandbox hooks?

**Comment by Khady** [comment]
A quick comment to talk about esy too. Don't know if it's the good place. You probably know about it. They have a cache system too which seems to be pretty efficient. But rather than to copy the directories from the cache to the "switch", they put in the environment the paths to all the packages that are required by the switch. I think it also avoid some problems like relocating `ocaml` (esy does something in addition to make ocaml relocatable from one computer to another, but it doesn't seem as important as a good local cache system to me). I thought it worth mentioning it.

**Comment by AltGr** [comment]
> Is it possible to combine those cache hooks with the sandbox hooks?

yes, of course

> rather than to copy the directories from the cache to the "switch", they put in the environment the paths to all the packages that are required by the switch.

this is where there is quite a bit of difference: IIUC, in esy, every package is installed to its own subtree, which is a nice property that allows easy mix & matching of already compiled packages. It requires quite a bit of cooperation from the underlying systems, though, in this case — correct me if I am wrong — significant ocamlfind hacks.

This is a mode that we would definitely be interested in supporting in opam, but it also remains an important part of the project philosophy to be agnostic and pragmatic on what the packages do (hence the simple shell commands for `build:` instructions, for example).

**Comment by Drup** [comment]
@AltGr I would encourage you to publish and promote this caching hook to get feedback. It's a very nice feature and even if it doesn't work perfectly just yet, I'm sure lot's of people would be interested. Enabling it would allow you to get feedback quickly.

**Comment by Khady** [comment]
Is there a reason to not release and enable the cache script by default? It seems to work very well. This is definitely something that would push the usage of local switches forward I think. And help to fight the "competition". I understand that for some packages like the ocaml compiler relocation might be a problem. But most of the time it works fine. And it could create motivation to fix this issue.

For people who want to have sandbox and cache at the same time, here is my configuration
https://gist.github.com/Khady/587a5e52679610b6aecfc4dbbd95e54d

**Comment by AltGr** [comment]
I have tested it for a while, and while it works correctly at first, once you e.g. remove the original switch the cache was made from, in my experience it doesn't behave well...
I tried some workarounds, e.g. forcing some env variables, but that added more problems.

Of course, there might be progress in ocamlfind configuration since then, that makes this more reliable?

You can have more detail at https://github.com/ocaml/opam-repository/issues/10863

**Comment by AltGr** [comment]
@Khady thanks for sharing your conf; I could publish a small script to easily enable/disable it, for those interested in testing ?

**Comment by Drup** [comment]
@AltGr please do, this is a really good feature and I think it's worth advertising it, even if it's not completely finished.

**Comment by ELLIOTTCABLE** [comment]
I've given this a stab, and it looks like it needs a small tweak for macOS. It's currently causing the failure of any package that's already been installed elsewhere:

```
#=== ERROR while installing astring.0.8.3 =====================================#
# context     2.0.0 | macos/x86_64 | ocaml-base-compiler.4.07.0 | https://opam.ocaml.org/2.0#0bce4f9a
# path        ~/.opam/default/.opam-switch/build/astring.0.8.3
# command     ~/.opam/opam-init/hooks/opam-bin-cache.sh restore 021592f72a3781d5db0a804a656335022129f66149419979d89f88e3b4460c83 astring
# exit-code   64
# env-file    ~/.opam/log/astring-41810-f19885.env
# output-file ~/.opam/log/astring-41810-f19885.out
### output ###
# [...]
# + shift
# + '[' -z 021592f72a3781d5db0a804a656335022129f66149419979d89f88e3b4460c83 ']'
# + CACHE_DIR=/Users/ec/.cache/opam-bin-cache/021592f72a3781d5db0a804a656335022129f66149419979d89f88e3b4460c83
# + case $COMMAND in
# + NAME=astring
# + shift
# + '[' -d /Users/ec/.cache/opam-bin-cache/021592f72a3781d5db0a804a656335022129f66149419979d89f88e3b4460c83 ']'
# + rm -f astring.install
# + cp -aT /Users/ec/.cache/opam-bin-cache/021592f72a3781d5db0a804a656335022129f66149419979d89f88e3b4460c83/ /Users/ec/.opam/default/
# cp: illegal option -- T
# usage: cp [-R [-H | -L | -P]] [-fi | -n] [-apvXc] source_file target_file
#        cp [-R [-H | -L | -P]] [-fi | -n] [-apvXc] source_file ... target_directory
```

macOS nor BSD `cp` have a `-T` flag (though it looks like the coreutils `cp` does?)

**Comment by Khady** [comment]
I created a 300 USD bounty for this issue. To be clear, I consider that solving it also requires solving https://github.com/ocaml/opam-repository/issues/10863. Actually most of the work is probably on https://github.com/ocaml/opam-repository/issues/10863 as `opam-bin-cache.sh` already works pretty well. I hope it can help to attract contributions.
https://www.bountysource.com/issues/1250468-local-cache-of-binary-packages

**Comment by UnixJunkie** [comment]
@Khady I'm curious, is this out of your pocket or is this your company/employer?

**Comment by Khady** [comment]
Out of my pocket.

**Comment by samoht** [comment]
This has been added directly in dune, see https://dune.readthedocs.io/en/stable/caching.html

**Comment by dbuenzli** [comment]
Isn't `opam` supposed to be a general purpose package manager ? I use it to integrate C packages in projects.

**Comment by avsm** [comment]
From the front page of opam.ocaml.org since time immemorial: "opam is a **source-based package** manager for OCaml <...>" (emphasis mine).  While we provide hooks for binary caching and reproducibility, it is very unlikely that the opam 2.x series will ever provide binary packages directly as a supported feature. That is down to the creator of the packages to architect, as it is deeply tied into the build mechanism of the package.

So, you are welcome to opam package C packages up, as are Coq developers for their tools, and as I do for running various shell scripts, but they all need to sort out their own caching mechanisms using the hooks.  Meanwhile, for the common case of compiling OCaml code in the ocaml/opam-repository, dune provides a caching mechanism that works at the level of build rules, and across opam packages.  Other OCaml build systems can also provide their own caching; for example distcc-based for Makefiles should work fine.

We can revisit this decision for the opam 3.x series, but not unless some compelling new facts or approaches come to light that address @AltGr's comments [above](https://github.com/ocaml/opam/issues/629#issuecomment-414956736).

**Comment by dbuenzli** [comment]
> From the front page of opam.ocaml.org since time immemorial: "opam is a **source-based package** manager for OCaml <...>" (emphasis mine).

Since quite some time now the trend has been to make `opam` more and more general and agnostic to OCaml. Thanks for clarifying that this no longer seems to be the case.

> That is down to the creator of the packages to architect, as it is deeply tied into the build mechanism of the package.

Systems like `esy` or `nix` rather prove that this hasn't to be the case.

**Comment by Khady** [comment]
At this stage of opam's life, to me the solution would be to extract what esy/nix does and use it as an opam hook. It might require to change opam slightly so that it stores switches in a path of fixed length (switch `foo` would be in `~/.opam/__________foo` for example). But it doesn't seem to be a big change for opam. And it should help support cache for any language.

**Comment by avsm** [comment]
@dbuenzli:
> Since quite some time now the trend has been to make opam more and more general and agnostic to OCaml. Thanks for clarifying that this no longer seems to be the case.

Those are your words; not what I said above at all, and an inaccurate characterisation.  I specifically said that the opam 2.x series will not provide binary caching of package descriptions. 

> Systems like esy or nix rather prove that this hasn't to be the case.

I'm aware of that, which is why opam fully supports the interpretation of opam files into being used by these systems, such as via [opam2nix](https://github.com/timbertson/opam2nix) and [domain specific solvers](https://github.com/talex5/opam-0install-solver).  The opam 2.x _client_ will not have this support in its core due to its focus on being a source-based and OCaml agnostic engine.

@Khady wrote:
> At this stage of opam's life, to me the solution would be to extract what esy/nix does and use it as an opam hook.

@Khady feel free to extract out such logic using the opam hooks, and publish it as an opam plugin. We'd be glad to have that in the opam repository for users to try out as an option.  We won't be adding any fixed-length switch hacks to the core client as the issue of relocation has been discussed at the OCaml developers meeting and we'd prefer to use the upstream solution in the opam-repository.  However, nothing stops you from imposing a switch-length limit in an opam plugin, in order to activate binary caching for those switches.

**Comment by Khady** [comment]
> @Khady feel free to extract out such logic using the opam hooks, and publish it as an opam plugin.

That is my plan. Currently on hold because esy authors are rewriting the part which needs to be extracted. If anyone wants to work on that I could create another bounty.

**Comment by rjbou** [comment]
@dbuenzli opam remains agnostic. Every feature we add, we take care to keep that. All OCaml or dune specific behaviors are not hardcoded but configurable.

@Khady  We'd be happy to help you, or the person who wants to implement such plugin, to go through the opam lib.

**Comment by UnixJunkie** [comment]
Having dune do the caching is unsatisfactory.
Not all packages use dune and I don't see why it should be the case.
For cluster users, a cache of binary packages would be very useful.
The fact that some people are translating opam packages to nix is telling.
