### ISSUE TITLE
Since update to 2.3.0 all builds using a local opam patch repo fail because patch files are not found any more.

### ISSUE THREAD

**Issue by MSoegtropIMC** [ocaml/opam#6294]
In the recent nightly build of Coq Platform, which used opam 2.3.0, all build variants failed because patch files in local opam patch repos are not found any more. This results in errors like:
```
Error:  Patch file "/home/runner/.opam/CP.2024.10.0~8.19~2024.10/.opam-switch/build/ocamlfind.1.9.5~relocatable/0001-Fix-bug-when-installing-with-a-system-compiler.patch" not found.
```
See https://github.com/coq/platform/actions/runs/11828794723/job/32959519144#step:5:631

Coq Platform comes with local opam patch repos to do some patches we need. I am aware that for the base opam repo files are now handled in a different way, but I wonder what I am supposed to do with local opam patch repos.

The Coq Platform patch repos are here: https://github.com/coq/platform/tree/main/opam

**I am sure this has upfront been discussed - my apologies that I didn't follow relevant discussions as much as I should. Please take this as quality stamp - opam is only rarely a source of problems. I tried to google this but couldn't find it easily.**

**Comment by rjbou** [comment]
Solution: You need to run `opam admin update-extrafiles` on your repositories.

Since [2.3.0~alpha1](https://opam.ocaml.org/blog/opam-2-3-0-alpha1/#Major-breaking-change), there is a change about how opam loads repositories, especially regarding files in `files/`: they are no more silently added on-the-fly to the package, they need to be specified in the opam file with their checksums.

Failing package have patches in file repository, but not in the [opam file](https://github.com/coq/platform/blob/main/opam/opam-repository/packages/ocamlfind/ocamlfind.1.9.5~relocatable/opam). Once the repository updated, your CI should be fixed.
